# Generated by Django 4.2 on 2026-09-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("village", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contributor",
            name="igbo_name",
        ),
        migrations.AddField(
            model_name="contributor",
            name="country",
            field=models.CharField(blank=True, default="Nigeria", max_length=100),
        ),
        migrations.AddField(
            model_name="contributor",
            name="full_name",
            field=models.CharField(
                blank=True, help_text="Name for Africa & World", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="type",
            field=models.CharField(
                choices=[
                    ("course", "Course"),
                    ("translation", "Translation"),
                    ("forum", "Forum Answer"),
                ],
                max_length=50,
            ),
        ),
    ]
