import os, django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'skillscontinua_core.settings')
django.setup()

from courses.models import Course
from certifications.models import Quiz, Question, Answer

def create_quiz(course_title, quiz_title, description, time_limit, questions_data):
    try:
        course = Course.objects.get(title=course_title)
        quiz, created = Quiz.objects.get_or_create(
            course=course,
            defaults={'title': quiz_title, 'description': description,
                      'pass_mark': 60, 'time_limit_minutes': time_limit, 'is_active': True}
        )
        if not created:
            quiz.title = quiz_title
            quiz.save()
            quiz.questions.all().delete()
        for order, (qtext, qtype, explanation, answers) in enumerate(questions_data, 1):
            q = Question.objects.create(quiz=quiz, question_text=qtext, question_type=qtype,
                                        order=order, marks=1, explanation=explanation)
            for atext, correct in answers:
                Answer.objects.create(question=q, answer_text=atext, is_correct=correct)
        print(f'OK: {course_title} — {quiz.questions.count()} questions')
    except Course.DoesNotExist:
        print(f'NOT FOUND: {course_title}')

# ============================================================
# ENTREPRENEURSHIP BASICS
# ============================================================
create_quiz('Entrepreneurship Basics', 'Entrepreneurship Basics — Final Assessment',
'Entrepreneurship is the engine of West African economic development. This assessment tests your understanding of what it takes to start, run and grow a successful business.',
25, [
('What is the most important quality of a successful entrepreneur?', 'multiple_choice',
'Resilience — the ability to recover from setbacks, learn from failure and persist through difficulty — is consistently identified as the most important entrepreneurial quality. Every successful entrepreneur has faced failure. The difference is not whether they failed but whether they got up, learned and tried again. Technical skills, ideas and capital can all be acquired, but without resilience, temporary obstacles become permanent defeats.',
[('A large amount of startup capital', False), ('Resilience — the ability to recover from setbacks and persist through difficulty', True), ('A university degree in business administration', False), ('Connections to wealthy and influential people', False)]),
('What is a value proposition?', 'multiple_choice',
'A value proposition is a clear statement of the specific benefit your business provides to a specific customer, better or differently than alternatives. It answers: Why should this customer choose you? What problem do you solve? What value do you create? A strong value proposition is specific, not generic ("We sell quality products at good prices" is not a value proposition — everyone claims this). Example: "We deliver cooked meals to office workers in Freetown within 30 minutes."',
[('The total monetary value of your business assets', False), ('A clear statement of the specific benefit you provide to customers better than alternatives', True), ('The price at which you sell your products or services', False), ('A promise to investors about the return they will receive', False)]),
('What is a business plan and do you always need one?', 'multiple_choice',
'A business plan is a written document describing your business, market, products/services, operations, team and financial projections. For large businesses seeking investment or loans, a formal plan is essential. For small startups, a shorter plan — even a one-page summary — forces you to think through key questions: Who are my customers? What will I charge? What are my costs? How will I find customers? The discipline of planning, not the length of the document, is what matters.',
[('A legal requirement for any registered business in West Africa', False), ('A written description of your business, market and financials — essential for loans and investment', True), ('A day-by-day schedule of all activities for the first year of business', False), ('A plan is unnecessary for small businesses — just start and adjust as you go', False)]),
('What is market research and why should you do it before starting a business?', 'multiple_choice',
'Market research is gathering information about potential customers, their needs, existing competitors and market size before launching. It prevents the most common startup mistake: building a product or service nobody wants at the price you need to charge. Methods: talk to potential customers (cheapest and most valuable), observe competitor businesses, survey your target market, research online. The information gathered shapes every other business decision.',
[('Studying the stock market to decide when to invest your startup capital', False), ('Gathering information about customers, competitors and market size before launching', True), ('Researching the legal requirements for registering your business type', False), ('Analysing reports published by large research companies about industry trends', False)]),
('What is the break-even point?', 'multiple_choice',
'The break-even point is the level of sales at which total revenue equals total costs — you are making neither profit nor loss. Every sale above break-even generates profit; every sale below means a loss. Calculating break-even before starting tells you: how many units must I sell monthly to survive? Is that realistic given my market? Break-even = Fixed costs divided by (Selling price per unit minus Variable cost per unit).',
[('The point at which a business has paid off all its startup debt', False), ('The sales level at which total revenue equals total costs — no profit, no loss', True), ('The moment when a business first becomes profitable', False), ('The maximum capacity a business can produce without hiring more staff', False)]),
('What is the difference between a sole trader and a limited company?', 'multiple_choice',
'A sole trader is an individual running a business in their own name. They keep all profits but are personally liable for all debts — creditors can come after personal assets. A limited company is a separate legal entity. The company can own assets and incur debts. Shareholders\' personal assets are protected (limited liability). The company is more complex to set up and has reporting requirements, but protects the owner and can have multiple shareholders.',
[('A sole trader has employees; a limited company is run by one person only', False), ('Sole trader = personal liability for all debts; limited company = separate entity with limited liability', True), ('A sole trader is informal; a limited company must be registered with the government', False), ('There is no practical difference — both pay the same taxes and face the same legal risks', False)]),
('What is customer retention and why does it matter more than customer acquisition?', 'multiple_choice',
'Customer retention means keeping existing customers coming back. Research consistently shows acquiring a new customer costs 5-7 times more than retaining an existing one. Existing customers buy more frequently, spend more per transaction, and refer new customers through word of mouth. A business focused only on finding new customers while losing existing ones is running to stand still. Exceptional service, consistent quality and personal relationships drive retention.',
[('Legally preventing customers from switching to competitors', False), ('Keeping existing customers coming back — cheaper and more profitable than always finding new ones', True), ('A strategy used only by large businesses with established customer bases', False), ('Offering customers credit to retain their loyalty long-term', False)]),
('What is a cash flow forecast?', 'multiple_choice',
'A cash flow forecast projects when money will come in and go out over a future period (typically monthly for a year). It shows in advance when the business might run short of cash — allowing the owner to plan: arrange a short-term loan, delay a large purchase, accelerate debt collection. Most businesses that fail do so not because they are unprofitable but because they run out of cash at a critical moment. Forecasting prevents this.',
[('A record of all cash transactions in the previous accounting period', False), ('A projection of future cash inflows and outflows to anticipate shortfalls', True), ('A bank statement showing current account balances', False), ('A plan for investing surplus cash in savings accounts or assets', False)]),
('What does it mean to "know your numbers" as an entrepreneur?', 'multiple_choice',
'Knowing your numbers means having current, accurate knowledge of: your monthly revenue and expenses, your profit margin, your cash position, your debtor and creditor balances, your break-even point, and your key cost drivers. Entrepreneurs who do not know these cannot make good decisions. They cannot tell if the business is growing or shrinking, which products are profitable, or when they will run out of cash. Numbers are the vital signs of a business.',
[('Having memorised all your supplier prices', False), ('Having accurate current knowledge of revenue, costs, margins, cash position and key metrics', True), ('Using accounting software to automatically track all transactions', False), ('Knowing how many customers you have served since you started', False)]),
('What is the most important marketing tool for a small business in West Africa?', 'multiple_choice',
'Word of mouth — satisfied customers telling others — is consistently the most powerful and cost-effective marketing for small businesses in West Africa. In high-trust, relationship-based economies, a recommendation from a trusted person is more persuasive than any advertisement. Delivering exceptional quality and service turns customers into advocates. WhatsApp and social media amplify word of mouth — a satisfied customer sharing your work reaches hundreds of their contacts instantly.',
[('Paid advertising on Facebook and Instagram', False), ('Word of mouth — satisfied customers telling others — amplified by WhatsApp and social media', True), ('Printing flyers and distributing them at markets and transport hubs', False), ('Registering the business on Google Maps so customers can find it online', False)]),
])

# ============================================================
# FINANCIAL MANAGEMENT
# ============================================================
create_quiz('Financial Management', 'Financial Management — Final Assessment',
'Financial management is the skill that determines whether a business survives and grows or struggles and fails. This assessment tests your understanding of business finance.',
25, [
('What is working capital?', 'multiple_choice',
'Working capital is the money available to fund day-to-day business operations — buying stock, paying wages, covering expenses before customers pay. It is calculated as Current Assets minus Current Liabilities. Positive working capital means the business can meet its short-term obligations. Negative working capital is a danger sign — the business cannot cover its near-term costs. Insufficient working capital is one of the most common causes of business failure.',
[('The money invested by the owner to start the business', False), ('Current assets minus current liabilities — money available for day-to-day operations', True), ('The total value of all business assets including long-term property', False), ('The weekly wage bill for all employees of the business', False)]),
('What is depreciation?', 'multiple_choice',
'Depreciation is the gradual reduction in value of assets over time due to use, wear and age. A vehicle bought for Le 50,000,000 will be worth less each year as it ages. In accounting, depreciation is recorded as an expense even though no cash leaves the business — it reflects the real cost of using the asset. Understanding depreciation helps you plan for asset replacement and correctly calculate the true cost of running your business.',
[('The decrease in currency value due to inflation', False), ('The gradual reduction in asset value over time, recorded as a business expense', True), ('A tax deduction available to businesses for large purchases', False), ('The amount a business owes to its creditors that reduces over time', False)]),
('What is gross profit versus net profit?', 'multiple_choice',
'Gross profit = Revenue minus Cost of Goods Sold (the direct cost of what you sold). Net profit = Gross profit minus all operating expenses (rent, wages, utilities, depreciation, marketing). Gross profit shows if your core trading activity is profitable. Net profit shows if the overall business is profitable after all overhead costs. A business with good gross profit but losses at net profit level has overhead costs that are too high relative to its sales.',
[('Gross profit is before tax; net profit is after tax is deducted', False), ('Gross profit = revenue minus cost of goods; net profit = gross profit minus all operating expenses', True), ('Gross profit is for large businesses; net profit is for small traders', False), ('They are calculated the same way — net just sounds more professional', False)]),
('What is a balance sheet?', 'multiple_choice',
'A balance sheet is a financial statement showing what a business owns (assets), what it owes (liabilities), and the owner\'s stake in the business (equity) at a specific point in time. Assets always equal Liabilities plus Equity — this is why it "balances." It is one of the three core financial statements (with the income statement and cash flow statement) that together give a complete picture of a business\'s financial health.',
[('A document listing all bank account transactions for the month', False), ('A financial statement showing assets, liabilities and equity at a point in time', True), ('A comparison of actual versus budgeted financial performance', False), ('A record of all loans and credit extended to customers', False)]),
('What is the purpose of a budget in business?', 'multiple_choice',
'A budget is a financial plan setting targets for income and expenditure over a future period. It provides a benchmark to measure actual performance against — if actual costs exceed budget, investigate why. Budgets force planning: you cannot budget without thinking about what revenue is realistic and what costs will be incurred. Businesses that budget consistently perform better than those that simply react to whatever happens.',
[('A restriction imposed by banks when they lend money to a business', False), ('A financial plan setting income and expenditure targets to guide and measure performance', True), ('A record of all money spent in the previous financial year', False), ('A legal requirement for businesses above a certain annual turnover', False)]),
('What does ROI stand for and how is it calculated?', 'multiple_choice',
'ROI stands for Return on Investment. It measures the profit generated from an investment as a percentage of the investment cost. ROI = (Net profit from investment divided by Cost of investment) times 100. Example: you invest Le 500,000 in a new piece of equipment and it generates Le 200,000 additional profit in a year. ROI = Le 200,000 divided by Le 500,000 times 100 = 40%. ROI allows you to compare different investment options.',
[('Rate of Interest — the interest paid on business loans', False), ('Return on Investment — profit from an investment as a percentage of its cost', True), ('Revenue over Income — the ratio of total revenue to net income', False), ('Risk of Insolvency — a measure of financial stability', False)]),
('What is the debt-to-equity ratio and what does it indicate?', 'multiple_choice',
'Debt-to-equity ratio = Total liabilities divided by Owner\'s equity. It shows how much of the business is funded by debt versus owner\'s own capital. A ratio above 1 means more of the business is financed by creditors than by the owner — increasing financial risk. Banks assess this ratio when considering loans. High debt-to-equity means the business is more vulnerable to interest rate rises and economic downturns.',
[('How much of the business revenue is used to repay debt each month', False), ('Total liabilities divided by equity — showing the balance between debt and owner funding', True), ('The ratio of long-term debt to short-term debt in the business', False), ('The proportion of profits paid to equity investors versus retained in the business', False)]),
('What is accounts receivable?', 'multiple_choice',
'Accounts receivable is money owed to your business by customers who have received goods or services but not yet paid — your debtors. It is an asset on the balance sheet because you are owed the money. High accounts receivable with slow collection is a cash flow risk — you have made the sales but not received the cash. Good management includes: clear payment terms, prompt invoicing, regular statements and active follow-up on overdue amounts.',
[('Money your business owes to suppliers for goods received but not yet paid', False), ('Money owed to your business by customers who have not yet paid — your debtors', True), ('The bank account into which all customer payments are received', False), ('Revenue from recurring subscription customers who pay automatically', False)]),
('What is the most important financial ratio for assessing a business\'s short-term survival?', 'multiple_choice',
'The current ratio (Current Assets divided by Current Liabilities) measures whether the business can meet its short-term obligations using its short-term assets. A ratio above 1.5 is generally healthy. Below 1.0 means current liabilities exceed current assets — the business cannot cover its near-term obligations without additional funding. This is the earliest warning sign of potential insolvency. Monitoring this ratio monthly is essential.',
[('The profit margin — showing whether the business makes sufficient profit', False), ('The current ratio — current assets divided by current liabilities, showing short-term survival ability', True), ('The gross margin — showing the profitability of core trading activity', False), ('The debt-to-equity ratio — showing overall financial leverage', False)]),
('What is the difference between fixed costs and variable costs?', 'multiple_choice',
'Fixed costs remain the same regardless of how much you produce or sell: rent, loan repayments, permanent salaries, insurance. Variable costs change with production or sales volume: raw materials, packaging, sales commissions, delivery costs. Understanding this distinction is essential for pricing and profitability analysis. When sales fall, variable costs fall with them but fixed costs remain — this is why fixed costs are the biggest risk in a downturn.',
[('Fixed costs are paid annually; variable costs are paid monthly', False), ('Fixed costs are constant regardless of output; variable costs change with production volume', True), ('Fixed costs are for large businesses; small traders only have variable costs', False), ('Fixed costs are predictable; variable costs cannot be predicted or managed', False)]),
])

# ============================================================
# FINANCIAL MANAGEMENT FOR SELF-EMPLOYMENT
# ============================================================
create_quiz('Financial Management for Self-Employment', 'Financial Management for Self-Employment — Final Assessment',
'Self-employed people face unique financial challenges. This assessment tests your ability to manage money when you are both the worker and the business owner.',
20, [
('What is the most common financial mistake made by self-employed people?', 'multiple_choice',
'Not separating personal and business money is the most common and damaging financial mistake for self-employed people. When business and personal funds mix: you cannot know your true profit, you accidentally spend business capital on personal needs, you cannot produce accurate records for tax or loans, and you lose control of both your business and personal finances simultaneously. The solution is a dedicated business account or cash box that never funds personal expenses.',
[('Not having a university degree in accounting', False), ('Mixing personal and business money making it impossible to track either accurately', True), ('Not investing in expensive accounting software from the beginning', False), ('Taking too much salary from the business', False)]),
('How should a self-employed person pay themselves?', 'multiple_choice',
'Set a fixed regular amount as your salary (called drawings or owner\'s salary) and pay it to yourself consistently — not by dipping into business cash whenever you need money. Calculate what the business can sustainably afford. Pay yourself on a regular schedule (weekly or monthly). This creates predictability for both personal and business finances, makes records clean, and forces discipline in separating business performance from personal income.',
[('Take whatever cash is in the business when personal needs arise', False), ('Set a fixed regular salary amount and pay it to yourself on a consistent schedule', True), ('Only take money from the business in months when profits are high', False), ('Reinvest all profits into the business and live on savings until the business grows', False)]),
('How should a self-employed person plan for tax?', 'multiple_choice',
'Set aside a percentage of every payment received into a separate tax savings account — the moment you receive it, not at year end. A common approach is to set aside 25-30% of net income for tax. This prevents the shock of a large tax bill that you cannot afford because you have already spent the money. Keep all receipts and records of business expenses — these reduce your taxable income legally.',
[('Pay tax only if the tax authority contacts you', False), ('Set aside a percentage of every payment received into a dedicated tax savings account', True), ('Register as a limited company so you do not need to pay personal tax', False), ('Tax is not a concern until your income exceeds Le 100,000,000 per year', False)]),
('What is an emergency fund for a self-employed person?', 'multiple_choice',
'Self-employed income is irregular — some months are excellent, others are poor. An emergency fund of 3-6 months of essential living expenses provides security during slow months, illness, equipment failure or any gap between contracts. Without one, a bad month becomes a crisis. Build the emergency fund gradually: set aside 10-20% of every good month until the fund reaches target. Only access it for genuine emergencies, not lifestyle expenses.',
[('A loan facility at the bank available when income is insufficient', False), ('3-6 months of essential living expenses saved to cover slow income periods', True), ('Government benefits available to self-employed people in Sierra Leone', False), ('A business insurance policy that pays out if the business fails', False)]),
('What expenses can legitimately be deducted from business income to reduce taxable profit?', 'multiple_choice',
'Legitimate business expenses that reduce taxable profit include: materials and stock purchased for the business, tools and equipment used for work, transport directly related to work (fuel, vehicle maintenance), phone and internet for business use, rent for a business premises, professional fees, and advertising costs. Personal expenses — household food, personal clothing, family holidays — cannot be deducted. Keep receipts for everything and record them contemporaneously.',
[('Any expense that reduces your personal financial burden', False), ('Legitimate business expenses: stock, tools, work transport, premises, professional fees', True), ('Only expenses above Le 100,000 are worth recording for tax purposes', False), ('Self-employed people cannot deduct any expenses — only limited companies can', False)]),
('What should you do when a client delays payment beyond the agreed date?', 'multiple_choice',
'Contact them promptly and professionally — not aggressively. A polite reminder email or call on the first day overdue. If no response, follow up again within 3 days. Escalate politely but firmly: "I need to resolve this outstanding invoice to continue our work together." Always maintain records of all payment communications. For significant amounts, consider a formal written demand. Silence and waiting almost never results in faster payment — proactive, professional follow-up does.',
[('Wait patiently — clients always pay eventually and chasing them damages the relationship', False), ('Contact them promptly and professionally with a polite but firm follow-up', True), ('Stop all work immediately and refuse any further communication until paid', False), ('Accept partial payment and write off the rest as bad debt', False)]),
('What is invoice factoring?', 'multiple_choice',
'Invoice factoring is a financial service where a factoring company buys your unpaid invoices for an immediate cash payment (typically 80-90% of the invoice value). The factoring company then collects payment from your client and takes a fee (typically 2-5% of invoice value). It solves the cash flow problem of waiting 30-90 days for clients to pay. Useful for growing businesses with reliable commercial clients but persistent cash flow gaps.',
[('A method of splitting a large invoice into smaller monthly payments for the client', False), ('Selling unpaid invoices to a third party for immediate cash, minus a fee', True), ('Creating false invoices to access business financing — an illegal practice', False), ('A discount offered to clients who pay invoices early', False)]),
('How should a self-employed person track income when clients pay in cash?', 'multiple_choice',
'Issue a numbered receipt for every cash payment immediately. Record it in your income book on the same day. Count cash at the end of each day and reconcile against receipts issued. Never let cash income go unrecorded — even for small amounts. The discipline of recording every transaction protects you: you know your true income, you can prove earnings if audited, and you prevent the gradual erosion of income through unrecorded transactions.',
[('Cash income does not need to be recorded if the client does not require a receipt', False), ('Issue a numbered receipt immediately and record in your income book the same day', True), ('Only record cash payments above a certain threshold to save time', False), ('Bank all cash immediately so the bank statement serves as the record', False)]),
('What is the most important document a self-employed person should issue before starting work?', 'multiple_choice',
'A written quotation or proposal (or at minimum a written agreement) before any work begins. This document defines: what work will be done, the price, payment terms (when and how), and what is excluded from the scope. When disputes arise — and they do — the written agreement is the reference point. Without it, you are relying on memory and goodwill. Even a simple WhatsApp message confirming the agreed price is better than nothing.',
[('A business card so the client has your contact details', False), ('A written quotation or agreement defining the work, price and payment terms before starting', True), ('A tax clearance certificate showing your taxes are up to date', False), ('An invoice (sent after the work is done and payment is due)', False)]),
('What is the "feast and famine" cycle in self-employment?', 'multiple_choice',
'The feast and famine cycle is when self-employed people are either overloaded with work (feast) or have no work at all (famine), with little in between. It happens because: during busy periods they focus entirely on delivery and stop marketing, so when work ends there are no new clients in the pipeline. The solution is consistent marketing activity even during busy periods, building a pipeline of future work, and saving aggressively during feast periods to fund famine periods.',
[('A seasonal pattern where business is always busy in December and quiet in January', False), ('Alternating periods of overwork and no work caused by stopping marketing during busy periods', True), ('The financial cycle of a restaurant business tied to meal service times', False), ('A legal term for self-employed people who earn above and below the tax threshold alternately', False)]),
])

# ============================================================
# SECONDARY MATHEMATICS
# ============================================================
create_quiz('Secondary Mathematics', 'Secondary Mathematics — Final Assessment',
'This assessment covers the secondary-level mathematics that underpins science, technology, engineering, business and everyday problem-solving.',
30, [
('What is a quadratic equation and what is the standard form?', 'multiple_choice',
'A quadratic equation has the standard form ax² + bx + c = 0, where a, b and c are constants and a ≠ 0. The highest power of x is 2 (squared). Quadratics model many real-world situations: projectile motion, area problems, profit optimisation. They can be solved by factoring, completing the square, or the quadratic formula: x = (-b ± √(b²-4ac)) / 2a. The discriminant (b²-4ac) tells you: positive = two solutions, zero = one solution, negative = no real solutions.',
[('An equation with one unknown variable raised to the power of 1', False), ('An equation where the highest power of the variable is 2, in the form ax² + bx + c = 0', True), ('Any equation involving multiplication of two variables', False), ('An equation requiring exactly four steps to solve', False)]),
('What is the Pythagoras theorem?', 'multiple_choice',
'In a right-angled triangle, the square of the hypotenuse (the longest side, opposite the right angle) equals the sum of the squares of the other two sides: a² + b² = c². This theorem is used constantly in construction, engineering, navigation and design. A carpenter checking that a corner is square uses the 3-4-5 rule (a special Pythagorean triple: 3² + 4² = 5²). Understanding Pythagoras is essential for any technical career.',
[('The sum of angles in any triangle always equals 180 degrees', False), ('In a right-angled triangle, c² = a² + b² where c is the hypotenuse', True), ('The area of a triangle equals half the base times the height', False), ('Parallel lines cut by a transversal create equal alternate angles', False)]),
('What is the difference between mean, median and mode?', 'multiple_choice',
'Mean: add all values and divide by the count. Median: the middle value when sorted. Mode: the most frequently occurring value. Each has advantages: mean uses all data but is distorted by outliers; median is not affected by extreme values (better for income data where a few very high earners distort the mean); mode works for categorical data. Understanding which measure to use — and which is being reported — is critical for interpreting statistics.',
[('They are three names for the same calculation — the average', False), ('Mean = average of all; median = middle value; mode = most frequent value', True), ('Mean is for continuous data; median for discrete data; mode for categorical only', False), ('Mean is the most accurate; median and mode are approximations', False)]),
('What is a ratio and how is 3:2 simplified?', 'multiple_choice',
'A ratio compares two quantities. 3:2 is already in its simplest form because 3 and 2 share no common factor greater than 1. 6:4 simplifies to 3:2 (divide both by 2). 15:10 simplifies to 3:2 (divide both by 5). Ratios are used in mixing (concrete, paint, medicine), scaling (maps, blueprints), and business (profit sharing, ingredient proportions). To share Le 500,000 in the ratio 3:2: total parts = 5, one part = Le 100,000, share 1 = Le 300,000, share 2 = Le 200,000.',
[('3:2 can be simplified to 1.5:1 by dividing both by 2', False), ('3:2 is already in simplest form — 3 and 2 share no common factor', True), ('3:2 simplifies to 3/2 = 1.5, a decimal', False), ('Ratios can only be simplified when both numbers are even', False)]),
('What is the gradient (slope) of a straight line?', 'multiple_choice',
'The gradient of a straight line measures its steepness: how much y changes for each unit increase in x. Gradient = (change in y) / (change in x) = (y₂ - y₁) / (x₂ - x₁). Positive gradient: line goes up left to right. Negative: goes down. Zero: horizontal line. Undefined: vertical line. In the equation y = mx + c, m is the gradient and c is the y-intercept. Gradient is used in engineering (road slopes), economics (marginal cost) and physics (velocity from distance-time graphs).',
[('The length of the line from one end to the other', False), ('The rate of change: how much y changes per unit change in x', True), ('The angle the line makes with the horizontal in degrees', False), ('The point where the line crosses the x-axis', False)]),
('What is a probability of 0.25 equivalent to?', 'multiple_choice',
'Probability of 0.25 = 25% = 1/4. Probability is always between 0 (impossible) and 1 (certain). 0.25 means a 25% chance — this event is expected to occur 1 time in every 4 trials on average. Probability is used in insurance (risk assessment), medicine (treatment success rates), business (demand forecasting) and everyday decision-making. Understanding probability prevents both over- and under-estimation of risk.',
[('A 2.5% chance of the event occurring', False), ('A 25% chance — equivalent to 1/4 or 1 in 4', True), ('A 75% chance — the complement of 0.75', False), ('Impossible to convert probability to percentage', False)]),
('What is simple interest and how is it calculated?', 'multiple_choice',
'Simple interest = Principal × Rate × Time. Example: Le 1,000,000 at 10% per year for 3 years: interest = Le 1,000,000 × 0.10 × 3 = Le 300,000. Total repayable = Le 1,300,000. Compound interest (more common in reality) also charges interest on accumulated interest, making it grow faster. Understanding both helps you evaluate loans and savings products accurately and avoid being misled by financial advertising.',
[('Divide the principal by the interest rate', False), ('Principal × Rate × Time — for example Le 1,000,000 at 10% for 3 years = Le 300,000 interest', True), ('Interest charged only on the first month then waived', False), ('A fixed fee charged once regardless of the loan duration', False)]),
('What is a function in mathematics?', 'multiple_choice',
'A function is a rule that assigns exactly one output value to each input value. Written f(x), it maps every x to exactly one y. Example: f(x) = 2x + 3 means for any input x, multiply by 2 and add 3. f(5) = 13. Functions model relationships: distance as a function of time, cost as a function of quantity, temperature as a function of altitude. Every spreadsheet formula is a function. Understanding functions is the gateway to advanced mathematics and programming.',
[('A mathematical equation with two or more unknown variables', False), ('A rule assigning exactly one output to each input — every x maps to exactly one y', True), ('A graph showing how two variables are related', False), ('Any calculation that produces a result', False)]),
('If 3x + 7 = 22, what is x?', 'multiple_choice',
'Solving: 3x + 7 = 22. Subtract 7 from both sides: 3x = 15. Divide both sides by 3: x = 5. Check: 3(5) + 7 = 15 + 7 = 22. ✓ Solving linear equations is the foundation of all algebra. The principle is always the same: isolate the unknown by performing the same operation on both sides. Equations model every quantitative problem in science, business and engineering.',
[('x = 3', False), ('x = 5', True), ('x = 7', False), ('x = 15', False)]),
('What is the area of a circle with radius 7cm? (Use π ≈ 3.14)', 'multiple_choice',
'Area of a circle = π × r². With radius 7cm: Area = 3.14 × 7² = 3.14 × 49 = 153.86 cm². Round to 153.9 cm². Circle area calculations are used in engineering (pipe cross-sections), construction (circular tanks and columns), manufacturing (cutting circular pieces) and many other applications. π (pi) is approximately 3.14159 — using 3.14 gives a good approximation for most practical purposes.',
[('21.98 cm²', False), ('43.96 cm²', False), ('153.86 cm²', True), ('219.8 cm²', False)]),
])

# ============================================================
# SECONDARY ENGLISH LANGUAGE
# ============================================================
create_quiz('Secondary English Language', 'Secondary English Language — Final Assessment',
'Secondary-level English covers literature, language analysis, formal writing and communication skills that prepare for examinations and professional life.',
25, [
('What is the difference between denotation and connotation?', 'multiple_choice',
'Denotation is the literal, dictionary definition of a word. Connotation is the emotional or cultural association the word carries. "Home" and "house" have similar denotations (a building where people live) but different connotations: "home" suggests warmth, belonging and comfort; "house" is more neutral and structural. Writers choose words deliberately for their connotations. Analysing word choice (diction) is a key skill in literature and language examination.',
[('Denotation is the spoken meaning; connotation is the written meaning', False), ('Denotation is the literal dictionary meaning; connotation is the emotional or cultural association', True), ('Both terms mean the same thing — the definition of a word', False), ('Denotation applies to nouns; connotation applies to adjectives', False)]),
('What is the purpose of a thesis statement in an essay?', 'multiple_choice',
'A thesis statement is a single sentence at the end of the introduction that clearly states the main argument or position of the entire essay. It tells the reader exactly what the essay will argue and why. Every paragraph in the essay should support and develop the thesis. A strong thesis is specific (not "This essay is about..."), debatable (not an obvious fact), and clear. Essays without a clear thesis lack direction and lose marks in examinations.',
[('To summarise all the points that will be made in the essay', False), ('To state the main argument clearly in a single sentence that the whole essay supports', True), ('To introduce the topic and provide background information for the reader', False), ('To acknowledge counter-arguments before making the main point', False)]),
('What are the five elements of a short story?', 'multiple_choice',
'The five key elements of narrative fiction: Plot (sequence of events — exposition, rising action, climax, falling action, resolution), Setting (time and place), Characters (protagonist, antagonist, supporting characters), Conflict (internal or external struggle driving the story), and Theme (the underlying message or truth about human experience). Understanding these elements allows analysis of any text and guides your own creative writing.',
[('Introduction, argument, evidence, counter-argument and conclusion', False), ('Plot, setting, characters, conflict and theme', True), ('Narrator, dialogue, description, action and ending', False), ('Beginning, middle and end — with a moral lesson at the end', False)]),
('What is an extended metaphor?', 'multiple_choice',
'An extended metaphor develops a single comparison across multiple sentences, stanzas or an entire text rather than using it in just one phrase. If a poem compares life to a journey in the first stanza, then continues developing the journey metaphor (roads, destinations, companions, weather) throughout, it is an extended metaphor. Extended metaphors create rich, sustained imagery that deepens meaning. They are common in poetry and literary prose.',
[('A very long metaphor that uses more than ten words', False), ('A comparison developed across multiple lines or sections rather than used once', True), ('A metaphor comparing two things from different cultures', False), ('Using the same metaphor in two different pieces of writing', False)]),
('What is the effect of short sentences in prose writing?', 'multiple_choice',
'Short sentences create: speed (the reader moves through them quickly, creating urgency), tension (in suspenseful or dramatic moments), impact (a short sentence after long ones hits hard), and directness (clear, unambiguous statements). "He ran. He fell. He did not get up." — the short sentences force the reader to experience each moment separately, creating more impact than one long sentence would. Good writers vary sentence length deliberately for effect.',
[('Short sentences indicate the writer has a limited vocabulary', False), ('Short sentences create speed, tension, impact and directness — used deliberately for effect', True), ('Short sentences are used in children\'s books but avoided in literary writing', False), ('Short sentences reduce the word count without reducing meaning', False)]),
('What is the difference between first-person and third-person narrative?', 'multiple_choice',
'First-person narrative uses "I" — the narrator is a character in the story telling events from their own perspective. This creates intimacy and immediacy but limits what we know to what the narrator experiences. Third-person narrative uses "he/she/they" — the narrator is outside the story. Third-person omniscient can reveal any character\'s thoughts. Third-person limited stays close to one character. Each perspective creates different effects on the reader\'s relationship with characters and events.',
[('First-person means the story happens in the present; third-person is in the past', False), ('First-person narrator is a character using "I"; third-person narrator is outside the story', True), ('First-person is for fiction; third-person is used in non-fiction only', False), ('Third-person narratives are always more reliable than first-person', False)]),
('What is irony?', 'multiple_choice',
'Verbal irony: saying the opposite of what you mean (calling a very tall person "Shorty"). Situational irony: when what happens is the opposite of what was expected (a fire station burns down). Dramatic irony: when the audience knows something a character does not. Irony creates complexity, humour and meaning in literature. Recognising and analysing irony is a key examination skill — examiners often ask about its effect on the reader.',
[('Using very dramatic language to exaggerate a point for effect', False), ('A contrast between what is said/expected and what actually occurs or is meant', True), ('Repeating an idea in different words to emphasise its importance', False), ('Using old-fashioned language to create a historical atmosphere', False)]),
('What is the correct structure for a PEEL paragraph in an essay?', 'multiple_choice',
'PEEL: Point (state the argument of this paragraph clearly), Evidence (quote or reference from the text that supports it), Explanation (analyse how the evidence supports your point — do not just quote and leave it), Link (connect back to the essay question or thesis). This structure ensures every paragraph is focused, evidenced and analytical rather than descriptive. It is the standard essay paragraph structure for WAEC and most secondary examinations.',
[('Paragraph, Example, Elaboration, Language analysis', False), ('Point, Evidence, Explanation, Link back to the question', True), ('Plan, Explore, Evaluate, Locate more evidence', False), ('Premise, Evidence, Extension, Limitation', False)]),
('What distinguishes a formal essay from an informal one?', 'multiple_choice',
'Formal essays: third person (avoid "I think"), no contractions (cannot not can\'t), advanced vocabulary, complex sentence structures, referenced evidence, objective tone, no colloquialisms or slang. Informal essays may use first person, contractions, conversational language and personal anecdote. WAEC examinations always require formal essay writing. Mixing formal and informal register in a single essay is a common error that costs marks.',
[('Formal essays are longer; informal essays can be any length', False), ('Formal essays use third person, no contractions, advanced vocabulary and objective tone', True), ('Formal essays always require a bibliography; informal essays do not', False), ('Formal essays are only for university; secondary school uses informal style', False)]),
('What is the most effective way to conclude an essay?', 'multiple_choice',
'An effective conclusion: restates the thesis in different words (not copied), briefly summarises the main points made, and leaves the reader with a final thought — a broader implication, a call to action, a thought-provoking question, or a return to an image or idea from the introduction (called a "circular structure"). It should NOT introduce new arguments or evidence. It should give the reader a sense of completion and reinforce the essay\'s central argument.',
[('Introduce the strongest argument that was saved for the end', False), ('Restate the thesis in new words, summarise main points and leave with a final thought', True), ('Ask several questions to make the reader continue thinking independently', False), ('Copy the introduction with minor changes to remind the reader of the starting point', False)]),
])

# ============================================================
# SECONDARY BIOLOGY
# ============================================================
create_quiz('Secondary Biology', 'Secondary Biology — Final Assessment',
'Biology is the study of living things — from cells to ecosystems. This assessment covers the key concepts that underpin all life sciences.',
25, [
('What is the basic unit of all living organisms?', 'multiple_choice',
'The cell is the basic structural and functional unit of all living organisms. All cells share: a cell membrane (controls what enters and exits), cytoplasm (fluid containing organelles), and DNA (genetic information). Plant cells also have: cell wall (rigid support), chloroplasts (for photosynthesis), and large central vacuole. Animal cells lack these plant-specific structures. Understanding cell structure is the foundation of all biology.',
[('The atom — the smallest particle of matter', False), ('The cell — the basic structural and functional unit of all living organisms', True), ('The organ — the unit that carries out specific body functions', False), ('The gene — the unit of hereditary information', False)]),
('What is photosynthesis?', 'multiple_choice',
'Photosynthesis is the process by which plants convert light energy into chemical energy (glucose). Equation: 6CO₂ + 6H₂O + light energy → C₆H₁₂O₆ + 6O₂. It occurs in chloroplasts (containing chlorophyll which absorbs light). Oxygen is released as a by-product. Photosynthesis is the foundation of almost all food chains — it converts solar energy into the chemical energy that flows through ecosystems. Without it, almost no life on Earth would be possible.',
[('The process by which organisms break down glucose to release energy', False), ('The process by which plants convert light energy into glucose using CO₂ and water', True), ('The process by which plants absorb water and minerals from the soil', False), ('The reproduction of plants through seeds and pollination', False)]),
('What is the difference between mitosis and meiosis?', 'multiple_choice',
'Mitosis produces two genetically identical diploid daughter cells — used for growth, repair and asexual reproduction. Meiosis produces four genetically unique haploid cells (gametes — sperm and eggs) — used for sexual reproduction. Meiosis involves two divisions and includes genetic recombination (crossing over), which creates genetic variation. Sexual reproduction creates diversity; asexual reproduction creates clones. Both are essential to life.',
[('Mitosis is for plants; meiosis is for animals', False), ('Mitosis produces 2 identical diploid cells; meiosis produces 4 unique haploid gametes', True), ('Mitosis happens in the nucleus; meiosis in the cytoplasm', False), ('They are the same process with different names in different countries', False)]),
('What is a food chain and what do arrows represent?', 'multiple_choice',
'A food chain shows the flow of energy from one organism to the next through feeding relationships. Example: Grass → Grasshopper → Frog → Snake → Eagle. Arrows represent the direction of energy flow — from the organism being eaten to the organism eating it. The first organism is always a producer (plant). Each subsequent organism is a consumer. Energy is lost at each step (as heat) — which is why food chains rarely exceed 5-6 links.',
[('Arrows show what each organism eats, pointing toward its food source', False), ('Arrows represent the direction of energy flow from prey to predator', True), ('Arrows indicate which organism controls the population of others', False), ('Food chains show competition between species for the same resources', False)]),
('What is the function of red blood cells?', 'multiple_choice',
'Red blood cells (erythrocytes) transport oxygen from the lungs to all body tissues and carry carbon dioxide back to the lungs for exhalation. They contain haemoglobin — the iron-containing protein that binds to oxygen. Red blood cells have no nucleus (more room for haemoglobin) and a biconcave shape (increases surface area for gas exchange). A deficiency of healthy red blood cells or haemoglobin causes anaemia — very common in West Africa, particularly in children and pregnant women.',
[('To fight infection by producing antibodies against pathogens', False), ('To transport oxygen from lungs to tissues and CO₂ from tissues to lungs', True), ('To carry nutrients absorbed from the digestive system to all cells', False), ('To produce hormones that regulate body processes', False)]),
('What is the role of the kidney?', 'multiple_choice',
'The kidneys filter blood, remove metabolic waste products (urea, excess salts), regulate blood water content (osmoregulation), and maintain blood pH. Each kidney contains approximately one million nephrons — the functional filtering units. Urine (water, urea, excess salts) is produced and passed to the bladder. Kidney disease allows waste to accumulate in the blood — eventually fatal if untreated. Drinking adequate water supports kidney function.',
[('To produce bile for digestion of fats in the small intestine', False), ('To filter blood, remove waste products and regulate water balance', True), ('To absorb nutrients from digested food into the bloodstream', False), ('To produce insulin to regulate blood glucose levels', False)]),
('What is DNA and what is its function?', 'multiple_choice',
'DNA (Deoxyribonucleic Acid) is the molecule that carries genetic information in all living organisms. It is structured as a double helix — two strands wound around each other, connected by base pairs (A-T and G-C). DNA contains genes — sequences of bases that code for proteins. Proteins determine structure and function of all cells. DNA replication ensures genetic information is passed to daughter cells during cell division. The sequence of DNA bases is unique to each individual (except identical twins).',
[('A protein that carries oxygen in red blood cells', False), ('The molecule carrying genetic information — a double helix coding for all proteins', True), ('An enzyme that breaks down nutrients in the digestive system', False), ('A hormone produced by the pancreas to regulate blood sugar', False)]),
('What is the difference between a virus and a bacterium?', 'multiple_choice',
'Bacteria are single-celled living organisms with their own metabolism. They can reproduce independently, respond to antibiotics, and can be beneficial (gut bacteria, fermentation) or harmful (cholera, tuberculosis). Viruses are not cells — they are protein coats around genetic material. They cannot reproduce independently; they hijack host cells to replicate. Viruses are not affected by antibiotics — antiviral drugs and vaccines are used instead. This distinction matters for treatment.',
[('Viruses are larger than bacteria and cause more serious disease', False), ('Bacteria are living cells; viruses are not cells and need host cells to reproduce', True), ('Bacteria are harmful; viruses can be beneficial to the body', False), ('Both are treated effectively with antibiotics', False)]),
('What is natural selection?', 'multiple_choice',
'Natural selection is the mechanism of evolution proposed by Charles Darwin. Organisms within a species show variation. Some variations are heritable (passed to offspring). Organisms with variations better suited to their environment survive and reproduce more successfully. Over many generations, beneficial traits become more common. This process, over long time periods, leads to the evolution of new species. Natural selection is the explanation for the diversity of life on Earth.',
[('The human practice of selectively breeding animals for desired traits', False), ('The process by which heritable variations that aid survival become more common over generations', True), ('The tendency of organisms to choose mates with the best genetic qualities', False), ('Random changes in species that occur over millions of years without any cause', False)]),
('What is the function of the alveoli in the lungs?', 'multiple_choice',
'Alveoli are tiny air sacs in the lungs where gas exchange occurs. Oxygen passes from inhaled air through the thin alveolar walls and surrounding capillary walls into the blood. Carbon dioxide passes in the opposite direction from blood to air. The alveoli have: very large total surface area (the size of a tennis court), very thin walls (one cell thick), good blood supply, and moist surfaces — all adaptations that maximise the rate of diffusion. Smoking damages alveoli, reducing gas exchange efficiency.',
[('To produce mucus that traps dust and bacteria before they reach the bloodstream', False), ('Tiny air sacs where oxygen passes into the blood and CO₂ passes out', True), ('To warm and humidify air before it reaches the gas exchange surface', False), ('To regulate the volume of air inhaled with each breath', False)]),
])

# ============================================================
# SECONDARY CHEMISTRY
# ============================================================
create_quiz('Secondary Chemistry', 'Secondary Chemistry — Final Assessment',
'Chemistry explains the composition and transformation of matter. This assessment covers the fundamental concepts of secondary chemistry.',
25, [
('What is an atom?', 'multiple_choice',
'An atom is the smallest unit of a chemical element that retains the properties of that element. It consists of a nucleus (protons and neutrons) surrounded by electrons in shells. The number of protons (atomic number) defines the element. Atoms of the same element with different numbers of neutrons are isotopes. Atoms combine to form molecules and compounds. Everything you can touch, taste, smell or see is made of atoms.',
[('The smallest visible particle that can be seen with a microscope', False), ('The smallest unit of an element — a nucleus of protons and neutrons surrounded by electrons', True), ('A molecule containing only one type of element', False), ('A charged particle found only in metals', False)]),
('What is the difference between a physical change and a chemical change?', 'multiple_choice',
'A physical change alters the form but not the chemical composition: melting ice (water remains H₂O), cutting paper, dissolving salt in water (retrievable by evaporation). A chemical change produces new substances with different properties: burning wood (produces CO₂ and water), rusting iron (produces iron oxide), cooking an egg. Chemical changes are generally irreversible. Signs of a chemical change: colour change, gas produced, temperature change, precipitate forms.',
[('Physical changes are reversible; chemical changes are also reversible with enough energy', False), ('Physical change alters form but not composition; chemical change produces new substances', True), ('Physical changes are caused by humans; chemical changes occur naturally', False), ('Physical changes affect solids; chemical changes affect liquids and gases', False)]),
('What is the pH scale?', 'multiple_choice',
'The pH scale measures acidity and alkalinity from 0 to 14. pH 7 is neutral (pure water). Below 7 is acidic (hydrochloric acid pH 1, vinegar pH 3, coffee pH 5). Above 7 is alkaline/basic (baking soda pH 9, bleach pH 12, caustic soda pH 14). Acids produce H⁺ ions in solution; bases produce OH⁻ ions. pH is critical in: agriculture (soil pH affects crop growth), medicine, water treatment and food science.',
[('A scale measuring the temperature at which a substance changes state', False), ('A scale from 0-14 measuring acidity (below 7) and alkalinity (above 7), neutral at 7', True), ('A measure of how quickly a chemical reaction occurs', False), ('A scale measuring the concentration of a solution in grams per litre', False)]),
('What is a chemical formula and what does H₂O represent?', 'multiple_choice',
'A chemical formula shows the elements in a compound and the ratio of their atoms. H₂O: H = hydrogen, O = oxygen, the 2 means 2 hydrogen atoms per molecule. So each water molecule contains 2 hydrogen atoms and 1 oxygen atom. CO₂ = 1 carbon + 2 oxygen. NaCl = 1 sodium + 1 chlorine (table salt). Understanding chemical formulas is fundamental to all chemistry.',
[('H₂O means hydrogen is twice as reactive as oxygen', False), ('H₂O means each water molecule contains 2 hydrogen atoms and 1 oxygen atom', True), ('H₂O is the formula only for distilled water — tap water has a different formula', False), ('The 2 in H₂O represents the number of bonds between hydrogen and oxygen', False)]),
('What is oxidation and reduction?', 'multiple_choice',
'In redox reactions: Oxidation is loss of electrons (or gain of oxygen); Reduction is gain of electrons (or loss of oxygen). OIL RIG: Oxidation Is Loss, Reduction Is Gain (of electrons). They always occur together — one substance is oxidised while another is reduced. Rusting is oxidation of iron. Combustion is oxidation. Respiration involves redox reactions. Understanding redox is essential for electrochemistry, batteries, corrosion and metabolism.',
[('Oxidation adds oxygen to a compound; reduction removes oxygen', False), ('Oxidation = loss of electrons; Reduction = gain of electrons — OIL RIG', True), ('Both are names for the same process depending on the country', False), ('Oxidation occurs in acids; reduction occurs in alkaline solutions', False)]),
('What is a catalyst?', 'multiple_choice',
'A catalyst is a substance that increases the rate of a chemical reaction without being consumed in the reaction — it remains unchanged at the end. Catalysts work by providing an alternative reaction pathway with lower activation energy. Industrial examples: iron catalyst in the Haber process (making ammonia for fertiliser), platinum in catalytic converters (reducing vehicle emissions). Biological catalysts are called enzymes — they catalyse all biochemical reactions in living things.',
[('A substance that starts a chemical reaction by providing energy', False), ('A substance that speeds up a reaction without being consumed in the process', True), ('A chemical that prevents unwanted reactions from occurring', False), ('An acidic substance that breaks down other compounds', False)]),
('What are the products of complete combustion of a hydrocarbon?', 'multiple_choice',
'Complete combustion of a hydrocarbon (like methane, petrol, diesel) in excess oxygen produces carbon dioxide (CO₂) and water (H₂O): CH₄ + 2O₂ → CO₂ + 2H₂O. Incomplete combustion (insufficient oxygen) produces carbon monoxide (CO — toxic) and carbon (soot). This is why adequate ventilation is critical when burning fuels indoors. CO from incomplete combustion is colourless and odourless — it poisons without warning.',
[('Carbon and hydrogen are produced as the hydrocarbon breaks down', False), ('Carbon dioxide and water — or carbon monoxide and soot if oxygen is insufficient', True), ('Nitrogen and oxygen are released back into the atmosphere', False), ('Only heat energy is produced — no new chemical substances form', False)]),
('What is electrolysis?', 'multiple_choice',
'Electrolysis uses direct electric current to drive a non-spontaneous chemical reaction. Electrodes (anode and cathode) are placed in an electrolyte (ionic solution or molten ionic compound). At the cathode (negative): positive ions (cations) gain electrons and are reduced. At the anode (positive): negative ions (anions) lose electrons and are oxidised. Applications: electroplating (coating metal with another metal), extraction of aluminium, purification of copper, hydrogen production.',
[('A reaction caused by exposing a chemical to electric light', False), ('Using electric current to decompose a compound — used in electroplating and metal extraction', True), ('Measuring the electrical conductivity of a solution', False), ('The separation of mixtures using electrical charges to attract particles', False)]),
('What is the difference between an element, a compound and a mixture?', 'multiple_choice',
'Element: contains only one type of atom (oxygen, iron, gold). Compound: two or more elements chemically bonded in fixed proportions — properties differ from constituent elements (water is not like hydrogen or oxygen). Mixture: two or more substances not chemically combined — each retains its properties and can be separated by physical means (filtration, evaporation, distillation). Salt water is a mixture; sodium chloride (the salt itself) is a compound.',
[('Elements are natural; compounds are man-made; mixtures can be either', False), ('Element = one type of atom; compound = chemically bonded elements; mixture = physically combined substances', True), ('Compounds are pure substances; elements and mixtures are both impure', False), ('The only difference is the number of atoms — more atoms makes a compound', False)]),
('What is the law of conservation of mass?', 'multiple_choice',
'The law of conservation of mass states that matter is neither created nor destroyed in a chemical reaction — the total mass of reactants equals the total mass of products. This is why chemical equations must be balanced. If 2g of hydrogen reacts with 16g of oxygen to form water, 18g of water is produced. This law underpins all quantitative chemistry — it allows calculation of how much product a reaction will yield from given quantities of reactants.',
[('The total energy in a chemical reaction is always conserved', False), ('The total mass of reactants always equals the total mass of products', True), ('The mass of the heavier reactant determines the mass of the product', False), ('Chemical reactions always produce less mass than the original reactants', False)]),
])

# Print summary
print('\n' + '='*60)
from certifications.models import Quiz
total_q = sum(q.questions.count() for q in Quiz.objects.all())
quiz_count = Quiz.objects.count()
print(f'Total quizzes: {quiz_count}')
print(f'Total questions: {total_q}')

courses_without_quiz = []
from courses.models import Course
for c in Course.objects.all().order_by('title'):
    try:
        c.quiz
    except:
        courses_without_quiz.append(c.title)
print(f'\nCourses still needing quizzes: {len(courses_without_quiz)}')
for t in courses_without_quiz:
    print(f'  - {t}')