import os
import django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'skillscontinua_core.settings')
django.setup()

from courses.models import Course, Lesson

def add_lessons(title, lessons_data):
    try:
        course = Course.objects.get(title=title)
        Lesson.objects.filter(course=course).delete()
        for order, lesson_title, duration, content in lessons_data:
            Lesson.objects.create(
                course=course,
                title=lesson_title,
                content_type='text',
                content_text=content,
                order=order,
                duration_minutes=duration,
                is_active=True
            )
        print(f'OK: {title} - {course.lessons.count()} lessons')
    except Course.DoesNotExist:
        print(f'NOT FOUND: {title}')

# Fix partial courses first
add_lessons('Carpentry Fundamentals', [
    (1, 'What is Carpentry?', 20,
     'Carpentry is the skilled trade of working with wood to construct and repair buildings, furniture and other wooden structures.\n\n'
     'WHY LEARN CARPENTRY?\n'
     'Wood is one of the most versatile and available materials in the world.\n'
     'Carpentry skills are needed in every building project.\n'
     'A skilled carpenter can always find work or create their own business.\n\n'
     'WHAT CARPENTERS BUILD:\n'
     'Roof structures: Trusses, rafters and purlins that support the roof.\n'
     'Doors and windows: Frames, panels and fittings.\n'
     'Furniture: Chairs, tables, beds, wardrobes and shelving.\n'
     'Floors: Timber flooring, decking and stairs.\n'
     'Formwork: Temporary wooden structures used in concrete construction.\n\n'
     'THE CARPENTER MINDSET:\n'
     'Measure twice, cut once. This principle prevents waste and errors.\n'
     'Precision matters - a millimetre error can ruin a joint.\n'
     'Patience produces quality. Good work cannot be rushed.\n'
     'Safety is always the priority.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Walk around your community and identify five wooden structures or items.\n'
     'For each one: What type of wood was used? How was it joined?\n'
     'What tools were needed to make it?\n'
     'Write your observations in a notebook.'),
    (2, 'Wood Types and Properties', 25,
     'Understanding wood is the foundation of all carpentry.\n\n'
     'HARDWOODS AND SOFTWOODS:\n'
     'Hardwoods come from deciduous trees that lose their leaves.\n'
     'They are generally harder, denser and more durable.\n'
     'Softwoods come from coniferous trees with needles.\n'
     'They are generally easier to work and lower in cost.\n\n'
     'COMMON WEST AFRICAN HARDWOODS:\n'
     'Iroko: Strong, durable, resistant to insects. Excellent for furniture and construction.\n'
     'Mahogany: Beautiful reddish-brown colour. Premium furniture and joinery.\n'
     'Sapele: Decorative grain. Used for furniture and panelling.\n'
     'Teak: Extremely durable, natural oils resist water. Premium outdoor furniture.\n\n'
     'ENGINEERED WOOD:\n'
     'Plywood: Thin layers glued with alternating grain. Strong and stable.\n'
     'MDF: Compressed wood fibres. Smooth surface. Good for painted furniture.\n'
     'Chipboard: Compressed wood chips. Cheaper but weaker.\n\n'
     'WOOD DEFECTS TO AVOID:\n'
     'Knots: Dark circular areas that can weaken the wood.\n'
     'Warping: Twisting or bowing. Unusable for precision work.\n'
     'Rot: Soft discoloured areas. Structurally compromised.\n'
     'Insect damage: Holes or tunnels from termites or woodworm.\n\n'
     'MOISTURE AND WOOD:\n'
     'Wood absorbs and releases moisture, causing expansion and contraction.\n'
     'Seasoned wood is dried to a stable moisture content before use.\n'
     'Always use properly seasoned wood for furniture and precision work.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Visit a timber yard or sawmill.\n'
     'Identify at least five different types of wood they stock.\n'
     'Ask about the properties, uses and price of each type.\n'
     'Record everything you learn.'),
    (3, 'Carpentry Tools', 30,
     'A carpenter is only as good as their tools.\n\n'
     'MEASURING AND MARKING TOOLS:\n'
     'Tape measure: For measuring lengths.\n'
     'Try square: For checking and marking right angles.\n'
     'Marking gauge: Scribes a line parallel to an edge.\n'
     'Spirit level: Checks horizontal and vertical accuracy.\n'
     'Chalk line: Snaps a straight chalk line over long distances.\n\n'
     'CUTTING TOOLS:\n'
     'Rip saw: For cutting along the grain.\n'
     'Cross cut saw: For cutting across the grain.\n'
     'Tenon saw: Fine-toothed for joinery and accurate cuts.\n'
     'Chisels: For cutting joints and removing waste wood.\n'
     'Plane: For smoothing and flattening surfaces.\n\n'
     'POWER TOOLS:\n'
     'Circular saw: Fast straight cuts in timber and sheet material.\n'
     'Jigsaw: For curved cuts and holes.\n'
     'Electric drill: For drilling holes and driving screws.\n'
     'Orbital sander: For fine finishing sanding.\n\n'
     'JOINING TOOLS:\n'
     'Hammer: For driving nails.\n'
     'Mallet: For striking chisels without damage.\n'
     'Screwdrivers: Flat and Phillips types.\n'
     'Clamps: For holding pieces while glue dries.\n\n'
     'TOOL SAFETY:\n'
     'Always wear safety goggles when cutting or chiselling.\n'
     'Wear a dust mask when sanding - wood dust causes lung disease.\n'
     'Keep fingers away from blade path at all times.\n'
     'Unplug power tools before changing blades or bits.\n\n'
     'PRACTICAL EXERCISE:\n'
     'List all the tools you currently own.\n'
     'Identify the five most important tools you do not yet have.\n'
     'Research current prices for those tools.\n'
     'Create a savings plan to acquire them over the next three months.'),
    (4, 'Basic Joints and Connections', 35,
     'A joint is where two pieces of wood meet. The quality of your work depends on your joints.\n\n'
     'BASIC JOINTS:\n\n'
     'BUTT JOINT:\n'
     'The simplest joint - two pieces meeting at right angles with no shaping.\n'
     'Weak unless reinforced with screws, nails or metal brackets.\n'
     'Used for basic box construction and rough framing.\n\n'
     'HALVING JOINT:\n'
     'Half the thickness removed from each piece where they overlap.\n'
     'Results in a joint that is the same thickness as each individual piece.\n'
     'Used for frame construction and grids.\n\n'
     'MORTISE AND TENON:\n'
     'One of the strongest traditional woodworking joints.\n'
     'Tenon: A tongue-shaped projection on one piece.\n'
     'Mortise: A rectangular hole in the other piece that receives the tenon.\n'
     'Used for chair and table legs, door frames and timber frame construction.\n\n'
     'MITRE JOINT:\n'
     'Both pieces cut at 45 degrees and joined at the corner.\n'
     'Creates a clean corner with no end grain visible.\n'
     'Used for picture frames, skirting boards and architraves.\n\n'
     'GLUING AND CLAMPING:\n'
     'Most joints are strengthened with wood glue (PVA or similar).\n'
     'Apply glue to both surfaces. Clamp firmly while drying.\n'
     'Standard drying time: 30 to 60 minutes for handling, 24 hours for full strength.\n'
     'Remove excess glue immediately with a damp cloth before it sets.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Cut and assemble two different joints from scrap wood:\n'
     'A butt joint reinforced with screws.\n'
     'A simple halving joint.\n'
     'Test the strength of each by trying to pull it apart.\n'
     'Note which is stronger and why.'),
    (5, 'Starting Your Carpentry Career', 25,
     'Carpentry offers excellent career and self-employment opportunities.\n\n'
     'CAREER PATHS IN CARPENTRY:\n'
     'Apprentice: Learning under an experienced carpenter.\n'
     'Employed carpenter: Working for a building contractor or furniture company.\n'
     'Self-employed: Taking your own jobs and clients.\n'
     'Specialist: Focusing on one area - furniture, cabinets, roofing.\n'
     'Contractor: Managing teams on large construction projects.\n\n'
     'SETTING UP A CARPENTRY WORKSHOP:\n'
     'Location: A covered space with good lighting and ventilation.\n'
     'Workbench: Sturdy bench at a comfortable working height.\n'
     'Tool storage: Every tool has a place.\n'
     'Power: Safe electrical connections for power tools.\n'
     'Fire safety: No smoking, fire extinguisher accessible.\n\n'
     'GETTING YOUR FIRST CLIENTS:\n'
     'Tell everyone you know that you are a carpenter.\n'
     'Take any job, even small ones, to build your portfolio.\n'
     'Photograph every completed job.\n'
     'Ask satisfied clients for referrals.\n'
     'Offer a small discount for referrals that lead to paid work.\n\n'
     'PRICING YOUR WORK:\n'
     'Calculate materials cost accurately. Add 10% for waste.\n'
     'Estimate labour hours and multiply by your hourly rate.\n'
     'Add profit margin of at least 20%.\n'
     'Always provide a written quotation before starting.\n\n'
     'BUILDING YOUR REPUTATION:\n'
     'Do what you say you will do. On time, every time.\n'
     'Communicate clearly with clients throughout the job.\n'
     'Clean up after yourself - leave the site better than you found it.\n'
     'Follow up after the job to check the client is happy.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Build a simple wooden tool box to store your own tools.\n'
     'Dimensions: 400mm x 200mm x 150mm.\n'
     'Use butt joints with screws and wood glue.\n'
     'Sand smooth. Apply a coat of paint or varnish.\n'
     'This is your first carpentry project.'),
])

add_lessons('Financial Management for Self-Employment', [
    (1, 'Managing Money as a Self-Employed Person', 25,
     'Being self-employed means you are both the worker and the business owner. Managing money well is essential to success.\n\n'
     'THE SELF-EMPLOYED FINANCIAL CHALLENGE:\n'
     'Your income is not fixed - it varies from month to month.\n'
     'You have no employer to deduct taxes or pay benefits for you.\n'
     'You are responsible for your own financial planning.\n'
     'Good financial management is what separates struggling from thriving self-employed people.\n\n'
     'SEPARATING BUSINESS AND PERSONAL MONEY:\n'
     'The most important financial habit for self-employed people.\n'
     'Open a separate bank account for business income and expenses.\n'
     'Pay yourself a salary from the business account into your personal account.\n'
     'This makes it possible to know if your business is profitable.\n\n'
     'YOUR SELF-EMPLOYED INCOME:\n'
     'Gross income: Total amount received from clients before any deductions.\n'
     'Business expenses: Materials, tools, transport, phone, marketing.\n'
     'Net business income: Gross income minus business expenses.\n'
     'Personal income (salary): What you pay yourself from net business income.\n\n'
     'SETTING YOUR SALARY:\n'
     'Calculate your personal monthly expenses - what you need to live.\n'
     'Your salary must cover your personal expenses.\n'
     'In good months, leave extra money in the business account as reserve.\n'
     'In slow months, your business reserve covers your salary.\n\n'
     'TRACKING INCOME AND EXPENSES:\n'
     'Record every payment received on the day it arrives.\n'
     'Record every business expense on the day you pay it.\n'
     'At the end of each month, total both.\n'
     'Net income = Total income minus Total expenses.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Calculate your average monthly income from the last three months.\n'
     'Calculate your total business expenses for the same period.\n'
     'Calculate your net business income.\n'
     'Is this enough to pay yourself adequately and keep the business growing?\n'
     'If not, write two specific actions to improve the position.'),
    (2, 'Pricing for Profit', 30,
     'Underpricing your work is not generosity. It is a path to business failure.\n\n'
     'WHY SELF-EMPLOYED PEOPLE UNDERPRICE:\n'
     'Fear of losing the job to a cheaper competitor.\n'
     'Not calculating the true cost of their time and overhead.\n'
     'Lack of confidence in their own value.\n'
     'Not understanding that price signals quality to customers.\n\n'
     'THE REAL COST OF YOUR WORK:\n'
     'Direct costs: Materials and components specific to the job.\n'
     'Labour cost: Your time at the rate you need to earn.\n'
     'Overhead: Tools, vehicle, phone, marketing divided across all jobs.\n'
     'Profit margin: The amount above cost that grows the business.\n\n'
     'CALCULATING YOUR MINIMUM HOURLY RATE:\n'
     'Step 1: Total monthly personal expenses (what you need to live).\n'
     'Step 2: Add monthly business overhead (tools, transport, phone, marketing).\n'
     'Step 3: Add monthly savings target.\n'
     'Step 4: Total divided by billable hours per month.\n'
     'This is your break-even hourly rate. Charge more to make a profit.\n\n'
     'EXAMPLE:\n'
     'Personal expenses: 60,000. Business overhead: 20,000. Savings target: 10,000.\n'
     'Total needed: 90,000 per month.\n'
     'Billable hours: 120 (6 hours per day, 5 days per week).\n'
     'Minimum rate: 90,000 divided by 120 equals 750 per hour.\n'
     'Add 30% profit: 750 times 1.3 equals 975 per hour.\n\n'
     'PRICING MODELS:\n'
     'Hourly rate: Charge per hour worked. Simple and transparent.\n'
     'Fixed price: Agree total price for the complete job.\n'
     'Day rate: Charge per day.\n'
     'Value-based pricing: Charge based on value delivered to the client.\n\n'
     'HANDLING PRICE OBJECTIONS:\n'
     'When a customer says your price is too high, do not immediately lower it.\n'
     'Ask: What budget do you have in mind?\n'
     'Explain the value they are getting - quality, reliability, your experience.\n'
     'Offer a smaller scope of work at a lower price rather than discounting the same work.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Calculate your minimum hourly rate using the formula above.\n'
     'Compare it to what you currently charge.\n'
     'If you are charging less, write a specific plan for how you will increase your rates over the next 6 months.'),
    (3, 'Cash Flow Management', 25,
     'Cash flow is the movement of money in and out of your business. Poor cash flow kills businesses even when they are profitable.\n\n'
     'WHAT IS CASH FLOW?\n'
     'Cash in: Money received from clients.\n'
     'Cash out: Money paid for materials, expenses, salary.\n'
     'Net cash flow: Cash in minus Cash out for the period.\n'
     'Positive cash flow: More coming in than going out. Healthy.\n'
     'Negative cash flow: More going out than coming in. Danger.\n\n'
     'THE CASH FLOW PROBLEM FOR SELF-EMPLOYED PEOPLE:\n'
     'You buy materials before you are paid for the job.\n'
     'Clients may pay late - or sometimes not at all.\n'
     'Large jobs tie up your cash for weeks or months.\n'
     'Seasonal slowdowns reduce income while fixed expenses continue.\n\n'
     'MANAGING CASH FLOW:\n\n'
     'DEPOSITS:\n'
     'Always collect a deposit before starting a job.\n'
     'Standard deposit: 30 to 50% of the total job value.\n'
     'The deposit covers your materials and initial labour.\n'
     'Never start a job without a deposit.\n\n'
     'PAYMENT TERMS:\n'
     'Agree payment terms before starting.\n'
     'State on every quotation: Payment due within 7 days of completion.\n'
     'Chase overdue payments immediately - do not let them drift.\n\n'
     'CASH RESERVE:\n'
     'Maintain a cash reserve of at least 2 to 3 months of operating costs.\n'
     'This covers slow months and unexpected expenses.\n'
     'Build this reserve during good months. Do not spend it.\n\n'
     'MANAGING EXPENSES:\n'
     'Buy materials only when you have a confirmed, paid order where possible.\n'
     'Negotiate credit with trusted suppliers - pay at the end of the month.\n'
     'Avoid unnecessary purchases during slow periods.\n\n'
     'CASH FLOW FORECAST:\n'
     'A spreadsheet projecting income and expenses week by week.\n'
     'Shows you in advance when you might run short of cash.\n'
     'Allows you to take action before the problem arrives.\n\n'
     'PRACTICAL EXERCISE:\n'
     'List every job you currently have or expect in the next month.\n'
     'For each job: When will you receive payment?\n'
     'List all expenses due in the next month and when they must be paid.\n'
     'Calculate: Will you have enough cash at all times?\n'
     'If not, what action will you take?'),
    (4, 'Taxes and Legal Requirements', 20,
     'Self-employed people have tax and legal obligations. Understanding them protects you from penalties.\n\n'
     'WHY TAXES MATTER:\n'
     'Taxes fund the roads, hospitals, schools and services your community uses.\n'
     'Not paying taxes when you should is illegal and can result in fines and prosecution.\n'
     'Registered, tax-paying businesses have access to government contracts and bank loans.\n\n'
     'WHAT TAXES SELF-EMPLOYED PEOPLE PAY:\n\n'
     'PERSONAL INCOME TAX:\n'
     'Tax paid on your earnings above a minimum threshold.\n'
     'In Nigeria: Paid as Personal Income Tax to the State Revenue Service.\n'
     'In Ghana: Paid as Income Tax to the Ghana Revenue Authority.\n'
     'In Sierra Leone: Paid as Personal Income Tax to the National Revenue Authority.\n'
     'Rates vary by country. Check current rates with your local tax authority.\n\n'
     'VALUE ADDED TAX (VAT):\n'
     'Tax charged on the sale of goods and services.\n'
     'Nigeria VAT: 7.5%. Ghana VAT: 15%. Sierra Leone: 15%.\n'
     'Only applies once your business exceeds the registration threshold.\n'
     'If registered for VAT, you collect it from customers and pay it to the tax authority.\n\n'
     'BUSINESS REGISTRATION:\n'
     'Registering your business is the first legal requirement.\n'
     'Nigeria: Register with the Corporate Affairs Commission (CAC).\n'
     'Ghana: Register with the Registrar General Department.\n'
     'Sierra Leone: Register with the Corporate Affairs Commission.\n'
     'Benefits: Legal business name, access to contracts, bank accounts, credibility.\n\n'
     'RECORD KEEPING FOR TAX:\n'
     'Keep all receipts and invoices for business expenses.\n'
     'Keep records of all income received.\n'
     'These records are required for your tax return.\n'
     'Keep records for at least 6 years.\n\n'
     'GETTING HELP:\n'
     'A bookkeeper or accountant can manage your tax affairs affordably.\n'
     'Many offer annual tax return services for small businesses.\n'
     'The cost is usually much less than the penalties for getting it wrong.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Find out the current rules for self-employed people in your country.\n'
     'At what income level must you register for tax?\n'
     'What is the current income tax rate for someone at your income level?\n'
     'Contact your nearest tax office or visit their website for this information.'),
    (5, 'Growing a Self-Employment Business', 20,
     'Going from working alone to building a real business requires deliberate growth strategy.\n\n'
     'THE TRANSITION FROM SELF-EMPLOYED TO BUSINESS OWNER:\n'
     'Self-employed: You do all the work yourself. Income stops when you stop working.\n'
     'Business owner: You build a team and systems. Business can function without you.\n'
     'The goal of growth is to move from self-employed to business owner.\n\n'
     'WHEN TO HIRE YOUR FIRST PERSON:\n'
     'When you consistently have more work than you can handle alone.\n'
     'When you are turning away good work because you are too busy.\n'
     'When a specific task takes your time but does not require your skill.\n\n'
     'HIRING YOUR FIRST EMPLOYEE OR APPRENTICE:\n'
     'Start with a specific role: Someone to assist on jobs, handle deliveries, or do administration.\n'
     'Hire for attitude first, skill second. Skills can be taught. Attitude cannot.\n'
     'Pay fairly - good reliable people are worth more than their wage.\n'
     'Train them in your systems and quality standards before giving them independence.\n\n'
     'SYSTEMS FOR GROWTH:\n'
     'Document your processes - how you do each type of job.\n'
     'Create templates for quotations, invoices and receipts.\n'
     'Set up a simple system for tracking all jobs, materials and payments.\n'
     'These systems allow others to maintain your quality standard.\n\n'
     'REINVESTING IN THE BUSINESS:\n'
     'When income exceeds needs, reinvest in growth.\n'
     'Better tools increase quality and speed.\n'
     'Marketing investment attracts more clients.\n'
     'Training improves quality and allows you to offer new services.\n\n'
     'SETTING GROWTH TARGETS:\n'
     'What revenue do you want to achieve in 12 months?\n'
     'How many clients do you need? At what average job value?\n'
     'What investment in tools or marketing is needed?\n'
     'Who will you hire and when?\n\n'
     'PRACTICAL EXERCISE:\n'
     'Write a 12-month growth plan.\n'
     'Include: Monthly revenue target, number of jobs, marketing activities, tools to purchase.\n'
     'Identify one person you could hire or one apprentice you could train.\n'
     'Track your progress against the plan every month.'),
])

# PRIMARY EDUCATION COURSES
add_lessons('Primary English Language', [
    (1, 'Reading and Comprehension', 25,
     'Reading is the gateway to all learning. Strong reading skills open every door.\n\n'
     'READING FOR UNDERSTANDING:\n'
     'Reading is not just recognising words - it is understanding meaning.\n'
     'Fluent reading means reading smoothly at an appropriate pace.\n'
     'Comprehension means understanding what you have read.\n\n'
     'READING STRATEGIES:\n'
     'Before reading: Look at the title and any pictures. What do you think this is about?\n'
     'During reading: Stop at difficult words. Use context to guess the meaning.\n'
     'After reading: Ask yourself what the main idea was. What did you learn?\n\n'
     'TYPES OF TEXTS:\n'
     'Stories (narrative): Tell a sequence of events with characters.\n'
     'Information texts: Give facts about a topic.\n'
     'Instructions: Tell you how to do something step by step.\n'
     'Letters and messages: Communication between people.\n'
     'Advertisements: Try to persuade you to buy or do something.\n\n'
     'VOCABULARY BUILDING:\n'
     'Read as much as possible - every new text brings new words.\n'
     'When you find a new word: Read the whole sentence. Guess the meaning from context.\n'
     'Look it up in a dictionary to confirm.\n'
     'Write it in a vocabulary book with the meaning and a sentence using it.\n'
     'Use the word in your own speaking and writing.\n\n'
     'COMPREHENSION QUESTIONS:\n'
     'Literal questions: The answer is directly in the text. Who? What? When? Where?\n'
     'Inference questions: The answer must be worked out from clues. Why? How?\n'
     'Personal response questions: Your own opinion. What do you think? Why?\n\n'
     'PRACTICAL EXERCISE:\n'
     'Read this passage and answer the questions:\n'
     'Amara is a carpenter. Every morning he goes to his workshop at seven o\'clock.\n'
     'He makes chairs and tables. His customers come from all over the town.\n'
     'Last week he made a beautiful dining table for a family. They were very happy.\n\n'
     'Questions:\n'
     'What is Amara\'s job? What time does he go to work? What did he make last week?\n'
     'Why do you think his customers come from all over town?\n'
     'Would you like to be a carpenter? Why or why not?'),
    (2, 'Grammar and Sentence Structure', 25,
     'Grammar is the set of rules that govern how we put words together to create meaning.\n\n'
     'PARTS OF SPEECH:\n\n'
     'NOUNS:\n'
     'A noun is the name of a person, place, thing or idea.\n'
     'Person: Amara, teacher, doctor, mother.\n'
     'Place: Freetown, Lagos, school, market.\n'
     'Thing: table, pen, phone, car.\n'
     'Idea: love, happiness, freedom, education.\n'
     'Proper nouns (specific names) use capital letters: Amara, Lagos, Monday.\n\n'
     'VERBS:\n'
     'A verb is an action word or a state of being.\n'
     'Action verbs: run, write, build, cook, teach.\n'
     'State verbs: is, are, was, were, has, have, feel, think, know.\n'
     'Every sentence must have a verb.\n\n'
     'ADJECTIVES:\n'
     'Adjectives describe nouns.\n'
     'A tall building. A hot day. Three red cars. Beautiful music.\n\n'
     'ADVERBS:\n'
     'Adverbs describe verbs, adjectives or other adverbs.\n'
     'She ran quickly. He speaks very well. The work is nearly finished.\n\n'
     'SENTENCE TYPES:\n'
     'Statement: Makes a fact or observation. The carpenter builds furniture.\n'
     'Question: Asks for information. What does the carpenter build?\n'
     'Command: Gives an instruction. Build the table carefully.\n'
     'Exclamation: Expresses strong feeling. What beautiful furniture!\n\n'
     'TENSES:\n'
     'Present tense: What is happening now. He works in the workshop.\n'
     'Past tense: What happened before. He worked yesterday.\n'
     'Future tense: What will happen. He will work tomorrow.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Identify the nouns, verbs and adjectives in these sentences:\n'
     'The young carpenter made a beautiful chair.\n'
     'Three students studied hard in the busy classroom.\n'
     'Write five sentences about your daily life using correct grammar.\n'
     'Check that each sentence has a subject and a verb.'),
    (3, 'Writing Skills', 25,
     'Good writing communicates ideas clearly and effectively.\n\n'
     'THE WRITING PROCESS:\n'
     'Planning: Decide what you want to write and organise your ideas.\n'
     'Drafting: Write your first version without worrying about perfection.\n'
     'Revising: Re-read and improve content - does it say what you meant?\n'
     'Editing: Fix grammar, spelling and punctuation errors.\n'
     'Publishing: Write or type the final clean version.\n\n'
     'PARAGRAPH WRITING:\n'
     'A paragraph is a group of sentences about one main idea.\n'
     'Topic sentence: The first sentence introduces the main idea of the paragraph.\n'
     'Supporting sentences: Give details, examples and evidence.\n'
     'Concluding sentence: Summarises or wraps up the paragraph.\n\n'
     'TYPES OF WRITING:\n\n'
     'NARRATIVE WRITING:\n'
     'Tells a story with a beginning, middle and end.\n'
     'Includes characters, setting and events.\n'
     'Uses descriptive language to bring the story alive.\n\n'
     'DESCRIPTIVE WRITING:\n'
     'Describes a person, place, object or experience in detail.\n'
     'Uses the five senses: what you see, hear, smell, taste and touch.\n'
     'Uses adjectives and precise language.\n\n'
     'LETTER WRITING:\n'
     'Formal letter: Date, address, Dear Sir/Madam, formal language, Yours faithfully.\n'
     'Informal letter: Dear Amara, friendly language, Best wishes, Kemi.\n\n'
     'REPORT WRITING:\n'
     'Factual account of events or findings.\n'
     'Clear headings. Formal language. Factual, not personal.\n\n'
     'PUNCTUATION:\n'
     'Capital letters at the start of sentences and for proper nouns.\n'
     'Full stops at the end of statements.\n'
     'Commas for lists and pauses within sentences.\n'
     'Apostrophes for possession (the carpenter\'s tools) and contractions (don\'t, can\'t).\n\n'
     'PRACTICAL EXERCISE:\n'
     'Write a short story (one page) about a day in the life of a skilled worker.\n'
     'Include: A beginning that introduces the character, a middle with a challenge, an end that resolves it.\n'
     'Check your story has correct grammar, punctuation and spelling.\n'
     'Read it aloud to check it flows naturally.'),
    (4, 'Speaking and Listening', 20,
     'Effective speaking and listening are essential life skills used in every area of life.\n\n'
     'EFFECTIVE SPEAKING:\n'
     'Speak clearly at a pace your listeners can follow.\n'
     'Use appropriate volume - loud enough to be heard, not so loud as to be unpleasant.\n'
     'Make eye contact with your audience.\n'
     'Choose words appropriate to your audience.\n'
     'Stay on topic - say what you need to say, then stop.\n\n'
     'FORMAL AND INFORMAL SPEAKING:\n'
     'Formal speaking: Presentations, interviews, meetings with authority figures.\n'
     'Use complete sentences. Avoid slang. Speak politely and professionally.\n'
     'Informal speaking: Friends, family, casual situations.\n'
     'More relaxed language. Local expressions acceptable.\n'
     'Know when each style is appropriate.\n\n'
     'ACTIVE LISTENING:\n'
     'Give the speaker your full attention.\n'
     'Do not interrupt or plan your response while they are still speaking.\n'
     'Show you are listening: Nod, maintain eye contact, make small acknowledgements.\n'
     'Ask questions if you do not understand.\n'
     'Summarise what you heard to confirm understanding.\n\n'
     'DISCUSSION SKILLS:\n'
     'Take turns speaking. Allow others to finish before responding.\n'
     'Build on what others have said.\n'
     'Disagree respectfully: I understand your point, but I think...\n'
     'Support opinions with reasons and evidence.\n\n'
     'PRESENTATIONS:\n'
     'Plan what you will say. Know your material.\n'
     'Speak slowly and clearly.\n'
     'Use examples to illustrate your points.\n'
     'Invite questions at the end.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Prepare a two-minute talk about any topic you know well.\n'
     'Practice it three times standing up.\n'
     'Deliver it to at least one other person.\n'
     'Ask for honest feedback: Was I clear? Did I speak at the right pace?\n'
     'What could I improve?'),
    (5, 'English in Everyday Life', 15,
     'English is the language of business, education and international communication.\n\n'
     'WHY ENGLISH MATTERS IN WEST AFRICA:\n'
     'Official language of Nigeria, Ghana, Sierra Leone, Liberia and Gambia.\n'
     'Language of government, courts, schools and universities.\n'
     'Language of international business and trade.\n'
     'Required for most professional careers.\n'
     'Essential for further education and professional certification.\n\n'
     'ENGLISH FOR WORK:\n'
     'Job applications: Must be in correct, professional English.\n'
     'Business communication: Letters, emails, proposals.\n'
     'Client interaction: Professional communication builds client confidence.\n'
     'Contracts and legal documents: Read carefully before signing.\n\n'
     'CONTINUING TO IMPROVE:\n'
     'Read English every day: Newspapers, books, online articles.\n'
     'Watch English films and television with subtitles.\n'
     'Practice speaking English in appropriate situations.\n'
     'Write in English regularly: Journal, messages, notes.\n'
     'Do not be afraid of making mistakes - they are how you learn.\n\n'
     'COMMON MISTAKES TO AVOID:\n'
     'Subject-verb agreement: The children are (not is) in school.\n'
     'Correct tense: I have finished (not I have finish) the work.\n'
     'Articles: A tree (not tree). The road (not road).\n'
     'Prepositions: I am interested in (not at) carpentry.\n\n'
     'BUILDING A PERSONAL LEARNING PLAN:\n'
     'Set a specific English language goal.\n'
     'Identify what resources you will use: Books, apps, classes.\n'
     'Practice for at least 15 minutes every day.\n'
     'Test your progress every month.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Write a professional introduction letter for yourself.\n'
     'Include: Your name, where you are from, your education, your skills, your career goals.\n'
     'This type of letter is used in job applications and business introductions.\n'
     'Check it carefully for grammar, spelling and punctuation.\n'
     'Have someone else read it and give feedback.'),
])

add_lessons('Primary Mathematics', [
    (1, 'Number and Place Value', 20,
     'Understanding numbers and how they are structured is the foundation of all mathematics.\n\n'
     'THE NUMBER SYSTEM:\n'
     'Our number system uses ten digits: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9.\n'
     'These ten digits can represent any number through place value.\n\n'
     'PLACE VALUE:\n'
     'Each position in a number has a value ten times greater than the position to its right.\n'
     'Units (ones): 1, 2, 3, 4, 5, 6, 7, 8, 9\n'
     'Tens: 10, 20, 30, 40, 50, 60, 70, 80, 90\n'
     'Hundreds: 100, 200, 300, 400, 500\n'
     'Thousands: 1,000, 2,000, 5,000\n'
     'Ten thousands: 10,000, 50,000\n'
     'Hundreds of thousands: 100,000, 500,000\n'
     'Millions: 1,000,000\n\n'
     'READING AND WRITING LARGE NUMBERS:\n'
     '4,750: Four thousand seven hundred and fifty.\n'
     '23,486: Twenty-three thousand four hundred and eighty-six.\n'
     '500,000: Five hundred thousand.\n'
     '1,250,000: One million two hundred and fifty thousand.\n\n'
     'COMPARING NUMBERS:\n'
     'Greater than (>): 500 > 300. Five hundred is greater than three hundred.\n'
     'Less than (<): 200 < 450. Two hundred is less than four hundred and fifty.\n'
     'Equal to (=): 250 = 250.\n\n'
     'ROUNDING NUMBERS:\n'
     'Round to the nearest 10: Look at the units digit. If 5 or more, round up. If less than 5, round down.\n'
     '47 rounded to nearest 10 = 50. 43 rounded to nearest 10 = 40.\n'
     'Round to the nearest 100: Look at the tens digit.\n'
     '470 rounded to nearest 100 = 500. 430 rounded to nearest 100 = 400.\n\n'
     'NEGATIVE NUMBERS:\n'
     'Numbers below zero. Written with a minus sign.\n'
     'Used for: Temperatures below zero, debts, below sea level.\n'
     'On a number line, negative numbers are to the left of zero.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Write these numbers in words: 3,450. 12,700. 250,000. 1,500,000.\n'
     'Write these in digits: Forty-five thousand. Three hundred and twelve thousand.\n'
     'Round each number to the nearest 100: 348. 562. 1,749. 23,455.'),
    (2, 'The Four Operations', 25,
     'Addition, subtraction, multiplication and division are the four fundamental operations in mathematics.\n\n'
     'ADDITION OF LARGE NUMBERS:\n'
     'Write numbers in columns, aligning digits by place value.\n'
     'Add from right to left.\n'
     'Carry tens to the next column when a column totals 10 or more.\n'
     'Example: 4,756 plus 2,489.\n'
     '6 plus 9 = 15. Write 5, carry 1.\n'
     '5 plus 8 plus 1 = 14. Write 4, carry 1.\n'
     '7 plus 4 plus 1 = 12. Write 2, carry 1.\n'
     '4 plus 2 plus 1 = 7.\n'
     'Answer: 7,245.\n\n'
     'SUBTRACTION OF LARGE NUMBERS:\n'
     'Write the larger number on top.\n'
     'Subtract from right to left.\n'
     'Borrow from the next column when the top digit is smaller.\n\n'
     'MULTIPLICATION:\n'
     'Long multiplication for numbers with two or more digits.\n'
     'Example: 47 times 23.\n'
     '47 times 3 = 141.\n'
     '47 times 20 = 940.\n'
     '141 plus 940 = 1,081.\n\n'
     'DIVISION:\n'
     'Short division for dividing by single digits.\n'
     'Long division for dividing by two or more digits.\n'
     'Always check by multiplying the answer by the divisor.\n\n'
     'ORDER OF OPERATIONS:\n'
     'When a calculation has multiple operations, follow BODMAS:\n'
     'Brackets first.\n'
     'Orders (powers and roots).\n'
     'Division and Multiplication (left to right).\n'
     'Addition and Subtraction (left to right).\n'
     'Example: 3 plus 4 times 2 = 3 plus 8 = 11 (not 14).\n\n'
     'PRACTICAL EXERCISE:\n'
     'A carpenter buys: 12 planks of wood at 850 naira each, 50 screws at 20 naira each, and 3 tins of varnish at 1,200 naira each. What is the total cost?\n'
     'He receives 20,000 naira from the client. How much change does he receive?\n'
     'If he completes 4 similar jobs this month, what is his total material cost?'),
    (3, 'Fractions, Decimals and Percentages', 25,
     'Fractions, decimals and percentages are three ways of expressing the same thing - parts of a whole.\n\n'
     'EQUIVALENT FRACTIONS:\n'
     'Fractions that represent the same value.\n'
     '1/2 = 2/4 = 4/8 = 50/100\n'
     '1/4 = 2/8 = 25/100\n'
     '3/4 = 6/8 = 75/100\n\n'
     'ADDING AND SUBTRACTING FRACTIONS:\n'
     'Same denominator: Add or subtract the numerators only.\n'
     '3/8 plus 2/8 = 5/8.\n'
     'Different denominators: Find a common denominator first.\n'
     '1/4 plus 1/3: Common denominator is 12. 3/12 plus 4/12 = 7/12.\n\n'
     'MULTIPLYING FRACTIONS:\n'
     'Multiply numerators together. Multiply denominators together.\n'
     '2/3 times 3/4 = 6/12 = 1/2.\n\n'
     'CONVERTING BETWEEN FORMS:\n'
     'Fraction to decimal: Divide numerator by denominator. 3/4 = 3 divided by 4 = 0.75.\n'
     'Decimal to percentage: Multiply by 100. 0.75 times 100 = 75%.\n'
     'Percentage to decimal: Divide by 100. 75% divided by 100 = 0.75.\n\n'
     'CALCULATING PERCENTAGES:\n'
     'Find 10%: Divide by 10.\n'
     'Find 5%: Find 10% and halve it.\n'
     'Find 20%: Find 10% and double it.\n'
     'Find 15%: Find 10%, find 5%, add them together.\n'
     'Find 1%: Divide by 100.\n\n'
     'PERCENTAGE INCREASE AND DECREASE:\n'
     'Price increase of 10%: Multiply by 1.10.\n'
     'Price decrease (discount) of 20%: Multiply by 0.80.\n\n'
     'PRACTICAL EXERCISE:\n'
     'A trader buys goods for 40,000 naira. He wants to sell them at a 35% profit.\n'
     'What is his profit amount? What is his selling price?\n'
     'A shop gives a 15% discount on a phone costing 80,000 naira. What is the discount? What is the sale price?\n'
     'Express 3/8 as a decimal and as a percentage.'),
    (4, 'Measurement and Geometry', 25,
     'Measurement and geometry are essential for construction, design and everyday problem solving.\n\n'
     'UNITS OF MEASUREMENT:\n'
     'Length: mm, cm, m, km. 10mm=1cm. 100cm=1m. 1000m=1km.\n'
     'Mass: g, kg, t. 1000g=1kg. 1000kg=1t.\n'
     'Capacity: ml, cl, l. 1000ml=1l.\n'
     'Time: seconds, minutes, hours, days, weeks, months, years.\n\n'
     'AREA:\n'
     'Rectangle: Length times width.\n'
     'Triangle: Base times height divided by 2.\n'
     'Circle: Pi times radius squared. Pi is approximately 3.14.\n\n'
     'PERIMETER:\n'
     'The total distance around a shape.\n'
     'Rectangle: 2 times (length plus width).\n'
     'Circle (circumference): 2 times Pi times radius.\n\n'
     'VOLUME:\n'
     'Cuboid (box): Length times width times height.\n'
     'Units are cubic: cm cubed, m cubed.\n\n'
     'ANGLES:\n'
     'Measured in degrees. A full turn is 360 degrees.\n'
     'Right angle: 90 degrees. A quarter turn.\n'
     'Straight angle: 180 degrees. A half turn.\n'
     'Acute angle: Less than 90 degrees.\n'
     'Obtuse angle: More than 90 degrees but less than 180 degrees.\n\n'
     'TYPES OF TRIANGLES:\n'
     'Equilateral: All three sides and angles equal. Each angle is 60 degrees.\n'
     'Isosceles: Two equal sides and two equal angles.\n'
     'Right-angled: One angle is 90 degrees.\n\n'
     'PYTHAGORAS THEOREM:\n'
     'In a right-angled triangle: a squared plus b squared equals c squared.\n'
     'c is the hypotenuse (longest side, opposite the right angle).\n'
     'Used by builders to check if corners are square.\n\n'
     'PRACTICAL EXERCISE:\n'
     'A room is 5.5m long and 4m wide. Calculate the floor area.\n'
     'If tiles are 50cm by 50cm, how many tiles are needed?\n'
     'A triangular piece of land has a base of 20m and height of 15m. Calculate the area.\n'
     'A cylindrical water tank has a radius of 1m and height of 1.5m. Calculate its volume.'),
    (5, 'Data Handling and Problem Solving', 20,
     'Mathematics is a tool for solving real problems. Data handling helps us make sense of information.\n\n'
     'COLLECTING DATA:\n'
     'Data is information collected for a purpose.\n'
     'Primary data: Collected by you directly through surveys, observations, experiments.\n'
     'Secondary data: Collected by others - statistics books, government reports, websites.\n\n'
     'TALLY CHARTS:\n'
     'Used to count and record data as it is collected.\n'
     'Draw a vertical line for each count. The fifth line crosses the previous four: 4 vertical lines then one diagonal line = 5.\n'
     'Easy to count in fives at the end.\n\n'
     'FREQUENCY TABLES:\n'
     'Organise data into categories showing how often each occurs.\n'
     'Category, Tally, Frequency (total count).\n\n'
     'AVERAGES:\n'
     'Mean: Add all values, divide by the number of values.\n'
     'Median: The middle value when data is arranged in order.\n'
     'Mode: The most frequently occurring value.\n'
     'Range: Highest value minus lowest value.\n\n'
     'GRAPHS AND CHARTS:\n'
     'Bar chart: Compares quantities using rectangular bars.\n'
     'Pie chart: Shows proportions of a whole.\n'
     'Line graph: Shows how a value changes over time.\n'
     'Pictogram: Uses symbols to represent data.\n\n'
     'PROBLEM SOLVING STRATEGY:\n'
     'Step 1: Read the problem carefully. What is being asked?\n'
     'Step 2: Identify the information given.\n'
     'Step 3: Decide which operation or method to use.\n'
     'Step 4: Work out the answer.\n'
     'Step 5: Check if the answer is reasonable.\n\n'
     'PRACTICAL EXERCISE:\n'
     'A carpenter recorded his daily earnings for one week: 8,500, 12,000, 6,000, 15,000, 9,500, 11,000, 7,000.\n'
     'Calculate the mean, median, mode and range.\n'
     'Draw a bar chart showing the earnings for each day.\n'
     'On which day did he earn the most? What was his total for the week?'),
])

add_lessons('Primary Science', [
    (1, 'Living Things and Their Environment', 20,
     'Science helps us understand the natural world and how it works.\n\n'
     'CHARACTERISTICS OF LIVING THINGS:\n'
     'All living things share seven characteristics, remembered as MRS GREN:\n'
     'Movement: All living things move in some way.\n'
     'Respiration: Release energy from food.\n'
     'Sensitivity: Respond to their environment.\n'
     'Growth: All living things grow and develop.\n'
     'Reproduction: Produce offspring of the same type.\n'
     'Excretion: Remove waste products from their bodies.\n'
     'Nutrition: Take in food and water.\n\n'
     'CLASSIFICATION OF LIVING THINGS:\n'
     'The main kingdoms of life:\n'
     'Animals: Move around, cannot make their own food.\n'
     'Plants: Cannot move around, make food using sunlight through photosynthesis.\n'
     'Fungi: Mushrooms, moulds. Cannot make their own food. Feed on dead matter.\n'
     'Bacteria: Microscopic single-celled organisms. Found everywhere.\n'
     'Viruses: Not technically alive. Cause diseases like flu, COVID-19, HIV.\n\n'
     'ECOSYSTEMS:\n'
     'An ecosystem is a community of living organisms interacting with their environment.\n'
     'West African ecosystems include: Tropical rainforest, savannah, coastal and marine, freshwater.\n'
     'Each ecosystem has its own climate, vegetation and animal life.\n\n'
     'FOOD CHAINS AND FOOD WEBS:\n'
     'A food chain shows who eats whom in an ecosystem.\n'
     'Grass - grasshopper - lizard - eagle.\n'
     'Producers: Plants that make food from sunlight.\n'
     'Primary consumers: Animals that eat plants.\n'
     'Secondary consumers: Animals that eat primary consumers.\n'
     'Top predators: At the top of the food chain. No natural predators.\n\n'
     'ENVIRONMENTAL THREATS:\n'
     'Deforestation: Cutting down forests destroys habitats.\n'
     'Pollution: Chemicals and waste harm ecosystems.\n'
     'Climate change: Altering rainfall patterns and temperatures.\n'
     'Biodiversity loss: Extinction of species weakens ecosystems.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Walk around your community and observe living things.\n'
     'List five animals and five plants you observe.\n'
     'For each animal: What does it eat? What might eat it? Draw its position in a food chain.\n'
     'Identify one environmental problem in your community and suggest a solution.'),
    (2, 'The Human Body', 20,
     'Understanding the human body helps us take better care of our health.\n\n'
     'BODY SYSTEMS:\n\n'
     'SKELETAL SYSTEM:\n'
     'The framework of bones that supports the body.\n'
     'Adults have 206 bones.\n'
     'Protects organs: skull protects brain, ribcage protects heart and lungs.\n'
     'Enables movement together with muscles.\n\n'
     'MUSCULAR SYSTEM:\n'
     'Muscles contract and relax to produce movement.\n'
     'Voluntary muscles: You control them. Arms, legs, face.\n'
     'Involuntary muscles: Work automatically. Heart, stomach, blood vessels.\n\n'
     'DIGESTIVE SYSTEM:\n'
     'Breaks down food so nutrients can be absorbed.\n'
     'Mouth, oesophagus, stomach, small intestine, large intestine, rectum.\n'
     'Takes 24 to 48 hours to digest a meal completely.\n\n'
     'RESPIRATORY SYSTEM:\n'
     'Takes in oxygen and removes carbon dioxide.\n'
     'Nose, throat, windpipe, bronchi, lungs.\n'
     'Oxygen passes into the blood and is carried to all cells.\n\n'
     'CIRCULATORY SYSTEM:\n'
     'Heart pumps blood around the body.\n'
     'Blood carries oxygen, nutrients and hormones to cells.\n'
     'Blood carries waste products (carbon dioxide) away from cells.\n'
     'Heart beats about 70 times per minute. About 100,000 times per day.\n\n'
     'NERVOUS SYSTEM:\n'
     'Brain and spinal cord form the central nervous system.\n'
     'Nerves carry signals between brain and body.\n'
     'Controls all body functions, thoughts, sensations and movements.\n\n'
     'STAYING HEALTHY:\n'
     'Balanced diet: Carbohydrates, proteins, fats, vitamins, minerals, water.\n'
     'Regular exercise: Strengthens heart, muscles and bones.\n'
     'Adequate sleep: 8 to 10 hours for children. 7 to 8 hours for adults.\n'
     'Hygiene: Wash hands, keep body clean, drink clean water.\n'
     'Regular medical check-ups: Detect problems early.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Draw an outline of a human body.\n'
     'Mark and label the location of: Brain, heart, lungs, stomach, kidneys, liver.\n'
     'Write one function of each organ.\n'
     'Write three things you do to keep your body healthy.'),
    (3, 'Matter and Materials', 20,
     'Everything around us is made of matter. Understanding materials helps us use them wisely.\n\n'
     'STATES OF MATTER:\n'
     'Solid: Has a fixed shape and volume. Cannot be compressed.\n'
     'Examples: Rock, wood, metal, ice.\n\n'
     'Liquid: Has a fixed volume but takes the shape of its container. Cannot be compressed.\n'
     'Examples: Water, oil, petrol, mercury.\n\n'
     'Gas: Has no fixed shape or volume. Fills any container. Can be compressed.\n'
     'Examples: Air, oxygen, carbon dioxide, steam.\n\n'
     'CHANGES OF STATE:\n'
     'Melting: Solid becomes liquid when heated. Ice to water at 0 degrees Celsius.\n'
     'Freezing: Liquid becomes solid when cooled. Water to ice at 0 degrees Celsius.\n'
     'Evaporation: Liquid becomes gas. Water evaporates from puddles in sunshine.\n'
     'Condensation: Gas becomes liquid when cooled. Water droplets on a cold glass.\n'
     'Boiling: Liquid turns to gas rapidly when heated to boiling point. Water boils at 100 degrees Celsius.\n\n'
     'PROPERTIES OF MATERIALS:\n'
     'Hardness: How resistant to scratching or denting.\n'
     'Flexibility: How much it can bend without breaking.\n'
     'Conductivity: How well it conducts heat or electricity.\n'
     'Transparency: How much light passes through.\n'
     'Solubility: Whether it dissolves in water.\n\n'
     'METALS:\n'
     'Good conductors of heat and electricity.\n'
     'Strong and durable.\n'
     'Most can be shaped when heated.\n'
     'Examples: Iron, steel, aluminium, copper, gold, silver.\n\n'
     'NON-METALS:\n'
     'Generally poor conductors of heat and electricity.\n'
     'Examples: Wood, plastic, rubber, glass, ceramics.\n\n'
     'MIXTURES AND SOLUTIONS:\n'
     'Mixture: Two or more substances mixed together but not chemically joined.\n'
     'Salt water: Salt dissolved in water. Can be separated by evaporation.\n'
     'Sand and water: Can be separated by filtering.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Collect five different materials from your environment.\n'
     'For each one, test and record: Is it hard or soft? Flexible or rigid? Does it conduct electricity?\n'
     'Is it a metal or non-metal? What is it used for?\n'
     'Dissolve salt in water. Describe what you observe.\n'
     'Leave the salt water in the sun for several days. What happens?'),
    (4, 'Energy and Forces', 20,
     'Energy and forces explain how everything in the universe moves and changes.\n\n'
     'WHAT IS ENERGY?\n'
     'Energy is the ability to do work or cause change.\n'
     'Energy cannot be created or destroyed - only converted from one form to another.\n\n'
     'TYPES OF ENERGY:\n'
     'Kinetic energy: Energy of motion. A moving car, falling water, wind.\n'
     'Potential energy: Stored energy. A stretched spring, water held behind a dam.\n'
     'Thermal energy: Heat energy. Produced by burning fuel, friction, the sun.\n'
     'Chemical energy: Stored in food, fuel and batteries.\n'
     'Electrical energy: Energy carried by electric current.\n'
     'Light energy: Radiated by the sun, fires and electric lights.\n'
     'Sound energy: Produced by vibrating objects.\n\n'
     'ENERGY CONVERSIONS:\n'
     'Burning wood: Chemical energy to thermal and light energy.\n'
     'Solar panel: Light energy to electrical energy.\n'
     'Car engine: Chemical energy (petrol) to kinetic energy and thermal energy.\n'
     'Electric light bulb: Electrical energy to light and thermal energy.\n\n'
     'RENEWABLE AND NON-RENEWABLE ENERGY:\n'
     'Non-renewable: Coal, oil, natural gas. Formed over millions of years. Will run out.\n'
     'Renewable: Solar, wind, hydro (water), geothermal. Replenished naturally. Will not run out.\n'
     'Africa has enormous renewable energy potential especially solar.\n\n'
     'FORCES:\n'
     'A force is a push or a pull that can change an object\'s motion or shape.\n'
     'Gravity: Pulls all objects toward each other. Keeps us on Earth.\n'
     'Friction: Opposes motion between surfaces in contact.\n'
     'Air resistance: Friction between an object and the air.\n'
     'Upthrust: Upward force from a fluid on an object immersed in it.\n'
     'Magnetic force: Attraction or repulsion between magnets.\n\n'
     'PRACTICAL EXERCISE:\n'
     'List five energy conversions you observe in your daily life.\n'
     'For each one: What type of energy goes in? What type comes out?\n'
     'Identify three sources of renewable energy available in your community.\n'
     'How could your home use renewable energy more effectively?'),
    (5, 'Earth and Space', 15,
     'Understanding our planet and its place in the universe.\n\n'
     'THE STRUCTURE OF THE EARTH:\n'
     'Inner core: Solid iron and nickel. Temperature around 5,000 degrees Celsius.\n'
     'Outer core: Liquid iron and nickel.\n'
     'Mantle: Thick layer of hot rock. Partly molten near the surface.\n'
     'Crust: The thin outer layer we live on. Ranges from 5 to 70 km thick.\n\n'
     'TECTONIC PLATES:\n'
     'The crust is divided into about 15 large plates.\n'
     'These plates move very slowly - a few centimetres per year.\n'
     'Where plates meet: Earthquakes, volcanoes and mountain ranges.\n\n'
     'THE WATER CYCLE:\n'
     'Evaporation: Water from oceans, lakes and rivers evaporates into the atmosphere.\n'
     'Condensation: Water vapour cools and forms clouds.\n'
     'Precipitation: Water falls as rain, hail or snow.\n'
     'Collection: Water flows into rivers, lakes and oceans.\n'
     'The cycle then repeats continuously.\n\n'
     'SEASONS AND CLIMATE:\n'
     'Earth tilts on its axis as it orbits the sun.\n'
     'This causes seasons: When the northern hemisphere tilts toward the sun, it is summer there.\n'
     'West Africa is close to the equator so has less distinct seasons.\n'
     'Main seasons: Rainy season and dry season.\n\n'
     'THE SOLAR SYSTEM:\n'
     'The sun is our nearest star.\n'
     'Eight planets orbit the sun: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune.\n'
     'Earth is the third planet from the sun.\n'
     'The moon orbits the Earth every 27.3 days.\n'
     'It takes Earth 365.25 days (one year) to orbit the sun.\n\n'
     'STARS AND GALAXIES:\n'
     'Stars are huge balls of hot gas that produce light and heat through nuclear fusion.\n'
     'Our sun is a medium-sized star.\n'
     'The Milky Way galaxy contains about 200 billion stars.\n'
     'The universe contains billions of galaxies.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Observe the sky on a clear night. What can you see?\n'
     'Find the moon. Is it full, half or crescent?\n'
     'Find the brightest star. In West Africa, the Southern Cross is visible.\n'
     'Research: What causes a solar eclipse? When is the next one visible from West Africa?'),
])

add_lessons('Primary Social Studies', [
    (1, 'Our Community and Society', 20,
     'We all live in communities. Understanding how communities work helps us be better members of them.\n\n'
     'WHAT IS A COMMUNITY?\n'
     'A community is a group of people who live in the same area and share resources, services and a sense of belonging.\n'
     'Communities can be small (a village) or large (a city).\n'
     'Members of a community share responsibilities and benefits.\n\n'
     'TYPES OF COMMUNITIES:\n'
     'Rural communities: Villages and farming areas. Agriculture is the main livelihood.\n'
     'Urban communities: Towns and cities. Commerce and industry are main livelihoods.\n'
     'Coastal communities: Near the sea. Fishing and maritime activities are important.\n\n'
     'COMMUNITY SERVICES AND INSTITUTIONS:\n'
     'Schools: Provide education for children and adults.\n'
     'Health facilities: Clinics and hospitals provide healthcare.\n'
     'Markets: Where goods are bought and sold.\n'
     'Places of worship: Churches, mosques, shrines provide spiritual support.\n'
     'Police: Maintain law and order.\n'
     'Local government: Provides infrastructure and local services.\n\n'
     'COMMUNITY ROLES:\n'
     'Leaders: Chiefs, elders, local government officials.\n'
     'Workers: Teachers, health workers, traders, farmers, artisans.\n'
     'Community members: Everyone has a role in building a strong community.\n\n'
     'COMMUNITY RESPONSIBILITIES:\n'
     'Keep your environment clean.\n'
     'Respect your neighbours.\n'
     'Participate in community development activities.\n'
     'Report crime and wrongdoing.\n'
     'Support community institutions.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Draw a map of your community.\n'
     'Mark: Your home, school, health facility, market, places of worship, police station.\n'
     'Write two things your community does well.\n'
     'Write two things that could be improved in your community.\n'
     'Suggest one practical action you could personally take to help improve your community.'),
    (2, 'History and Culture of West Africa', 20,
     'Understanding our history and culture gives us identity and pride.\n\n'
     'ANCIENT WEST AFRICAN KINGDOMS:\n'
     'West Africa has a proud history of powerful and sophisticated kingdoms.\n\n'
     'MALI EMPIRE (1235-1600 CE):\n'
     'One of the largest empires in African history.\n'
     'Controlled trans-Saharan trade routes in gold and salt.\n'
     'Mansa Musa: Greatest Mali emperor. Considered the wealthiest person in history.\n'
     'Timbuktu: Major centre of Islamic learning and commerce.\n\n'
     'SONGHAI EMPIRE (1464-1591 CE):\n'
     'Succeeded the Mali Empire. Even larger territory.\n'
     'Askia Muhammad: Greatest Songhai ruler. Advanced Islamic scholarship.\n'
     'Fell to Moroccan invasion in 1591.\n\n'
     'OYO EMPIRE (Nigeria, 1300s-1800s):\n'
     'Yoruba kingdom. Major power in West Africa.\n'
     'Famous for its cavalry and military strength.\n'
     'Controlled trade routes to the coast.\n\n'
     'ASHANTI EMPIRE (Ghana, 1701-1901):\n'
     'Powerful Akan kingdom known for gold trade.\n'
     'Golden Stool: Sacred symbol of Ashanti unity.\n'
     'Resisted British colonialism until 1901.\n\n'
     'BENIN KINGDOM (Nigeria, 1440-1897):\n'
     'Famous for its bronze artworks, still celebrated worldwide.\n'
     'Highly organised state with sophisticated administration.\n\n'
     'THE COLONIAL PERIOD:\n'
     'European nations colonised West Africa from the late 1800s.\n'
     'Britain, France, Germany and Portugal divided Africa among themselves.\n'
     'Independence movements led to independence for most West African nations in the 1950s and 1960s.\n\n'
     'CULTURAL HERITAGE:\n'
     'Languages: West Africa has hundreds of languages. Hausa, Yoruba, Igbo, Twi, Wolof, Krio, Mende.\n'
     'Music and dance: Highlife, Afrobeats, traditional music are known worldwide.\n'
     'Art: Traditional and contemporary art. Kente cloth, bronze sculpture, beadwork.\n'
     'Food: Jollof rice, egusi soup, fufu, groundnut stew - beloved across the region.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Research one ancient West African kingdom not mentioned above.\n'
     'Write: When it existed, where it was, its main achievements, why it ended.\n'
     'Ask an elder in your community about the history of your local area.\n'
     'Write down what you learn.'),
    (3, 'Geography of West Africa', 20,
     'Geography shapes how people live, what they eat and how they earn a living.\n\n'
     'WEST AFRICA - AN OVERVIEW:\n'
     'West Africa includes 16 countries.\n'
     'Countries of the Economic Community of West African States (ECOWAS):\n'
     'Nigeria, Ghana, Sierra Leone, Liberia, Guinea, Guinea-Bissau, Senegal, Gambia, Mali, Burkina Faso, Niger, Ivory Coast, Togo, Benin, Cape Verde, Mauritania.\n\n'
     'PHYSICAL FEATURES:\n'
     'Atlantic coastline: Stretches from Mauritania to Nigeria.\n'
     'Major rivers: Niger, Senegal, Volta, Gambia.\n'
     'Lake Chad: Shared by Nigeria, Niger, Chad and Cameroon.\n'
     'Sahara Desert: Northern boundary of West Africa.\n'
     'Tropical rainforest: Southern coastal areas.\n'
     'Savannah: Between the desert and rainforest.\n\n'
     'CLIMATE ZONES:\n'
     'Sahel: Semi-arid. Sparse rainfall. North of the region.\n'
     'Sudan savannah: More rainfall. Grasslands with trees.\n'
     'Guinea savannah: Heavy rainfall. Tall grasses and forests.\n'
     'Tropical rainforest: Very high rainfall. Dense vegetation.\n'
     'Coastal: Humid. High temperatures year-round.\n\n'
     'NATURAL RESOURCES:\n'
     'Oil and gas: Nigeria, Ghana.\n'
     'Gold: Ghana, Mali, Guinea.\n'
     'Diamonds: Sierra Leone, Guinea.\n'
     'Bauxite (aluminium ore): Guinea, Ghana.\n'
     'Cocoa: Ivory Coast and Ghana produce over 60% of the world supply.\n'
     'Groundnuts: Nigeria, Senegal.\n\n'
     'POPULATION:\n'
     'Nigeria is the most populous country in Africa with over 220 million people.\n'
     'West Africa has a young population - many people are under 25 years old.\n'
     'Urbanisation is rapid - cities are growing very fast.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Draw a simple map of West Africa.\n'
     'Mark and label at least 8 countries.\n'
     'Mark the Niger River and the Atlantic coastline.\n'
     'Choose one West African country other than your own. Research:\n'
     'Its capital city, population, main languages, main resources and one cultural fact.'),
    (4, 'Government and Citizenship', 20,
     'Citizens have rights and responsibilities. Understanding government helps us participate effectively.\n\n'
     'TYPES OF GOVERNMENT:\n'
     'Democracy: Government by the people through elected representatives.\n'
     'Citizens vote for their leaders in regular elections.\n'
     'Leaders are accountable to the people.\n'
     'Majority West African countries are democracies.\n\n'
     'LEVELS OF GOVERNMENT:\n'
     'Local government: Manages local services. Roads, markets, sanitation, local schools.\n'
     'State/regional government: Manages state services. State roads, state hospitals.\n'
     'National government: Defence, currency, national policies, international relations.\n\n'
     'BRANCHES OF GOVERNMENT IN NIGERIA (example):\n'
     'Executive: President and ministers. Implements laws and runs the government.\n'
     'Legislature: National Assembly (Senate and House of Representatives). Makes laws.\n'
     'Judiciary: Courts and judges. Interprets laws and settles disputes.\n'
     'The three branches balance and check each other.\n\n'
     'ELECTIONS:\n'
     'Citizens choose their leaders through elections.\n'
     'To vote, you must be registered.\n'
     'Voting is secret - no one should be forced to vote for a particular person.\n'
     'Accepting election results is the foundation of peaceful democracy.\n\n'
     'THE CONSTITUTION:\n'
     'The supreme law of the land.\n'
     'Sets out the structure of government.\n'
     'Protects the rights of citizens.\n'
     'All other laws must be consistent with the constitution.\n\n'
     'CITIZENS AND GOVERNANCE:\n'
     'Register and vote in every election.\n'
     'Know your rights - freedom of expression, assembly, movement.\n'
     'Know your duties - pay taxes, obey laws, serve on juries if required.\n'
     'Hold leaders accountable through peaceful means.\n'
     'Report corruption and wrongdoing.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Find out who your local government representative is.\n'
     'What is their role? What have they done for your community?\n'
     'What one issue would you raise with them if you had the opportunity?\n'
     'Write a letter (even if you do not send it) raising this issue professionally.'),
    (5, 'Economics and Livelihoods', 15,
     'Understanding economics helps us make better decisions about money, work and trade.\n\n'
     'BASIC ECONOMIC CONCEPTS:\n'
     'Needs: Things essential for survival. Food, water, shelter, clothing.\n'
     'Wants: Things desired but not essential for survival. Television, new clothes, entertainment.\n'
     'Scarcity: Resources are limited but wants are unlimited.\n'
     'Choice: Because of scarcity, we must choose how to use our resources.\n\n'
     'ECONOMIC ACTIVITIES:\n'
     'Primary sector: Working directly with natural resources. Farming, fishing, mining.\n'
     'Secondary sector: Manufacturing and processing. Factories, construction.\n'
     'Tertiary sector: Services. Teaching, trading, banking, transport.\n\n'
     'LIVELIHOODS IN WEST AFRICA:\n'
     'Agriculture: The most common livelihood. Subsistence and commercial farming.\n'
     'Key crops: Cocoa, cassava, yam, maize, rice, groundnuts, palm oil.\n'
     'Fishing: Especially in coastal and riverine communities.\n'
     'Trade: Very important. Markets are central to West African economic life.\n'
     'Services: Growing rapidly. Education, healthcare, finance, technology.\n\n'
     'TRADE AND MARKETS:\n'
     'Markets allow producers and buyers to exchange goods and services.\n'
     'Price is determined by supply (how much is available) and demand (how much is wanted).\n'
     'When supply falls or demand rises: Prices go up.\n'
     'When supply rises or demand falls: Prices go down.\n\n'
     'MONEY AND BANKING:\n'
     'Money solves the problem of barter (exchanging goods directly).\n'
     'Banks keep money safe and lend to people who need capital for business.\n'
     'Interest: The cost of borrowing money.\n'
     'Savings: Building financial security for the future.\n\n'
     'TRADE BETWEEN COUNTRIES:\n'
     'Countries export what they produce in excess.\n'
     'Countries import what they cannot produce themselves or not enough of.\n'
     'ECOWAS (Economic Community of West African States): Promotes free trade between member countries.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Visit your local market.\n'
     'Observe and record: What goods are sold? Where do they come from?\n'
     'Ask a trader: What is your main product? Where do you buy it? Who are your customers?\n'
     'What factors affect the price you pay or receive?\n'
     'Write a one-page report on what you observed and learned.'),
])

add_lessons('Primary Creative Arts', [
    (1, 'Introduction to Visual Art', 15,
     'Art is a way of expressing ideas, emotions and experiences through visual forms.\n\n'
     'WHAT IS VISUAL ART?\n'
     'Visual art creates works that are primarily seen and experienced with the eyes.\n'
     'Forms include: Drawing, painting, sculpture, printmaking, photography, design.\n\n'
     'ELEMENTS OF ART:\n'
     'Line: Marks that define edges, shapes and forms.\n'
     'Horizontal lines suggest calm. Vertical lines suggest strength. Diagonal lines suggest movement.\n\n'
     'Shape: Two-dimensional areas defined by lines or colour.\n'
     'Geometric shapes: Circles, squares, triangles, rectangles.\n'
     'Organic shapes: Irregular, found in nature.\n\n'
     'Colour: The visual property produced by different wavelengths of light.\n'
     'Primary colours: Red, yellow, blue. Cannot be made by mixing other colours.\n'
     'Secondary colours: Made by mixing two primaries. Orange, green, violet.\n'
     'Warm colours: Red, orange, yellow. Suggest warmth, energy, excitement.\n'
     'Cool colours: Blue, green, violet. Suggest calm, peace, distance.\n\n'
     'Texture: The surface quality of a work. Rough, smooth, soft, hard.\n'
     'Form: Three-dimensional shape with height, width and depth.\n'
     'Space: The area around and within objects.\n'
     'Value: The lightness or darkness of a colour.\n\n'
     'WEST AFRICAN ART TRADITIONS:\n'
     'Masks: Used in ceremonies. Each culture has unique mask traditions.\n'
     'Bronze casting: Benin bronzes are famous worldwide.\n'
     'Kente cloth (Ghana): Woven in strips with specific patterns and meanings.\n'
     'Batik: Wax-resist dyeing on fabric.\n'
     'Wood carving: Sculptures, furniture and ceremonial objects.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Draw a scene from your daily life using only lines of different types.\n'
     'Use horizontal, vertical, diagonal, curved and dotted lines.\n'
     'Add shading to show light and shadow.\n'
     'Title your drawing and write two sentences describing what it shows.'),
    (2, 'Drawing and Painting', 20,
     'Drawing and painting are fundamental visual art skills.\n\n'
     'DRAWING TECHNIQUES:\n\n'
     'OBSERVATIONAL DRAWING:\n'
     'Drawing what you actually see, not what you think you see.\n'
     'Look carefully at your subject. Study its shapes, proportions and details.\n'
     'Draw what your eyes see, not what your mind thinks the object looks like.\n\n'
     'PROPORTION:\n'
     'The size relationships between different parts of a drawing.\n'
     'When drawing a person: The head is approximately one-seventh of the total height.\n'
     'Eyes are halfway between the top of the head and the chin.\n'
     'Proportion errors make drawings look wrong.\n\n'
     'SHADING TECHNIQUES:\n'
     'Shading shows the effect of light and creates the illusion of three dimensions.\n'
     'Hatching: Parallel lines. Closer lines = darker areas.\n'
     'Cross-hatching: Two sets of parallel lines crossing. Creates darker tones.\n'
     'Blending: Smooth gradation from light to dark.\n'
     'Stippling: Dots of varying density. Many dots = darker areas.\n\n'
     'PERSPECTIVE:\n'
     'The technique of representing three-dimensional objects on a flat surface.\n'
     'One-point perspective: Objects appear smaller as they recede to a single vanishing point.\n'
     'Used for drawing roads, buildings and interiors.\n\n'
     'PAINTING:\n'
     'Watercolour: Transparent paint. Work from light to dark. Cannot cover mistakes easily.\n'
     'Acrylic: Fast-drying, water-soluble while wet. Versatile.\n'
     'Oil paint: Slow-drying. Very rich colours. Can be blended and reworked.\n'
     'Gouache: Opaque watercolour. Can paint light colours over dark.\n\n'
     'COLOUR MIXING:\n'
     'Red plus yellow = Orange.\n'
     'Yellow plus blue = Green.\n'
     'Blue plus red = Violet.\n'
     'Adding white makes colours lighter (tint). Adding black makes them darker (shade).\n\n'
     'PRACTICAL EXERCISE:\n'
     'Draw a still life arrangement: Three objects from your kitchen or workshop.\n'
     'Focus on: Correct proportion and relative sizes.\n'
     'Add shading to make objects look three-dimensional.\n'
     'If you have paint, add colour.'),
    (3, 'Craft and Design', 15,
     'Craft combines artistic skill with practical making. Design solves problems beautifully.\n\n'
     'WHAT IS CRAFT?\n'
     'Craft is the skilled making of objects by hand.\n'
     'Traditional West African crafts: Weaving, pottery, basketry, beadwork, leather work, wood carving.\n'
     'These skills have been passed down through generations.\n'
     'They have both cultural significance and commercial value.\n\n'
     'PRINCIPLES OF GOOD DESIGN:\n'
     'Function: Does it do what it is supposed to do?\n'
     'Aesthetics: Does it look good?\n'
     'Safety: Is it safe to use?\n'
     'Durability: Will it last?\n'
     'Sustainability: Is it made from materials that do not harm the environment?\n'
     'Cost: Can it be made and sold at a price that makes it accessible?\n\n'
     'THE DESIGN PROCESS:\n'
     'Step 1: Identify the problem or need.\n'
     'Step 2: Research existing solutions.\n'
     'Step 3: Generate ideas through sketching.\n'
     'Step 4: Select the best idea.\n'
     'Step 5: Make a prototype.\n'
     'Step 6: Test and evaluate.\n'
     'Step 7: Improve based on testing.\n\n'
     'MATERIALS AND TOOLS:\n'
     'Paper and card: Cutting, folding, joining. Tools: scissors, glue, ruler.\n'
     'Clay: Moulding and shaping. Tools: modelling tools, water.\n'
     'Fabric: Cutting, sewing. Tools: needles, thread, scissors.\n'
     'Natural materials: Leaves, grasses, fibres. Tools: knives, needles.\n\n'
     'WEST AFRICAN CRAFTS TO LEARN:\n'
     'Batik: Wax-resist dyeing of fabric.\n'
     'Weaving: Creating fabric from threads on a loom.\n'
     'Basketry: Weaving plant fibres into baskets and mats.\n'
     'Pottery: Shaping clay into vessels and objects.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Make something useful using only natural or recycled materials.\n'
     'Ideas: A basket from grass or palm leaves, a bowl from clay, a decorative item from recycled materials.\n'
     'Apply the design process: Plan first, make, evaluate.\n'
     'Photograph your finished product.\n'
     'Write: What is it for? What materials did you use? What would you improve?'),
    (4, 'Music and Performance', 15,
     'Music and performance are central to West African culture and identity.\n\n'
     'ELEMENTS OF MUSIC:\n'
     'Rhythm: The pattern of long and short sounds. The heartbeat of music.\n'
     'Melody: A sequence of notes that make up a tune. What you hum.\n'
     'Harmony: Two or more notes sounded together. Creates richness.\n'
     'Tempo: The speed of music. Slow (largo) to very fast (presto).\n'
     'Dynamics: The volume of music. Soft (piano) to loud (forte).\n'
     'Timbre: The distinctive sound quality of an instrument or voice.\n\n'
     'WEST AFRICAN MUSICAL TRADITIONS:\n'
     'Drumming: Central to West African music. The master drummer communicates meaning.\n'
     'Talking drums: Drums that imitate the tones of speech.\n'
     'Griot tradition: Hereditary musicians and storytellers who preserve oral history.\n'
     'Call and response: A leader sings a phrase, the group responds.\n\n'
     'TRADITIONAL INSTRUMENTS:\n'
     'Djembe: Goblet-shaped drum from West Africa. Used across the region.\n'
     'Talking drum (dundun): Hourglass drum. Pitch changes by squeezing.\n'
     'Kora: 21-string harp-lute from Mande tradition.\n'
     'Balafon: Wooden xylophone with gourd resonators.\n'
     'Shekere: Gourd covered with beaded net.\n\n'
     'MODERN WEST AFRICAN MUSIC:\n'
     'Highlife: Developed in Ghana and Nigeria. Combines Western instruments with African rhythms.\n'
     'Afrobeats: Contemporary genre. Fela Kuti, Burna Boy, Wizkid, Davido are stars.\n'
     'Afropop: Contemporary pop music from across Africa.\n\n'
     'PERFORMANCE SKILLS:\n'
     'Stage presence: Confidence and engagement with the audience.\n'
     'Timing: Starting and stopping together in ensemble.\n'
     'Expression: Conveying emotion through performance.\n'
     'Preparation: Thorough practice before performance.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Learn and practice a traditional song from your culture.\n'
     'Create a simple rhythm pattern on an available percussion instrument or surfaces.\n'
     'Perform both for your family or friends.\n'
     'Record a brief description of the song: Its origin, meaning and when it is traditionally sung.'),
    (5, 'Technology and Innovation', 15,
     'Technology transforms societies. Africa is embracing technology to leapfrog development challenges.\n\n'
     'WHAT IS TECHNOLOGY?\n'
     'Technology is the application of scientific knowledge to solve practical problems.\n'
     'Technology is as old as humanity: Fire, the wheel, writing, printing.\n'
     'Modern technology: Computers, internet, mobile phones, renewable energy.\n\n'
     'THE IMPACT OF MOBILE TECHNOLOGY IN AFRICA:\n'
     'Africa has one of the highest rates of mobile phone adoption in the world.\n'
     'Mobile money: M-Pesa in Kenya changed banking. Similar services across West Africa.\n'
     'Mobile health: Diagnosis, telemedicine, health records on phones.\n'
     'Mobile agriculture: Farmers access market prices, weather forecasts, expert advice.\n'
     'Digital commerce: Buying and selling through phones and apps.\n\n'
     'SOLAR TECHNOLOGY IN WEST AFRICA:\n'
     'West Africa receives abundant solar energy.\n'
     'Solar panels provide electricity to homes and businesses without grid connection.\n'
     'Solar water pumps bring water to villages without running water.\n'
     'Solar-powered irrigation allows farming in dry seasons.\n\n'
     'AFRICAN INNOVATION:\n'
     'Many Africans are solving African problems with African solutions.\n'
     'M-Pesa: Mobile money system that started in Kenya.\n'
     'Zipline: Drones delivering medical supplies to remote Rwanda.\n'
     'BRCK: Rugged internet device designed for African conditions.\n'
     'Lifebank: Technology delivering blood and oxygen to Nigerian hospitals.\n\n'
     'THE FUTURE OF TECHNOLOGY IN WEST AFRICA:\n'
     'Artificial Intelligence: Learning algorithms improving healthcare, agriculture and business.\n'
     'Blockchain: Secure digital records for land ownership, supply chains.\n'
     'Robotics: Automation of manufacturing and agriculture.\n'
     'Internet of Things: Connected devices improving efficiency and safety.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Identify one problem in your community that could be solved with technology.\n'
     'Research whether a technology solution already exists anywhere in the world.\n'
     'If yes: How could it be adapted for your community?\n'
     'If no: What technology solution could you imagine?\n'
     'Sketch or describe your idea. This is how innovations begin.'),
])

add_lessons('Primary Music', [
    (1, 'Rhythm and Beat', 15,
     'Rhythm is the heartbeat of music. Every piece of music is built on rhythm.\n\n'
     'WHAT IS RHYTHM?\n'
     'Rhythm is the pattern of sounds and silences in music.\n'
     'It is what makes you want to tap your foot or clap your hands.\n'
     'Without rhythm, music would have no energy or structure.\n\n'
     'BEAT:\n'
     'The beat is the steady, regular pulse of music.\n'
     'Like a heartbeat or a ticking clock - regular and continuous.\n'
     'When you clap along to music, you are following the beat.\n'
     'Tempo is how fast or slow the beat is.\n\n'
     'RHYTHM VS BEAT:\n'
     'Beat: The steady pulse. Never changes within a piece.\n'
     'Rhythm: Patterns of long and short sounds that move with the beat.\n'
     'Different instruments or voices can play different rhythms over the same beat.\n\n'
     'NOTE VALUES:\n'
     'Whole note: 4 beats.\n'
     'Half note: 2 beats.\n'
     'Quarter note: 1 beat.\n'
     'Eighth note: Half a beat.\n'
     'These are the building blocks of rhythm in written music.\n\n'
     'WEST AFRICAN RHYTHM:\n'
     'West African music is famous for complex, layered rhythms.\n'
     'Multiple drummers play different rhythmic patterns simultaneously.\n'
     'These patterns interlock to create complex rhythmic tapestries.\n'
     'This tradition has influenced music worldwide - jazz, blues, rock all have African rhythm at their roots.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Clap a steady beat. Keep it absolutely steady.\n'
     'While clapping, tap your foot twice as fast.\n'
     'Now try clapping three times for every two foot taps.\n'
     'This is called polyrhythm - multiple rhythms at once.\n'
     'Practice with a partner: One person keeps the beat, the other plays rhythmic variations.'),
    (2, 'Melody and Harmony', 15,
     'Melody is what you sing. Harmony is what surrounds it.\n\n'
     'MELODY:\n'
     'A melody is a sequence of notes that forms a musical idea or tune.\n'
     'It is what you hum or whistle when you remember a piece of music.\n'
     'A melody moves up (ascending) and down (descending) and has shape.\n\n'
     'PITCH:\n'
     'Pitch is how high or low a sound is.\n'
     'Determined by how fast the sound vibrates (frequency).\n'
     'High frequency = high pitch. Low frequency = low pitch.\n'
     'The musical alphabet uses the letters A, B, C, D, E, F, G.\n'
     'The scale progresses from low to high: C D E F G A B C.\n\n'
     'SCALES:\n'
     'A scale is a series of notes in order from low to high.\n'
     'The major scale: Do Re Mi Fa Sol La Ti Do.\n'
     'It has a pattern of steps: Whole whole half whole whole whole half.\n'
     'This pattern gives major scales their bright, happy sound.\n'
     'Minor scales have a different pattern and a sadder, deeper sound.\n\n'
     'HARMONY:\n'
     'Harmony is when two or more notes are played or sung at the same time.\n'
     'Consonant harmony: Notes that sound pleasant together. A chord.\n'
     'Dissonant harmony: Notes that create tension. Resolves to consonance.\n'
     'A chord is three or more notes played simultaneously.\n\n'
     'SINGING IN HARMONY:\n'
     'Singing the same melody together is called unison.\n'
     'Singing different notes that work together is called harmony.\n'
     'Two-part harmony: Two different melodic lines.\n'
     'Call and response is a form of harmony common in West African music.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Sing the major scale: Do Re Mi Fa Sol La Ti Do.\n'
     'Go slowly and listen carefully to each interval.\n'
     'Now sing it backwards from Do Ti La Sol Fa Mi Re Do.\n'
     'With a partner: One sings a melody, the other hums a note that sounds good with it.\n'
     'Experiment until you find notes that create pleasing harmony.'),
    (3, 'Traditional West African Music', 20,
     'West Africa has one of the richest musical traditions in the world.\n\n'
     'THE GRIOT TRADITION:\n'
     'Griots are hereditary musician-storytellers found across West Africa.\n'
     'In Mande culture they are called Jali. In Wolof culture, Gewel.\n'
     'They preserve oral history, genealogies and cultural knowledge.\n'
     'They are advisors, historians, praise singers and entertainers.\n'
     'This tradition is thousands of years old.\n\n'
     'THE ROLE OF DRUMS:\n'
     'Drums are the foundation of West African music.\n'
     'The master drummer leads the ensemble and communicates to other musicians.\n'
     'Talking drums can imitate the tonal patterns of speech.\n'
     'The djembe is now famous worldwide. Originated in Guinea and Mali.\n\n'
     'MUSIC AND CEREMONY:\n'
     'Music accompanies every major life event in West African culture.\n'
     'Birth: Songs celebrating new life.\n'
     'Initiation: Music marking transition from childhood to adulthood.\n'
     'Marriage: Songs of celebration and blessing.\n'
     'Harvest: Music giving thanks for abundance.\n'
     'Funeral: Music to mourn and celebrate the life of the deceased.\n\n'
     'WEST AFRICAN MUSICAL INSTRUMENTS:\n'
     'Kora: 21-string harp-lute from Mande tradition. Complex, beautiful instrument.\n'
     'Balafon: Wooden xylophone. Played with rubber mallets.\n'
     'Djembe: Goblet drum. Played with bare hands.\n'
     'Talking drum (dundun): Hourglass drum. Pitch changed by squeezing.\n'
     'Shekere: Gourd covered with net of beads. Shaken for rhythm.\n'
     'Bells and rattles: Used to mark the beat.\n\n'
     'MUSIC IN YOUR CULTURE:\n'
     'Every ethnic group in West Africa has unique musical traditions.\n'
     'These traditions are part of your heritage and identity.\n'
     'Learning and preserving them is a form of cultural stewardship.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Interview an elder in your community about traditional music.\n'
     'Ask: What traditional songs do you remember? When were they sung?\n'
     'Ask them to sing or hum one for you.\n'
     'Record it if possible or write down the words.\n'
     'Learn one traditional song from your culture.'),
    (4, 'Reading and Writing Music', 15,
     'Musical notation allows music to be written down and shared.\n\n'
     'THE STAFF:\n'
     'Music is written on a staff: Five horizontal lines and four spaces.\n'
     'Each line and space represents a different pitch.\n'
     'Notes written on higher lines and spaces are higher in pitch.\n\n'
     'CLEFS:\n'
     'A clef is a symbol at the start of the staff that identifies the pitches.\n'
     'Treble clef: Used for higher instruments and voices.\n'
     'Bass clef: Used for lower instruments and voices.\n\n'
     'NOTE NAMES ON THE TREBLE CLEF:\n'
     'Lines (bottom to top): Every Good Boy Does Fine (E G B D F).\n'
     'Spaces (bottom to top): FACE.\n\n'
     'NOTE VALUES:\n'
     'Whole note: Open oval. 4 beats.\n'
     'Half note: Open oval with a stem. 2 beats.\n'
     'Quarter note: Filled oval with a stem. 1 beat.\n'
     'Eighth note: Filled oval with stem and flag. Half a beat.\n\n'
     'TIME SIGNATURES:\n'
     'Two numbers at the start of the music.\n'
     'Top number: How many beats in each bar.\n'
     'Bottom number: What type of note gets one beat.\n'
     '4/4: Four beats per bar, quarter note gets one beat. Most common.\n'
     '3/4: Three beats per bar. Waltz time.\n'
     '6/8: Six eighth notes per bar. Compound time.\n\n'
     'RESTS:\n'
     'Rests are silences. Each note value has a corresponding rest symbol.\n'
     'Silences are just as important as sounds in music.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Draw a treble clef on a staff.\n'
     'Write the notes E G B D F on the lines.\n'
     'Write the notes F A C E in the spaces.\n'
     'Write a simple four-bar rhythm using quarter notes and half notes.\n'
     'Clap the rhythm you have written.'),
    (5, 'Creating and Performing Music', 15,
     'Creating and performing music develops creativity, confidence and cultural connection.\n\n'
     'COMPOSITION:\n'
     'Composition means creating original music.\n'
     'A composition can be simple or complex.\n'
     'Every professional musician started with simple compositions.\n\n'
     'STARTING TO COMPOSE:\n'
     'Begin with a simple rhythm pattern. Repeat it and vary it.\n'
     'Add a melody over the rhythm.\n'
     'Develop the melody: Where does it go? Does it repeat? Does it change?\n'
     'Add harmony if you have other musicians.\n'
     'Give your piece a title that reflects its mood or meaning.\n\n'
     'MUSICAL FORM:\n'
     'Form is the structure of a musical piece.\n'
     'A B form: Two contrasting sections.\n'
     'A B A form: Return to the opening section after a contrasting middle section.\n'
     'Verse-chorus: Common in songs. Verses tell the story. Chorus repeats the main theme.\n'
     'Call and response: Leader plays/sings, group responds. Very common in West Africa.\n\n'
     'PERFORMANCE SKILLS:\n'
     'Preparation: Know your music thoroughly before performing.\n'
     'Focus: Concentrate on the music, not the audience.\n'
     'Ensemble skills: Listen to others. Keep time together.\n'
     'Expression: Bring emotion and meaning to your performance.\n'
     'Recovery: If you make a mistake, continue without stopping.\n\n'
     'STAGE PRESENCE:\n'
     'Confidence comes from thorough preparation.\n'
     'Stand or sit with good posture.\n'
     'Make appropriate eye contact with the audience.\n'
     'Acknowledge applause graciously.\n\n'
     'PRACTICAL PROJECT:\n'
     'Compose a short piece of music in call-and-response form.\n'
     'The call can be a drum pattern or a sung phrase.\n'
     'The response should answer the call musically.\n'
     'Perform it with at least one other person.\n'
     'If possible, record your performance.\n'
     'Evaluate: What worked well? What would you do differently?'),
])

# Print summary
print('\n' + '='*60)
from courses.models import Course
total = 0
for c in Course.objects.all().order_by('title'):
    count = c.lessons.count()
    total += count
    if count == 0:
        print(f'  STILL NEEDS LESSONS: {c.title}')
print(f'\nTOTAL LESSONS: {total}')