import os
import django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'skillscontinua_core.settings')
django.setup()

from courses.models import Course, Lesson

def add_lessons(title, lessons_data):
    try:
        course = Course.objects.get(title=title)
        Lesson.objects.filter(course=course).delete()
        for order, lesson_title, duration, content in lessons_data:
            Lesson.objects.create(
                course=course,
                title=lesson_title,
                content_type='text',
                content_text=content,
                order=order,
                duration_minutes=duration,
                is_active=True
            )
        print(f'OK: {title} - {course.lessons.count()} lessons')
    except Course.DoesNotExist:
        print(f'NOT FOUND: {title}')

# ============================================================
# SPREADSHEETS AND NUMBERS
# ============================================================
add_lessons('Spreadsheets and Numbers', [
    (1, 'Introduction to Spreadsheets', 20,
     'Spreadsheets are one of the most powerful business tools ever created.\n\n'
     'WHAT IS A SPREADSHEET?\n'
     'A spreadsheet is a grid of cells arranged in rows and columns.\n'
     'Each cell can hold text, numbers, dates or formulas.\n'
     'Formulas perform calculations automatically.\n'
     'Charts visualise data graphically.\n\n'
     'COMMON SPREADSHEET APPLICATIONS:\n'
     'Microsoft Excel: Industry standard. Part of Microsoft Office.\n'
     'LibreOffice Calc: Free, open source. Compatible with Excel files.\n'
     'Google Sheets: Free, browser-based. Real-time collaboration.\n\n'
     'WHAT SPREADSHEETS ARE USED FOR:\n'
     'Financial management: Income records, expense tracking, budgets, profit calculations.\n'
     'Business data: Customer lists, inventory, price lists, order tracking.\n'
     'Analysis: Comparing options, calculating trends, making projections.\n'
     'Reporting: Charts and graphs for presentations.\n\n'
     'THE SPREADSHEET INTERFACE:\n'
     'Cell: The intersection of a row and column. Named by column letter and row number such as A1, B3, C12.\n'
     'Active cell: The selected cell. Highlighted with a border.\n'
     'Formula bar: Shows the content of the active cell.\n'
     'Name box: Shows the address of the active cell.\n'
     'Sheet tabs: Multiple sheets in one file.\n'
     'Rows are numbered 1, 2, 3 and columns are lettered A, B, C.\n\n'
     'NAVIGATING:\n'
     'Click any cell to select it.\n'
     'Arrow keys move one cell at a time.\n'
     'CTRL plus Arrow jumps to the last filled cell in a direction.\n'
     'CTRL plus Home goes to cell A1.\n'
     'CTRL plus End goes to the last used cell.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Open LibreOffice Calc or Google Sheets.\n'
     'Type your name in cell A1.\n'
     'Type today\'s date in B1.\n'
     'Type the numbers 1 to 10 in cells A2 to A11.\n'
     'Navigate using keyboard shortcuts.\n'
     'Save the file as My_First_Spreadsheet.'),

    (2, 'Data Entry and Formatting', 25,
     'Organised, well-formatted data is the foundation of useful spreadsheets.\n\n'
     'ENTERING DATA:\n'
     'Click a cell and type. Press Enter to confirm and move down. Press Tab to move right.\n'
     'Numbers: Type digits. No currency symbols needed - format cells separately.\n'
     'Dates: Type in the format your system uses, usually DD/MM/YYYY.\n'
     'Text: Type normally. Long text may overflow into adjacent cells.\n\n'
     'EDITING DATA:\n'
     'Click a cell and type to replace content.\n'
     'F2 edits a cell without replacing - puts cursor inside cell.\n'
     'Backspace clears cell content.\n'
     'CTRL plus Z undoes the last action.\n\n'
     'SELECTING RANGES:\n'
     'Click and drag to select a rectangle of cells.\n'
     'Click, hold Shift, click another cell to select a range.\n'
     'CTRL plus click selects multiple non-adjacent cells.\n'
     'CTRL plus A selects all cells.\n\n'
     'NUMBER FORMATS:\n'
     'Right-click selected cells and choose Format Cells then Number tab.\n'
     'General: Default. Number: Specify decimal places.\n'
     'Currency: Adds currency symbol. Percentage: Multiplies by 100 and adds percent symbol.\n\n'
     'TEXT FORMATTING:\n'
     'Bold: CTRL plus B. Italic: CTRL plus I. Underline: CTRL plus U.\n'
     'Font, size and colour from the toolbar.\n'
     'Wrap text: Displays long text on multiple lines within the cell.\n\n'
     'COLUMN WIDTH:\n'
     'Double-click column border to auto-fit to content.\n'
     'Freeze panes: View then Freeze Rows and Columns. Keeps headers visible when scrolling.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Create a monthly income and expense tracker.\n'
     'Column A: Date. Column B: Description. Column C: Income. Column D: Expense.\n'
     'Enter at least 10 transactions.\n'
     'Format income column in green and expense column in red.\n'
     'Format all number cells as Currency. Bold the header row.'),

    (3, 'Formulas and Functions', 30,
     'Formulas are what make spreadsheets powerful. They perform calculations automatically.\n\n'
     'FORMULAS:\n'
     'All formulas start with the equals sign.\n'
     'Examples of basic formulas:\n'
     'equals A1 plus B1: Add the values in A1 and B1.\n'
     'equals A1 minus B1: Subtract B1 from A1.\n'
     'equals A1 times B1: Multiply A1 by B1.\n'
     'equals A1 divided by B1: Divide A1 by B1.\n\n'
     'CELL REFERENCES:\n'
     'When you reference a cell in a formula, it uses the value in that cell.\n'
     'If the value changes, the formula result updates automatically.\n'
     'This is the power of spreadsheets.\n\n'
     'RELATIVE REFERENCES:\n'
     'When you copy a formula, the references adjust relative to the new position.\n'
     'Formula in C1: equals A1 plus B1. Copied to C2 becomes equals A2 plus B2.\n\n'
     'ABSOLUTE REFERENCES:\n'
     'Add dollar sign before column letter and row number to fix the reference.\n'
     'Dollar A Dollar 1 always refers to A1 regardless of where the formula is copied.\n'
     'Use when a formula must always refer to one fixed cell such as a tax rate.\n\n'
     'COMMON FUNCTIONS:\n\n'
     'SUM: Adds a range of values.\n'
     'equals SUM open bracket A1 colon A10 close bracket adds all values from A1 to A10.\n\n'
     'AVERAGE: Calculates average of values in the range.\n\n'
     'MAX and MIN: Find the largest or smallest value in a range.\n\n'
     'COUNT: Counts cells containing numbers.\n\n'
     'IF: Performs different actions based on a condition.\n'
     'Syntax: equals IF open bracket condition, value if true, value if false close bracket.\n'
     'Example: Shows Good if C1 is over 1000, otherwise shows Low.\n\n'
     'VLOOKUP: Looks up a value in a table and returns a related value.\n'
     'Useful for looking up a product code to return its price.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Create a business income tracker for one month.\n'
     'Columns: Week number, Income, Expenses, Profit calculated as Income minus Expenses.\n'
     'Add a row at the bottom with totals using SUM, average using AVERAGE,\n'
     'best week using MAX, and worst week using MIN.'),

    (4, 'Charts and Data Analysis', 25,
     'Charts turn numbers into pictures. Data analysis turns data into insights.\n\n'
     'CREATING CHARTS:\n'
     'Select the data you want to chart.\n'
     'Click Insert then Chart.\n'
     'Choose chart type. Preview updates as you select.\n'
     'Add title, axis labels and legend.\n'
     'Click outside the chart to deselect. Click inside to edit.\n\n'
     'CHART TYPES:\n\n'
     'COLUMN CHART:\n'
     'Best for comparing values across categories.\n'
     'Example: Monthly sales by product, income by month.\n\n'
     'LINE CHART:\n'
     'Best for showing trends over time.\n'
     'Example: Monthly revenue trend over the year.\n\n'
     'PIE CHART:\n'
     'Best for showing proportions of a whole.\n'
     'Do not use pie charts with more than 5 or 6 categories - becomes hard to read.\n\n'
     'SORTING DATA:\n'
     'Select the data range.\n'
     'Click Data then Sort.\n'
     'Choose the column to sort by and direction.\n\n'
     'FILTERING DATA:\n'
     'Click Data then AutoFilter. Adds dropdown arrows to headers.\n'
     'Click an arrow to show only rows matching a criteria.\n\n'
     'PIVOT TABLES:\n'
     'Powerful tool for summarising large amounts of data.\n'
     'Click Insert then Pivot Table.\n'
     'Drag fields to Rows, Columns and Values areas.\n'
     'Instantly summarises data in different ways without formulas.\n\n'
     'CONDITIONAL FORMATTING:\n'
     'Automatically formats cells based on their value.\n'
     'Example: Highlight expenses over budget in red. Highlight top performers in green.\n'
     'Makes patterns visible at a glance.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Take your monthly income tracker.\n'
     'Create a column chart showing income versus expenses by week.\n'
     'Create a pie chart showing the proportion of different expense categories.\n'
     'Add conditional formatting to highlight weeks where profit was negative in red.'),

    (5, 'Spreadsheets for Business', 20,
     'Spreadsheets can manage almost every aspect of a small business efficiently.\n\n'
     'ESSENTIAL BUSINESS SPREADSHEETS:\n\n'
     'CASH FLOW FORECAST:\n'
     'Projects income and expenses week by week or month by month.\n'
     'Shows when cash will be tight before it happens.\n'
     'Columns: Month, Opening balance, Income, Expenses, Closing balance.\n\n'
     'QUOTATION CALCULATOR:\n'
     'Enter job details such as materials and labour hours.\n'
     'Spreadsheet calculates the price automatically.\n'
     'Reduces errors and ensures consistent pricing.\n\n'
     'CUSTOMER DATABASE:\n'
     'Name, contact details, address, last order date, total spent.\n'
     'Filter to find customers who have not ordered recently.\n'
     'Sort by spending to identify best customers.\n\n'
     'INVENTORY TRACKER:\n'
     'Product, quantity in stock, reorder level, cost price, selling price.\n'
     'Formula alerts when stock falls below reorder level.\n\n'
     'PAYROLL CALCULATOR:\n'
     'Employee names, hours worked, hourly rate.\n'
     'Formula calculates gross pay, deductions and net pay.\n\n'
     'TIPS FOR PROFESSIONAL SPREADSHEETS:\n'
     'Use one row for headers. Make them bold.\n'
     'Keep data in one consistent table - one type of data per sheet.\n'
     'Protect important formulas to prevent accidental overwriting.\n'
     'Document complex formulas with comments or a Notes sheet.\n\n'
     'SHARING AND COLLABORATION:\n'
     'Google Sheets: Share with a link. Control who can view or edit.\n'
     'Multiple people can work simultaneously.\n'
     'All changes are tracked with user and timestamp.\n\n'
     'PRACTICAL PROJECT:\n'
     'Build a business starter pack in one file with four sheets:\n'
     'Sheet 1: Monthly income and expense tracker.\n'
     'Sheet 2: Customer list with contact details.\n'
     'Sheet 3: Simple quotation calculator for your trade.\n'
     'Sheet 4: Basic inventory tracker.\n'
     'This is your business management system.'),
])

# ============================================================
# SOCIAL MEDIA FOR BUSINESS
# ============================================================
add_lessons('Social Media for Business', [
    (1, 'Introduction to Social Media for Business', 20,
     'Social media has transformed how businesses find customers. Used well, it is one of the most powerful free marketing tools available.\n\n'
     'WHAT IS SOCIAL MEDIA?\n'
     'Social media are online platforms that allow people to create and share content and connect with others.\n'
     'Major platforms: Facebook, Instagram, WhatsApp, TikTok, Twitter, LinkedIn, YouTube.\n'
     'Over 4 billion people use social media worldwide.\n'
     'In West Africa, Facebook and WhatsApp have the highest penetration.\n\n'
     'WHY SOCIAL MEDIA MATTERS FOR YOUR BUSINESS:\n'
     'Free or low cost compared to traditional advertising.\n'
     'Reaches your local community and far beyond.\n'
     'Builds trust through consistent, quality content.\n'
     'Allows two-way conversation with potential customers.\n\n'
     'CHOOSING THE RIGHT PLATFORMS:\n\n'
     'FACEBOOK:\n'
     'Largest social network. Good for local community businesses.\n'
     'Facebook Pages for businesses. Facebook Groups for community building.\n'
     'Paid advertising targets by location, age and interests with great precision.\n'
     'Best for most businesses, especially services targeting adults.\n\n'
     'INSTAGRAM:\n'
     'Visual platform of photos and videos.\n'
     'Stories, Reels and Posts available.\n'
     'Best for visual trades like carpentry, tiling, design and food.\n'
     'Very powerful for before-and-after content.\n\n'
     'WHATSAPP BUSINESS:\n'
     'Direct communication with customers.\n'
     'Business profile, quick replies and product catalogue.\n'
     'Broadcast lists for updates to multiple customers.\n'
     'Best for all businesses. Almost everyone in West Africa uses WhatsApp.\n\n'
     'TIKTOK:\n'
     'Short videos. Growing rapidly across all ages.\n'
     'Organic reach is still very high - free content can reach thousands.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Search for three businesses in your trade on Facebook and Instagram.\n'
     'Note: How often do they post? What type of content? How many followers?\n'
     'What are they doing well? What could be improved?\n'
     'This competitive research will shape your own strategy.'),

    (2, 'Creating Content That Attracts Customers', 25,
     'Content is what you share on social media. Good content attracts, educates and converts.\n\n'
     'THE CONTENT MINDSET:\n'
     'Social media is not advertising. It is providing value.\n'
     '80% of content should educate, entertain or inspire. 20% can be promotional.\n'
     'Think: What does my potential customer find useful, interesting or entertaining?\n'
     'Give value first. Sales follow naturally.\n\n'
     'TYPES OF CONTENT THAT WORK:\n\n'
     'BEFORE AND AFTER:\n'
     'Show the transformation your work creates.\n'
     'A painted room, a repaired engine, a completed building, a finished garment.\n'
     'Extremely powerful. Easy to create. Gets high engagement.\n'
     'Always get permission before sharing client property.\n\n'
     'PROCESS VIDEOS:\n'
     'Short clips of you working. People love to see how things are done.\n'
     'A carpenter cutting a joint, a plumber fitting a pipe.\n'
     'Shows skill and professionalism. Builds trust.\n\n'
     'TIPS AND ADVICE:\n'
     'Share knowledge freely. This positions you as an expert.\n'
     'Five things to check before hiring a plumber.\n'
     'How to tell if your roof needs attention.\n'
     'People share useful content - it extends your reach.\n\n'
     'TESTIMONIALS:\n'
     'Ask satisfied clients to record a short video or write a few sentences.\n'
     'Screenshot positive WhatsApp messages with permission.\n'
     'Social proof is the most powerful form of marketing.\n\n'
     'CONTENT PLANNING:\n'
     'Post consistently - 3 to 5 times per week is ideal.\n'
     'Plan content a week in advance.\n'
     'Monday: Tip or advice. Wednesday: Before and after. Friday: Behind the scenes.\n\n'
     'PHOTOGRAPHY TIPS:\n'
     'Good lighting makes a huge difference. Use natural light where possible.\n'
     'Clean the area before photographing. Remove clutter.\n'
     'Horizontal photos for Facebook. Square or vertical for Instagram.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Take three photos of your work this week.\n'
     'Write a caption for each: What was the job? What problem did it solve?\n'
     'Post one to your business page or WhatsApp status. Note the response.'),

    (3, 'Building Your Following and Engagement', 20,
     'Followers and engagement are the currency of social media.\n\n'
     'SETTING UP YOUR BUSINESS PROFILE:\n'
     'Use your business name, not a personal name.\n'
     'Profile photo: Your logo, your face or a clean photo of your work.\n'
     'Cover photo: A professional image of your best work.\n'
     'Bio section: What you do, where you are, how to contact you.\n'
     'Include your phone number and location.\n\n'
     'GROWING YOUR FOLLOWING:\n\n'
     'START WITH PEOPLE YOU KNOW:\n'
     'Ask friends, family and existing customers to like or follow your page.\n'
     'Your first 100 followers come from your existing network.\n\n'
     'ENGAGE WITH YOUR COMMUNITY:\n'
     'Comment meaningfully on posts from potential customers.\n'
     'Join local Facebook Groups and contribute value.\n'
     'Follow and engage with local influencers in your area.\n\n'
     'USE RELEVANT HASHTAGS:\n'
     'Hashtags make your content discoverable.\n'
     'Use specific hashtags like Lagos carpenter, Accra plumber, Freetown electrician.\n'
     '5 to 10 relevant hashtags per post is sufficient.\n\n'
     'UNDERSTANDING THE ALGORITHM:\n'
     'Algorithms show your content to more people when it gets engagement.\n'
     'Engagement means likes, comments, shares and saves.\n'
     'Ask people to like, comment or share.\n'
     'Content that generates conversation reaches far more people.\n\n'
     'WHATSAPP STATUS STRATEGY:\n'
     'Post to WhatsApp status daily - all your contacts see it.\n'
     'Mix: Work photos, tips, offers, personal moments.\n'
     'Respond to anyone who views and replies.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Set up or improve your Facebook Business Page this week.\n'
     'Complete all profile sections.\n'
     'Post three times this week: one tip, one before and after, one personal message.\n'
     'Record your follower count. Check again in four weeks.'),

    (4, 'Paid Advertising and Analytics', 25,
     'Free organic content builds slowly. Paid advertising accelerates your reach dramatically.\n\n'
     'FACEBOOK AND INSTAGRAM ADVERTISING:\n'
     'Even very small budgets get results.\n'
     'Targeting options: Location within a radius of your business, Age, Gender, Interests.\n'
     'This precision is impossible with traditional advertising.\n\n'
     'CREATING A FACEBOOK AD:\n\n'
     'Step 1: Go to your Facebook Page. Click Promote or Boost Post.\n'
     'Step 2: Choose your objective. For most small businesses, Get more messages is most effective.\n'
     'Step 3: Define your audience.\n'
     'Location: Your city or a radius around your location.\n'
     'Age: 25 to 55 for most services.\n'
     'Interests: Homeowners, new homes, construction for building trades.\n'
     'Step 4: Set budget and duration.\n'
     'Start small: 1000 to 2000 naira per day for 7 days.\n'
     'Test before spending large amounts.\n'
     'Step 5: Create the ad.\n'
     'Use your best before and after photo or a short video.\n'
     'Headline: Your business name and what you do.\n'
     'Text: Who you help, what problem you solve, how to contact you.\n'
     'Call to action button: Send Message or Call Now.\n'
     'Step 6: Monitor and adjust.\n'
     'Check results daily. Stop ads that are not performing.\n'
     'Scale up ads that are working.\n\n'
     'UNDERSTANDING ANALYTICS:\n\n'
     'REACH: How many unique people saw your content.\n'
     'IMPRESSIONS: How many times your content was displayed.\n'
     'ENGAGEMENT RATE: Likes plus comments plus shares divided by reach. Above 3% is good.\n'
     'CLICK-THROUGH RATE: Percentage of people who clicked your link. Above 1% is good for paid ads.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Boost one post on your Facebook Page.\n'
     'Budget: The minimum available - just to learn the process.\n'
     'Target: Your city, age 25 to 55, all genders.\n'
     'Run for 7 days.\n'
     'Record: Reach, engagements, messages received.\n'
     'Calculate: Cost per message received. Was it worth it?'),

    (5, 'Digital Marketing Strategy', 15,
     'A strategy turns random posting into a systematic customer acquisition machine.\n\n'
     'YOUR DIGITAL MARKETING STRATEGY:\n\n'
     'DEFINE YOUR GOAL:\n'
     'What do you want digital marketing to achieve?\n'
     'More enquiries? More sales of a specific service? More clients in a new area?\n'
     'One clear goal makes everything else easier.\n\n'
     'DEFINE YOUR CUSTOMER:\n'
     'Who is your ideal customer?\n'
     'Where do they live? What do they earn? What do they worry about?\n'
     'What social media do they use? When are they online?\n\n'
     'CHOOSE YOUR PLATFORMS:\n'
     'You do not need to be on every platform.\n'
     'Pick one or two where your customers spend time.\n'
     'Facebook plus WhatsApp Business is the minimum for most West African businesses.\n\n'
     'CREATE A CONTENT CALENDAR:\n'
     'Plan what you will post each week.\n'
     'Monday: Educational tip. Wednesday: Work photo. Friday: Customer testimonial.\n'
     'Consistency beats perfection.\n\n'
     'MEASURE AND IMPROVE:\n'
     'Check your analytics monthly.\n'
     'What content got the most engagement? Make more of that.\n'
     'Which posts generated the most enquiries? Understand why.\n\n'
     'INTEGRATING ONLINE AND OFFLINE:\n'
     'Put your social media handles on business cards, vehicle and workwear.\n'
     'Tell every customer to follow you.\n'
     'Encourage happy customers to leave a Google review and tag you in posts.\n\n'
     'THE CONTENT MACHINE:\n'
     'Every job is content.\n'
     'Photo before starting. Photo during key stages. Photo of the completed work.\n'
     'Caption: What the job was. What problem it solved. Call to action: contact details.\n'
     '30 minutes of content creation per week can transform your business visibility.\n\n'
     'PRACTICAL PROJECT:\n'
     'Create a one-month social media plan for your business.\n'
     'Week 1: Set up or improve profiles on Facebook and Instagram.\n'
     'Week 2: Post Monday, Wednesday, Friday with varied content.\n'
     'Week 3: Engage with comments and try one paid boost.\n'
     'Week 4: Review analytics and plan Month 2.\n'
     'Commit to this for three months. Results take time but they compound.'),
])

# ============================================================
# GRAPHICS AND MEDIA PRODUCTION
# ============================================================
add_lessons('Graphics and Media Production', [
    (1, 'Introduction to Graphic Design', 20,
     'Graphic design communicates visually. It is the art of making information attractive, clear and memorable.\n\n'
     'WHAT IS GRAPHIC DESIGN?\n'
     'Graphic design combines text, images, colour and layout to communicate a message.\n'
     'Used in: Logos, business cards, social media posts, flyers, signage, packaging, websites.\n'
     'Good design attracts attention, communicates clearly and builds trust.\n'
     'Poor design repels and undermines credibility.\n\n'
     'WHY GRAPHIC DESIGN SKILLS ARE VALUABLE:\n'
     'Every business needs design - logos, flyers, social media graphics, business cards.\n'
     'Designers charge well for their services.\n'
     'Self-employed people can design their own materials - saves money and gives control.\n'
     'Growing demand as more businesses go online and need digital content.\n\n'
     'TOOLS FOR GRAPHIC DESIGN:\n\n'
     'CANVA (RECOMMENDED FOR BEGINNERS):\n'
     'Free web-based tool. Also has a mobile app.\n'
     'Hundreds of templates for every design need.\n'
     'Drag-and-drop interface. No design experience needed.\n'
     'Free plan is excellent. Find it at canva.com.\n\n'
     'ADOBE PHOTOSHOP:\n'
     'Industry standard for photo editing and digital art.\n'
     'Powerful but complex. Subscription cost.\n\n'
     'GIMP:\n'
     'Free alternative to Photoshop. Open source.\n'
     'Find it at gimp.org.\n\n'
     'INKSCAPE:\n'
     'Free alternative to Illustrator for vector graphics.\n'
     'Excellent for logos and icons. Find it at inkscape.org.\n\n'
     'FUNDAMENTAL DESIGN PRINCIPLES:\n'
     'Contrast: Make important elements stand out.\n'
     'Alignment: Everything should line up with something else.\n'
     'Repetition: Repeat colours, fonts and styles for consistency.\n'
     'Proximity: Group related items together.\n'
     'Hierarchy: Guide the eye from most important to least important.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Create a free account at canva.com.\n'
     'Browse the templates for social media posts.\n'
     'Open any template and explore: Change the text, colours and images.\n'
     'Create one simple graphic for your trade - a quote, tip or announcement.\n'
     'Download it and post to your WhatsApp status.'),

    (2, 'Colour, Typography and Composition', 25,
     'The three elements of design that separate professional from amateur work.\n\n'
     'COLOUR PSYCHOLOGY:\n'
     'Colours communicate emotions and meanings.\n'
     'Red: Energy, urgency, passion. Used for sales, food, emergency services.\n'
     'Blue: Trust, reliability, professionalism. Used for banks, technology, healthcare.\n'
     'Green: Nature, growth, health, money. Used for environment, finance, food.\n'
     'Yellow: Optimism, energy, warmth. Use carefully - hard to read as text.\n'
     'Orange: Creativity, enthusiasm, affordability.\n'
     'Black: Luxury, sophistication, power.\n'
     'White: Cleanliness, simplicity, space.\n\n'
     'BUILDING A COLOUR PALETTE:\n'
     'Choose 2 to 3 colours for your brand and stick to them.\n'
     'Primary colour: Your main brand colour.\n'
     'Secondary colour: Complements the primary.\n'
     'Accent colour: Used sparingly for highlights.\n'
     'Use free tools like Coolors.co to generate harmonious palettes.\n\n'
     'CONTRAST:\n'
     'Light text on dark background, or dark text on light background.\n'
     'Never use yellow text on white or light grey text on white.\n'
     'Always check: Can I read this easily from one metre away?\n\n'
     'TYPOGRAPHY:\n\n'
     'FONT CATEGORIES:\n'
     'Serif fonts: Have small strokes at letter ends. Times New Roman. Traditional, formal, trustworthy.\n'
     'Sans-serif fonts: Clean, no strokes. Arial, Helvetica. Modern, clean, digital-friendly.\n'
     'Display fonts: Decorative. Use only for headlines, never for body text.\n\n'
     'FONT RULES:\n'
     'Use a maximum of two font families in any design.\n'
     'One for headings, one for body text.\n'
     'Sans-serif fonts are more readable on screens.\n'
     'Never use Comic Sans for professional work.\n\n'
     'COMPOSITION:\n\n'
     'THE RULE OF THIRDS:\n'
     'Divide your design into a 3x3 grid.\n'
     'Place the most important element at the intersection of the grid lines.\n'
     'Creates visual interest and balance.\n\n'
     'WHITE SPACE:\n'
     'Empty space is not wasted space.\n'
     'White space gives the eye room to rest and makes content more readable.\n'
     'Crowded designs feel cheap. Spacious designs feel premium.\n\n'
     'PRACTICAL EXERCISE:\n'
     'In Canva, create a business card design.\n'
     'Include: Your name, trade, phone number, location.\n'
     'Use your brand colours and two fonts only.\n'
     'Apply the rule of thirds to place your main text.\n'
     'Leave adequate white space.'),

    (3, 'Creating Business Marketing Materials', 25,
     'Every business needs design materials. Create yours professionally.\n\n'
     'LOGO DESIGN:\n'
     'Your logo is the foundation of your brand identity.\n'
     'A good logo is: Simple, memorable, works in black and white, works at any size.\n\n'
     'Creating a logo in Canva:\n'
     'Search for Logo in Canva templates.\n'
     'Choose a template in your industry.\n'
     'Replace text with your business name.\n'
     'Adjust colours to your brand palette.\n'
     'Download as PNG with transparent background.\n\n'
     'What makes a good logo:\n'
     'Simple: Can be drawn from memory.\n'
     'Appropriate: Looks right for your industry.\n'
     'Distinctive: Different from competitors.\n'
     'Scalable: Looks good small and large.\n\n'
     'BUSINESS CARDS:\n'
     'Standard size: 90mm x 55mm.\n'
     'Essential information only: Name, title, phone, email, social media handle.\n'
     'Front: Name and contact. Back: Services or a key message.\n\n'
     'FLYERS AND POSTERS:\n'
     'Clear hierarchy: Headline, subheading, details, call to action.\n'
     'One main message per flyer. Do not overcrowd.\n'
     'Include: What, when, where, how to contact.\n\n'
     'SOCIAL MEDIA GRAPHICS:\n'
     'Facebook post: 1200 x 630 pixels.\n'
     'Instagram post: 1080 x 1080 pixels square or 1080 x 1350 portrait.\n'
     'Instagram Story: 1080 x 1920 pixels.\n'
     'Canva has templates pre-sized for each platform.\n'
     'Consistency: Use same fonts, colours and style across all platforms.\n\n'
     'PRACTICAL PROJECT:\n'
     'Create a complete identity package for your business using Canva:\n'
     '1. Logo or improved version of existing logo.\n'
     '2. Business card.\n'
     '3. Social media profile header for Facebook.\n'
     '4. One social media post template.\n'
     '5. Simple flyer advertising your main service.\n'
     'This is your brand identity kit.'),

    (4, 'Photo Editing and Image Creation', 20,
     'Your work photos are your most powerful marketing material.\n\n'
     'TAKING GREAT PHOTOS FOR BUSINESS:\n\n'
     'LIGHTING:\n'
     'The most important factor in a good photo.\n'
     'Natural daylight is best. Face a window or photograph outdoors.\n'
     'Avoid harsh direct sunlight - it creates hard shadows.\n'
     'Overcast days produce beautiful soft light.\n\n'
     'COMPOSITION:\n'
     'Remove clutter from the frame before photographing.\n'
     'Get close to the subject - fill the frame.\n'
     'Use the rule of thirds: Place your main subject off-centre.\n'
     'Photograph from different angles.\n\n'
     'BEFORE AND AFTER PHOTOGRAPHY:\n'
     'Take the before photo from the same position as the after photo.\n'
     'Same angle, same distance, same lighting as much as possible.\n'
     'Side by side comparisons are very powerful for marketing.\n\n'
     'BASIC PHOTO EDITING IN CANVA:\n'
     'Upload your photo to Canva.\n'
     'Adjust: Brightness, contrast, saturation, sharpness.\n'
     'Crop: Remove distracting elements around the edges.\n'
     'Filters: Apply subtle filters for consistent look across all photos.\n'
     'Do not over-edit - natural looking photos build more trust.\n\n'
     'FREE STOCK PHOTOS:\n'
     'Sometimes you need photos you do not have.\n'
     'Free stock photo sites: Unsplash.com, Pexels.com, Pixabay.com.\n'
     'Always check the licence - most are free for commercial use.\n\n'
     'PHOTO TOOLS:\n'
     'Canva: Photo editing and graphic creation.\n'
     'Snapseed: Excellent free mobile photo editor by Google.\n'
     'Lightroom Mobile: Professional photo editing on your phone. Free version available.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Take five photos of your work or workspace.\n'
     'Import them to Canva.\n'
     'Adjust brightness and contrast on each.\n'
     'Crop to remove distractions.\n'
     'Create one before-and-after graphic combining two of your photos.\n'
     'Add your business name as a watermark on each photo.'),

    (5, 'Running a Design Freelance Service', 15,
     'Graphic design is a skill with significant income potential.\n\n'
     'THE DESIGN MARKET:\n'
     'Every business needs design but most small business owners cannot do it themselves.\n'
     'Business cards, logos, flyers, social media graphics, signage, menus.\n'
     'The market is enormous and largely untapped at community level.\n\n'
     'SERVICES YOU CAN OFFER:\n\n'
     'ENTRY LEVEL using Canva:\n'
     'Social media graphics: Regular posts for businesses.\n'
     'Flyers and posters: Events, promotions, announcements.\n'
     'Business cards: Design and supply print-ready files.\n'
     'Price range: 5,000 to 30,000 naira per project.\n\n'
     'INTERMEDIATE LEVEL:\n'
     'Logo design: Creating brand identities.\n'
     'Complete brand identity kits: Logo, business card, letterhead, social media.\n'
     'Price range: 30,000 to 150,000 naira.\n\n'
     'BUILDING A PORTFOLIO:\n'
     'Before charging clients, create practice pieces.\n'
     'Design logos and materials for imaginary businesses.\n'
     'Offer free or discounted work to first clients in exchange for testimonials.\n'
     'Display your portfolio on social media.\n\n'
     'FINDING CLIENTS:\n'
     'Small businesses in your community.\n'
     'Restaurants, shops, churches, schools all need design work.\n'
     'Offer to redesign the worst-looking menu or flyer you see.\n'
     'Freelance platforms: Fiverr.com, Upwork.com for international clients.\n\n'
     'PRICING YOUR WORK:\n'
     'Charge for your time and skill, not just materials.\n'
     'Quote per project, not per hour initially.\n'
     'Collect a deposit of 50% before starting work.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Create a sample logo and business card for an imaginary local business.\n'
     'Post it to social media with the caption: Redesign concept for small businesses.\n'
     'Note the response.\n'
     'This is how you attract your first design clients.'),
])

# ============================================================
# FOUNDATIONAL LITERACY COURSES
# ============================================================
add_lessons('Reading and Writing for Beginners', [
    (1, 'Letters, Sounds and the Alphabet', 20,
     'Every word you will ever read or write is built from letters. Learning letters is the first step to literacy.\n\n'
     'THE ALPHABET:\n'
     'The English alphabet has 26 letters.\n'
     'Each letter has a capital form and a small form.\n'
     'Capital: A B C D E F G H I J K L M N O P Q R S T U V W X Y Z\n'
     'Small: a b c d e f g h i j k l m n o p q r s t u v w x y z\n\n'
     'VOWELS AND CONSONANTS:\n'
     'Vowels: A, E, I, O, U. Every word must contain at least one vowel.\n'
     'Consonants: All the other 21 letters.\n'
     'Vowels are the sounds that open your mouth. Consonants shape the sound.\n\n'
     'LETTER SOUNDS:\n'
     'Each letter makes one or more sounds.\n'
     'A says ah as in ant. B says buh as in ball. C says kuh as in cat.\n'
     'D says duh as in dog. E says eh as in egg. F says fuh as in fish.\n'
     'G says guh as in goat. H says huh as in hat. I says ih as in ink.\n'
     'J says juh as in jar. K says kuh as in kite. L says luh as in lamp.\n'
     'M says muh as in man. N says nuh as in nut. O says oh as in ox.\n'
     'P says puh as in pen. Q says kwuh as in queen. R says ruh as in rat.\n'
     'S says suh as in sun. T says tuh as in tap. U says uh as in up.\n'
     'V says vuh as in van. W says wuh as in wet. X says ks as in fox.\n'
     'Y says yuh as in yes. Z says zuh as in zoo.\n\n'
     'WRITING THE LETTERS:\n'
     'Practice writing each letter many times.\n'
     'Start with capital letters - they are simpler shapes.\n'
     'Then practice small letters.\n'
     'Good handwriting comes from practice. Do not rush.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Write the alphabet in capitals from A to Z.\n'
     'Write the alphabet in small letters from a to z.\n'
     'Say the sound of each letter as you write it.\n'
     'Repeat this exercise every day until it is automatic.'),

    (2, 'Building Words from Sounds', 20,
     'When you put letter sounds together, they form words. This is the foundation of reading.\n\n'
     'HOW WORDS ARE BUILT:\n'
     'Every word is a combination of letter sounds spoken in order.\n'
     'Cat: C-A-T. Say each sound: kuh-ah-tuh. Blend them together: cat.\n'
     'Man: M-A-N. Say each sound: muh-ah-nuh. Blend them: man.\n'
     'This skill of blending sounds is called phonics.\n\n'
     'SHORT VOWEL WORDS:\n'
     'Start with simple three-letter words using short vowels.\n\n'
     'Short A words: cat, hat, mat, bat, sat, fat, rat, can, man, ran, van, fan\n'
     'Short E words: bed, red, ten, hen, men, set, net, pet, wet, jet\n'
     'Short I words: big, dig, fig, pig, wig, bit, fit, sit, hit, win\n'
     'Short O words: cot, dot, hot, lot, pot, rot, top, hop, mop, cop\n'
     'Short U words: bun, fun, run, sun, gun, cup, pup, cut, but, hut\n\n'
     'HOW TO SOUND OUT A NEW WORD:\n'
     'Step 1: Look at the first letter. What sound does it make?\n'
     'Step 2: Look at each letter in order. Say its sound.\n'
     'Step 3: Blend all the sounds together quickly.\n'
     'Step 4: Does it sound like a real word you know?\n\n'
     'COMMON SIGHT WORDS:\n'
     'Some words do not follow simple sound rules. Learn them by sight.\n'
     'The, is, are, was, were, has, have, be, am, to, do, go, so\n'
     'And, but, or, not, from, with, this, that, they, them, then, when\n'
     'I, you, he, she, it, we, me, my, your, his, her, our\n\n'
     'PRACTICAL EXERCISE:\n'
     'Practice reading these words aloud: cat, dog, red, big, hot, cup, man, pen, sit, run.\n'
     'For each word: say each letter sound, then blend them.\n'
     'Write each word three times while saying it aloud.\n'
     'Practice until you can read each word immediately without sounding out.'),

    (3, 'Reading Simple Sentences', 20,
     'Words combine to form sentences. Sentences carry meaning.\n\n'
     'WHAT IS A SENTENCE?\n'
     'A sentence is a group of words that expresses a complete thought.\n'
     'Every sentence begins with a capital letter.\n'
     'Every sentence ends with a full stop, question mark or exclamation mark.\n\n'
     'SENTENCE STRUCTURE:\n'
     'A basic sentence has two parts:\n'
     'Subject: Who or what the sentence is about.\n'
     'Predicate: What the subject does or is.\n\n'
     'Examples:\n'
     'The cat sits. (The cat is the subject. sits is the predicate.)\n'
     'The man runs fast. (The man is the subject. runs fast is the predicate.)\n'
     'She has a red bag. (She is the subject. has a red bag is the predicate.)\n\n'
     'READING SIMPLE SENTENCES:\n'
     'Read each word from left to right.\n'
     'If you do not know a word, sound it out letter by letter.\n'
     'After reading, ask: What does this sentence mean?\n'
     'Can you say the same thing in your own words?\n\n'
     'PRACTICE SENTENCES:\n'
     'The dog is big and fat.\n'
     'I can run and hop and skip.\n'
     'The hen has ten red eggs.\n'
     'A man sat on the mat.\n'
     'She can get the bag for him.\n'
     'The sun is hot and the sky is blue.\n'
     'We go to the shop and buy food.\n'
     'He has a pen and he can write.\n\n'
     'PUNCTUATION:\n'
     'Full stop: Ends a statement. I am a carpenter.\n'
     'Question mark: Ends a question. Can you help me?\n'
     'Exclamation mark: Shows strong feeling. That is excellent!\n'
     'Comma: A short pause inside a sentence. I need wood, nails and glue.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Read the practice sentences above aloud.\n'
     'Point to each word as you say it.\n'
     'After reading each sentence, say what it means in your own words.\n'
     'Copy each sentence in your notebook.'),

    (4, 'Writing Words and Sentences', 20,
     'Reading is receiving words. Writing is creating them. Both skills strengthen each other.\n\n'
     'HOW TO HOLD A PEN OR PENCIL:\n'
     'Hold the pen between your thumb and first finger.\n'
     'Rest it on your middle finger.\n'
     'Hold near the writing end but not too close.\n'
     'Keep a relaxed grip - tension causes cramping and poor writing.\n\n'
     'LETTER FORMATION:\n'
     'Write each letter in the same way every time.\n'
     'Start capital letters from the top.\n'
     'Some small letters start at the middle line: a, c, e, m, n, o, r, s, u, v, w, x, z.\n'
     'Some small letters start at the top line: b, d, f, h, i, j, k, l, p, q, t, y.\n\n'
     'WRITING WORDS:\n'
     'Say the word aloud.\n'
     'Think about what sounds you hear.\n'
     'Write the letter for each sound in order.\n'
     'Check: Does it look right? Does it say what you wanted?\n\n'
     'COMMON SPELLING PATTERNS:\n'
     'Words ending in tion: nation, action, station, mention.\n'
     'Words ending in ing: running, jumping, working, writing.\n'
     'Words ending in ed: worked, jumped, painted, repaired.\n'
     'Words ending in er: worker, painter, carpenter, builder.\n\n'
     'WRITING SENTENCES:\n'
     'Think of what you want to say.\n'
     'Start with a capital letter.\n'
     'Write each word with spaces between.\n'
     'End with a full stop.\n'
     'Read what you wrote. Does it make sense?\n\n'
     'COMMON MISTAKES TO AVOID:\n'
     'No capital at the start of a sentence.\n'
     'No full stop at the end.\n'
     'Words joined together without spaces.\n'
     'Letters written backwards such as b and d, p and q.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Write five sentences about yourself.\n'
     'Include: Your name, where you live, your work, your family, one thing you enjoy.\n'
     'Check each sentence starts with a capital and ends with a full stop.\n'
     'Read them aloud to check they make sense.'),

    (5, 'Reading in Everyday Life', 20,
     'Literacy is not just a school skill. It is a life skill that opens every door.\n\n'
     'WHERE READING IS NEEDED EVERY DAY:\n'
     'Signs: Road signs, shop signs, warning signs.\n'
     'Forms: Government forms, job applications, bank forms.\n'
     'Labels: Medicine labels, food labels, product instructions.\n'
     'Messages: WhatsApp, SMS, email.\n'
     'Receipts and bills: To know what you are paying for.\n'
     'Contracts: Before you sign anything.\n\n'
     'READING MEDICINE LABELS:\n'
     'The most critical reading skill.\n'
     'Always read: The name of the medicine, the dose, how often to take it, warnings.\n'
     'Never take medicine without reading the label.\n'
     'If you cannot read it, ask someone you trust to read it for you.\n\n'
     'READING FORMS:\n'
     'Read the entire form before filling anything in.\n'
     'Look for words: Name, Date of birth, Address, Signature.\n'
     'Print letters clearly. Use capital letters unless told otherwise.\n'
     'Date format: Many forms use DD/MM/YYYY. For example 15/06/1985.\n\n'
     'READING RECEIPTS AND BILLS:\n'
     'Check the items listed are what you purchased.\n'
     'Check the amounts add up correctly.\n'
     'Look for the total amount due.\n'
     'Look for the payment due date.\n\n'
     'CONTINUING TO IMPROVE:\n'
     'Read every day. Even five minutes makes a difference.\n'
     'Start with simple materials: Short articles, signs, WhatsApp messages.\n'
     'Use a dictionary or ask someone when you find an unknown word.\n'
     'Write a little every day: A diary, messages to friends, notes to yourself.\n'
     'The more you read and write, the better you get.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Find three items with writing on them in your home or community.\n'
     'Read each one carefully.\n'
     'Write down: What is this? What does it tell you? What do you do with this information?\n'
     'This is reading for real life.'),
])

add_lessons('Basic Numeracy and Mathematics', [
    (1, 'Numbers and Counting', 20,
     'Numbers are the language of business, science and everyday life. Understanding them is essential.\n\n'
     'WHOLE NUMBERS:\n'
     'The counting numbers are: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10...\n'
     'Zero: 0. The number that represents nothing.\n'
     'The digits 0 to 9 combine to make all numbers.\n\n'
     'PLACE VALUE:\n'
     'The position of a digit tells you its value.\n'
     'In the number 347:\n'
     '7 is in the units place: it means 7.\n'
     '4 is in the tens place: it means 40.\n'
     '3 is in the hundreds place: it means 300.\n'
     'So 347 means 300 plus 40 plus 7.\n\n'
     'LARGE NUMBERS:\n'
     'Thousands: 1,000 to 9,999. One thousand to nine thousand nine hundred and ninety-nine.\n'
     'Ten thousands: 10,000 to 99,999.\n'
     'Hundreds of thousands: 100,000 to 999,999.\n'
     'Millions: 1,000,000 and above.\n'
     'Commas separate groups of three digits making large numbers easier to read.\n\n'
     'READING NUMBERS:\n'
     '25: Twenty-five.\n'
     '130: One hundred and thirty.\n'
     '4,500: Four thousand five hundred.\n'
     '50,000: Fifty thousand.\n'
     '1,000,000: One million.\n\n'
     'ODD AND EVEN NUMBERS:\n'
     'Even numbers end in 0, 2, 4, 6 or 8. They can be divided by 2 exactly.\n'
     'Odd numbers end in 1, 3, 5, 7 or 9. They cannot be divided by 2 exactly.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Write the numbers 1 to 20 in your notebook.\n'
     'Write the number name for each: 1 = one, 2 = two and so on.\n'
     'Circle all the even numbers.\n'
     'Write down the price of five items in your home or local shop.\n'
     'Read each price aloud.'),

    (2, 'Addition and Subtraction', 25,
     'Addition and subtraction are the two most essential calculations in daily life.\n\n'
     'ADDITION:\n'
     'Addition means combining numbers to find the total.\n'
     'The plus sign + means add.\n'
     'The equals sign = means the result.\n'
     '3 + 4 = 7. Three plus four equals seven.\n\n'
     'ADDITION METHODS:\n\n'
     'COUNTING ON:\n'
     'Start with the larger number. Count on using the smaller number.\n'
     '8 + 3: Start at 8. Count on 3: nine, ten, eleven. Answer: 11.\n\n'
     'COLUMN ADDITION:\n'
     'Write numbers in columns - units under units, tens under tens.\n'
     'Add from right to left.\n'
     'If the sum of a column is 10 or more, carry the tens digit to the next column.\n'
     'Example: 47 plus 35.\n'
     '7 plus 5 equals 12. Write 2, carry 1.\n'
     '4 plus 3 plus 1 carried equals 8.\n'
     'Answer: 82.\n\n'
     'SUBTRACTION:\n'
     'Subtraction means taking one number away from another.\n'
     'The minus sign means subtract.\n'
     '9 minus 4 = 5. Nine minus four equals five.\n\n'
     'SUBTRACTION METHOD:\n'
     'Write the larger number on top. Subtract the smaller number.\n'
     'Work from right to left.\n'
     'If the top digit is smaller than the bottom digit, borrow 10 from the next column.\n\n'
     'REAL LIFE APPLICATIONS:\n'
     'You have 5,000 naira. You spend 2,350. How much is left?\n'
     '5,000 minus 2,350 equals 2,650 naira remaining.\n\n'
     'A customer pays 10,000 for a job that costs 7,500. What change do you give?\n'
     '10,000 minus 7,500 equals 2,500 naira change.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Solve these calculations:\n'
     '25 plus 43. 67 plus 28. 100 minus 37. 500 minus 175. 1,000 minus 456.\n'
     'A plumber buys materials: pipes cost 3,500, fittings cost 1,200 and tape costs 300.\n'
     'What is the total material cost?\n'
     'If the customer pays 8,000, what is the profit?'),

    (3, 'Multiplication and Division', 25,
     'Multiplication is fast addition. Division is sharing equally.\n\n'
     'MULTIPLICATION:\n'
     'Multiplication means adding a number to itself a certain number of times.\n'
     '4 times 3 means 4 added 3 times: 4 plus 4 plus 4 equals 12.\n'
     'The times sign means multiply.\n'
     '4 times 3 equals 12.\n\n'
     'THE MULTIPLICATION TABLE:\n'
     'Learning your times tables makes calculation fast.\n'
     '2 times: 2, 4, 6, 8, 10, 12, 14, 16, 18, 20\n'
     '3 times: 3, 6, 9, 12, 15, 18, 21, 24, 27, 30\n'
     '4 times: 4, 8, 12, 16, 20, 24, 28, 32, 36, 40\n'
     '5 times: 5, 10, 15, 20, 25, 30, 35, 40, 45, 50\n'
     '10 times: 10, 20, 30, 40, 50, 60, 70, 80, 90, 100\n\n'
     'MULTIPLYING LARGER NUMBERS:\n'
     'Price of one tile: 500 naira. Number of tiles needed: 80.\n'
     'Total cost: 500 times 80 equals 40,000 naira.\n\n'
     'DIVISION:\n'
     'Division means sharing a number equally into groups.\n'
     '12 divided by 3 means: Share 12 into 3 equal groups. Each group has 4.\n'
     '12 divided by 3 equals 4.\n\n'
     'DIVISION APPLICATIONS:\n'
     'You earn 45,000 in a month working 15 days. How much per day?\n'
     '45,000 divided by 15 equals 3,000 per day.\n\n'
     'You need 120 blocks for a wall. Each row takes 20 blocks. How many rows?\n'
     '120 divided by 20 equals 6 rows.\n\n'
     'REMAINDERS:\n'
     'Sometimes division does not come out exactly.\n'
     '13 divided by 4 equals 3 remainder 1.\n'
     '3 groups of 4 make 12. The remaining 1 is the remainder.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Solve these problems:\n'
     '6 times 7. 9 times 8. 50 times 12. 100 divided by 4. 360 divided by 6.\n'
     'You are paid 1,200 naira per hour. You work 8 hours. How much do you earn?\n'
     'You earn 54,000 in 6 days. How much per day?'),

    (4, 'Fractions, Percentages and Decimals', 20,
     'Fractions, percentages and decimals are three ways of expressing parts of a whole.\n\n'
     'FRACTIONS:\n'
     'A fraction represents a part of a whole.\n'
     'One half: 1/2. One quarter: 1/4. Three quarters: 3/4.\n'
     'The bottom number is the denominator: how many equal parts the whole is divided into.\n'
     'The top number is the numerator: how many of those parts you have.\n\n'
     'FRACTIONS IN REAL LIFE:\n'
     'You complete half a job today. You have completed 1/2.\n'
     'A recipe needs three quarters of a cup. You need 3/4 cup.\n'
     'A tank is one third full. It contains 1/3 of its capacity.\n\n'
     'DECIMALS:\n'
     'Decimals use a point to separate whole numbers from parts.\n'
     '0.5 is the same as one half.\n'
     '0.25 is the same as one quarter.\n'
     '0.75 is the same as three quarters.\n'
     '2.5 means two and a half.\n\n'
     'PERCENTAGES:\n'
     'A percentage is a fraction out of 100.\n'
     'Percent means out of 100.\n'
     '50% means 50 out of 100, which is one half.\n'
     '25% means 25 out of 100, which is one quarter.\n'
     '10% means 10 out of 100, which is one tenth.\n\n'
     'CALCULATING PERCENTAGES:\n'
     'To find 10% of a number: Divide by 10.\n'
     '10% of 50,000 equals 5,000.\n\n'
     'To find 20%: Find 10% and multiply by 2.\n'
     '20% of 50,000: 10% is 5,000, times 2 equals 10,000.\n\n'
     'VAT and tax: If price is 10,000 and VAT is 7.5%:\n'
     '7.5% of 10,000: 10% is 1,000. Half of that is 500. So 7.5% is 750.\n'
     'Total with VAT: 10,000 plus 750 equals 10,750.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Calculate: 25% of 80,000. 10% of 15,000. 50% of 6,400.\n'
     'A material costs 40,000. There is a 15% discount. What is the discount amount?\n'
     'What is the final price after discount?'),

    (5, 'Measurement and Everyday Maths', 20,
     'Measurement skills are essential for every trade and for daily life.\n\n'
     'LENGTH:\n'
     'Millimetres: Very small measurements. 10mm equals 1cm.\n'
     'Centimetres: cm. 100cm equals 1 metre.\n'
     'Metres: m. The main unit for most construction measurements.\n'
     'Kilometres: km. 1000 metres. Used for distances.\n\n'
     'MEASURING LENGTH:\n'
     'Use a tape measure for lengths over 30cm.\n'
     'Use a ruler for shorter precise measurements.\n'
     'Always measure twice before cutting.\n\n'
     'AREA:\n'
     'Area measures the size of a flat surface.\n'
     'Area equals length times width.\n'
     'A room 4 metres long and 3 metres wide has an area of 12 square metres.\n'
     'Square metres written as m squared.\n\n'
     'VOLUME:\n'
     'Volume measures how much space a 3D object fills.\n'
     'Volume equals length times width times height.\n'
     'A water tank 2m long, 1m wide and 1m high holds 2 cubic metres of water.\n'
     '1 cubic metre equals 1000 litres.\n\n'
     'WEIGHT:\n'
     'Grams: g. Small amounts.\n'
     'Kilograms: kg. 1000g equals 1kg. Main unit for materials.\n'
     'Tonnes: t. 1000kg. Used for large quantities of materials.\n\n'
     'TIME:\n'
     '60 seconds equals 1 minute. 60 minutes equals 1 hour. 24 hours equals 1 day.\n'
     '7 days equals 1 week. 4 weeks approximately equals 1 month. 12 months equals 1 year.\n\n'
     'TEMPERATURE:\n'
     'Celsius: The temperature scale used in most of the world.\n'
     'Water freezes at 0 degrees Celsius. Water boils at 100 degrees Celsius.\n'
     'Body temperature is about 37 degrees Celsius.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Measure the length and width of a room you are in.\n'
     'Calculate its area in square metres.\n'
     'If floor tiles are 0.5m by 0.5m, how many tiles do you need for this room?\n'
     'If tiles cost 800 naira each, what is the total tile cost for this room?'),
])

add_lessons('Life Skills Literacy', [
    (1, 'Functional Reading for Adults', 20,
     'Functional literacy means being able to read and use the written information you encounter every day.\n\n'
     'WHAT IS FUNCTIONAL LITERACY?\n'
     'Functional literacy is the ability to read and understand the texts you need for daily life.\n'
     'It is different from academic literacy.\n'
     'You do not need to read novels. You need to read forms, signs, labels and messages.\n\n'
     'READING FOR INFORMATION:\n'
     'Purpose: What is this text for? What does it want me to know or do?\n'
     'Key information: What are the most important facts? Numbers, names, dates, amounts.\n'
     'Action required: Do I need to do something after reading this?\n\n'
     'TYPES OF TEXTS YOU ENCOUNTER:\n\n'
     'OFFICIAL FORMS:\n'
     'Bank account opening forms.\n'
     'Government registration forms.\n'
     'Loan application forms.\n'
     'Job application forms.\n\n'
     'LEGAL DOCUMENTS:\n'
     'Contracts and agreements.\n'
     'Receipts and invoices.\n'
     'Property documents.\n'
     'Never sign anything you have not read and understood.\n'
     'If you cannot read it fully, ask someone you trust to read it with you.\n\n'
     'PRODUCT LABELS AND INSTRUCTIONS:\n'
     'Medicine labels: Dose, frequency, warnings, expiry date.\n'
     'Food labels: Ingredients, nutritional information, expiry date.\n'
     'Chemical labels: Handling instructions, safety warnings.\n\n'
     'DIGITAL TEXTS:\n'
     'WhatsApp messages and announcements.\n'
     'Emails from banks, government, employers.\n'
     'Social media information.\n'
     'Website information.\n\n'
     'IDENTIFYING TRUSTWORTHY INFORMATION:\n'
     'Who wrote this? Is it a known, reliable source?\n'
     'Is it recent? Old information may no longer be correct.\n'
     'Does it match what you know from other sources?\n'
     'Be suspicious of information that sounds too good to be true.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Find three different types of written text in your community this week.\n'
     'For each one write: What type of text is it? What is its purpose?\n'
     'What is the key information? Is there any action required?\n'
     'This exercise practises reading for real purposes.'),

    (2, 'Health Literacy', 20,
     'Understanding health information allows you to take better care of yourself and your family.\n\n'
     'WHY HEALTH LITERACY MATTERS:\n'
     'Good health literacy leads to better health decisions.\n'
     'People with strong health literacy are more likely to follow medical advice.\n'
     'They understand their conditions better and use medicines correctly.\n'
     'They know when to seek medical help and when to manage at home.\n\n'
     'READING MEDICINE LABELS:\n'
     'Active ingredient: The medicine that treats the condition.\n'
     'Dose: How much to take.\n'
     'Frequency: How often to take it. Three times daily means every 8 hours.\n'
     'Duration: For how many days to take it. Complete the full course even if feeling better.\n'
     'Warnings: Who should not take it. Interactions with other medicines. Side effects.\n'
     'Expiry date: Never take medicine after this date.\n'
     'Storage instructions: Keep in a cool dry place means away from heat and moisture.\n\n'
     'UNDERSTANDING HEALTH INFORMATION:\n'
     'Symptoms: Signs that something is wrong with your body.\n'
     'Diagnosis: What condition you have.\n'
     'Treatment: What is done to address the condition.\n'
     'Prevention: What you can do to avoid the condition.\n\n'
     'WHEN TO SEEK MEDICAL HELP:\n'
     'High fever that does not come down with medicine.\n'
     'Chest pain or difficulty breathing.\n'
     'Severe headache that comes on suddenly.\n'
     'Any condition that does not improve after 3 days.\n'
     'Any condition that worries you.\n\n'
     'PREVENTIVE HEALTH:\n'
     'Vaccination: Protects against diseases like measles, polio, COVID-19.\n'
     'Hand washing: The single most effective way to prevent disease spread.\n'
     'Clean water: Prevents cholera, typhoid and diarrhoeal diseases.\n'
     'Mosquito nets and repellent: Prevent malaria.\n'
     'Regular health check-ups: Detect problems early.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Find a medicine in your home.\n'
     'Read the label completely and answer:\n'
     'What is it for? What is the dose for an adult? How often is it taken?\n'
     'What are the warnings? When does it expire?\n'
     'If you cannot answer all these questions, the label needs to be read more carefully.'),

    (3, 'Financial Literacy', 20,
     'Financial literacy is understanding money well enough to make good decisions with it.\n\n'
     'UNDERSTANDING YOUR MONEY:\n'
     'Income: Money coming in - wages, business income, gifts.\n'
     'Expenses: Money going out - food, rent, transport, bills, materials.\n'
     'Savings: Money kept for the future or for emergencies.\n'
     'Debt: Money owed to others that must be repaid.\n\n'
     'INCOME MINUS EXPENSES:\n'
     'If your income is greater than your expenses: You have a surplus. Save it.\n'
     'If your expenses equal your income: You are just surviving. Find ways to reduce costs or increase income.\n'
     'If your expenses are greater than income: You have a deficit. This is a crisis. Must be addressed immediately.\n\n'
     'BANKING:\n'
     'A bank account keeps your money safe.\n'
     'A deposit puts money into the account.\n'
     'A withdrawal takes money out.\n'
     'Balance: How much money is currently in the account.\n'
     'Statement: A record of all transactions.\n'
     'PIN: Personal Identification Number. Keep it secret. Never write it on your card.\n\n'
     'MOBILE MONEY:\n'
     'MTN MoMo, Airtel Money and other mobile money services allow transactions on your phone.\n'
     'Keep your PIN secret.\n'
     'Verify who you are sending money to before confirming.\n'
     'Check the amount before confirming.\n\n'
     'LOANS AND BORROWING:\n'
     'A loan is borrowed money that must be repaid with interest.\n'
     'Interest: Extra money paid for the use of borrowed money.\n'
     'Only borrow for productive purposes: To buy equipment, stock or invest in growth.\n'
     'Never borrow to cover everyday expenses.\n'
     'Before borrowing, calculate: Can I repay this from the income it will generate?\n\n'
     'AVOIDING FINANCIAL SCAMS:\n'
     'If it sounds too good to be true, it is a scam.\n'
     'Double your money schemes are always scams.\n'
     'Never send money to receive money.\n'
     'Never give your PIN, password or OTP to anyone.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Write down your income and expenses for the last month.\n'
     'Calculate: Total income, total expenses, difference.\n'
     'Identify one expense you could reduce.\n'
     'Identify one way you could increase your income.'),

    (4, 'Civic Literacy', 20,
     'Civic literacy means understanding your rights, responsibilities and how your community and country work.\n\n'
     'YOUR RIGHTS AS A CITIZEN:\n'
     'The right to vote in elections.\n'
     'The right to freedom of expression - to speak your mind peacefully.\n'
     'The right to freedom of movement - to travel within your country.\n'
     'The right to education.\n'
     'The right to fair treatment under the law.\n'
     'The right to own property.\n\n'
     'YOUR RESPONSIBILITIES AS A CITIZEN:\n'
     'Pay your taxes.\n'
     'Obey the law.\n'
     'Respect the rights of others.\n'
     'Participate in community life.\n'
     'Vote in elections.\n'
     'Care for the environment.\n\n'
     'HOW GOVERNMENT WORKS:\n'
     'Local government: The council or authority responsible for your town or local area.\n'
     'Provides: Roads, water, sanitation, local markets, primary schools.\n'
     'State or regional government: Responsible for larger area.\n'
     'Provides: Secondary education, state hospitals, roads.\n'
     'National government: Responsible for the whole country.\n'
     'Provides: National security, federal roads, currency, national policies.\n\n'
     'IMPORTANT DOCUMENTS:\n'
     'National Identity Card: Proves who you are.\n'
     'Birth Certificate: Proves when and where you were born.\n'
     'Voter Card: Allows you to vote in elections.\n'
     'Passport: Allows international travel.\n'
     'Driver Licence: Authorises you to drive.\n'
     'Business Registration Certificate: Authorises you to operate a business.\n'
     'Keep all documents in a safe place. Replace lost documents promptly.\n\n'
     'YOUR LEGAL RIGHTS IN BUSINESS:\n'
     'You have the right to be paid for your work.\n'
     'You have the right to a written agreement before starting work.\n'
     'You have the right to refuse unsafe working conditions.\n'
     'Customers have rights too - to receive what was agreed for the price agreed.\n\n'
     'PRACTICAL EXERCISE:\n'
     'List the important documents you currently have.\n'
     'Identify which important documents you are missing.\n'
     'Find out what you need to do to obtain any missing documents.\n'
     'Store all your documents together in a safe, waterproof container.'),

    (5, 'Digital Literacy for Daily Life', 20,
     'Digital literacy means being able to use digital technology effectively and safely.\n\n'
     'WHY DIGITAL LITERACY MATTERS:\n'
     'The world is increasingly digital. Government services, banking, communication and commerce happen online.\n'
     'People without digital skills are excluded from growing opportunities.\n'
     'Digital skills are now as fundamental as reading and writing.\n\n'
     'USING A SMARTPHONE:\n'
     'A smartphone is a computer in your pocket.\n'
     'Basic skills: Making calls, sending messages, using the internet, taking photos.\n'
     'Installing apps: Google Play Store for Android, App Store for iPhone.\n'
     'Managing storage: Delete unused apps and photos to free space.\n'
     'Charging: Charge before it reaches 10%. Avoid letting it fully drain.\n\n'
     'WHATSAPP FOR COMMUNICATION AND BUSINESS:\n'
     'Text messages, voice calls, video calls - all free over the internet.\n'
     'Share photos, documents and locations.\n'
     'WhatsApp Business: Additional features for businesses including a product catalogue.\n'
     'Groups: Communicate with multiple people at once.\n'
     'Status: Share updates visible to all your contacts for 24 hours.\n\n'
     'ONLINE SAFETY:\n'
     'Strong passwords: At least 8 characters including numbers and symbols.\n'
     'Never share your PIN, password or OTP with anyone.\n'
     'Be careful what you share publicly on social media.\n'
     'Scam messages often claim you have won something or that there is an emergency.\n'
     'Verify before acting: Call the person or organisation directly to confirm.\n\n'
     'USING THE INTERNET FOR INFORMATION:\n'
     'Google Search: Type your question and press search.\n'
     'YouTube: Search for videos on any topic. Excellent for learning.\n'
     'Government websites: Check .gov for official information.\n'
     'Evaluate sources: Is this a trustworthy website?\n\n'
     'MOBILE BANKING AND PAYMENTS:\n'
     'Most banks have mobile apps. Manage your account from your phone.\n'
     'Mobile money: Send and receive money without a bank account.\n'
     'Always verify the recipient before sending money.\n'
     'Keep your transaction history and check it regularly.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Using your smartphone, find the answer to these questions using Google:\n'
     'What is the current price of petrol in your country?\n'
     'What is the phone number of your nearest hospital?\n'
     'What are the opening hours of your local government office?\n'
     'Note: How easy or difficult was it to find each answer?'),
])

# FINAL SUMMARY
print('\n' + '='*50)
print('FINAL COURSE STATUS:')
total = 0
for c in Course.objects.all().order_by('title'):
    count = c.lessons.count()
    total += count
    status = 'OK' if count >= 5 else 'NEEDS LESSONS' if count == 0 else f'PARTIAL ({count})'
    print(f'  {status}: {c.title} - {count} lessons')
print(f'\nTOTAL LESSONS: {total}')