import os, django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'skillscontinua_core.settings')
django.setup()

from courses.models import Course, Lesson

def add_lessons(title, lessons_data):
    try:
        course = Course.objects.get(title=title)
        Lesson.objects.filter(course=course).delete()
        for order, lesson_title, duration, content in lessons_data:
            Lesson.objects.create(
                course=course, title=lesson_title, content_type='text',
                content_text=content, order=order,
                duration_minutes=duration, is_active=True
            )
        print(f'OK: {title} — {course.lessons.count()} lessons')
    except Course.DoesNotExist:
        print(f'NOT FOUND: {title}')

# ============================================================
# TRADING AND PETTY BUSINESS MANAGEMENT
# ============================================================
add_lessons('Trading and Petty Business Management', [
    (1, 'Why Most Traders Lose Money Without Knowing It', 25,
     'This lesson reveals the hidden truth behind why hardworking traders struggle despite being busy every day.\n\n'
     'THE DANGEROUS MISTAKE:\n'
     'Imagine Fatima buys a bag of onions for Le 50,000. She sells them for Le 65,000.\n'
     'She thinks her profit is Le 15,000. Is she right?\n\n'
     'Let us count what she actually spent:\n'
     'Cost of onions: Le 50,000\n'
     'Transport to market: Le 3,000\n'
     'Market fee (daily): Le 1,500\n'
     'Carrier (porterage): Le 1,000\n'
     'Mobile money fee (receiving payment): Le 500\n'
     'Spoiled onions (5%): Le 2,500\n'
     'TOTAL REAL COST: Le 58,500\n\n'
     'Her REAL profit: Le 65,000 minus Le 58,500 = Le 6,500\n'
     'NOT Le 15,000. She was wrong by more than half.\n\n'
     'If she uses that Le 65,000 to buy more onions thinking she has Le 15,000 profit to spend,\n'
     'she is actually spending money she needs to cover her costs next time.\n'
     'Over time, her business gets smaller without her knowing why.\n\n'
     'THIS IS THE MOST COMMON REASON TRADERS FAIL.\n\n'
     'THE TRUE COST OF GOODS FORMULA:\n'
     'True Cost = Purchase Price\n'
     '          + Transport and freight\n'
     '          + Market and toll fees\n'
     '          + Handling and porterage\n'
     '          + Storage costs\n'
     '          + Expected spoilage or losses\n'
     '          + Mobile money and transaction fees\n'
     '          + Interest on borrowed money (if you used a loan)\n'
     '          + Your own time cost (your labour has value)\n\n'
     'PRACTICAL EXERCISE:\n'
     'Think about the last item you bought and sold.\n'
     'Write down EVERY cost involved — not just what you paid for the goods.\n'
     'Add them all up. That is your true cost.\n'
     'Now calculate your real profit.\n'
     'Were you surprised? Most traders are.\n'
     'This exercise could change how you run your business permanently.'),

    (2, 'Calculating True Cost and Setting the Right Price', 30,
     'Once you know your true cost, you can price correctly and guarantee a profit every single time.\n\n'
     'THE PRICING FORMULA:\n'
     'Selling Price = True Cost + Your Desired Profit\n\n'
     'THE PROFIT MARGIN:\n'
     'Profit margin is profit expressed as a percentage of the selling price.\n'
     'Profit margin = (Profit divided by Selling Price) times 100\n\n'
     'OR use the markup on cost:\n'
     'Markup = (Profit divided by True Cost) times 100\n\n'
     'EXAMPLE — AMARA THE RICE TRADER:\n'
     'Amara buys a 50kg bag of rice for Le 180,000.\n'
     'Transport: Le 8,000\n'
     'Market fee: Le 2,000 per day, 2 days to sell = Le 4,000\n'
     'Porterage: Le 2,000\n'
     'Losses (2% spoilage): Le 3,600\n'
     'Transaction fees: Le 1,000\n'
     'TRUE COST: Le 198,600\n\n'
     'If Amara sells at Le 220,000 she thinks profit = Le 40,000.\n'
     'Real profit = Le 220,000 minus Le 198,600 = Le 21,400.\n\n'
     'To make a 20% profit on cost:\n'
     'Selling price = Le 198,600 times 1.20 = Le 238,320\n'
     'He should sell for Le 238,000 (rounded) to make a real 20% profit.\n\n'
     'BUT WHAT IF CUSTOMERS WON\'T PAY THAT PRICE?\n'
     'Then you must either:\n'
     '1. Reduce your costs (buy more cheaply, reduce transport, reduce losses)\n'
     '2. Sell a different product with better margins\n'
     '3. Add value to the product so you can charge more\n\n'
     'Never reduce your price below true cost. You are working for nothing or going backwards.\n\n'
     'PRACTICAL EXERCISE:\n'
     'For your main product:\n'
     'Step 1: Calculate your true cost using every cost from Lesson 1.\n'
     'Step 2: Decide what profit percentage you need (minimum 20%).\n'
     'Step 3: Calculate your selling price.\n'
     'Step 4: Compare to what you are currently charging.\n'
     'Step 5: If you are undercharging, make a plan to increase your price gradually.'),

    (3, 'Profit and Loss — Knowing If Your Business Is Healthy', 25,
     'Every trader must be able to answer one simple question: Is my business actually making money?\n\n'
     'THE PROFIT AND LOSS STATEMENT:\n'
     'A profit and loss statement (P&L) shows all your income and all your costs for a period of time.\n'
     'What is left after costs is your profit.\n'
     'If costs are more than income, you are making a loss.\n\n'
     'SIMPLE P&L FOR TRADERS:\n\n'
     'SALES (what you received from customers)\n'
     'Minus COST OF GOODS SOLD (what you paid for the goods you sold)\n'
     'Minus TRADING EXPENSES (transport, fees, losses, transaction costs)\n'
     '= GROSS PROFIT\n\n'
     'Minus OVERHEAD EXPENSES (regular fixed costs: rent for stall, phone credit, staff wages)\n'
     '= NET PROFIT\n\n'
     'NET PROFIT is what you actually made.\n\n'
     'EXAMPLE — MARY\'S USED CLOTHING BUSINESS:\n'
     'This month:\n'
     'Sales: Le 1,200,000\n'
     'Cost of goods (bale of clothes): Le 600,000\n'
     'Transport from warehouse: Le 40,000\n'
     'Market fees (20 days): Le 30,000\n'
     'Losses (unsold items discounted): Le 50,000\n'
     'GROSS PROFIT: Le 480,000\n\n'
     'Stall rent: Le 60,000\n'
     'Phone credit for business: Le 10,000\n'
     'Assistant wages: Le 80,000\n'
     'NET PROFIT: Le 330,000\n\n'
     'Mary earned Le 330,000 this month.\n'
     'But she was working full days. Is Le 330,000 enough for her time and effort?\n'
     'Only she can decide. But now she KNOWS what she made.\n\n'
     'THE CRITICAL DISTINCTION:\n'
     'NET PROFIT is NOT the money you can spend on personal things.\n'
     'You must keep some in the business for next month\'s stock.\n'
     'You should save some for emergencies.\n'
     'Only then should you take the rest for personal use.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Write your P&L for last month.\n'
     'If you do not have the numbers, estimate as best you can.\n'
     'This is the most important financial exercise you will do.\n'
     'Compare it to what you thought you made.\n'
     'The gap between those two numbers is what this course is about.'),

    (4, 'Cash Flow — The Difference Between Having Money and Making Money', 25,
     'Many traders have money today but cannot buy stock tomorrow. This is a cash flow problem.\n\n'
     'CASH FLOW vs PROFIT:\n'
     'Profit is what you MADE over a period.\n'
     'Cash flow is what MONEY you have available RIGHT NOW.\n\n'
     'You can be profitable but have no cash. How?\n'
     'If you bought on credit and must pay back before you sell your stock.\n'
     'If you gave goods on credit and customers have not paid you.\n'
     'If you spent cash on stock before the last batch sold.\n\n'
     'COMMON CASH FLOW TRAPS FOR TRADERS:\n\n'
     'THE CREDIT TRAP:\n'
     'You give goods to customers on credit.\n'
     'They delay payment.\n'
     'You need to buy new stock but have no cash.\n'
     'SOLUTION: Avoid giving credit unless you can afford to wait. Always charge more for credit sales to compensate for the delay and risk.\n\n'
     'THE BIG ORDER TRAP:\n'
     'Someone gives you a large order. You buy lots of stock.\n'
     'They cancel or delay payment.\n'
     'You are stuck with stock and no cash.\n'
     'SOLUTION: Always get a deposit for large orders. Minimum 50%.\n\n'
     'THE SEASONAL TRAP:\n'
     'You make good money in busy season. You spend it.\n'
     'Slow season comes. No money to buy stock or pay expenses.\n'
     'SOLUTION: Save 20-30% of profits in busy season specifically for slow periods.\n\n'
     'THE MIXING TRAP:\n'
     'You mix business money and personal money.\n'
     'You spend business cash on personal needs.\n'
     'You do not realise until the business has no cash to operate.\n'
     'SOLUTION: Keep business money completely separate from personal money.\n\n'
     'THE CASH FLOW RULE:\n'
     'Always know how much cash your business has.\n'
     'Always know how much is owed to you (receivables).\n'
     'Always know how much you owe (payables and debts).\n'
     'Cash available = Cash in hand + Cash in account\n\n'
     'PRACTICAL EXERCISE:\n'
     'Right now, answer these questions:\n'
     'How much cash does your business have today?\n'
     'How much do customers owe you?\n'
     'How much do you owe to suppliers?\n'
     'What expenses must you pay in the next 7 days?\n'
     'After paying those expenses, how much cash will you have left to buy stock?\n'
     'This is your cash position. Every trader should know this every day.'),

    (5, 'Growing Your Trading Business — From Surviving to Thriving', 20,
     'Once your trading business is profitable and stable, you can begin to grow it deliberately.\n\n'
     'THE GROWTH STAGES:\n\n'
     'STAGE 1 — SURVIVING (most traders are here):\n'
     'Making just enough to survive day to day.\n'
     'No savings. No plan. Reactive rather than proactive.\n'
     'The fix: Calculate your true costs, price correctly, separate business and personal money.\n\n'
     'STAGE 2 — STABLE:\n'
     'Consistent profit every month.\n'
     'Small cash reserve for emergencies.\n'
     'Clear records of what is coming in and going out.\n'
     'The fix: Apply lessons 1-4 consistently for 3 months.\n\n'
     'STAGE 3 — GROWING:\n'
     'Saving a portion of profit to reinvest in more stock or better stock.\n'
     'Building supplier relationships that give better prices or credit terms.\n'
     'Expanding your product range or customer base.\n'
     'Building a reputation that brings customers back.\n\n'
     'STAGE 4 — THRIVING:\n'
     'Running a business that generates consistent income.\n'
     'Employing at least one other person.\n'
     'Planning for the future with real financial targets.\n\n'
     'HOW TO MOVE FROM STAGE 1 TO STAGE 3:\n\n'
     'Calculate your true costs from today.\n'
     'Set your prices correctly with a minimum 20% profit on true cost.\n'
     'Separate business and personal money from today.\n'
     'Keep a simple daily record (covered in the Bookkeeping course).\n'
     'Save 20% of all profit for the business.\n'
     'After 3 months, review: Are you making real profit? Is cash flow positive?\n'
     'Only then increase your investment in stock.\n\n'
     'WHAT TO DO WITH PROFIT:\n'
     '50% — reinvest in the business (more/better stock, equipment, marketing).\n'
     '20% — emergency savings for the business.\n'
     '30% — personal income.\n'
     'This ratio keeps your business growing while paying you fairly.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Decide which stage your business is currently at.\n'
     'Write three specific actions you will take this week to move to the next stage.\n'
     'Write your income target for 3 months from now.\n'
     'Calculate how much stock you need and what margins you need to achieve that target.\n'
     'This is your business plan. Start working it today.'),
])

# ============================================================
# SIMPLE BOOKKEEPING FOR SMALL BUSINESSES
# ============================================================
add_lessons('Simple Bookkeeping for Small Businesses', [
    (1, 'Why Every Business Needs Records', 20,
     'Keeping records is not just for accountants and big companies. Every trader and small business owner needs records to survive and grow.\n\n'
     'WHY RECORDS MATTER:\n\n'
     'TO KNOW YOUR REAL PROFIT:\n'
     'Without records, you are guessing. And as you learned in Trading, your guess is usually wrong.\n'
     'Records give you the truth about your business.\n\n'
     'TO GET LOANS:\n'
     'Banks and microfinance institutions require financial records before lending.\n'
     'Good records unlock capital for growth.\n\n'
     'TO PAY THE RIGHT TAX:\n'
     'Without records, you cannot prove what you earned or spent.\n'
     'You may end up paying too much tax, or face penalties for paying too little.\n\n'
     'TO DETECT THEFT:\n'
     'If you employ anyone, records help you notice if money or stock is disappearing.\n\n'
     'TO MAKE BETTER DECISIONS:\n'
     'Which product makes you the most profit?\n'
     'Which month is busiest? Which is slowest?\n'
     'Which customer never pays on time?\n'
     'Records answer these questions.\n\n'
     'TO GROW YOUR BUSINESS:\n'
     'Investors and larger buyers ask to see your records.\n'
     'Good records make your business credible.\n\n'
     'THE FEAR OF BOOKKEEPING:\n'
     'Many small business owners avoid records because they think it is complicated.\n'
     'It is not. You do not need to be an accountant.\n'
     'You need three things: a notebook, a pen, and the habit of writing things down.\n\n'
     'Or a phone with a simple spreadsheet app.\n\n'
     'THE GOLDEN RULE:\n'
     'Write it down TODAY. Not tomorrow. Not when you remember.\n'
     'TODAY. Every transaction, every day.\n\n'
     'PRACTICAL EXERCISE:\n'
     'For the next 7 days, write down every transaction in your business.\n'
     'Every sale. Every purchase. Every expense.\n'
     'At the end of 7 days, add everything up.\n'
     'This is the beginning of your bookkeeping practice.'),

    (2, 'The Daily Sales and Expense Record', 25,
     'The most important book in your business is your daily record. Here is how to keep it simply and correctly.\n\n'
     'WHAT YOU NEED:\n'
     'A notebook (cash book) with two sections: INCOME and EXPENSES.\n'
     'Or a phone with a notes app or spreadsheet.\n'
     'Commit 10 minutes at the end of each trading day to update it.\n\n'
     'THE DAILY RECORD FORMAT:\n\n'
     'DATE: [Today\'s date]\n\n'
     'INCOME (Money Coming In):\n'
     'Item sold | Quantity | Price each | Total received\n'
     'Rice 50kg | 1 bag | 230,000 | 230,000\n'
     'Tomatoes | 3 trays | 15,000 | 45,000\n'
     'TOTAL INCOME: 275,000\n\n'
     'EXPENSES (Money Going Out):\n'
     'Item | Amount\n'
     'Transport to market | 3,000\n'
     'Market fee | 1,500\n'
     'New stock - rice | 180,000\n'
     'New stock - tomatoes | 30,000\n'
     'Phone credit | 1,000\n'
     'TOTAL EXPENSES: 215,500\n\n'
     'TODAY\'S NET: 275,000 minus 215,500 = 59,500 surplus\n\n'
     'IMPORTANT DISTINCTIONS:\n\n'
     'CASH SALES vs CREDIT SALES:\n'
     'Cash sales: Money received immediately. Write in income on the day of sale.\n'
     'Credit sales: Goods given, payment to come. Write separately as "money owed to me" (debtors).\n'
     'Only count credit sales as income when the customer actually pays.\n\n'
     'STOCK PURCHASED vs STOCK SOLD:\n'
     'Write the purchase of stock as an expense on the day you buy.\n'
     'Write the sale of stock as income on the day you sell.\n'
     'These happen on DIFFERENT days — do not confuse them.\n\n'
     'MONTHLY SUMMARY:\n'
     'At the end of each month:\n'
     'Add all income. Add all expenses.\n'
     'Income minus Expenses = Profit (or Loss).\n'
     'Compare each month. Is your business growing?\n\n'
     'PRACTICAL EXERCISE:\n'
     'Set up your daily record book today.\n'
     'Write the date and column headings.\n'
     'Record today\'s transactions using the format above.\n'
     'Do this every day for one month. It will change your business.'),

    (3, 'Stock Control — Knowing What You Have and What It Is Worth', 25,
     'Your stock is money. Knowing exactly what stock you have is knowing exactly how much money you have in the business.\n\n'
     'THE STOCK RECORD:\n'
     'A stock record shows:\n'
     'What stock you have (type, quantity, description)\n'
     'When you received it and what you paid\n'
     'How much you have sold\n'
     'How much stock remains\n\n'
     'SIMPLE STOCK RECORD FORMAT:\n\n'
     'Product: Rice 50kg bags\n'
     'Date received | Quantity in | Cost per unit | Total cost\n'
     '01 June | 10 bags | 180,000 | 1,800,000\n\n'
     'Date sold | Quantity out | Price per unit | Total received\n'
     '02 June | 3 bags | 230,000 | 690,000\n'
     '03 June | 4 bags | 230,000 | 920,000\n\n'
     'Stock remaining: 3 bags\n'
     'Value of remaining stock (at cost): 3 times 180,000 = 540,000\n\n'
     'WHY STOCK CONTROL MATTERS:\n\n'
     'PREVENTS THEFT:\n'
     'If you know you had 10 bags and sold 7, you should have 3.\n'
     'If you only have 2, where did the 10th go?\n'
     'Stock records make theft visible.\n\n'
     'PREVENTS RUNNING OUT:\n'
     'You can see when stock is getting low before it runs out completely.\n'
     'Running out of popular stock costs you sales.\n\n'
     'SHOWS YOUR ACTUAL CAPITAL:\n'
     'Stock value + Cash = Total business assets.\n'
     'Knowing this tells you if your business is growing or shrinking.\n\n'
     'IDENTIFIES SLOW-MOVING STOCK:\n'
     'Stock that does not sell ties up your money.\n'
     'Record keeping reveals which products move quickly and which do not.\n'
     'Focus on fast-moving products.\n\n'
     'SPOILAGE AND LOSSES:\n'
     'Record when stock is lost, spoiled or stolen.\n'
     'If 5% of your tomatoes spoil every week, that is a real cost that must be in your prices.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Count all the stock in your business right now.\n'
     'Write down every item, quantity and what you paid for it.\n'
     'Calculate the total value of your stock at cost price.\n'
     'This is your stock record starting point.\n'
     'Update it every time stock comes in or goes out.'),

    (4, 'Debtors and Creditors — Managing Money Owed', 20,
     'Giving and receiving credit is common in trading. Managing it well is the difference between a healthy and a struggling business.\n\n'
     'DEBTORS — PEOPLE WHO OWE YOU MONEY:\n'
     'When you sell goods on credit, the buyer becomes a debtor.\n'
     'You are owed money. This is an asset of your business.\n'
     'But money owed is not money in hand — it is a risk.\n\n'
     'DEBTOR RECORD FORMAT:\n'
     'Name | Date | Goods | Amount owed | Date due | Paid | Balance\n'
     'James | 01/06 | 2 bags rice | 460,000 | 08/06 | 230,000 | 230,000\n'
     'Saffie | 03/06 | Tomatoes | 45,000 | 10/06 | 0 | 45,000\n\n'
     'RULES FOR GIVING CREDIT:\n'
     'Only give credit to people you trust and have dealt with before.\n'
     'Always agree a specific payment date before giving goods.\n'
     'Charge a higher price for credit sales — you deserve to be paid for waiting.\n'
     'Do not give more credit until the existing debt is paid.\n'
     'Chase debts immediately when they fall due. Do not let them drift.\n'
     'Know your total debtors every week. If it is growing, your cash flow will suffer.\n\n'
     'CREDITORS — PEOPLE YOU OWE MONEY TO:\n'
     'When you buy on credit, you become a debtor to your supplier.\n'
     'They are your creditor.\n'
     'This is a liability — money you must pay.\n\n'
     'CREDITOR RECORD FORMAT:\n'
     'Supplier | Date | Goods | Amount owed | Date due | Paid | Balance\n'
     'Koroma Wholesalers | 01/06 | 5 bags rice | 900,000 | 15/06 | 450,000 | 450,000\n\n'
     'RULES FOR BUYING ON CREDIT:\n'
     'Only use credit for stock you are confident you can sell before payment is due.\n'
     'Always know exactly how much you owe and when it is due.\n'
     'Pay on time — your credit reputation determines future credit terms.\n'
     'Never use credit to cover personal expenses.\n\n'
     'THE CREDIT BALANCE:\n'
     'Total debtors minus Total creditors = Net credit position.\n'
     'If debtors are bigger than creditors: Your business is owed money overall.\n'
     'If creditors are bigger than debtors: You owe more than is owed to you. This is a risk.\n\n'
     'PRACTICAL EXERCISE:\n'
     'List everyone who currently owes your business money.\n'
     'List everyone your business currently owes money to.\n'
     'Calculate the net position.\n'
     'Plan immediate action for any overdue debts.'),

    (5, 'Monthly Review — Reading the Health of Your Business', 20,
     'At the end of every month, take 30 minutes to review your business. This monthly habit separates successful traders from those who drift.\n\n'
     'THE MONTHLY REVIEW CHECKLIST:\n\n'
     '1. INCOME:\n'
     'Total all sales for the month.\n'
     'Compare to last month. Up or down? Why?\n'
     'Which products sold best? Which sold poorly?\n\n'
     '2. EXPENSES:\n'
     'Total all expenses for the month.\n'
     'Is any category unusually high? Why?\n'
     'Are there expenses you could reduce?\n\n'
     '3. PROFIT:\n'
     'Income minus Expenses = Profit.\n'
     'What is your profit margin? (Profit divided by Income times 100)\n'
     'A healthy trading business should make 15-30% net profit margin.\n'
     'If your margin is lower, your prices are too low or your costs are too high.\n\n'
     '4. CASH:\n'
     'How much cash does the business have?\n'
     'Does this match what the records say you should have?\n'
     'If the records show profit but you have less cash than expected:\n'
     'Money may be going missing.\n'
     'You may be mixing business and personal funds.\n'
     'Debts owed to you are not being collected.\n\n'
     '5. STOCK:\n'
     'What stock do you have at the end of the month?\n'
     'What is it worth at cost price?\n'
     'Is stock growing (you are accumulating) or shrinking (you are selling well)?\n\n'
     '6. DEBTORS AND CREDITORS:\n'
     'Who owes you money? Is it being collected?\n'
     'Who do you owe money to? Are you paying on time?\n\n'
     'THE SIMPLE MONTHLY BALANCE SHEET:\n'
     'ASSETS (what the business owns or is owed):\n'
     'Cash in hand + Cash in bank account = Cash total\n'
     'Stock value at cost = Stock total\n'
     'Debtors (money owed to you) = Debtors total\n'
     'TOTAL ASSETS = Cash + Stock + Debtors\n\n'
     'LIABILITIES (what the business owes):\n'
     'Creditors (money you owe) = Creditors total\n\n'
     'NET WORTH OF BUSINESS = Total Assets minus Total Liabilities\n\n'
     'If your net worth grows each month, your business is growing.\n'
     'If it stays the same, you are maintaining.\n'
     'If it shrinks, you have a serious problem that must be addressed immediately.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Do your first monthly review using the checklist above.\n'
     'Calculate your net worth.\n'
     'Set three targets for next month.\n'
     'Review again next month.\n'
     'Do this every month without fail. Your business will thank you.'),
])

# ============================================================
# VALUE-ADDED BUSINESS
# ============================================================
add_lessons('Value-Added Business — Transforming Raw Materials into Profit', [
    (1, 'Understanding Value-Added Business', 20,
     'A value-added business transforms raw materials into something more valuable before selling. This creates more profit — but also more complexity in costing.\n\n'
     'WHAT IS VALUE-ADDED?\n'
     'Value-added means you take something in its basic form and improve it before selling.\n\n'
     'EXAMPLES:\n'
     'Mama Kadiatu buys raw groundnuts for Le 20,000 per cup.\n'
     'She roasts and salts them, packs them in small sachets.\n'
     'She sells 10 sachets at Le 5,000 each = Le 50,000.\n'
     'She added value through labour, packaging and skill.\n\n'
     'Ibrahim buys raw timber and cuts and polishes it into furniture.\n'
     'He transformed a raw material worth Le 50,000 into furniture worth Le 500,000.\n\n'
     'Hawa buys plain fabric and tailors it into a dress.\n'
     'She transformed Le 80,000 of fabric into a dress worth Le 300,000.\n\n'
     'THE OPPORTUNITY:\n'
     'Value-added businesses generally make more profit than pure traders.\n'
     'Why? Because customers pay for your skill, your time and the transformation.\n'
     'They cannot easily do it themselves.\n\n'
     'THE CHALLENGE:\n'
     'Costing is more complex. You must account for:\n'
     'Raw materials (and their true cost)\n'
     'Your labour time (which has a cost)\n'
     'Equipment and tools (which wear out and must be replaced)\n'
     'Utilities (electricity, gas, water used in production)\n'
     'Packaging materials\n'
     'Waste and spoilage during processing\n\n'
     'THE KEY PRINCIPLE:\n'
     'The transformation creates value — but it also creates cost.\n'
     'You must charge for both the materials AND the value you add.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Describe your business or one you are planning.\n'
     'What is the raw material or input?\n'
     'What transformation do you perform?\n'
     'What is the finished product?\n'
     'Estimate: What does the input cost? What does the output sell for?\n'
     'That gap is your potential — but first you must understand all your costs.'),

    (2, 'Costing a Value-Added Product', 30,
     'Accurate costing is the foundation of a profitable value-added business. Most producers underprice because they forget to include all costs.\n\n'
     'THE FULL COST OF PRODUCTION:\n\n'
     '1. MATERIALS COST:\n'
     'Every ingredient or raw material used.\n'
     'Include waste — if you use 1kg of tomatoes but 100g is waste, your cost is for 1kg even though only 900g is in the product.\n\n'
     '2. DIRECT LABOUR:\n'
     'Your time and the time of any workers directly making the product.\n'
     'Value your own time honestly. If you could earn Le 15,000 per hour working for someone else,\n'
     'your time costs your business Le 15,000 per hour.\n'
     'If you spend 2 hours making something, that is Le 30,000 of your time.\n\n'
     '3. PACKAGING:\n'
     'Bags, sachets, boxes, labels, stickers.\n'
     'Include every piece of packaging per unit.\n\n'
     '4. UTILITIES:\n'
     'Gas, electricity or firewood used in production.\n'
     'Estimate: if your gas costs Le 50,000 per month and you produce 500 units,\n'
     'that is Le 100 of gas per unit.\n\n'
     '5. EQUIPMENT DEPRECIATION:\n'
     'Your tools and equipment wear out and must eventually be replaced.\n'
     'If your blender cost Le 200,000 and lasts 2 years (24 months),\n'
     'it costs your business approximately Le 8,333 per month.\n'
     'If you make 200 units per month, that is Le 42 per unit for the blender.\n\n'
     '6. OVERHEAD:\n'
     'Rent, water, market fees, phone credit, transport to sell.\n'
     'Divide monthly overhead by number of units produced to get per-unit overhead.\n\n'
     'EXAMPLE — GROUNDNUT CANDY:\n'
     'Making 100 packs per day:\n'
     'Groundnuts (1kg per 100 packs): Le 25,000 / 100 = Le 250 per pack\n'
     'Sugar: Le 10,000 / 100 = Le 100 per pack\n'
     'Packaging (sachets): Le 500 each\n'
     'Gas: Le 5,000 / 100 = Le 50 per pack\n'
     'Your labour (4 hours at Le 10,000 per hour = Le 40,000): Le 400 per pack\n'
     'Overhead allocation: Le 200 per pack\n'
     'TOTAL COST PER PACK: Le 1,500\n\n'
     'To make 50% markup: Sell at Le 2,250 per pack.\n'
     'Revenue from 100 packs: Le 225,000\n'
     'Total cost of 100 packs: Le 150,000\n'
     'Gross profit per day: Le 75,000\n\n'
     'PRACTICAL EXERCISE:\n'
     'Choose one product you make or plan to make.\n'
     'List every single cost involved.\n'
     'Calculate the cost per unit.\n'
     'Add your desired profit margin.\n'
     'Compare to what you currently charge or plan to charge.'),

    (3, 'Pricing Your Value-Added Products', 20,
     'Pricing in a value-added business must reflect your skill, time and the value customers receive — not just your material costs.\n\n'
     'THREE APPROACHES TO PRICING:\n\n'
     '1. COST-PLUS PRICING:\n'
     'Calculate total cost per unit.\n'
     'Add desired profit margin.\n'
     'This guarantees you cover costs and make profit.\n'
     'Problem: It may price you out of the market, or leave profit on the table.\n\n'
     '2. MARKET PRICING:\n'
     'Research what customers pay for similar products.\n'
     'Price competitively within that range.\n'
     'Problem: If your costs are higher than competitors, you may not be profitable at market price.\n'
     'Solution: Reduce costs, differentiate your product, or find a different market.\n\n'
     '3. VALUE-BASED PRICING:\n'
     'Charge what your product is worth to the customer, not just what it costs you.\n'
     'A wedding cake costs Le 50,000 in materials. But it is worth Le 500,000 to the bride.\n'
     'Your skill, reputation and uniqueness justify premium pricing.\n'
     'This is the most profitable approach when you have a quality product.\n\n'
     'CALCULATING YOUR MINIMUM PRICE:\n'
     'Minimum price = Total cost per unit.\n'
     'Never sell below this. You are working for free or worse.\n\n'
     'TARGET PRICE:\n'
     'Minimum price plus at least 40% profit for value-added products.\n'
     '(Value-added products deserve higher margins than pure trading because of the skill and time involved)\n\n'
     'WHEN CUSTOMERS SAY YOUR PRICE IS TOO HIGH:\n'
     'Do not immediately reduce your price.\n'
     'Ask: Which customer? For which product?\n'
     'Are they comparing to a lower-quality product? Explain the difference.\n'
     'Can you reduce packaging or portion size to meet their budget while maintaining your margin?\n'
     'Are they the right customer for your product? Some customers cannot afford quality — find customers who can.\n\n'
     'PRACTICAL EXERCISE:\n'
     'For your main product:\n'
     'Calculate your minimum price (total cost).\n'
     'Research what similar products sell for in your market.\n'
     'Decide on your target selling price.\n'
     'Calculate your profit per unit and profit margin.\n'
     'Is the margin good enough? If not, what must change?'),

    (4, 'Managing Production and Quality', 20,
     'Consistent quality builds reputation. Reputation builds loyal customers. Loyal customers build a thriving business.\n\n'
     'CONSISTENCY IS EVERYTHING:\n'
     'In a value-added business, customers return because they know what to expect.\n'
     'If your product is excellent today and poor tomorrow, customers stop trusting you.\n'
     'Consistency requires systems — doing things the same way every time.\n\n'
     'THE RECIPE OR PROCESS SHEET:\n'
     'Write down exactly how you make every product.\n'
     'Exact quantities of each ingredient.\n'
     'Exact steps in the process.\n'
     'Exact temperature, time, or technique required.\n'
     'Quality checks at each stage.\n\n'
     'WHY WRITE IT DOWN?\n'
     'So anyone helping you follows the same process.\n'
     'So you do not vary the recipe from memory.\n'
     'So you can scale up production while maintaining quality.\n'
     'So the business does not depend entirely on your personal knowledge.\n\n'
     'QUALITY CHECKS:\n'
     'Before production: Is raw material fresh and up to standard?\n'
     'During production: Is the process being followed correctly?\n'
     'After production: Does the finished product meet your standard?\n'
     'Customer feedback: Listen to complaints and compliments.\n\n'
     'MANAGING WASTE:\n'
     'Every piece of waste is money lost.\n'
     'Track your waste percentage and try to reduce it.\n'
     'Even small reductions in waste significantly improve profitability.\n'
     'Some waste can be repurposed into other products.\n\n'
     'SCALING UP PRODUCTION:\n'
     'Before scaling, ensure:\n'
     'Your process is documented and consistent.\n'
     'You have reliable suppliers for increased volumes.\n'
     'You have buyers for the increased output.\n'
     'You have sufficient cash flow to finance larger production runs.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Write your process sheet for your main product.\n'
     'Include every ingredient, every step, every timing.\n'
     'Have someone else follow your process sheet and make the product.\n'
     'Did the result match your standard?\n'
     'Refine the process sheet until it produces consistent results.'),

    (5, 'Growing Your Value-Added Business', 20,
     'A successful value-added business creates wealth through skill, reputation and smart reinvestment.\n\n'
     'YOUR COMPETITIVE ADVANTAGES:\n'
     'Unlike pure traders who all sell the same goods, you have:\n'
     'A unique product or process that others cannot easily copy.\n'
     'A skill that took time to develop.\n'
     'A reputation for quality that can command premium prices.\n'
     'The ability to differentiate and innovate.\n\n'
     'BUILDING YOUR REPUTATION:\n'
     'Quality first — always. One bad product damages what ten good ones built.\n'
     'Hygiene and presentation matter as much as taste or quality.\n'
     'Packaging builds perceived value — well-presented products command higher prices.\n'
     'Customer service builds loyalty — a warm, reliable seller beats a rude one.\n\n'
     'MARKETING YOUR VALUE-ADDED PRODUCTS:\n'
     'WhatsApp Business: Share photos of your products. Take advance orders. Build a group of regular buyers.\n'
     'Word of mouth: The most powerful marketing in West African markets. Delight your customers.\n'
     'Free samples: Tastings, trials and samples convert doubters into buyers.\n'
     'Regular markets: Consistent presence at the same location builds familiarity and trust.\n'
     'Event catering: Large orders at events provide volume and visibility.\n\n'
     'GROWING YOUR PRODUCT RANGE:\n'
     'Start with one excellent product.\n'
     'Perfect it and build your reputation around it.\n'
     'Only then add complementary products.\n'
     'Each new product must meet the same quality standard as your flagship.\n\n'
     'WHEN TO HIRE HELP:\n'
     'When you have more orders than you can fill.\n'
     'When production is taking time away from selling and managing.\n'
     'Start with one part-time helper.\n'
     'Train them to your standard using your process sheet.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Write your 6-month growth plan:\n'
     'Target monthly revenue in 6 months.\n'
     'How many units must you sell to reach that target?\n'
     'What do you need to produce that volume?\n'
     'What marketing will you do?\n'
     'When will you need to hire help?\n'
     'Review this plan every month.'),
])

# ============================================================
# MARKET TRADING — BUYING AND RESELLING
# ============================================================
add_lessons('Market Trading — Buying and Reselling for Profit', [
    (1, 'The Fundamentals of Profitable Trading', 20,
     'Pure trading is simple in theory: buy low, sell higher. In practice, it requires knowledge, discipline and systems to be truly profitable.\n\n'
     'THE PROFIT EQUATION FOR TRADERS:\n'
     'Profit = Selling Price minus True Cost of Goods\n\n'
     'The True Cost includes EVERYTHING:\n'
     'Purchase price of goods\n'
     'Transport from supplier to you\n'
     'Market fees, tolls and daily charges\n'
     'Porterage and handling\n'
     'Storage if you keep stock overnight\n'
     'Expected losses (spoilage, theft, breakage)\n'
     'Transaction fees (mobile money, bank charges)\n'
     'Your own time cost\n\n'
     'THE THREE MARGINS EVERY TRADER MUST KNOW:\n\n'
     '1. GROSS MARGIN:\n'
     '(Selling price minus Purchase price) divided by Selling price times 100\n'
     'This tells you: for every Le 100 you receive, how much came from buying price versus profit.\n\n'
     '2. NET MARGIN:\n'
     '(Selling price minus True cost) divided by Selling price times 100\n'
     'This is your REAL profit percentage after ALL costs.\n\n'
     '3. MARKUP:\n'
     '(Profit divided by True cost) times 100\n'
     'This is how much above your true cost you are charging.\n\n'
     'WHAT IS A HEALTHY MARGIN FOR TRADERS?\n'
     'Groceries and produce: 15-25% net margin (highly competitive)\n'
     'Clothing and fabric: 25-40% net margin\n'
     'Electronics and phones: 10-20% net margin (high volume)\n'
     'Specialized goods: 30-60% net margin\n\n'
     'PRACTICAL EXERCISE:\n'
     'For your main product:\n'
     'Calculate your gross margin.\n'
     'Calculate your net margin (including ALL costs).\n'
     'Calculate your markup.\n'
     'Compare your net margin to the healthy ranges above.\n'
     'If you are below the range, what must change?'),

    (2, 'Finding and Negotiating with Suppliers', 25,
     'Your profit starts at the point of purchase. Buying well is the foundation of profitable trading.\n\n'
     'FINDING GOOD SUPPLIERS:\n\n'
     'WHOLESALE MARKETS:\n'
     'Where large quantities arrive from producers or importers.\n'
     'In Sierra Leone: Freetown waterfront, Kissy terminal, major markets.\n'
     'You pay less per unit but must buy in larger quantities.\n'
     'Better for traders who move volume quickly.\n\n'
     'DIRECT FROM PRODUCERS:\n'
     'Cut out the middleman. You buy directly from the farmer, manufacturer or importer.\n'
     'Requires more effort to establish relationships.\n'
     'Potentially the cheapest source if you can buy in sufficient quantity.\n\n'
     'MIDDLEMEN AND AGENTS:\n'
     'Sometimes the most practical option when you buy small quantities.\n'
     'Their margin reduces yours — but access to the source is not always practical.\n\n'
     'HOW TO NEGOTIATE:\n\n'
     'KNOW YOUR TARGET PRICE:\n'
     'Before negotiating, know the maximum you can pay and still make your required profit.\n'
     'This is your walk-away price. Never exceed it.\n\n'
     'BUY IN VOLUME:\n'
     'The single most powerful negotiating tool is volume.\n'
     'Can you partner with another trader to buy jointly and share the discount?\n\n'
     'PAY PROMPTLY OR PAY CASH:\n'
     'Suppliers love reliable cash buyers.\n'
     'Offering to pay immediately (versus credit) often secures a discount.\n\n'
     'BUILD RELATIONSHIPS:\n'
     'A supplier who trusts you gives you first access to good stock.\n'
     'They may hold goods for you, extend credit, or give you advance notice of price changes.\n'
     'Relationships are your competitive advantage.\n\n'
     'ASK FOR EXTRAS:\n'
     'If price reduction is impossible, ask for: free delivery, better payment terms, priority stock, or small extras.\n\n'
     'PRACTICAL EXERCISE:\n'
     'List all your current suppliers.\n'
     'When did you last negotiate with each?\n'
     'What would you need to buy more of to get a better price?\n'
     'Choose one supplier and prepare for a negotiation this week.'),

    (3, 'Stock Selection and Product Knowledge', 20,
     'Not all products are equally profitable. Choosing the right products is crucial to your success as a trader.\n\n'
     'WHAT MAKES A GOOD TRADING PRODUCT?\n\n'
     'HIGH TURNOVER:\n'
     'Sells quickly. Does not sit in stock.\n'
     'Fast-moving goods mean faster cash flow and less spoilage risk.\n'
     'Example: Daily consumption items (food, toiletries) versus seasonal items (holiday clothes).\n\n'
     'GOOD MARGIN:\n'
     'Enough difference between true cost and selling price to make worthwhile profit.\n'
     'Low margin products require very high volume to be profitable.\n\n'
     'LOW SPOILAGE RISK:\n'
     'Perishable goods are risky — they must be sold before they go bad.\n'
     'Non-perishable goods can be held longer.\n\n'
     'CONSISTENT DEMAND:\n'
     'Products with steady year-round demand are more reliable.\n'
     'Seasonal products can be very profitable but require timing and cash management.\n\n'
     'WHAT YOUR CUSTOMERS WANT:\n'
     'The best product is the one your customers actually buy.\n'
     'Talk to them. What else do they need? What are they buying elsewhere?\n\n'
     'PRODUCT KNOWLEDGE:\n'
     'Know your products thoroughly:\n'
     'Quality grades and differences.\n'
     'How to identify fresh versus poor quality.\n'
     'Proper storage to maintain quality.\n'
     'Which suppliers have the best quality at which times.\n'
     'Seasonal price patterns.\n\n'
     'Customers trust traders who know their products deeply.\n'
     'This knowledge is part of your competitive advantage.\n\n'
     'DIVERSIFICATION:\n'
     'Do not rely on one product.\n'
     'If that product becomes scarce, prices rise, or demand falls, your entire income is affected.\n'
     '2-4 complementary products give stability.\n'
     'But do not spread too thin — focus and expertise matter.\n\n'
     'PRACTICAL EXERCISE:\n'
     'List all the products you currently sell.\n'
     'For each: What is the margin? How fast does it sell? What is the spoilage risk?\n'
     'Rank them from most to least profitable.\n'
     'Consider: Should you stop selling the least profitable and focus on the best?'),

    (4, 'Managing Your Trading Day', 20,
     'How you manage your trading day determines how much you make. Professional traders are disciplined and organised.\n\n'
     'THE PROFESSIONAL TRADER\'S DAY:\n\n'
     'BEFORE THE MARKET:\n'
     'Know your stock levels.\n'
     'Know your cash position.\n'
     'Know your prices for the day based on current costs.\n'
     'Know any orders to fulfil.\n'
     'Plan: Do you need to restock today? From where?\n\n'
     'AT THE MARKET:\n'
     'Set up your stall attractively — presentation matters.\n'
     'Display prices clearly where appropriate.\n'
     'Greet customers warmly — people buy from people they like.\n'
     'Record every sale. Do not try to remember at the end of the day.\n'
     'Monitor stock levels throughout the day.\n\n'
     'HANDLING MONEY:\n'
     'Keep your money organised and safe.\n'
     'Never mix today\'s income with last night\'s cash or stock purchasing money.\n'
     'If using mobile money, check receipts.\n'
     'Give accurate change — shortchanging customers destroys trust.\n\n'
     'DEALING WITH SLOW PERIODS:\n'
     'Use quiet times to restock, tidy your display, contact suppliers or update records.\n'
     'Never reduce prices impulsively because trade is slow — know your minimum price.\n\n'
     'END OF TRADING DAY:\n'
     'Count your cash.\n'
     'Record all sales and expenses.\n'
     'Count remaining stock.\n'
     'Calculate today\'s profit.\n'
     'Plan tomorrow: What needs restocking? Who owes you money?\n\n'
     'CUSTOMER RELATIONSHIPS:\n'
     'Regular customers are the backbone of your business.\n'
     'Know their names. Remember their preferences.\n'
     'A small discount or a piece of extra product for loyal customers builds priceless goodwill.\n'
     'Treat complaints seriously — a complaint is a customer giving you a chance to keep them.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Today, record every single sale and every expense throughout the day.\n'
     'At the end of the day, calculate:\n'
     'Total income. Total expenses. Cash profit for the day.\n'
     'Was it more or less than you expected?\n'
     'Do this every day for one week.'),

    (5, 'Scaling Your Trading Business', 15,
     'Once your trading business is consistently profitable, you can plan for growth.\n\n'
     'SIGNS YOU ARE READY TO SCALE:\n'
     'You make consistent profit every month.\n'
     'You have 1-3 months of operating cash as a reserve.\n'
     'Your records are accurate and up to date.\n'
     'You understand exactly where your profit comes from.\n'
     'Customers are regularly asking for more than you can supply.\n\n'
     'HOW TRADERS SCALE:\n\n'
     '1. INCREASE STOCK VOLUME:\n'
     'Buy more of your best-selling products.\n'
     'Larger volumes unlock better prices from suppliers.\n'
     'Only increase stock when you have the cash AND the buyers.\n\n'
     '2. ADD COMPLEMENTARY PRODUCTS:\n'
     'If you sell rice, can you also sell cooking oil?\n'
     'Customers buying one often need the other.\n'
     'Cross-selling increases average transaction value.\n\n'
     '3. EXPAND YOUR SELLING LOCATIONS:\n'
     'More stalls, more markets, or an agent who sells for you.\n'
     'More locations means more revenue from the same products.\n\n'
     '4. MOVE UP THE SUPPLY CHAIN:\n'
     'Instead of buying from a wholesaler, can you buy directly?\n'
     'Can you become the wholesaler yourself and sell to other traders?\n\n'
     '5. ADD VALUE:\n'
     'Can you process or package your products to sell at a higher price?\n'
     'This transitions you from pure trading to value-added business.\n\n'
     'THE CAPITAL QUESTION:\n'
     'Growth requires capital. Where will it come from?\n'
     'Savings from profits (safest and recommended).\n'
     'Microfinance loan (only if you can clearly repay from the increased revenue).\n'
     'Partnership with another trader (share risk and rewards).\n\n'
     'NEVER borrow to cover losses or to maintain your current level of trading.\n'
     'Only borrow to finance growth you are confident will generate the repayment.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Are you ready to scale? Answer the readiness questions honestly.\n'
     'If yes: Write one growth action you will take in the next 30 days.\n'
     'If not: Write what needs to be in place before you scale.\n'
     'Review this in 90 days.'),
])

print('\nAll done!')
from courses.models import Course
for c in ['Trading and Petty Business Management', 'Simple Bookkeeping for Small Businesses',
          'Value-Added Business — Transforming Raw Materials into Profit',
          'Market Trading — Buying and Reselling for Profit']:
    try:
        course = Course.objects.get(title=c)
        print(f'  {c}: {course.lessons.count()} lessons')
    except:
        print(f'  NOT FOUND: {c}')