# Generated by Django 4.2 on 2026-08-31 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("community", "0002_add_image_likes_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[
                    ("blog", "📝 Blog"),
                    ("reel", "🎬 Reel"),
                    ("thread", "🧵 Thread"),
                    ("forum", "💬 Forum Question"),
                    ("achievement", "🏆 Achievement"),
                    ("job", "💼 Job / Opportunity"),
                    ("podcast", "🎙️ Podcast"),
                    ("poll", "📊 Poll"),
                    ("event", "📅 Event"),
                ],
                default="blog",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="video_url",
            field=models.URLField(
                blank=True, help_text="YouTube / Loom / Drive link for Reel/Podcast"
            ),
        ),
    ]
