# Generated by Django 6.0.7 on 2026-07-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pillar',
            field=models.CharField(choices=[('literacy', 'Foundational Literacy'), ('computer', 'Computer Literacy'), ('vocational', 'Vocational Trades'), ('certification', 'Certifications'), ('life_skills', 'Life Skills'), ('primary', 'Primary Education'), ('secondary_arts', 'Secondary Education - Arts'), ('secondary_commercial', 'Secondary Education - Commercial'), ('secondary_science', 'Secondary Education - Science'), ('secondary_technical', 'Secondary Education - Technical'), ('secondary_trade', 'Secondary Education - Trade'), ('building', 'Building Construction'), ('housing', 'Housing and Appliances'), ('electrical', 'Electrical Installation'), ('auto_motorcycle', 'Automotive - Motorcycles'), ('auto_cars', 'Automotive - Cars and Vans'), ('auto_heavy', 'Automotive - Heavy Vehicles'), ('beauty_hair', 'Hair Care and Styling'), ('beauty_makeup', 'Makeup and Beauty'), ('it', 'Information Technology'), ('digital', 'Digital Skills'), ('carpentry', 'Carpentry and Woodwork'), ('welding', 'Welding and Metalwork'), ('agriculture', 'Agriculture and Farming'), ('tailoring', 'Tailoring and Fashion'), ('financial', 'Financial Literacy')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='learning_approach',
            field=models.CharField(choices=[('pedagogic', 'Pedagogic (Child-focused)'), ('andragogic', 'Andragogic (Adult-focused)'), ('heutagogic', 'Heutagogic (Self-determined)'), ('cybergogic', 'Cybergogic (Tech-enhanced)')], max_length=20),
        ),
    ]
