# Generated by Django 6.0.7 on 2026-07-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_category_description_ar_category_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='prerequisites_ar',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prerequisites_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prerequisites_es',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prerequisites_fr',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prerequisites_pt',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prerequisites_sw',
        ),
        migrations.RemoveField(
            model_name='course',
            name='target_audience_ar',
        ),
        migrations.RemoveField(
            model_name='course',
            name='target_audience_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='target_audience_es',
        ),
        migrations.RemoveField(
            model_name='course',
            name='target_audience_fr',
        ),
        migrations.RemoveField(
            model_name='course',
            name='target_audience_pt',
        ),
        migrations.RemoveField(
            model_name='course',
            name='target_audience_sw',
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_es',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_pt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_sw',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='pillar',
            field=models.CharField(choices=[('literacy', 'Foundational Literacy'), ('computer', 'Computer Literacy'), ('vocational', 'Vocational Trades'), ('certification', 'Certifications'), ('life_skills', 'Life Skills'), ('primary', 'Primary Education'), ('secondary_arts', 'Secondary Education - Arts'), ('secondary_commercial', 'Secondary Education - Commercial'), ('secondary_science', 'Secondary Education - Science'), ('secondary_technical', 'Secondary Education - Technical'), ('secondary_trade', 'Secondary Education - Trade'), ('building', 'Building Construction'), ('housing', 'Housing and Appliances'), ('electrical', 'Electrical Installation'), ('auto_motorcycle', 'Automotive - Motorcycles'), ('auto_cars', 'Automotive - Cars and Vans'), ('auto_heavy', 'Automotive - Heavy Vehicles'), ('beauty_hair', 'Hair Care and Styling'), ('beauty_makeup', 'Makeup and Beauty'), ('it', 'Information Technology'), ('digital', 'Digital Skills'), ('carpentry', 'Carpentry and Woodwork'), ('welding', 'Welding and Metalwork'), ('agriculture', 'Agriculture and Farming'), ('tailoring', 'Tailoring and Fashion'), ('financial', 'Financial Literacy'), ('auto_marine', 'Automotive Marine')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description_sw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title_es',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title_pt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title_sw',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_sw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title_es',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title_pt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title_sw',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
