# Generated by Django 5.2.17 on 2026-08-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_userprogress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="pillar",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="learning_approach",
            field=models.CharField(
                choices=[
                    ("pedagogic", "Pedagogic"),
                    ("andragogic", "Andragogic"),
                    ("heutagogic", "Heutagogic"),
                    ("cybergogic", "Cybergogic"),
                ],
                max_length=20,
            ),
        ),
    ]
