# Generated by Django 5.2.17 on 2026-08-22 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_quiz'),
    ]

    operations = [
    ]
