# Generated by Django 4.2 on 2026-09-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_quiz"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="lessons/audios/"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("video", "Video - Practical Demo"),
                    ("audio", "Audio - Theory / Igbo Explanation"),
                    ("pdf", "PDF - Manual / Diagram"),
                    ("text", "Text - Step by Step"),
                ],
                default="video",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="lessons/pdfs/"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="lessons/videos/"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="youtube_url",
            field=models.URLField(
                blank=True, help_text="For ABIAPOLY - use YouTube to save server cost"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
