# Generated by Django 4.2 on 2026-09-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_lesson_audio_file_lesson_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="image_file",
            field=models.FileField(blank=True, null=True, upload_to="lessons/images/"),
        ),
        migrations.AlterField(
            model_name="course",
            name="age_group",
            field=models.CharField(
                choices=[
                    ("child", "Child (6-12)"),
                    ("teen", "Teen (13-17)"),
                    ("adult", "Adult (18+)"),
                    ("all", "All Ages"),
                ],
                default="adult",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="learning_approach",
            field=models.CharField(
                choices=[
                    ("pedagogy", "Pedagogy - Child Led (6-12, Nursery)"),
                    ("andragogy", "Andragogy - Adult Led (Market Women, Aba Youths)"),
                    ("heutagogy", "Heutagogy - Self-Determined (CEO, Business Owner)"),
                    ("cybergogy", "Cybergogy - Tech/Cyber (AI, Online, Solar)"),
                ],
                default="andragogy",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("video", "Video - Practical Demo"),
                    ("audio", "Audio - Theory / Igbo Explanation"),
                    ("pdf", "PDF - Manual / Diagram"),
                    ("text", "Text - Step by Step"),
                    ("image", "Image - Photo / Illustration"),
                    ("logo", "Logo / Brand Asset"),
                    ("diagram", "Diagram / Infographic"),
                    ("slide", "Slide / Presentation"),
                    ("zip", "ZIP / Project Files"),
                    ("link", "External Link / Resource"),
                ],
                default="video",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="Quiz",
        ),
    ]
