# Generated by Django 6.0.7 on 2026-07-18 05:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
        ('courses', '0002_alter_category_pillar_alter_course_learning_approach'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('template_type', models.CharField(choices=[('course_completion', 'Course Completion'), ('skill_mastery', 'Skill Mastery'), ('professional', 'Professional Certification'), ('honors', 'Honors Certificate')], max_length=50)),
                ('background_color', models.CharField(default='#1a3c6e', max_length=20)),
                ('text_color', models.CharField(default='#ffffff', max_length=20)),
                ('accent_color', models.CharField(default='#e8a838', max_length=20)),
                ('font_family', models.CharField(default='Georgia, serif', max_length=100)),
                ('header_text', models.CharField(default='Certificate of Completion', max_length=200)),
                ('body_text', models.TextField(default='This certifies that [student_name] has successfully completed the course [course_name]')),
                ('footer_text', models.CharField(default='SkillsContinua - Building communities through skills', max_length=200)),
                ('logo', models.ImageField(blank=True, upload_to='certificates/logos/')),
                ('signature_image', models.ImageField(blank=True, upload_to='certificates/signatures/')),
                ('background_image', models.ImageField(blank=True, upload_to='certificates/backgrounds/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='learneranswer',
            name='selected_answer',
        ),
        migrations.RemoveField(
            model_name='learneranswer',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='learneranswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='learner',
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-issue_date']},
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='issued_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='score_percent',
            new_name='duration_hours',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='is_valid',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='learner',
            new_name='student',
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('student', 'course')},
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_type',
            field=models.CharField(choices=[('course_completion', 'Course Completion'), ('skill_mastery', 'Skill Mastery'), ('professional', 'Professional Certification'), ('honors', 'Honors Certificate')], default='course_completion', max_length=50),
        ),
        migrations.AddField(
            model_name='certificate',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='grade',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issue_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='certificate',
            name='score_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='certificate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='verification_code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='verification_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='CertificateVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_by', models.CharField(blank=True, max_length=100)),
                ('verification_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_successful', models.BooleanField(default=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='certifications.certificate')),
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='LearnerAnswer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='quiz_attempt',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='rating',
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
    ]
