import os, django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'skillscontinua_core.settings')
django.setup()

from courses.models import Category, Course, Lesson
from accounts.models import User

admin = User.objects.filter(is_superuser=True).first()

# Get or create Sierra Leone specific category
sl_cat, _ = Category.objects.get_or_create(
    name='Sierra Leone — Local Knowledge',
    defaults={'pillar': 'entrepreneurship', 'language': 'English'}
)

voc_cat = Category.objects.filter(pillar='vocational').first()
fin_cat = Category.objects.filter(pillar='financial').first()

def make_course(title, description, category, level='beginner', hours=25):
    course, created = Course.objects.get_or_create(
        title=title,
        defaults={
            'category': category,
            'description': description,
            'level': level,
            'age_group': 'adult',
            'language': 'English',
            'duration_hours': hours,
            'is_compulsory': False,
            'is_active': True,
            'created_by': admin,
        }
    )
    status = 'CREATED' if created else 'EXISTS'
    print(f'{status}: {title}')
    return course

def add_lessons(course, lessons_data):
    Lesson.objects.filter(course=course).delete()
    for order, title, duration, content in lessons_data:
        Lesson.objects.create(
            course=course, title=title, content_type='text',
            content_text=content, order=order,
            duration_minutes=duration, is_active=True
        )
    print(f'  → {course.lessons.count()} lessons added')

# ============================================================
# 1. FISHING AND FISH PROCESSING
# ============================================================
c = make_course(
    'Fishing and Fish Processing',
    'Essential knowledge for Sierra Leone fishing communities. Covers traditional and improved fishing methods, fish handling, smoking and drying for preservation, market selling and the economics of a fishing livelihood. Especially relevant for Aberdeen, Tombo, Shenge and coastal communities.',
    voc_cat, hours=30
)
add_lessons(c, [
    (1, 'The Fishing Livelihood in Sierra Leone', 20,
     'Fishing is one of the oldest and most important livelihoods in Sierra Leone. Understanding it as a business — not just a way of life — is the key to making it more profitable.\n\n'
     'SIERRA LEONE\'S FISHING COMMUNITIES:\n'
     'Aberdeen (Freetown): The main artisanal fishing village in the capital. Hundreds of canoes go out daily.\n'
     'Tombo: Major fishing town south of Freetown. Hub for smoked fish trade.\n'
     'Shenge and Bonthe: Important coastal fishing communities.\n'
     'River fishing: Inland communities on the Rokel, Jong and Sewa rivers.\n\n'
     'THE FISHING VALUE CHAIN:\n'
     'Fisher catches fish.\n'
     'Fish is landed at the beach.\n'
     'Fish processors (mostly women) buy fresh fish, smoke or dry it.\n'
     'Traders transport smoked fish inland to markets.\n'
     'End consumers buy in markets across Sierra Leone.\n\n'
     'WHO MAKES MONEY?\n'
     'The fisher sells at landing price. This is usually the lowest price in the chain.\n'
     'The processor adds value by smoking or drying — selling at 2-3 times the fresh price.\n'
     'The trader adds value by transporting to areas of scarcity.\n'
     'Understanding where you sit in this chain — and how to move up — is the first business lesson.\n\n'
     'COMMON FISH SPECIES IN SIERRA LEONE WATERS:\n'
     'Bonga (Ethmalosa fimbriata): Most important fish. Schools near surface. Smoked widely.\n'
     'Snappers (Lutjanidae): High value. Sold fresh.\n'
     'Barracuda: Good eating. Market demand steady.\n'
     'Catfish (various): Common in rivers and estuaries.\n'
     'Shrimp: High value, especially for export and hotels.\n'
     'Tilapia: Increasingly important from aquaculture.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Visit Aberdeen fishing beach or any local landing site.\n'
     'Observe: When do boats return? Who buys the fish? What prices are paid?\n'
     'Talk to a fisher and a fish processor.\n'
     'Write down what you learned about how money flows in fishing.'),

    (2, 'Fishing Methods and Equipment', 25,
     'Using the right equipment and method for the target species makes the difference between a profitable trip and a wasted one.\n\n'
     'ARTISANAL FISHING METHODS IN SIERRA LEONE:\n\n'
     'CAST NETTING:\n'
     'Circular net thrown by hand over fish. Sinks quickly, trapping fish beneath.\n'
     'Best for: Shallow water, near shore, estuaries.\n'
     'Species: Bonga, small pelagics, mullet.\n'
     'Skill: The throw requires practice to spread the net properly.\n\n'
     'GILLNETTING:\n'
     'Net suspended vertically in water. Fish swim into it and gills become trapped.\n'
     'Types: Surface gill net (for pelagics), bottom gill net (for demersal fish).\n'
     'Set and retrieve after several hours.\n'
     'Best maintained: Check for tears, remove debris, dry before storing.\n\n'
     'HOOK AND LINE:\n'
     'Handline: Single line with hook(s). Effective for snappers, barracuda.\n'
     'Longline: Many hooks on branch lines. Set for bottom-dwelling species.\n'
     'Rod and line: Less common in artisanal fishing.\n\n'
     'BEACH SEINE:\n'
     'Large net deployed from canoe, surrounding a school of fish.\n'
     'Both ends pulled to shore by teams of haulers.\n'
     'Catches large quantities of bonga and small pelagics.\n'
     'Requires a team — typically 10-20 people.\n\n'
     'FISH TRAPS:\n'
     'Woven baskets or wire cages placed on riverbed or reef.\n'
     'Baited to attract fish. Checked daily or every few days.\n'
     'Effective in rivers and shallow coastal areas.\n\n'
     'CANOE AND ENGINE MAINTENANCE:\n'
     'Wooden canoe: Caulk (seal) any cracks before each season.\n'
     'Outboard engine: Change oil, check spark plugs, clean fuel filter.\n'
     'Store engine properly in off-season. Flush with fresh water after saltwater use.\n'
     'Life jackets: Every person in the canoe must have one.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Identify the fishing method used most in your community.\n'
     'What equipment is needed? What is the approximate cost?\n'
     'What species does it target? What are the best seasons?\n'
     'Talk to an experienced fisher about what they do differently from beginners.'),

    (3, 'Fish Handling and Quality', 20,
     'Fish quality begins the moment the fish leaves the water. Poor handling destroys value.\n\n'
     'WHY QUALITY MATTERS:\n'
     'Fresh fish commands the highest price.\n'
     'Poorly handled fish spoils faster, sells for less or cannot be sold.\n'
     'High quality fish opens access to hotels, restaurants and export markets.\n'
     'In Sierra Leone\'s heat, fish spoils within hours without proper handling.\n\n'
     'FRESHNESS SIGNS:\n'
     'Fresh fish: Bright clear eyes, red gills, firm flesh, mild sea smell.\n'
     'Stale fish: Cloudy sunken eyes, grey/brown gills, soft flesh, strong smell.\n'
     'Buyers check eyes and gills first — so should you before buying.\n\n'
     'HANDLING FRESH FISH:\n'
     'Kill fish immediately after landing (spiking or icing): Reduces stress, improves quality.\n'
     'Keep in shade: Direct sun degrades quality rapidly.\n'
     'Ice: The most effective preservation. 1kg ice per 1kg fish.\n'
     'In Sierra Leone, ice is available from ice factories in Freetown and major towns.\n'
     'Ice chest (cool box): Insulated containers extend ice effectiveness.\n\n'
     'HANDLING WITHOUT ICE:\n'
     'Eviscerate (gut) fish immediately — gut bacteria accelerates spoilage.\n'
     'Keep wet with clean seawater.\n'
     'Transport quickly to processor or market.\n'
     'Do not mix fresh fish with spoiled fish — spoilage spreads.\n\n'
     'SORTING AND GRADING:\n'
     'Sort by species and size at landing.\n'
     'Grade by quality: Premium (hotel/restaurant), standard (market), processed (smoking/drying).\n'
     'Different buyers for different grades — know your market.\n\n'
     'FOOD SAFETY:\n'
     'Clean hands, clean equipment, clean surface.\n'
     'Do not handle fish after using toilet without thorough handwashing.\n'
     'Fish is a major cause of food poisoning in West Africa when improperly handled.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Visit a fish landing site or fish market.\n'
     'Examine fresh, medium and stale fish.\n'
     'Note the differences in appearance, smell and texture.\n'
     'Ask a seller: How do they explain the difference to customers? How does price differ by freshness?'),

    (4, 'Fish Smoking and Drying for Preservation', 30,
     'Smoking and drying transforms perishable fresh fish into storable, tradeable products with higher value.\n\n'
     'WHY PROCESS FISH:\n'
     'Fresh fish spoils in hours. Smoked fish lasts weeks. Dried fish lasts months.\n'
     'Processed fish can travel inland to areas with no access to fresh fish.\n'
     'Women processors in communities like Aberdeen and Tombo earn significant income through smoking.\n\n'
     'FISH SMOKING:\n\n'
     'TRADITIONAL DRUM SMOKING:\n'
     'Steel drum modified with racks inside for fish and fuel below.\n'
     'Firewood or coconut shells used as fuel.\n'
     'Process:\n'
     '1. Scale, gut and wash fish. Cut large fish into portions.\n'
     '2. Spread on smoking rack inside drum.\n'
     '3. Light fire below. Maintain moderate, steady heat.\n'
     '4. First phase (hot smoking): 1-2 hours at high heat. Kills bacteria, partially cooks fish.\n'
     '5. Second phase (cold smoking): 4-8 hours at lower heat. Dries and preserves further.\n'
     '6. Cool completely before packaging. Hot fish in sealed packaging creates moisture and mould.\n\n'
     'IMPROVED CHORKOR KILN:\n'
     'More efficient than single drum. Stacked trays allow rotation.\n'
     'Lower fuel consumption. Higher capacity. More consistent result.\n'
     'Used widely in Ghana and increasingly in Sierra Leone.\n\n'
     'SIGNS OF GOOD SMOKING:\n'
     'Golden to deep brown colour. Firm, dry texture. Smoky aroma.\n'
     'Should not be wet or tacky to touch.\n'
     'Should have no raw areas.\n\n'
     'SUN DRYING:\n'
     'Clean, gut, salt and lay fish on raised racks in full sun.\n'
     'Turn twice daily. Protect from flies with mesh or light covering.\n'
     'Dry completely — 2-4 days depending on sun and fish size.\n'
     'Fully dried fish can last months in sealed storage.\n\n'
     'QUALITY PROBLEMS:\n'
     'Mould: Fish was not dry enough before storage. Increase drying time.\n'
     'Insect infestation: Store in sealed containers. Keep storage dry.\n'
     'Discolouration: Inconsistent temperature during smoking. Adjust process.\n\n'
     'PRICING SMOKED FISH:\n'
     'Calculate true cost: Fresh fish cost + fuel + labour + packaging + transport.\n'
     'Smoked fish should sell for at least 2x the cost of equivalent fresh fish.\n'
     'Premium smoked bonga in Freetown markets commands significantly more than fresh.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Observe or assist at a smoking operation.\n'
     'Calculate: Cost of 20kg fresh bonga + fuel + labour.\n'
     'Weigh the smoked result (drying removes 50-60% of weight).\n'
     'Calculate the price per kg of smoked fish needed to make a 40% profit.'),

    (5, 'The Fishing Business — Income, Costs and Growth', 20,
     'Fishing is not just a way of life. Managed well, it is a profitable business.\n\n'
     'UNDERSTANDING FISHING ECONOMICS:\n\n'
     'COSTS PER TRIP:\n'
     'Fuel (outboard engine): Le 40,000-80,000 depending on distance.\n'
     'Ice: Le 10,000-20,000 for a full day trip.\n'
     'Food for crew: Le 10,000-15,000.\n'
     'Net repairs or consumables: Le 5,000-20,000 average.\n'
     'Crew share: Typically the catch is divided — owner takes 50-60%, crew share the rest.\n'
     'TOTAL COST PER TRIP: approximately Le 80,000-150,000 before crew share.\n\n'
     'For the trip to be profitable, catch value must exceed this significantly.\n'
     'A bad trip (small catch, low price) can make a loss.\n'
     'This is the financial reality of fishing.\n\n'
     'REDUCING RISKS:\n'
     'Weather monitoring: Do not go out in dangerous conditions. The sea takes lives.\n'
     'Equipment maintenance: A breakdown at sea is dangerous and expensive.\n'
     'Diversify income: Fish processing, trading, boat hire on non-fishing days.\n'
     'Savings: Set aside money in good weeks for equipment repair and bad weeks.\n\n'
     'FISH PROCESSING AS INCOME:\n'
     'Women processors can earn more than fishers per unit.\n'
     'Lower risk: Buy fish after it is landed. No sea risk.\n'
     'Add value through smoking or drying. Sell at 2-3x purchase price.\n'
     'Build trading relationships with inland market sellers.\n\n'
     'COOPERATIVES:\n'
     'Fishing cooperatives allow: Shared equipment purchase, group savings and loans, collective bargaining for better prices, access to government programmes.\n'
     'Most successful fishing communities have strong cooperatives.\n\n'
     'GOVERNMENT SUPPORT:\n'
     'Sierra Leone Ministry of Fisheries provides: Subsidised outboard engines and fuel, training programmes, access to cold storage facilities.\n'
     'Register with your local fisheries committee to access these benefits.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Calculate the economics of one week of fishing:\n'
     'Estimate: Number of trips. Fuel cost. Ice cost. Expected catch. Expected price.\n'
     'What is the net income after costs and crew share?\n'
     'Compare to alternative income: What else could you earn in one week?\n'
     'Is fishing profitable at current prices and costs? What would need to change?'),
])

# ============================================================
# 2. UNDERSTANDING THE LEONE AND INFLATION
# ============================================================
c = make_course(
    'Understanding the Leone and Inflation',
    'Essential financial knowledge for Sierra Leonean traders, business owners and families. Learn what inflation is, why the Leone loses value, how this affects your business, and practical strategies to protect your income and savings from the effects of currency devaluation.',
    fin_cat, hours=15
)
add_lessons(c, [
    (1, 'What Is Inflation and Why Does It Happen?', 20,
     'Inflation is not just a government problem. It directly affects every trader, every family and every business in Sierra Leone every day.\n\n'
     'WHAT IS INFLATION?\n'
     'Inflation means prices are rising. A bag of rice that cost Le 100,000 last year now costs Le 150,000.\n'
     'Your money buys less than it did before.\n'
     'The value of your savings in Leones is falling.\n\n'
     'SIERRA LEONE\'S INFLATION HISTORY:\n'
     'Sierra Leone has experienced very high inflation repeatedly.\n'
     'In 2022-2023, inflation exceeded 40% — meaning prices rose by nearly half in one year.\n'
     'The Leone has lost enormous value against the US dollar over the past decade.\n'
     'A dollar that bought Le 7,000 in 2015 bought over Le 22,000 by 2023.\n'
     'Every Leone you save buys less and less over time.\n\n'
     'WHY DOES INFLATION HAPPEN?\n\n'
     '1. GOVERNMENT PRINTING MONEY:\n'
     'When the government needs money and cannot raise enough in taxes, it may print more currency.\n'
     'More money chasing the same goods means prices rise.\n\n'
     '2. IMPORT DEPENDENCY:\n'
     'Sierra Leone imports most of its food, fuel and goods.\n'
     'When the Leone loses value against the dollar, imports cost more in Leones.\n'
     'This pushes all prices up.\n\n'
     '3. FUEL PRICES:\n'
     'Nearly everything in Sierra Leone is transported by road or sea.\n'
     'When fuel prices rise, transport costs rise, and all prices follow.\n\n'
     '4. GLOBAL FACTORS:\n'
     'When global prices of food and fuel rise (as happened after COVID-19 and after the Ukraine war), Sierra Leone feels this immediately.\n\n'
     'WHO SUFFERS MOST FROM INFLATION?\n'
     'People who save in Leones (their savings lose value).\n'
     'Workers with fixed Leone salaries (their real pay falls).\n'
     'Traders who price in Leones without adjusting regularly (they lose margin).\n'
     'The poorest families who spend most income on food (food inflation hurts them most).\n\n'
     'PRACTICAL EXERCISE:\n'
     'Write down the price of five things you buy regularly (rice, fuel, transport fare, bread, phone credit).\n'
     'Try to remember what each cost one year ago.\n'
     'Calculate the percentage increase for each.\n'
     'That is your personal inflation rate. How does it compare to your income increase over the same period?'),

    (2, 'How Inflation Destroys Your Trading Business', 20,
     'Inflation is a silent thief that steals from traders who do not understand it.\n\n'
     'THE TRADER WHO DID NOT UNDERSTAND INFLATION:\n'
     'Mohamed bought 10 bags of rice in January for Le 1,500,000.\n'
     'He sold them by March for Le 1,800,000.\n'
     'He thought he made Le 300,000 profit.\n'
     'Then he went to buy more rice. The same 10 bags now cost Le 1,950,000.\n'
     'He could not afford to restock.\n'
     'His Le 300,000 "profit" was not enough to maintain his stock level.\n'
     'He was not making a profit. He was slowly going out of business.\n\n'
     'THIS IS INFLATION DESTROYING A BUSINESS.\n\n'
     'THE REPLACEMENT COST PRINCIPLE:\n'
     'The relevant question is not: What did I pay for this stock?\n'
     'The relevant question is: What will it cost me to REPLACE this stock?\n'
     'Your selling price must cover the REPLACEMENT cost, not just the original cost.\n\n'
     'EXAMPLE:\n'
     'You buy rice at Le 180,000 per bag in January.\n'
     'By March when you have sold it, the price has risen to Le 210,000 per bag.\n'
     'If you priced based on your January cost, you sold too cheaply.\n'
     'You cannot maintain your stock levels.\n'
     'Price based on what it will cost to replace the stock, not what you paid.\n\n'
     'ADJUSTING PRICES FOR INFLATION:\n'
     'Monitor your supplier prices every time you restock.\n'
     'Adjust your selling prices as your costs increase.\n'
     'Customers understand price increases when they are explained clearly.\n'
     'Customers who do not understand should be shown: Your rice now costs Le 210,000. I must sell for more.\n\n'
     'DO NOT ABSORB INFLATION:\n'
     'Many traders keep their prices the same when costs rise.\n'
     'They absorb the inflation themselves.\n'
     'This is working harder for less money every month.\n'
     'Raise prices. Explain why. Customers adjust.\n\n'
     'PRACTICAL EXERCISE:\n'
     'For your main product:\n'
     'What did you pay per unit 6 months ago?\n'
     'What do you pay per unit now?\n'
     'Calculate the percentage price increase.\n'
     'Have you raised your selling price by the same percentage?\n'
     'If not, you have been absorbing inflation. Correct this immediately.'),

    (3, 'Protecting Your Business and Savings from Inflation', 20,
     'You cannot stop inflation. But you can protect yourself from it.\n\n'
     'STRATEGY 1 — PRICE IN DOLLARS, COLLECT IN LEONES:\n'
     'Many Sierra Leonean businesses quote prices in US dollars.\n'
     'They collect in Leones at the day\'s exchange rate.\n'
     'This protects them from the Leone losing value between purchase and sale.\n'
     'Works well for: Professionals (doctors, lawyers, consultants), service businesses, landlords.\n'
     'Less practical for: Market traders with small daily transactions.\n\n'
     'STRATEGY 2 — FAST STOCK TURNOVER:\n'
     'The longer you hold stock before selling, the more inflation erodes your margin.\n'
     'Turn stock over quickly. Do not hold large quantities for long periods.\n'
     'Buy frequently in smaller quantities at current prices rather than buying large stocks at old prices.\n\n'
     'STRATEGY 3 — HOLD STOCK, NOT CASH:\n'
     'During high inflation, cash in Leones loses value daily.\n'
     'Stock (goods) holds its value or rises with inflation.\n'
     'Buying stock with excess cash protects value better than holding Leones.\n'
     'Risk: If prices fall (rare but possible), you hold overpriced stock.\n\n'
     'STRATEGY 4 — SAVE IN DOLLARS OR ASSETS:\n'
     'If you have savings, holding them in US dollars protects against Leone devaluation.\n'
     'Banks offer dollar accounts in Sierra Leone.\n'
     'Other inflation-resistant assets: Gold, property, livestock.\n'
     'Avoid: Long-term fixed deposits in Leones during high inflation — the interest rarely keeps pace.\n\n'
     'STRATEGY 5 — REDUCE DELAY BETWEEN BUYING AND SELLING:\n'
     'Credit sales lock in the price at time of sale.\n'
     'If the customer pays 30 days later, you receive Leones worth less than when you sold.\n'
     'Collect payment quickly. Or add an inflation premium to credit prices.\n\n'
     'STRATEGY 6 — PASS COSTS ON IMMEDIATELY:\n'
     'The moment your supplier raises prices, raise yours.\n'
     'Do not absorb even one week of higher costs.\n'
     'The psychological barrier to raising prices is harder than the practical one.\n'
     'Overcome it. Your business survival depends on it.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Calculate: In the last 12 months, by how much has the Leone fallen against the dollar?\n'
     'If you had Le 10,000,000 in a Leone account at the start, what is it worth in dollars today versus 12 months ago?\n'
     'What would it have been worth if you had held it in dollars?\n'
     'This is the cost of holding Leones during inflation.'),

    (4, 'Reading Exchange Rates and Using Them', 15,
     'Understanding the exchange rate is essential for any Sierra Leonean who buys imported goods.\n\n'
     'WHAT IS THE EXCHANGE RATE?\n'
     'The exchange rate tells you how many Leones buy one US dollar.\n'
     'If the rate is Le 22,000 per dollar:\n'
     'Le 22,000 = USD 1\n'
     'Le 220,000 = USD 10\n'
     'Le 2,200,000 = USD 100\n\n'
     'WHERE TO FIND THE RATE:\n'
     'Bank of Sierra Leone website: Official rate.\n'
     'Commercial banks: May offer slightly different rates.\n'
     'Money changers: Market rate, sometimes better than bank rate.\n'
     'News and radio: Rate often reported.\n'
     'Check the rate before any significant transaction involving foreign currency.\n\n'
     'HOW THE RATE AFFECTS TRADERS:\n'
     'Most imports into Sierra Leone are priced in dollars at source.\n'
     'The importer pays dollars. Passes the cost to wholesalers in Leones.\n'
     'As the Leone weakens, the same dollar-priced goods cost more Leones.\n'
     'This is why imported goods get more expensive when the Leone falls.\n\n'
     'BUYING AT THE WATERFRONT:\n'
     'Goods at Freetown waterfront are often priced in dollars.\n'
     'Always calculate: Dollar price times current exchange rate = Leone cost.\n'
     'Then add: Clearing fees, transport, your margin.\n'
     'Never buy at waterfront without knowing the current exchange rate.\n\n'
     'SENDING AND RECEIVING MONEY:\n'
     'Western Union, MoneyGram, Wave, Orange Money all use different rates.\n'
     'Compare rates before transferring. Small rate differences on large amounts matter significantly.\n'
     'When receiving money from abroad: Choose the channel with the best exchange rate.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Find today\'s Leone-to-dollar exchange rate from a bank or money changer.\n'
     'Calculate: What does USD 50 cost in Leones today?\n'
     'Find out what the rate was one year ago (ask someone, or check records).\n'
     'Calculate: How much more in Leones does USD 50 cost today than it did one year ago?\n'
     'This is the direct cost of Leone devaluation to your business.'),

    (5, 'Building Financial Resilience in Sierra Leone', 15,
     'Financial resilience means your household and business can survive economic shocks.\n\n'
     'BUILDING RESILIENCE:\n\n'
     'EMERGENCY FUND:\n'
     'Save 3 months of essential expenses in accessible form.\n'
     'Part in cash (for immediate needs). Part in a bank account.\n'
     'Consider holding some in dollars to protect against devaluation.\n'
     'Do not touch except for genuine emergencies.\n\n'
     'INCOME DIVERSIFICATION:\n'
     'Do not rely on one income source.\n'
     'Trader: Add a service (phone charging, copy services, tailoring).\n'
     'Fisher: Add processing or trading.\n'
     'Employee: Add a side business.\n'
     'Multiple income streams mean one problem does not destroy your livelihood.\n\n'
     'GROUP SAVINGS (OSUSU / SUSU):\n'
     'Traditional rotating savings groups are effective and trusted in Sierra Leone.\n'
     'Each member contributes weekly. One member gets the lump sum each week.\n'
     'Enforces savings discipline. Provides access to lump sum for investment.\n'
     'Widely practised in Freetown markets. Very effective for traders.\n\n'
     'MICROFINANCE:\n'
     'Several microfinance institutions operate in Sierra Leone.\n'
     'Loans available for business investment.\n'
     'Only borrow for investment that will clearly generate more than the repayment cost.\n'
     'Never borrow to cover losses or fund consumption.\n\n'
     'INVESTMENT IN CHILDREN\'S EDUCATION:\n'
     'Education is the most inflation-resistant investment.\n'
     'A child with skills earns more regardless of Leone value.\n'
     'Education is denominated in future earning power, not Leones.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Assess your financial resilience:\n'
     'How many months could your household survive on savings if income stopped?\n'
     'How many income sources do you have?\n'
     'Do you have any savings in dollars or other inflation-resistant assets?\n'
     'Are you part of an osusu or savings group?\n'
     'For each question where the answer is no or zero: Write one action you will take this month.'),
])

# ============================================================
# 3. KRIO FOR BUSINESS COMMUNICATION
# ============================================================
c = make_course(
    'Krio for Business Communication',
    'Practical Krio language skills for market trading, business negotiation and everyday communication in Freetown and across Sierra Leone. Designed for Sierra Leoneans from upcountry communities, and for non-Krio speakers who need to communicate effectively in the Freetown market environment.',
    sl_cat, hours=20
)
add_lessons(c, [
    (1, 'Introduction to Krio — The Language of Sierra Leone\'s Markets', 15,
     'Krio is the common language of Sierra Leone. It is the language of Freetown markets, transport, business and community. Speaking it confidently opens doors.\n\n'
     'WHAT IS KRIO?\n'
     'Krio is an English-based Creole language. It developed among freed slaves who settled in Freetown from the 1780s onwards.\n'
     'Today, Krio is spoken by virtually all Sierra Leoneans regardless of their ethnic background.\n'
     'It is the language of the market, of public transport, of everyday life in Freetown and most of Sierra Leone.\n'
     'Without functional Krio, trading in Freetown is very difficult.\n\n'
     'HOW KRIO WORKS:\n'
     'Many words come from English but with Sierra Leonean pronunciation and grammar.\n'
     'Grammar is simpler than English in many ways.\n'
     'Context and tone carry much meaning.\n'
     'Once you start speaking, people will help you improve.\n\n'
     'BASIC GREETINGS:\n'
     'Aw di bodi? — How are you? (Literally: How is the body?)\n'
     'Di bodi fine — I am fine (Literally: The body is fine)\n'
     'Aw yu du? — How do you do? / How are you?\n'
     'A de — I am here / I am fine\n'
     'Wetin? — What? / What is it?\n'
     'Whosai yu de go? — Where are you going?\n'
     'A de go maket — I am going to market\n'
     'Tenki — Thank you\n'
     'Tenki plenti — Thank you very much\n'
     'Na watin — You are welcome / It is nothing\n\n'
     'TIME GREETINGS:\n'
     'Gud mɔnin — Good morning\n'
     'Gud aaftanun — Good afternoon\n'
     'Gud ivin — Good evening\n'
     'Gud nɛt — Good night\n\n'
     'PRACTICAL EXERCISE:\n'
     'Practise greeting five people today in Krio.\n'
     'Use: Aw di bodi? — and respond to their answer.\n'
     'If someone replies in Krio and you do not understand, say:\n'
     '"Padi, tɔk slɔ slɔ" — Friend, speak slowly.\n'
     'People in Sierra Leone are patient and friendly with learners.'),

    (2, 'Numbers, Money and Market Transactions', 25,
     'Numbers and money are the foundation of market Krio. These phrases are used in every transaction.\n\n'
     'NUMBERS IN KRIO:\n'
     'Wan — 1\n'
     'Tu — 2\n'
     'Tri — 3\n'
     'Fɔ — 4\n'
     'Fayf — 5\n'
     'Siks — 6\n'
     'Sɛvɛn — 7\n'
     'Ɛt — 8\n'
     'Nain — 9\n'
     'Tɛn — 10\n'
     'Tɛn wan — 11\n'
     'Tuenti — 20\n'
     'Tɛti — 30\n'
     'Fɔti — 40\n'
     'Fifti — 50\n'
     'Wan ondred — 100\n'
     'Wan tɔznd — 1,000\n'
     'Tɛn tɔznd — 10,000\n'
     'Wan ondred tɔznd — 100,000\n'
     'Wan miliɔn — 1,000,000\n\n'
     'MONEY PHRASES:\n'
     'Aw much dis kɔs? — How much does this cost?\n'
     'Di pris na... — The price is...\n'
     'Tɔ much! — Too much!\n'
     'Ridus di pris — Reduce the price\n'
     'A go gi yu... — I will give you...\n'
     'Na faynal pris? — Is that your final price?\n'
     'Wi kin dil? — Can we make a deal?\n'
     'Gi mi wan dɔzen — Give me one dozen\n'
     'Gi mi tri kilo — Give me three kilos\n'
     'Weigh am — Weigh it\n'
     'Di skɛl tif! — The scale is cheating! (The scale is wrong!)\n'
     'Tɛs am — Test it / Try it\n'
     'Na fris? — Is it fresh?\n'
     'Na tude? — Is it from today?\n\n'
     'PAYING:\n'
     'A wan pay — I want to pay\n'
     'Gi mi chɛnj — Give me change\n'
     'Yu owe mi... — You owe me...\n'
     'A de pay by phone mɔni — I am paying by mobile money\n'
     'Sɛnd di nomba — Send the number (for mobile money)\n\n'
     'PRACTICAL EXERCISE:\n'
     'Go to a market with Le 20,000.\n'
     'Buy something using only Krio.\n'
     'Practice: Asking the price, bargaining, paying, receiving change.\n'
     'Write down any words you did not know and find out their meaning.'),

    (3, 'Common Market Phrases and Negotiation', 20,
     'Negotiation is at the heart of West African market trading. These phrases give you confidence at any stall.\n\n'
     'OPENING A CONVERSATION WITH A SELLER:\n'
     'Padi! — Friend! (to get attention)\n'
     'Watin yu get? — What do you have?\n'
     'Sho mi — Show me\n'
     'A luk fɔ... — I am looking for...\n'
     'Yu get rɛd pɛpa? — Do you have red pepper?\n'
     'Aw much di wan bɛg? — How much is one bag?\n\n'
     'BARGAINING:\n'
     'Di pris tɔ much — The price is too much\n'
     'A nor get plenti mɔni — I do not have much money\n'
     'Mek a prɔmis — Let me make a promise (offer)\n'
     'A go gi yu... — I will give you...\n'
     'Dat na mi last prɔmis — That is my last offer\n'
     'If yu nor gri, a go — If you do not agree, I will go\n'
     'Ɔlrait, tak am — Alright, take it (accepting an offer)\n'
     'Wi bi frɛn, mek yu mek mi gud pris — We are friends, give me a good price\n\n'
     'QUALITY QUESTIONS:\n'
     'Di tin gut? — Is the thing good? / Is it quality?\n'
     'No dɔnt mi — Do not deceive me\n'
     'A tɛs am fɛs — I will test it first\n'
     'If am nor gut a go kɔmɔt — If it is not good I will come back / return it\n\n'
     'PROBLEMS AND COMPLAINTS:\n'
     'Dis tin bɔku bad — This thing is very bad\n'
     'Yu tif mi — You cheated me / You stole from me\n'
     'Gi mi bak mi mɔni — Give me back my money\n'
     'A go kɔmplɛn — I will complain\n\n'
     'TRANSPORT:\n'
     'Drɛbɛ, yu de go wɛ? — Driver, where are you going?\n'
     'Ɔp fɔ mi at... — Stop for me at...\n'
     'Aw much di fɛ? — How much is the fare?\n'
     'Mɔv — Move / Go\n\n'
     'PRACTICAL EXERCISE:\n'
     'Write ten Krio sentences you would use in a typical market visit.\n'
     'Practice saying them out loud until they feel natural.\n'
     'Then use at least five of them in a real market or shop today.'),

    (4, 'Krio for Business and Professional Settings', 20,
     'Professional Krio is slightly more formal but still accessible. These phrases serve you in offices, with clients and in negotiations beyond the market.\n\n'
     'INTRODUCTIONS:\n'
     'Nɛm a mi na... — My name is...\n'
     'A de wɔk fɔ... — I work for...\n'
     'A na... (occupation) — I am a...\n'
     'A wan to do biznɛs wit yu — I want to do business with you\n'
     'A bring lɛta fɔ yu — I have brought a letter for you\n\n'
     'APPOINTMENTS AND MEETINGS:\n'
     'A wan mit di ɔfisa — I want to meet the officer/official\n'
     'A get apɔintmɛnt — I have an appointment\n'
     'Wɛn di mita go bi? — When will the meeting be?\n'
     'A go kam bakɔ — I will come back\n'
     'Yu bizi? — Are you busy?\n'
     'Wait wan minit — Wait one minute\n\n'
     'EXPLAINING YOUR BUSINESS:\n'
     'A sɛl... — I sell...\n'
     'A mek... — I make...\n'
     'A de luk fɔ wɔk — I am looking for work\n'
     'A fit du dis wɔk — I can do this work\n'
     'A get ɛkspɛriɛns — I have experience\n'
     'A wan lɛn — I want to learn\n\n'
     'COMMON QUESTIONS YOU WILL BE ASKED:\n'
     'Whosai yu kɔmɔt? — Where are you from?\n'
     'Yu sabi Krio? — Do you know Krio?\n'
     'Yu stei wɛ? — Where do you stay / live?\n'
     'Yu don it? — Have you eaten? (a friendly greeting)\n'
     'Wi don it — We have eaten / Yes (in response)\n\n'
     'DEALING WITH DIFFICULTIES:\n'
     'A nor andastand — I do not understand\n'
     'Tɔk slɔ slɔ — Speak slowly\n'
     'Ripɛt dat wan — Repeat that one\n'
     'A wan Inglis plis — I want English please\n'
     'Elp mi — Help me\n\n'
     'PRACTICAL EXERCISE:\n'
     'Introduce yourself in Krio to three different people today.\n'
     'Explain: Your name, where you are from, what work you do.\n'
     'Ask each person: What is their name and where are they from.\n'
     'Write down any new words you learned from this exercise.'),

    (5, 'Building Your Krio Confidence', 15,
     'Language learning is about using, not just studying. Confidence comes from practice.\n\n'
     'HOW TO IMPROVE YOUR KRIO QUICKLY:\n\n'
     'LISTEN:\n'
     'Sierra Leone Broadcasting Service (SLBS) radio broadcasts in Krio.\n'
     'Listen to conversations around you in markets and on transport.\n'
     'Do not just hear — actively try to understand each sentence.\n'
     'Note words you do not know. Ask someone what they mean.\n\n'
     'SPEAK:\n'
     'Even imperfect Krio is better than no Krio.\n'
     'Sierra Leoneans are encouraging to those trying to learn.\n'
     'Make mistakes. That is how you learn. Laugh with people when you make errors.\n'
     'Find one Krio speaker to practise with daily.\n\n'
     'ASK:\n'
     'When you hear a word you do not know, ask: Wetin dat wɔd min? (What does that word mean?)\n'
     'People are happy to explain.\n'
     'Carry a small notebook. Write new words and their meanings.\n\n'
     'READ:\n'
     'Krio has a written form though it is less standardised than English.\n'
     'Awareness Network Sierra Leone publishes materials in Krio.\n'
     'Reading Krio reinforces hearing and speaking.\n\n'
     'KEY PHRASES TO MASTER FIRST:\n'
     'Greetings (Lesson 1): Use every day.\n'
     'Numbers and prices (Lesson 2): Use in every market transaction.\n'
     'Negotiation phrases (Lesson 3): Use whenever bargaining.\n'
     'Asking for help and clarification: Use whenever you do not understand.\n\n'
     'THE ATTITUDE THAT WINS:\n'
     'Do not be embarrassed. Every Krio speaker admires someone making the effort to learn.\n'
     'Ask to be corrected. "Kɔrɛkt mi if a mek mistɛk" — Correct me if I make a mistake.\n'
     'Six months of daily practice will make you comfortable.\n'
     'Twelve months and Krio will feel natural.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Commit to using Krio every day for the next 30 days.\n'
     'Set a daily target: At least 3 Krio conversations per day.\n'
     'After 7 days, write down 20 new words you have learned this week.\n'
     'After 30 days, review: How comfortable do you feel now compared to Day 1?'),
])

# ============================================================
# 4. PORT AND LOGISTICS WORK
# ============================================================
c = make_course(
    'Port and Logistics Work',
    'Career skills for Sierra Leoneans seeking work in the Freetown port, shipping, freight forwarding and logistics sector. Covers port operations, customs procedures, freight forwarding basics, documentation and career pathways in one of Sierra Leone\'s most important employment sectors.',
    sl_cat, hours=25
)
add_lessons(c, [
    (1, 'Introduction to Freetown Port and Shipping', 20,
     'The Queen Elizabeth II Quay in Freetown is the economic heartbeat of Sierra Leone. Understanding how it works opens careers.\n\n'
     'WHY THE PORT MATTERS:\n'
     'Almost all of Sierra Leone\'s imports arrive by sea through Freetown.\n'
     'Exports (iron ore, rutile, bauxite, cocoa, coffee) leave through the port.\n'
     'The port employs thousands directly and tens of thousands indirectly.\n'
     'Shipping, clearing, forwarding, transport and warehousing all depend on the port.\n\n'
     'KEY PLAYERS AT THE PORT:\n\n'
     'SIERRA LEONE PORTS AUTHORITY (SLPA):\n'
     'Government body managing the port infrastructure.\n'
     'Controls berths, cranes, yard space and access.\n\n'
     'SHIPPING LINES:\n'
     'Companies that own or operate cargo ships.\n'
     'Examples: Maersk, MSC, CMA CGM. They bring goods to Freetown.\n'
     'Their local representatives are shipping agents.\n\n'
     'SHIPPING AGENTS:\n'
     'Local companies representing shipping lines.\n'
     'Handle ship calls, cargo manifests, Delivery Orders (DO).\n\n'
     'CLEARING AGENTS (CUSTOMS BROKERS):\n'
     'Licensed agents who clear goods through customs on behalf of importers.\n'
     'Must be licensed by Sierra Leone Revenue Authority (SLRA).\n'
     'Key career pathway for this course.\n\n'
     'FREIGHT FORWARDERS:\n'
     'Arrange the entire logistics of moving goods: Booking shipping space, documentation, insurance, customs clearance, delivery.\n\n'
     'STEVEDORES:\n'
     'Workers who load and unload ships. Physical work at the quay.\n\n'
     'SLRA CUSTOMS OFFICERS:\n'
     'Government officers who control import and export, collect duties and taxes.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Visit Freetown port area (Aberdeen Wharf or QE2 Quay).\n'
     'Observe the activity: Trucks, containers, ships.\n'
     'Identify: Where are goods being offloaded? Where are they stored? Where do trucks collect?\n'
     'Ask someone working there about their role.'),

    (2, 'Customs Procedures and Documentation', 30,
     'Customs is the gateway through which all imports must pass. Understanding the process is essential for anyone in logistics.\n\n'
     'WHAT IS CUSTOMS CLEARANCE?\n'
     'When goods arrive in Sierra Leone, they must be declared to customs (SLRA).\n'
     'Duties (import taxes) are calculated and paid.\n'
     'Only after clearance can goods leave the port and enter the country.\n'
     'Goods stuck in port cost demurrage (daily storage fees) — expensive.\n'
     'Speed and accuracy in customs clearance saves importers significant money.\n\n'
     'THE ASYCUDA SYSTEM:\n'
     'ASYCUDA World is the electronic customs management system used in Sierra Leone.\n'
     'All import and export declarations are filed electronically through ASYCUDA.\n'
     'Clearing agents must be trained and licensed to use ASYCUDA.\n'
     'Training is available through SLRA.\n\n'
     'KEY DOCUMENTS IN IMPORT CLEARANCE:\n\n'
     'BILL OF LADING (BL):\n'
     'Document issued by the shipping line. Proves ownership of the cargo.\n'
     'The holder of the original BL can claim the goods.\n'
     'Original BL must be presented to the shipping agent to get the Delivery Order.\n\n'
     'DELIVERY ORDER (DO):\n'
     'Issued by the shipping agent after original BL is surrendered and freight paid.\n'
     'Allows goods to be released from the shipping line\'s custody.\n\n'
     'COMMERCIAL INVOICE:\n'
     'Shows what was sold, by whom, to whom, and at what price.\n'
     'Customs uses this to calculate duty.\n\n'
     'PACKING LIST:\n'
     'Detailed list of every item in each package or container.\n'
     'Allows customs to check contents against declaration.\n\n'
     'CERTIFICATE OF ORIGIN:\n'
     'Shows which country goods were made in.\n'
     'Affects duty rates (some countries have preferential rates).\n\n'
     'IMPORT DECLARATION (ASYCUDA ENTRY):\n'
     'Filed by the clearing agent in ASYCUDA.\n'
     'Declares all goods, their value, origin and applicable duty tariff.\n\n'
     'DUTY CALCULATION:\n'
     'Duty is typically a percentage of the CIF value (Cost + Insurance + Freight).\n'
     'Rates vary by product category. Check the Sierra Leone Customs Tariff.\n'
     'Example: Rice may have 10% duty. Luxury goods may have 30% or more.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Research: What is the import duty rate for rice in Sierra Leone?\n'
     'What is the duty rate for second-hand clothing?\n'
     'What is the duty rate for motor vehicles?\n'
     'Where can you find the complete Sierra Leone Customs Tariff?'),

    (3, 'Freight Forwarding and Supply Chain', 20,
     'Freight forwarding is the management of the entire logistics process from seller to buyer.\n\n'
     'WHAT A FREIGHT FORWARDER DOES:\n'
     'Receives instructions from exporter or importer.\n'
     'Books space on a ship (or aircraft for air freight).\n'
     'Arranges collection of goods from the seller.\n'
     'Prepares and checks all shipping documents.\n'
     'Arranges cargo insurance.\n'
     'Tracks the shipment from origin to destination.\n'
     'Arranges customs clearance at destination.\n'
     'Arranges delivery to the importer\'s warehouse.\n\n'
     'CONTAINER TYPES:\n'
     '20 foot container (1 TEU): Approximately 33 cubic metres. Common for smaller shipments.\n'
     '40 foot container (2 TEU): Approximately 67 cubic metres. Most common for larger shipments.\n'
     'Reefer container: Refrigerated. For perishable goods.\n'
     'Open top: For machinery or cargo too tall for standard containers.\n'
     'Flat rack: For oversized machinery or vehicles.\n\n'
     'INCOTERMS:\n'
     'International terms defining who pays for what stage of shipping.\n'
     'EXW (Ex Works): Buyer pays everything from seller\'s factory.\n'
     'FOB (Free On Board): Seller pays to load on ship at origin port. Buyer pays from there.\n'
     'CIF (Cost Insurance Freight): Seller pays to destination port including insurance.\n'
     'DDP (Delivered Duty Paid): Seller delivers to buyer\'s door, duty paid. Buyer pays nothing more.\n\n'
     'Understanding Incoterms is essential for calculating total import cost.\n'
     'A CIF price includes freight and insurance. An FOB price does not — you must add these.\n\n'
     'CARGO TRACKING:\n'
     'All major shipping lines have online tracking systems.\n'
     'Enter container number or Bill of Lading number to track position.\n'
     'Maersk, MSC and others have mobile apps for tracking.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Visit a freight forwarding or clearing company in Freetown.\n'
     'Ask them to explain their process for clearing one container.\n'
     'What documents do they need from the importer?\n'
     'How long does clearance typically take? What are the main costs?'),

    (4, 'Warehousing and Transport', 15,
     'After goods are cleared, they must be stored and delivered. Warehousing and transport are major employment sectors.\n\n'
     'PORT WAREHOUSING:\n'
     'Transit shed: Covered storage at or near the port for goods awaiting clearance.\n'
     'Container yard (CY): Open storage for full containers.\n'
     'Container freight station (CFS): Where Less than Container Load (LCL) cargo is sorted.\n'
     'Demurrage: Daily charge for containers left at port beyond free storage period.\n'
     'The longer goods stay in port, the more demurrage accumulates.\n'
     'Good clearing agents prioritise speed to minimise demurrage for their clients.\n\n'
     'PRIVATE WAREHOUSING:\n'
     'Importers or third-party logistics companies store goods in private warehouses.\n'
     'Key requirements: Security, fire protection, pest control, inventory management.\n'
     'Warehouse jobs: Storekeeper, inventory controller, security, forklift operator.\n\n'
     'TRANSPORT FROM PORT:\n'
     'Trucks and lorries collect containers from the port.\n'
     'Transport to: Importer\'s warehouse, distribution centres, upcountry destinations.\n'
     'Truck drivers, mates (assistants), loaders and dispatchers are all needed.\n\n'
     'COLD CHAIN:\n'
     'Refrigerated transport for fish, dairy, medicine and other perishables.\n'
     'Freetown has a growing demand for cold chain services as the food sector develops.\n'
     'Refrigerated truck driver is a specialised and well-paid role.\n\n'
     'INVENTORY MANAGEMENT:\n'
     'Tracking what stock is in a warehouse, where it is and how much there is.\n'
     'Manual systems: Bin cards, tally sheets.\n'
     'Electronic systems: Warehouse Management System (WMS) software.\n'
     'Accuracy is critical — shortages and overages both cost money.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Visit a warehouse in Freetown (ask permission first).\n'
     'Observe: How is stock organised? How are deliveries recorded? What security measures exist?\n'
     'Ask the warehouse manager: What skills do they look for when hiring?'),

    (5, 'Career Pathways in Port and Logistics', 15,
     'Port and logistics offer stable, well-paid career pathways for Sierra Leoneans at all education levels.\n\n'
     'ENTRY LEVEL JOBS:\n'
     'Stevedore / dock worker: Physical loading and unloading. Strength and reliability needed.\n'
     'Warehouse labourer: Loading and offloading trucks and containers.\n'
     'Driver\'s mate: Assists truck driver. Learn routes, documentation, vehicle care.\n'
     'Security officer at port or warehouse.\n\n'
     'TECHNICAL AND SKILLED JOBS:\n'
     'Forklift operator: Requires certification. Higher pay.\n'
     'Customs agent assistant: Working with a licensed clearing agent, learning the trade.\n'
     'Shipping operations clerk: Data entry, document processing, container tracking.\n'
     'Freight forwarding assistant: Supporting coordination of shipments.\n\n'
     'PROFESSIONAL LEVEL:\n'
     'Licensed clearing agent: Requires SLRA licensing examination. Significant income potential.\n'
     'Freight forwarder: Arranges complete logistics solutions for importers and exporters.\n'
     'Logistics manager: Manages warehousing, transport and distribution operations.\n'
     'Port operations officer: SLPA employment. Manages berth allocations, vessel calls.\n\n'
     'GETTING YOUR FIRST JOB:\n'
     'Visit clearing agent offices in the port area: Aberdeen, Cline Town, Cotton Tree.\n'
     'Many clearing agents will take on assistants who show initiative and willingness to learn.\n'
     'Offer to work as an unpaid apprentice initially if needed — the experience and training is worth it.\n'
     'Complete ASYCUDA training when the opportunity arises — this certification opens doors.\n\n'
     'PROFESSIONAL DEVELOPMENT:\n'
     'Chartered Institute of Logistics and Transport (CILT): Professional body offering qualifications in transport and logistics. Internationally recognised.\n'
     'SLRA training programmes: Customs procedures and ASYCUDA.\n'
     'International Chamber of Commerce: Incoterms and trade finance courses available online.\n\n'
     'PRACTICAL EXERCISE:\n'
     'Research: Where are the main clearing agent offices in Freetown?\n'
     'Identify three companies you could approach for an entry-level opportunity.\n'
     'Write a short introduction letter explaining your interest in the industry and what you offer.\n'
     'This letter, combined with what you have learned in this course, is your starting point.'),
])

print('\n' + '='*60)
from courses.models import Course
for title in [
    'Fishing and Fish Processing',
    'Understanding the Leone and Inflation',
    'Krio for Business Communication',
    'Port and Logistics Work',
]:
    try:
        c = Course.objects.get(title=title)
        print(f'OK: {c.title} — {c.lessons.count()} lessons')
    except Course.DoesNotExist:
        print(f'NOT FOUND: {title}')

print(f'\nTotal courses: {Course.objects.count()}')
print(f'Total lessons: {sum(c.lessons.count() for c in Course.objects.all())}')