import os, django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'skillscontinua_core.settings')
django.setup()

from courses.models import Course
from certifications.models import Quiz, Question, Answer

def create_quiz(course_title, quiz_title, description, time_limit, questions_data):
    try:
        course = Course.objects.get(title=course_title)
        quiz, created = Quiz.objects.get_or_create(
            course=course,
            defaults={'title': quiz_title, 'description': description,
                      'pass_mark': 60, 'time_limit_minutes': time_limit, 'is_active': True}
        )
        if not created:
            quiz.title = quiz_title
            quiz.save()
            quiz.questions.all().delete()
        for order, (qtext, qtype, explanation, answers) in enumerate(questions_data, 1):
            q = Question.objects.create(quiz=quiz, question_text=qtext, question_type=qtype,
                                        order=order, marks=1, explanation=explanation)
            for atext, correct in answers:
                Answer.objects.create(question=q, answer_text=atext, is_correct=correct)
        print(f'OK: {course_title} — {quiz.questions.count()} questions')
    except Course.DoesNotExist:
        print(f'NOT FOUND: {course_title}')

# ============================================================
# ALL REMAINING 28 COURSES — 5-10 QUESTIONS EACH
# ============================================================

create_quiz('Car Repairs and Maintenance', 'Car Repairs and Maintenance — Final Assessment',
'This assessment tests your knowledge of car systems, maintenance and diagnosis.',
20, [
('What is the primary function of engine oil?', 'multiple_choice', 'Engine oil lubricates all moving metal surfaces, reducing friction and wear. It also cools components water cannot reach, cleans by carrying debris to the filter, protects against corrosion, and seals gaps between piston rings and cylinder walls. Without oil, an engine seizes within minutes.', [('Fuel the engine in emergencies', False), ('Lubricate, cool, clean and protect all moving engine components', True), ('Only lubricate the gearbox', False), ('Cool the engine externally', False)]),
('A car pulls strongly to the left when braking. Most likely cause?', 'multiple_choice', 'Brake pull indicates unequal braking force between left and right wheels — usually a stuck caliper, uneven pad wear, contaminated pads or collapsed brake hose. This is a serious safety issue requiring immediate investigation.', [('Steering wheel not centred', False), ('Unequal braking force — likely caliper, pad or hose fault', True), ('Tyre pressure difference', False), ('Wheel alignment issue', False)]),
('What does OBD-II allow a mechanic to do?', 'multiple_choice', 'OBD-II (On-Board Diagnostics) monitors all engine and emissions systems and stores fault codes (DTCs). A basic reader reads these codes, allowing fast accurate diagnosis. Every modern mechanic needs one.', [('Manually adjust fuel injection timing', False), ('Read stored fault codes for fast electronic diagnosis', True), ('Reprogram the engine control unit', False), ('Measure engine oil pressure directly', False)]),
('Why must timing belts be replaced at the manufacturer interval?', 'multiple_choice', 'If the timing belt snaps, pistons and valves collide — causing catastrophic engine damage costing far more than belt replacement. Many engines are interference engines where this damage is immediate and total.', [('It affects fuel efficiency', False), ('A broken belt causes catastrophic engine damage — replacement is far cheaper', True), ('It affects the electrical system', False), ('Only older vehicles need timing belt changes', False)]),
('What is wheel alignment?', 'multiple_choice', 'Wheel alignment sets the angles at which tyres contact the road. Incorrect alignment causes uneven tyre wear, increased fuel consumption, poor handling and pulling to one side. Check after any significant impact and with every tyre change.', [('Balancing wheel weights', False), ('Setting correct tyre angles for even wear and good handling', True), ('Ensuring all tyres are at the same pressure', False), ('Centring the steering wheel', False)]),
])

create_quiz('Catering and Food Processing', 'Catering and Food Processing — Final Assessment',
'This assessment covers food safety, menu costing, event catering and food preservation.',
20, [
('What is the food temperature danger zone?', 'multiple_choice', 'Bacteria multiply rapidly between 5°C and 63°C. Hot food must be kept above 63°C and cold food below 5°C. Never leave cooked food at room temperature for more than 2 hours. In West Africa\'s heat, this time is even shorter.', [('0°C to 100°C', False), ('5°C to 63°C — the zone of rapid bacterial multiplication', True), ('20°C to 80°C', False), ('Below 0°C only', False)]),
('How do you calculate food cost percentage?', 'multiple_choice', 'Food cost percentage = (food cost per portion divided by selling price) times 100. A healthy food cost percentage is 25-35% of the selling price. If your food cost is 40% or more, your prices are too low or your costs are too high.', [('Selling price divided by food cost', False), ('Food cost divided by selling price, times 100', True), ('Total ingredients cost divided by number of meals', False), ('Profit divided by revenue times 100', False)]),
('What is the most important personal hygiene requirement for a food handler?', 'multiple_choice', 'Thorough handwashing with soap for at least 20 seconds before handling food, after using the toilet, after handling raw meat, and after touching hair or face. Most foodborne illness transmission starts with contaminated hands.', [('Wearing a uniform', False), ('Thorough handwashing with soap for 20 seconds at critical points', True), ('Wearing gloves at all times', False), ('Tying back long hair', False)]),
('What deposit should you require before catering an event?', 'multiple_choice', 'A minimum 50% deposit before purchasing any ingredients or beginning preparation protects you from clients who cancel after you have incurred costs. Always use written contracts specifying the menu, guest number, price and cancellation terms.', [('No deposit — trust builds the relationship', False), ('Minimum 50% deposit before purchasing any ingredients', True), ('10% to show goodwill', False), ('Full payment upfront always', False)]),
('What is the Chorkor kiln used for?', 'multiple_choice', 'The Chorkor kiln is an improved fish smoking system using stacked trays that can be rotated during smoking. It uses less fuel than traditional drum smoking, has higher capacity, and produces more consistent quality. Widely used in Ghana and increasingly in Sierra Leone.', [('Baking bread for large events', False), ('Improved fish smoking with stacked trays — more efficient than traditional drum smoking', True), ('Deep frying fish in large quantities', False), ('Drying vegetables using solar heat', False)]),
])

create_quiz('Crop Farming and Agribusiness', 'Crop Farming and Agribusiness — Final Assessment',
'This assessment covers soil management, crop production, pest control and agribusiness principles.',
20, [
('What is the critical weed-free period for most crops?', 'multiple_choice', 'The first 4-6 weeks after planting are the critical weed-free period. Weeds competing during this window can reduce yield by 50-80%. Miss this period and no amount of later weeding fully recovers the lost yield potential.', [('The last 2 weeks before harvest', False), ('The first 4-6 weeks after planting — missing this window causes severe yield loss', True), ('Only during flowering', False), ('Weeding is not critical if rainfall is adequate', False)]),
('What does NPK on a fertiliser bag mean?', 'multiple_choice', 'NPK stands for Nitrogen (N), Phosphorus (P) and Potassium (K) — the three primary plant nutrients. N promotes leafy green growth, P promotes root and flower development, K promotes overall plant health and disease resistance. The numbers (e.g. 15:15:15) show the percentage of each nutrient in the bag.', [('Natural, Pure, Known — indicating organic certification', False), ('Nitrogen, Phosphorus, Potassium — the three primary plant nutrients', True), ('Neutral, Productive, Kinetic — soil quality ratings', False), ('The three soil types the fertiliser is suitable for', False)]),
('What is crop rotation and why is it practiced?', 'multiple_choice', 'Crop rotation means growing different crops in the same field in successive seasons. It breaks pest and disease cycles (pests that feed on one crop starve when a different crop follows), improves soil fertility (legumes fix nitrogen), and reduces erosion. Growing the same crop year after year depletes specific nutrients and allows pest populations to build up.', [('Rotating crops on a conveyor for even distribution', False), ('Growing different crops in succession to break pest cycles and maintain soil health', True), ('Moving crops to different fields each day', False), ('Rotating between two identical crops for consistency', False)]),
('What is post-harvest loss and why does it matter?', 'multiple_choice', 'Post-harvest losses in West Africa average 30-50% of produce — food grown but never consumed or sold. Causes: poor storage (heat, moisture, pests), mechanical damage during handling, inadequate transport. Reducing post-harvest loss is as important as increasing production — it increases income without additional farming cost.', [('Loss of profits after the harvest is sold at market', False), ('Food produced but lost before reaching consumers — averaging 30-50% in West Africa', True), ('The reduction in crop yield compared to previous years', False), ('Soil nutrients lost after harvesting a crop', False)]),
('What is FIFO and why is it important in crop storage?', 'multiple_choice', 'First In, First Out — sell or use the oldest stock before the newer. Older grain, vegetables or processed products deteriorate over time. FIFO prevents old stock being buried under new stock and going bad unnoticed. Critical for all perishable agricultural produce.', [('Find and Identify Faulty Output', False), ('First In First Out — use oldest stock first to prevent deterioration', True), ('Farm Input and Farming Output — a cost tracking system', False), ('Freshness Index for Output — a quality grading standard', False)]),
])

create_quiz('Event Planning and Management', 'Event Planning and Management — Final Assessment',
'This assessment covers event planning, budgeting, vendor management and on-day execution.',
20, [
('What document must a professional event planner always have on event day?', 'multiple_choice', 'A run-of-show document lists every element of the event in precise time order — vendor arrival times, setup schedule, guest arrival, programme sequence, each element to the minute. Without it, an event has no reliable structure and things will be missed or happen in the wrong order.', [('A guest list only', False), ('A run-of-show document listing every element in precise time order', True), ('The venue hire contract', False), ('The client\'s contact number', False)]),
('What is the minimum deposit that should be collected when a client signs an event contract?', 'multiple_choice', '50% deposit at contract signing protects the planner from clients who book and cancel after significant preparation work has begun. It also filters out unserious enquiries. The balance should be due before or on the event day.', [('10% — just to confirm the booking', False), ('50% at signing — the balance before or on the event day', True), ('100% upfront for all events', False), ('No deposit — this builds client trust', False)]),
('What should you do if a key vendor cancels 2 hours before an event?', 'multiple_choice', 'Contact your backup vendor immediately — which is why maintaining a list of alternative vendors for every category is essential. Inform the client calmly with your solution already prepared. Never tell a client about a problem without already having a solution.', [('Cancel the event and refund the client', False), ('Contact backup vendors immediately and inform client with your solution ready', True), ('Tell the client the vendor cancelled and let them solve it', False), ('Proceed without the vendor and hope nobody notices', False)]),
('What is a vendor briefing?', 'multiple_choice', 'A vendor briefing is a pre-event communication (in person, by phone or written) confirming with every vendor: arrival time, what they need from the venue (power, tables, access), setup time, contact number on the day, and what happens if there is a problem. Vendors who are not briefed make mistakes and arrive late.', [('The invoice the vendor sends after the event', False), ('Pre-event confirmation of arrival times, requirements, contacts and contingency plans', True), ('The list of menu items provided by the caterer', False), ('A legal agreement between planner and vendor', False)]),
('What skill separates excellent event planners from good ones?', 'multiple_choice', 'Calm problem-solving under pressure. Every event has problems — deliveries late, equipment failing, guests arriving early, weather changing. The planner who stays calm, finds solutions quickly and prevents guests from noticing is invaluable. Panicking, visibly stressing or passing problems to the client is what inexperienced planners do.', [('Perfect planning that prevents all problems', False), ('Calm problem-solving — finding solutions quickly without guests noticing', True), ('Having the largest vendor network in the city', False), ('Charging the highest prices in the market', False)]),
])

create_quiz('Fishing and Fish Processing', 'Fishing and Fish Processing — Final Assessment',
'This assessment covers Sierra Leone fishing methods, fish quality, smoking and the economics of the fishing livelihood.',
20, [
('What is the most commercially important fish in Sierra Leone waters?', 'multiple_choice', 'Bonga (Ethmalosa fimbriata) is the most important fish by volume in Sierra Leone. It schools near the surface, is caught in large quantities by beach seine and cast nets, and is widely smoked and traded inland. Bonga smoked fish is a staple protein source across Sierra Leone.', [('Snapper', False), ('Bonga — the most important fish by volume, widely smoked and traded', True), ('Barracuda', False), ('Tilapia', False)]),
('How can you tell fresh fish from stale fish?', 'multiple_choice', 'Fresh fish has bright clear eyes, red gills, firm flesh and a mild sea smell. Stale fish has cloudy sunken eyes, grey-brown gills, soft flesh and a strong unpleasant smell. Eyes and gills are the first things buyers and sellers should check. Stale fish must not be sold as fresh.', [('Fresh fish is always lighter in colour', False), ('Fresh: bright eyes, red gills, firm flesh, mild smell; stale: cloudy eyes, soft flesh, strong smell', True), ('Only smell determines freshness — eyes are not reliable', False), ('Fresh fish floats; stale fish sinks', False)]),
('What is the correct temperature ratio when icing fish?', 'multiple_choice', 'Use approximately 1kg of ice per 1kg of fish for effective preservation. Ice reduces bacterial growth by cooling the fish rapidly. Without ice in Sierra Leone\'s heat, fish degrades within 2-4 hours of landing. Ice is available from ice factories in Freetown and major towns.', [('1 bucket of ice for every 10 kg of fish', False), ('Approximately 1kg of ice per 1kg of fish for effective preservation', True), ('Ice is not necessary if fish is kept in the shade', False), ('Cover fish with salt instead of ice for better results', False)]),
('In fish smoking, what is the purpose of the second (cold smoking) phase?', 'multiple_choice', 'After the initial hot smoking phase kills bacteria and partially cooks the fish, the second cold smoking phase (lower heat, longer duration) drives out remaining moisture, further drying the fish. This extended drying is what gives smoked fish its extended shelf life of weeks.', [('To add more flavour by increasing the temperature', False), ('To dry the fish further by driving out remaining moisture — extending shelf life', True), ('To cool the fish rapidly before packaging', False), ('To add a second layer of smoke flavour', False)]),
('What is the fishing cooperative\'s role in Sierra Leone coastal communities?', 'multiple_choice', 'Fishing cooperatives allow members to: pool resources to purchase equipment (engines, nets, boats), access group savings and microfinance loans, collectively negotiate better prices with traders, access government fisheries programmes and subsidies, and share knowledge and training. Individual fishers have far less bargaining power than organised cooperatives.', [('Cooperatives only organise social events for fishing families', False), ('Pool resources, access finance, negotiate better prices and access government programmes', True), ('Cooperatives control all fishing in Sierra Leone under government licence', False), ('Only large commercial fishing operations need cooperatives', False)]),
])

create_quiz('Hair and Beauty', 'Hair and Beauty — Final Assessment',
'This assessment covers professional hair services, beauty treatments, hygiene and salon business management.',
20, [
('What is traction alopecia and how is it caused?', 'multiple_choice', 'Traction alopecia is hair loss caused by constant pulling tension on hair follicles — from tight braiding, weaves, extensions or hair tied too tightly. The follicles become damaged and eventually stop producing hair, causing permanent bald patches particularly at the hairline. Braiders must always use appropriate, not excessive, tension.', [('Hair loss from chemical relaxer applied incorrectly', False), ('Hair loss from constant pulling tension on follicles — caused by too-tight braiding or extensions', True), ('Temporary hair shedding after illness', False), ('Hair breakage from heat styling tools', False)]),
('What is a contraindication for hair relaxing?', 'multiple_choice', 'Never relax if: the client has open scalp sores or scratches (chemical will burn severely), the hair was relaxed within the last 6-8 weeks (overlap causes breakage), or the hair is already severely damaged. These are absolute contraindications — proceeding causes serious harm to the client.', [('Client has natural hair that has never been relaxed before', False), ('Open scalp sores, relaxer applied within 6-8 weeks, or severely damaged hair', True), ('Client is requesting a stronger relaxer than their last service', False), ('The weather is hot and humid', False)]),
('Why must tools be sanitised between clients?', 'multiple_choice', 'Tools that contact skin or hair can transfer: ringworm (tinea capitis), head lice, scalp infections (seborrheic dermatitis), hepatitis B (if skin is broken by scissors or razors). Sanitising between every client prevents cross-contamination. This is both a hygiene requirement and a legal obligation in most jurisdictions.', [('To make the salon look professional to new clients', False), ('To prevent transfer of infections including ringworm, lice and scalp conditions between clients', True), ('To prevent product buildup on tools', False), ('Chemical disinfectants make tools last longer', False)]),
('What is the correct order for a professional manicure?', 'multiple_choice', 'Professional manicure sequence: remove old polish, shape nails, soak hands, push back and clean cuticles, moisturise, apply base coat, apply colour (two thin coats), apply top coat, clean up edges. The base coat improves adhesion and prevents staining of the nail. The top coat adds shine and extends wear.', [('Apply colour first, then base coat, then top coat', False), ('Remove polish, shape, soak, cuticles, moisturise, base coat, colour, top coat', True), ('Cuticles should be cut, not pushed back, for a clean result', False), ('Top coat is optional — it only adds shine not durability', False)]),
('How should a salon owner build a loyal client base?', 'multiple_choice', 'Consistent quality and genuine personal relationships are the foundation of salon loyalty. Know clients\' names, remember their preferences and service history. Follow up after services. Treat every complaint as an opportunity to retain a client. Special occasion reminders (text before graduations, weddings) show you remember them. In West African salon culture, the personal relationship between stylist and client is the primary reason clients stay or leave.', [('Offer the lowest prices in the neighbourhood', False), ('Know clients by name, remember preferences, follow up and build genuine personal relationships', True), ('Advertise on social media constantly to attract new clients', False), ('Specialise in only one service to become the best at it', False)]),
])

create_quiz('Heavy Plant and Equipment Operation', 'Heavy Plant and Equipment Operation — Final Assessment',
'This assessment covers heavy plant types, safety, operation and career pathways in construction.',
20, [
('What is the first check before operating any piece of heavy plant?', 'multiple_choice', 'A pre-operational inspection: engine oil, coolant, fuel levels; hydraulic fluid and leaks; tyre or track condition; lights and horn; attachment pins secured; fire extinguisher present. Only after completing this inspection should the operator start the machine. This is both a legal requirement and a career-protecting habit.', [('Start the engine and listen for unusual sounds', False), ('Complete a pre-operational inspection of all fluid levels, tracks, attachments and safety equipment', True), ('Check the fuel level only — other items are the mechanic\'s responsibility', False), ('Radio the supervisor to confirm it is safe to start', False)]),
('What does VLOS mean in excavator operation?', 'multiple_choice', 'In excavator operation, VLOS is not applicable (that is a drone term). The equivalent principle is knowing your working radius and swing zone. The key safety rule for excavators is the 10 metre kill zone — no pedestrians within 10 metres of an operating excavator without a banksman controlling their access.', [('Visual Line of Sight — the operator must see the bucket at all times', False), ('Maintaining a safe 10 metre zone around the excavator — no pedestrians without banksman control', True), ('Verified Load on Site — confirming the ground can bear the machine weight', False), ('Vehicle Limitation on Speed — the maximum travel speed on site', False)]),
('What is a banksman?', 'multiple_choice', 'A banksman is a trained ground worker who guides vehicle and plant movements in areas where the operator cannot see clearly — near excavations, when reversing, when working near other workers or structures. The banksman uses standardised hand signals. No heavy plant should reverse or work in blind areas without a banksman present.', [('The person responsible for financial records on a construction site', False), ('A trained ground worker who guides plant movements in areas of restricted visibility', True), ('The operator who sits in the cab of a crane', False), ('A safety officer responsible for site inspections', False)]),
('What is the most common cause of heavy plant accidents on construction sites?', 'multiple_choice', 'Being struck by moving plant is the most common fatal accident category on construction sites. People working near excavators, dozers and dumpers who are not seen by operators. The solution: exclusion zones, banksmen, high-visibility clothing for all ground workers, and operators conducting 360° checks before any movement.', [('Mechanical failure of the machine', False), ('Ground workers being struck by plant they did not see coming', True), ('Operators working excessive hours', False), ('Incorrect fuel type causing engine failure', False)]),
('How do operators typically start a career in heavy plant?', 'multiple_choice', 'Most heavy plant operators begin as labourers or helpers on construction sites, observing operators, demonstrating reliability and initiative. Supervisors notice workers who show interest and ability. Formal training and certification follow — either through an employer or a training school. There is no substitute for starting on site and building trust through consistent, careful work.', [('Direct application for operator positions without prior site experience', False), ('Starting as a labourer, demonstrating initiative, gaining operator trust, then formal training', True), ('Completing a university engineering degree first', False), ('Purchasing your own machine and hiring it out to construction companies', False)]),
])

create_quiz('Krio for Business Communication', 'Krio for Business Communication — Final Assessment',
'This assessment tests your practical knowledge of Krio for market trading and business communication in Sierra Leone.',
15, [
('What does "Aw di bodi?" mean in Krio?', 'multiple_choice', 'Aw di bodi? means "How are you?" — literally "How is the body?" It is the most common Krio greeting. The standard response is "Di bodi fine" (The body is fine). This greeting is used in all informal and many business settings across Sierra Leone.', [('Where are you going?', False), ('How are you? — the most common Krio greeting', True), ('What do you want?', False), ('Are you well today?', False)]),
('How do you say "How much does this cost?" in Krio?', 'multiple_choice', 'Aw much dis kos? is the standard price inquiry in market Krio. Learning this phrase and the number system is the foundation of trading in any Sierra Leonean market. Sellers respond with Di pris na... (The price is...).', [('Wetin yu get?', False), ('Aw much dis kos? — how much does this cost?', True), ('Na faynal pris?', False), ('Gi mi wan', False)]),
('What does "Tɔ much!" mean?', 'multiple_choice', 'Tɔ much! means "Too much!" — the standard opening response when bargaining in a West African market. It signals that you consider the price too high and opens the negotiation. This phrase is used across Sierra Leone in all market contexts.', [('Thank you very much!', False), ('Too much! — the standard market bargaining opening', True), ('I want more!', False), ('That is correct!', False)]),
('What does "Tenki plenti" mean?', 'multiple_choice', 'Tenki plenti means "Thank you very much." Tenki alone means "Thank you." Adding plenti (plenty/much) intensifies it. Expressions of gratitude are important in West African business culture — they build the personal warmth that makes customer relationships last.', [('Thank you a little', False), ('Thank you very much', True), ('Many thanks to everyone', False), ('Thank you for coming', False)]),
('How would you ask someone to speak slowly in Krio?', 'multiple_choice', 'Tɔk slɔ slɔ means "Speak slowly." This is an essential phrase for Krio learners — Sierra Leoneans are patient and friendly when someone is learning, especially when they ask for slower speech. Combined with A nor andastand (I do not understand), these two phrases allow any learner to continue a conversation despite gaps in knowledge.', [('Tok kwik kwik', False), ('Tɔk slɔ slɔ — speak slowly', True), ('Stop tok', False), ('Aw yu tok?', False)]),
])

create_quiz('Livestock Farming and Animal Husbandry', 'Livestock Farming and Animal Husbandry — Final Assessment',
'This assessment covers poultry, goat and livestock management for small-scale West African farmers.',
20, [
('What vaccination must poultry receive to prevent Newcastle Disease?', 'multiple_choice', 'Newcastle Disease (ND) is the most dangerous viral disease of poultry in West Africa. It kills entire flocks within days. Vaccination at Day 7, Day 21, and then monthly prevents ND. A single missed vaccination round leaves the flock vulnerable. There is no treatment — only prevention through vaccination.', [('Gumboro vaccine', False), ('Newcastle Disease vaccine — given at Day 7, Day 21 and monthly thereafter', True), ('Coccidiosis vaccine', False), ('Marek\'s Disease vaccine', False)]),
('What is the feed conversion ratio (FCR) in broiler farming?', 'multiple_choice', 'FCR is the amount of feed required to produce 1kg of liveweight gain. A typical broiler FCR is 2:1 — 2kg of feed per 1kg of growth. Lower FCR = more efficient, more profitable. FCR is affected by: feed quality, disease, housing conditions and breed. Monitoring FCR tells you whether your flock is performing as expected.', [('The ratio of female to male chicks in a batch', False), ('Feed required per kg of liveweight gain — typically 2:1 for broilers', True), ('The proportion of feed cost to total production cost', False), ('The conversion rate of grains to processed animal feed', False)]),
('Why are goats described as browsers rather than grazers?', 'multiple_choice', 'Goats prefer to eat leaves, shrubs, bark, herbs and browse (tree material) rather than grass. This makes them well-suited to forested and scrub areas where cattle cannot be raised. Goats also select quality feed — they will not eat dirty or contaminated material. This selective feeding makes their nutrition management different from cattle and sheep.', [('Because they graze exclusively in groups called browsers', False), ('Goats prefer leaves and shrubs over grass — they are selective about feed quality', True), ('Because they move quickly while eating rather than staying in one place', False), ('The term is historical — modern goats will eat anything', False)]),
('What is the most important disease challenge in goat farming?', 'multiple_choice', 'Internal parasites (stomach worms, lungworms) are the single biggest health challenge in goat farming across West Africa. They cause weight loss, anaemia, poor growth and death. Regular strategic deworming is essential. Resistance to dewormers is growing — rotate between different anthelmintic classes and always dose accurately.', [('Newcastle Disease — common in both poultry and goats', False), ('Internal parasites — worms are the biggest health challenge requiring regular strategic deworming', True), ('Foot and mouth disease', False), ('Rabies from dog bites', False)]),
('When is the best time to sell livestock for maximum price?', 'multiple_choice', 'Livestock prices peak dramatically before major festivals and religious celebrations — particularly Eid al-Adha (massive demand for rams and goats, prices triple or more), Christmas and New Year (high demand for poultry and pigs), and Ramadan. Plan production cycles to have animals at market weight and condition just before these peak demand periods.', [('Always sell immediately after the animals reach market weight', False), ('Before major festivals and religious celebrations when demand and prices peak', True), ('During the rainy season when farmers have more cash', False), ('Price is constant throughout the year — timing does not matter', False)]),
])

create_quiz('Market Trading — Buying and Reselling for Profit', 'Market Trading — Final Assessment',
'This assessment tests the core principles of profitable market trading.',
20, [
('What is the TRUE cost of goods for a market trader?', 'multiple_choice', 'True cost = purchase price + transport + market and toll fees + porterage + storage + expected losses (spoilage/theft) + mobile money transaction fees + loan interest if applicable + time cost. Most traders only subtract the purchase price, systematically underestimating their real costs and overestimating their profit.', [('Only the price paid to the supplier', False), ('Purchase price plus ALL costs to bring goods to the point of sale', True), ('The price similar goods sell for at other stalls', False), ('Purchase price plus transport only', False)]),
('Gross margin versus net margin — what is the difference?', 'multiple_choice', 'Gross margin = (selling price minus purchase price) divided by selling price times 100. Net margin = (selling price minus ALL costs) divided by selling price times 100. Net margin is your real profit percentage. Most traders confuse gross margin with profit — a dangerous mistake that leads to underpricing.', [('They are the same calculation with different names', False), ('Gross margin excludes most costs; net margin includes all costs — net is the real profit percentage', True), ('Gross is for large traders; net is for small traders', False), ('Gross margin is more important for planning', False)]),
('A trader buys goods for Le 100,000 including all costs and sells for Le 130,000. What is the markup?', 'multiple_choice', 'Markup = (profit divided by cost) times 100 = (30,000 divided by 100,000) times 100 = 30%. The profit margin on sales = (30,000 divided by 130,000) times 100 = 23%. Understanding the difference between markup on cost and margin on sales prevents pricing errors.', [('23%', False), ('30%', True), ('13%', False), ('3%', False)]),
('What is the most powerful negotiating tool when buying from suppliers?', 'multiple_choice', 'Volume is the single most powerful negotiating tool. Suppliers give their best prices to buyers who purchase the most. Even if you cannot buy in large quantities alone, partnering with other traders to buy jointly unlocks bulk discounts. Cash payment (versus credit) is the second most powerful negotiation tool.', [('Being friends with the supplier personally', False), ('Volume — buying more unlocks better prices, or partnering with other traders for joint buying', True), ('Threatening to buy from a competitor', False), ('Paying with mobile money for a digital record', False)]),
('What should you do the moment your supplier raises their prices?', 'multiple_choice', 'Raise your selling prices immediately by at least the same percentage. Absorbing supplier price increases — even for one week — means you are selling for less real margin every day. There is a psychological barrier to raising prices, but your business depends on passing cost increases to customers promptly.', [('Wait to see if competitors raise prices first', False), ('Raise your selling price immediately by at least the same percentage', True), ('Absorb the increase for one month to maintain customer loyalty', False), ('Find a different product with more stable pricing', False)]),
])

create_quiz('Motorcycle and Tricycle Repairs', 'Motorcycle and Tricycle Repairs — Final Assessment',
'This assessment covers motorcycle and tricycle maintenance, electrical diagnosis and workshop management.',
20, [
('What is the recommended oil change interval for a motorcycle engine?', 'multiple_choice', 'Most small motorcycles require an oil change every 2,000 to 3,000 km or every 3 months, whichever comes first. For heavily used commercial motorcycles (okada running all day), the shorter interval is critical. Dirty, degraded oil causes accelerated engine wear and premature failure.', [('Every 10,000 km — the same as a car', False), ('Every 2,000-3,000 km or every 3 months for commercial bikes', True), ('Only when the oil looks dark', False), ('Once per year regardless of mileage', False)]),
('What does a fouled black spark plug indicate?', 'multiple_choice', 'A black sooty spark plug indicates an overly rich fuel mixture (too much fuel, not enough air) or oil burning. Possible causes: blocked air filter, stuck choke, worn piston rings or valve seals. Address the underlying cause before fitting a new plug — a new plug will foul again if the cause is not fixed.', [('The engine is running too lean', False), ('Rich mixture or oil burning — address the cause before replacing the plug', True), ('The plug needs a larger gap', False), ('Normal wear — just replace it', False)]),
('What is the correct chain tension for most motorcycles?', 'multiple_choice', 'Most motorcycle chains should have 20-30mm of free play measured at the mid-point between sprockets. Too tight causes bearing wear and chain breakage. Too loose causes slapping, jumping teeth and dangerous chain derailment. Adjust by loosening the rear axle nut and moving the wheel back, then re-checking alignment.', [('Chain should be completely tight with no slack', False), ('20-30mm of free play at the mid-point between sprockets', True), ('50-60mm of free play', False), ('Chain tension is factory-set and never requires adjustment', False)]),
('What is the most common electrical fault on small motorcycles?', 'multiple_choice', 'A blown fuse or a dead battery is the most common electrical fault. Always check the fuse first when electrical components stop working — it is the quickest diagnosis. Fuses are usually located under the seat or near the battery. Keep spare fuses in the workshop for every common motorcycle type.', [('Failed alternator requiring complete replacement', False), ('Blown fuse or flat battery — always check these first', True), ('Faulty CDI unit', False), ('Broken ignition coil', False)]),
('What is the business advantage of offering mobile repair service?', 'multiple_choice', 'Mobile repair service (going to breakdowns) commands a premium fee of 50-100% above normal rates because the customer is stranded and the convenience has high value. It differentiates you from workshop-only competitors, builds loyalty and generates word-of-mouth referrals. Equipment needed: basic tool kit, portable air compressor, common spare parts.', [('Mobile service eliminates the need for a workshop', False), ('Premium pricing for convenience — typically 50-100% above normal rates, builds loyalty', True), ('Mobile service is less profitable than workshop work', False), ('Customers prefer to bring bikes to workshops always', False)]),
])

create_quiz('Music - Instruments and Performance', 'Music — Instruments and Performance — Final Assessment',
'This assessment covers musical instruments, performance skills and the music industry.',
20, [
('What is the difference between a chordophone and a membranophone?', 'multiple_choice', 'Chordophones produce sound through vibrating strings: guitar, kora, violin, piano. Membranophones produce sound through a vibrating membrane (skin): drums, talking drum, djembe. This Hornbostel-Sachs classification system organises all instruments into: chordophones, membranophones, aerophones (wind), idiophones (body of instrument vibrates — xylophone, bell).', [('Chordophones are European instruments; membranophones are African', False), ('Chordophones have vibrating strings; membranophones have vibrating skins/membranes', True), ('Chordophones are played solo; membranophones are ensemble instruments', False), ('The terms refer to the material instruments are made from', False)]),
('What is stage fright and how do professional musicians manage it?', 'multiple_choice', 'Stage fright (performance anxiety) is the nervous response to performing before an audience — increased heart rate, shaking, dry mouth, memory blanks. Management strategies: thorough preparation (confidence from knowing the material), controlled breathing (activates the calm nervous system), positive visualisation (imagining a successful performance), experience (the more you perform, the less frightening it becomes). Stage fright affects virtually all performers — the goal is to use the energy productively, not eliminate it.', [('A physical illness that prevents professional performance', False), ('Normal anxiety managed through preparation, breathing, visualisation and accumulated experience', True), ('Something only beginners experience — professionals never get nervous', False), ('A sign that you are not suited for performance', False)]),
('What is the purpose of a sound check before a live performance?', 'multiple_choice', 'A sound check tests and balances all audio equipment before the audience arrives. The sound engineer adjusts: monitor levels (what performers hear on stage), front-of-house mix (what the audience hears), microphone positions and gains, feedback prevention (eliminating the piercing squeal), and equipment functionality. A good sound check means the performance sounds professional from the first note. Never skip a sound check.', [('To show the venue manager the setlist in advance', False), ('To test and balance all audio equipment and prevent feedback before the audience arrives', True), ('To practise the entire show one more time before the audience', False), ('Sound checks are only needed for large concerts', False)]),
('How does streaming revenue work for African musicians?', 'multiple_choice', 'Streaming platforms (Spotify, Apple Music, Boomplay, Audiomack) pay per stream — typically $0.003-$0.005 per stream. At this rate, 1 million streams generates approximately $3,000-$5,000. African artists receive lower rates than Western artists on many platforms due to market pricing differences. The key is: upload music to distribution platforms (DistroKid, TuneCore, Boomplay), build streaming numbers, supplement with live performance income and merchandise.', [('Musicians receive 100% of subscription revenue from platforms', False), ('Platforms pay per stream (approximately $0.003-$0.005) — supplement with live income and merchandise', True), ('Streaming is free for musicians — revenue comes only from advertising', False), ('African musicians cannot earn from international streaming platforms', False)]),
('What is the most effective way to build a music audience in West Africa?', 'multiple_choice', 'Consistent social media presence (short video content on TikTok, Instagram Reels, YouTube Shorts) combined with live performance builds audiences most effectively in West Africa today. Viral short-form video creates awareness; live performance converts awareness to loyal fans. WhatsApp groups maintain fan community. Collaborations with established artists accelerate growth.', [('Record and release one album then wait for radio play', False), ('Consistent short-form video content combined with live performance and WhatsApp fan community', True), ('Only pursue radio play — streaming audiences are too small to matter', False), ('Focus exclusively on international markets where streaming pays more', False)]),
])

create_quiz('Phone and Electronics Repairs', 'Phone and Electronics Repairs — Final Assessment',
'This assessment covers smartphone diagnosis, screen replacement, battery issues and repair business management.',
20, [
('What is the first step before opening any smartphone for repair?', 'multiple_choice', 'Power off the phone completely before opening it. Then disconnect the battery connector before touching any other component. Static electricity, short circuits from live connections and accidental activation of circuits can all cause further damage. Battery disconnection is non-negotiable before internal repairs.', [('Remove the SIM card', False), ('Power off and disconnect the battery before touching any components', True), ('Update the software to the latest version', False), ('Test all functions to document what works', False)]),
('What is the most common cause of phone charging problems?', 'multiple_choice', 'A faulty or damaged cable causes the majority of charging complaints. Always test with a different cable and charger first before assuming the phone has a hardware problem. Lint and debris in the charging port is the second most common cause — clean carefully with a non-conductive tool. Only if these checks fail should port replacement be considered.', [('Faulty charging IC chip on the motherboard', False), ('Faulty cable — always test with a different cable first', True), ('Battery completely dead and needing replacement', False), ('Damaged charging port requiring immediate replacement', False)]),
('What does a swollen battery indicate?', 'multiple_choice', 'A swollen (puffed) battery is a safety emergency. Internal chemical breakdown produces gas, causing the battery case to expand. Risk of rupture and fire is real. Never charge a swollen battery. Do not puncture it. Replace immediately. Advise the customer urgently — a swollen battery in a pocket is a genuine danger.', [('The battery is fully charged and ready to use', False), ('A safety emergency — internal breakdown with fire risk, replace immediately', True), ('The battery needs recalibration to show accurate charge level', False), ('Normal aging — swollen batteries can continue to be used safely', False)]),
('What is OEM versus aftermarket replacement screen?', 'multiple_choice', 'OEM (Original Equipment Manufacturer) screens are made by or to the same specification as the original manufacturer. They provide the best colour accuracy, touch sensitivity and brightness. Aftermarket screens are copies — typically cheaper but with inferior display quality, sometimes poor touch sensitivity and shorter lifespan. Always inform customers of the difference and let them choose.', [('OEM screens are counterfeit; aftermarket are genuine', False), ('OEM meets original specifications; aftermarket is cheaper but lower quality — inform customers of the difference', True), ('Both are identical — OEM is just more expensive branding', False), ('Aftermarket is always better because it uses newer technology', False)]),
('What is the most profitable service to add to a phone repair business?', 'multiple_choice', 'Accessories sales (cases, screen protectors, chargers, earphones, power banks) alongside repairs provides high-margin, low-skill additional income. Customers who come for repairs are already present and often need accessories. Accessories typically have 50-100% markup and require no technical skill to sell. Refurbished phone sales (buy broken, fix, resell) is the highest-margin opportunity for experienced repairers.', [('Software repair only — no tools required', False), ('Accessories sales and refurbished phone trading — high margin, complements repair business', True), ('Focus only on one brand to become the official service centre', False), ('Water damage repair only — it commands the highest single-job fees', False)]),
])

create_quiz('Photography and Videography', 'Photography and Videography — Final Assessment',
'This assessment covers camera fundamentals, composition, lighting and building a photography business.',
20, [
('What is the exposure triangle?', 'multiple_choice', 'The three settings controlling how much light reaches the camera sensor: ISO (sensitivity to light), Shutter Speed (how long the sensor is exposed), and Aperture (size of the lens opening). Together these three control exposure — too much light = overexposed (white); too little = underexposed (dark). Adjusting one requires compensating with another to maintain correct exposure.', [('Brightness, contrast and saturation', False), ('ISO, shutter speed and aperture — the three controls of exposure', True), ('Resolution, frame rate and file format', False), ('White balance, focus and zoom', False)]),
('What is the rule of thirds?', 'multiple_choice', 'Divide the frame into a 3x3 grid. Place subjects and key visual elements at the intersections of the grid lines rather than dead centre. This creates more visually interesting, balanced compositions. Most cameras have a grid overlay option in settings. The rule of thirds applies to photography, video, graphic design and all visual composition.', [('Never use more than three colours in one image', False), ('Divide the frame into a 3x3 grid and place subjects at the grid intersections', True), ('One third of the image should always be in focus', False), ('Three exposures of the same subject for HDR', False)]),
('What is the golden hour in photography?', 'multiple_choice', 'The golden hour is the first hour after sunrise and the last hour before sunset. The sun is low in the sky, creating soft, warm, directional light that is flattering for portraits, landscapes and architecture. Harsh midday sun creates unflattering shadows and high contrast. Professional photographers schedule golden hour shoots whenever possible for the best natural light.', [('The hour when photographs are processed most efficiently', False), ('The first hour after sunrise and last before sunset — soft, warm, directional light', True), ('The time of day when golden-coloured objects photograph best', False), ('Any hour when the sky is cloudless and bright', False)]),
('What file format should professional photos be delivered in to clients?', 'multiple_choice', 'JPEG is the standard delivery format for clients — widely compatible with all devices and software, manageable file size, and high quality at appropriate compression settings. RAW files are used for editing but should not be delivered to clients unless specifically requested and they have compatible software. Avoid PNG for photos (unnecessarily large files) and TIFF (too large for routine delivery).', [('RAW files so clients can edit them themselves', False), ('JPEG — widely compatible, appropriate file size, high quality for delivery', True), ('PNG — lossless and therefore highest quality', False), ('BMP — the original uncompressed format', False)]),
('What is the most important investment for starting a photography business?', 'multiple_choice', 'A strong portfolio of real work is more important than any specific equipment. Clients hire photographers whose previous work they can see and trust. Build the portfolio first — shoot events (with permission), portraits, products, anything that demonstrates your skills. Once you have a portfolio that converts enquiries to bookings, invest in better equipment. Without a portfolio, the best camera in the world will not get you paid jobs.', [('The most expensive camera body available', False), ('A strong portfolio of real work — clients hire based on what they can see you have done', True), ('A professional website before taking any clients', False), ('Expensive studio lighting equipment for indoor shoots', False)]),
])

create_quiz('Port and Logistics Work', 'Port and Logistics Work — Final Assessment',
'This assessment covers Freetown port operations, customs clearance, freight forwarding and logistics careers.',
20, [
('What is a Bill of Lading and why is it important?', 'multiple_choice', 'A Bill of Lading (BL) is issued by the shipping line and proves ownership of the cargo. The holder of the original BL can claim the goods. It must be presented to the shipping agent to obtain the Delivery Order (which releases the goods). Without the original BL, goods cannot legally be released from the shipping line\'s custody.', [('A list of all the items loaded onto a ship for customs reference', False), ('The shipping line\'s document proving cargo ownership — must be presented to release goods', True), ('The government\'s permission for a ship to enter the port', False), ('The receipt issued when port dues are paid', False)]),
('What is the ASYCUDA system?', 'multiple_choice', 'ASYCUDA World is the electronic customs management system used in Sierra Leone. All import and export declarations are filed electronically through ASYCUDA. Clearing agents must be trained and licensed to use it. Training is available through SLRA (Sierra Leone Revenue Authority). Knowledge of ASYCUDA is the key skill for customs clearing work in Sierra Leone.', [('A database of all registered importers and exporters in Sierra Leone', False), ('The electronic customs declaration system used for all import and export clearance in Sierra Leone', True), ('A shipping tracking system for monitoring containers at sea', False), ('The accounting software used by the Sierra Leone Ports Authority', False)]),
('What is demurrage?', 'multiple_choice', 'Demurrage is a daily fee charged for containers or vessels that remain in the port beyond the free storage period (typically 3-5 days). The longer goods stay, the more demurrage accumulates — costs can reach thousands of dollars for delayed shipments. Fast, accurate customs clearance minimises demurrage and is one of the key services that clearing agents provide.', [('The cost of loading or unloading cargo from a vessel', False), ('Daily fee for containers or vessels remaining in port beyond the free storage period', True), ('The import duty levied on goods arriving from certain countries', False), ('The agent\'s commission for arranging customs clearance', False)]),
('What does CIF mean in international trade?', 'multiple_choice', 'CIF stands for Cost, Insurance, Freight. A CIF price includes: the cost of the goods, marine insurance, and freight (shipping cost) to the destination port. The seller pays these three elements and delivers the goods to the destination port. Import duty in Sierra Leone is calculated on the CIF value. An FOB price excludes insurance and freight — you must add these to calculate your total landed cost.', [('Customs, Import and Fees — all port charges combined', False), ('Cost, Insurance, Freight — the seller pays these to the destination port', True), ('Container, Invoice, Freight — the three documents for clearance', False), ('Certificate of Import and Forwarding — the clearance approval', False)]),
('What career pathway requires the SLRA clearing agent licence?', 'multiple_choice', 'The SLRA clearing agent licence is required to file import and export declarations (customs entries) in ASYCUDA on behalf of importers and exporters. Licensed clearing agents can build significant businesses handling multiple importers\' shipments. The licence requires an examination. Starting as an assistant to a licensed clearing agent is the standard pathway to obtaining the licence.', [('Stevedore working on the quayside loading ships', False), ('Customs clearing agent — filing import/export declarations in ASYCUDA on behalf of importers', True), ('Port security officer checking vessel manifests', False), ('Shipping agent representing shipping lines', False)]),
])

create_quiz('Refrigeration and Air Conditioning', 'Refrigeration and Air Conditioning — Final Assessment',
'This assessment covers refrigeration principles, AC installation, fault diagnosis and business development.',
20, [
('What is the refrigeration cycle and its four main components?', 'multiple_choice', 'The refrigeration cycle transfers heat from inside (cool space) to outside (warm exhaust). Four components: Compressor (compresses refrigerant gas, raising temperature and pressure), Condenser (hot gas releases heat to outside air, becomes liquid), Expansion valve (liquid drops in pressure and temperature rapidly), Evaporator (cold liquid absorbs heat from the space, becomes gas). The cycle repeats continuously.', [('Evaporator, Filter, Fan, Thermostat', False), ('Compressor, Condenser, Expansion valve, Evaporator — the four components of the refrigeration cycle', True), ('Compressor, Refrigerant, Copper pipe, Thermostat', False), ('Motor, Fan, Coil, Controller', False)]),
('Why must you never charge refrigerant into a system without first vacuuming it?', 'multiple_choice', 'Air and moisture in the refrigeration system cause: moisture freezing at the expansion valve (blocking flow), acid formation from moisture reacting with refrigerant (corroding components), non-condensable gases reducing system efficiency, and contamination of the compressor oil. A proper vacuum for at least 30 minutes removes all air and moisture before refrigerant is charged.', [('Refrigerant flows better after vacuuming', False), ('Air and moisture cause blockages, acid corrosion and reduced efficiency if not removed', True), ('Vacuuming is only required for new installations, not recharges', False), ('It is a legal requirement with no technical reason', False)]),
('What does an MPPT charge controller do that a PWM controller does not?', 'multiple_choice', 'In the context of solar systems (which are increasingly combined with AC and refrigeration for off-grid cold storage), MPPT (Maximum Power Point Tracking) controllers extract 10-30% more power from solar panels than PWM (Pulse Width Modulation) controllers by continuously adjusting to find the optimal operating point. MPPT is more expensive but significantly more efficient, especially when panel voltage is much higher than battery voltage.', [('MPPT controllers are larger and more expensive with no performance benefit', False), ('MPPT extracts 10-30% more solar power by optimising the operating point continuously', True), ('PWM is always better — MPPT is only used in large commercial systems', False), ('They are identical — the names are different regional terms', False)]),
('What is the most common fault causing a split AC to not cool?', 'multiple_choice', 'A dirty air filter is by far the most common cause of reduced AC cooling performance. A blocked filter restricts airflow over the evaporator coil, reducing heat exchange and cooling capacity. Cleaning the filter monthly restores performance. This is free, takes 5 minutes, and is the first check for any AC that is not cooling adequately — before assuming refrigerant loss or compressor problems.', [('Low refrigerant charge requiring immediate gas top-up', False), ('Dirty air filter — clean it monthly before diagnosing any other fault', True), ('Failed compressor requiring replacement', False), ('Incorrect thermostat setting', False)]),
('How do you build a recurring income maintenance contract for commercial refrigeration?', 'multiple_choice', 'Approach hotels, supermarkets, restaurants and hospitals — businesses where refrigeration failure causes immediate financial loss. Offer a maintenance contract: quarterly or bi-annual service visits (cleaning coils, checking refrigerant, verifying temperatures), priority call-out response when equipment fails, one invoice instead of separate charges per visit. Recurring contracts provide predictable income and long-term client relationships that are very hard to dislodge.', [('Offer emergency repairs only — regular maintenance is not needed', False), ('Offer quarterly service contracts to businesses where refrigeration failure causes financial loss', True), ('Only work for private homes — commercial clients are too demanding', False), ('Compete on price alone — the cheapest wins all commercial contracts', False)]),
])

create_quiz('Security Services and Guard Training', 'Security Services and Guard Training — Final Assessment',
'This assessment tests professional security knowledge including access control, emergency response and report writing.',
20, [
('What is the primary role of a security officer?', 'multiple_choice', 'A security officer\'s primary role is observation, communication and deterrence — not physical confrontation. Professional security is about preventing incidents through visible presence, vigilant observation, and communicating with police and management when incidents occur. Physical force is used only as a legal last resort when there is immediate threat to life.', [('To physically detain and arrest criminals', False), ('Observation, communication and deterrence — physical force only as a legal last resort', True), ('To replace police officers on private premises', False), ('To check identification documents for authenticity', False)]),
('What procedure do you follow when logging a visitor?', 'multiple_choice', 'Visitor log procedure: request identification, note full name and ID number, note time of arrival, note the host they are visiting (and confirm with host by phone or intercom), issue a visitor pass, note the vehicle registration if applicable, and log departure time when they leave. Every visitor must be logged — no exceptions for familiarity or apparent status.', [('Just wave through anyone who looks like they belong', False), ('Request ID, note details, confirm with host, issue visitor pass, log arrival and departure', True), ('Only log visitors after 6pm when risk increases', False), ('Log only vehicle registrations — names are not necessary', False)]),
('What is the correct response to a fire alarm?', 'multiple_choice', 'When a fire alarm activates: assume it is real until confirmed otherwise. Activate the evacuation procedure — direct people to designated fire exits and assembly points. Do not use lifts. Account for all persons at the assembly point. Call the fire service. Do not allow re-entry until fire service gives the all clear. Do not investigate the source of smoke or fire yourself unless specifically trained and equipped.', [('Investigate the source before raising the alarm to avoid false evacuations', False), ('Activate evacuation procedure, direct to exits, account for all persons, call fire service', True), ('Sound the alarm then wait for the fire service to arrive before evacuating', False), ('Only evacuate if you can see visible flames or smoke', False)]),
('What makes a good security incident report?', 'multiple_choice', 'A good incident report answers: Who (all persons involved), What (exactly what happened in sequence), When (exact times), Where (exact location), How (how the incident occurred). Language must be factual — only what you directly observed or were told. No personal opinions. No emotional language. Clear and specific. Written as soon as possible after the incident while memory is fresh.', [('Include your personal opinion about who was at fault', False), ('Answer who, what, when, where, how — factual language only, written immediately after the incident', True), ('Keep it short — one sentence is ideal for efficiency', False), ('Incident reports are only needed for serious crimes', False)]),
('What is the most important quality for a professional security officer to develop?', 'multiple_choice', 'Integrity — the security officer is trusted with access to premises, knowledge of security procedures, and responsibility for protecting people and property. Officers who abuse this trust (accepting bribes, allowing unauthorised access, sharing security information) cause serious harm and permanently damage their career. Officers with proven integrity advance fastest in the profession.', [('Physical strength and fighting ability', False), ('Integrity — trusted with access and security information, abuse destroys career and causes harm', True), ('The ability to appear intimidating to deter criminals', False), ('Speed of response to incidents', False)]),
])

create_quiz('Solar Energy Installation', 'Solar Energy Installation — Final Assessment',
'This assessment covers solar system design, installation, maintenance and the solar business in West Africa.',
20, [
('What does peak sun hours mean and how many does West Africa typically get?', 'multiple_choice', 'Peak sun hours (PSH) is the number of hours per day when sunlight intensity is equivalent to 1,000 W/m2 (full rated output). West Africa typically receives 4-6 peak sun hours per day. This figure is used in sizing calculations: daily energy production = panel wattage times peak sun hours. Higher PSH means more energy per panel — West Africa is excellent for solar.', [('Total daylight hours from sunrise to sunset', False), ('Hours of equivalent full-rated sunlight — typically 4-6 per day in West Africa', True), ('The hottest hours of the day when panels are most efficient', False), ('Hours when the sun is directly overhead', False)]),
('How do you calculate the battery capacity needed for a solar system?', 'multiple_choice', 'Battery capacity in Ah = (Daily load in Wh times days of autonomy) divided by (system voltage times depth of discharge). Example: 1,000 Wh daily load, 2 days autonomy, 12V system, 50% depth of discharge: (1,000 times 2) divided by (12 times 0.5) = 333 Ah. Always round up to the nearest available battery size.', [('Number of panels times 100Ah per panel', False), 'Daily load times autonomy days divided by voltage times depth of discharge', True), ('Estimate based on the size of the house', False), ('Same capacity as the inverter rating in watts', False)]),
('What happens if you connect batteries in series versus parallel?', 'multiple_choice', 'Series connection (positive to negative): voltage adds up, capacity stays the same. Two 12V 100Ah batteries in series = 24V 100Ah. Parallel connection (positive to positive, negative to negative): capacity adds up, voltage stays the same. Two 12V 100Ah batteries in parallel = 12V 200Ah. Most small home systems use parallel batteries at 12V; larger systems use series for 24V or 48V efficiency.', [('Series increases capacity; parallel increases voltage', False), ('Series increases voltage; parallel increases capacity', True), ('Both connections produce identical results', False), ('Series is for solar panels; parallel is for batteries only', False)]),
('What is the most common fault causing a solar system to underperform?', 'multiple_choice', 'Dirty panels are the most common and easily fixed performance issue. Dust, bird droppings and general grime can reduce panel output by 15-25%. Clean with water and a soft cloth monthly or after dusty periods. This costs nothing and can restore significant lost performance. After checking panel cleanliness, check all connections for corrosion, then measure battery voltage under load.', [('Undersized inverter limiting power output', False), ('Dirty panels — dust and grime reduce output by 15-25%, clean monthly', True), ('Battery overcharging from excessive sunlight', False), ('Charge controller firmware requiring update', False)]),
('What makes Starlink particularly valuable for the SkillsContinua platform?', 'multiple_choice', 'Starlink provides reliable high-speed internet (typically 50-200 Mbps) via satellite, bypassing unreliable terrestrial networks. In Sierra Leone where mobile internet is unreliable and fixed broadband limited, Starlink enables consistent access to online learning platforms, content management and remote communication — critical for a platform serving learners across the country. Its power consumption (65W) is manageable with a small solar system.', [('Starlink is cheaper than all other internet options in Sierra Leone', False), ('Starlink provides reliable high-speed internet via satellite, bypassing unreliable terrestrial networks', True), ('Starlink only works in urban areas like Freetown', False), ('Starlink requires a government licence to operate in Sierra Leone', False)]),
])

create_quiz('Tailoring and Fashion Design', 'Tailoring and Fashion Design — Final Assessment',
'This assessment covers tailoring techniques, garment construction, African styles and business management.',
20, [
('What measurement determines whether a bodice will fit correctly at the chest?', 'multiple_choice', 'The bust or chest measurement (taken around the fullest part of the chest/bust) is the primary measurement for fitting a bodice. Add ease (4-8cm for a regular fit) to the body measurement before drafting or cutting. Without ease, a garment fits the measurement exactly but restricts movement and looks uncomfortably tight when worn.', [('The shoulder width measurement', False), ('The bust/chest measurement plus appropriate ease for the intended fit', True), ('The waist measurement at the natural waist', False), ('The length from shoulder to waist', False)]),
('What is the purpose of interfacing in garment making?', 'multiple_choice', 'Interfacing is a fabric attached to the wrong side of outer fabric to add structure, stiffness and stability. Used in: collars (to hold their shape), cuffs, waistbands, button plackets (prevents stretching), front bodice facings. Without interfacing these areas become limp and lose their shape after washing. Woven interfacing for structured areas; non-woven for lighter areas.', [('To add weight and make garments hang better', False), ('To add structure and stability to areas like collars, cuffs and waistbands', True), ('To prevent fabric from shrinking when washed', False), ('A decorative layer sewn between the lining and outer fabric', False)]),
('What is the correct seam allowance for most dressmaking patterns?', 'multiple_choice', 'Standard seam allowance is 1.5cm (or 5/8 inch in imperial measurement). This is the distance between the cut edge of fabric and the stitch line. Always sew at the marked seam allowance — not by eye. If you vary from the seam allowance, the garment will not be the intended size. Larger seam allowances (3cm) are used for tailoring to allow adjustment.', [('0.5cm — the smallest possible for clean seams', False), ('1.5cm — the standard seam allowance used in most dressmaking patterns', True), ('3cm — standard for all garments', False), ('There is no standard — measure by eye based on the fabric', False)]),
('What is asoebi and why is it important for tailors?', 'multiple_choice', 'Asoebi (also written aso ebi) is the practice of groups — typically families at weddings, naming ceremonies or funerals — wearing identical or coordinated fabric to show unity and solidarity. This is extremely important for tailors because asoebi orders are typically for 10-100+ outfits at one time. A tailor with a reputation for good asoebi work will receive very large repeat orders from social groups.', [('A type of Ankara fabric particularly popular in Sierra Leone', False), ('Groups wearing identical fabric at events — large repeat orders for tailors who do it well', True), ('The practice of adding decorative embroidery to traditional garments', False), ('A West African measurement system different from European sizing', False)]),
('What deposit should a tailor require before buying fabric for a client order?', 'multiple_choice', 'A minimum 50% deposit before purchasing any fabric. Fabric bought for a specific client order is often not returnable or resaleable. If the client changes their mind or disappears, the tailor bears the full cost. A 50% deposit covers the fabric cost at minimum. The balance is collected before the garment is handed over.', [('No deposit — this builds trust with new clients', False), ('Minimum 50% before purchasing fabric — protects against client default', True), ('10% to confirm the booking', False), ('Full payment upfront before any work begins', False)]),
])

create_quiz('Truck and Commercial Vehicle Maintenance', 'Truck and Commercial Vehicle Maintenance — Final Assessment',
'This assessment covers diesel engine maintenance, air brakes, tyres and fleet management.',
20, [
('What is the most critical daily check on a truck with air brakes?', 'multiple_choice', 'Air brake pressure must reach the normal operating range (690-760 kPa / 100-110 psi) before the vehicle moves. The low pressure warning must sound when pressure drops below 414 kPa (60 psi). If the system cannot build pressure or the warning activates at rest, the vehicle must not be moved until the fault is investigated.', [('Check the windscreen wipers work correctly', False), ('Verify air brake pressure reaches normal operating range before moving', True), ('Test the horn and lights only', False), ('Check the engine oil level', False)]),
('Why does a diesel truck\'s fuel filter need to be changed more frequently than a petrol engine?', 'multiple_choice', 'Diesel fuel quality in West Africa is often inconsistent — contaminated with water, sediment and microbes. Dirty fuel destroys injectors, which are expensive precision components. Frequent fuel filter changes (every 20,000-30,000 km) protect the injectors. The fuel filter also has a water separator — drain this weekly. Prevention is far cheaper than injector replacement.', [('Diesel engines use more fuel so filters fill faster', False), ('Inconsistent diesel fuel quality in West Africa makes protection of injectors critical', True), ('Diesel filters are smaller so they need changing more often', False), ('Diesel burns at higher temperature which degrades filters faster', False)]),
('What is tyre overloading and what are the consequences?', 'multiple_choice', 'Tyre overloading occurs when the total vehicle weight (including cargo) exceeds the load rating stamped on the tyre sidewall. Consequences: heat build-up leading to tyre failure (blowout), accelerated wear, reduced braking and steering response, suspension and chassis damage. In West Africa where overloading is common, tyre blowouts at speed are a major cause of fatal road accidents.', [('Using tyres with a higher speed rating than necessary', False), ('Exceeding the tyre\'s load rating — causes heat, blowout risk, accelerated wear and accident risk', True), ('Overinflating tyres to carry heavier loads more efficiently', False), ('Mixing tyre brands on the same axle', False)]),
('What is a pre-trip inspection and who is responsible for it?', 'multiple_choice', 'A pre-trip inspection is a systematic check of the vehicle before each journey: air brake pressure, oil, coolant, fuel, tyre pressures and condition (all wheels including spare), lights (all positions), mirrors, load security, documentation. The driver is responsible — not the mechanic or fleet manager. A driver who operates a defective vehicle is liable for any resulting accident.', [('A monthly inspection performed by the fleet mechanic only', False), ('The driver\'s daily check of brakes, fluids, tyres, lights, load and documentation before departure', True), ('An annual inspection required for vehicle licensing', False), ('An inspection performed by police at roadside checkpoints', False)]),
('What is fleet maintenance scheduling and why does it improve profitability?', 'multiple_choice', 'Fleet maintenance scheduling means servicing each vehicle at its specified interval regardless of apparent condition — oil changes, filter replacements, brake inspections — during planned downtime. Planned maintenance costs less than breakdown repair, prevents unexpected off-road time (which loses revenue), extends vehicle life, and maintains safety. A truck off the road for breakdown repairs costs far more in lost revenue than the service that would have prevented it.', [('Only maintaining vehicles when they show visible problems', False), ('Scheduled preventive maintenance reduces breakdown costs, lost revenue and extends vehicle life', True), ('Fleet maintenance is the manufacturer\'s responsibility under warranty', False), ('Maintenance scheduling only applies to vehicles over 5 years old', False)]),
])

create_quiz('Understanding the Leone and Inflation', 'Understanding the Leone and Inflation — Final Assessment',
'This assessment tests your understanding of how inflation and currency devaluation affect Sierra Leonean businesses and households.',
20, [
('What is inflation and how is it measured?', 'multiple_choice', 'Inflation is the general, sustained rise in the price level of goods and services — money buys less than before. It is measured using the Consumer Price Index (CPI): a basket of typical household purchases is priced regularly. The percentage change in CPI is the inflation rate. Sierra Leone\'s inflation exceeded 40% in 2022-2023 — meaning the same basket of goods cost 40% more than the previous year.', [('A government tax on imports that raises prices', False), ('The general sustained rise in prices measured by the Consumer Price Index (CPI)', True), ('The difference between the official and black market exchange rate', False), ('Price increases caused only by international factors', False)]),
('How does Leone devaluation affect an importer?', 'multiple_choice', 'When the Leone weakens against the dollar, imports cost more Leones to purchase even though the dollar price has not changed. An importer who paid Le 10,000 per dollar last year now pays Le 22,000 per dollar. The same $1,000 shipment now costs Le 22,000,000 instead of Le 10,000,000. This cost increase must be passed to customers — which is why imported goods get more expensive when the Leone falls.', [('Importers benefit from Leone devaluation because exports become cheaper', False), ('Weaker Leone means imports cost more Leones — costs must be passed to customers', True), ('Devaluation only affects exporters, not importers', False), ('The importer\'s dollar price rises when the Leone weakens', False)]),
('What is the replacement cost principle for traders?', 'multiple_choice', 'Price based on what it will cost to REPLACE your stock, not what you originally paid. If you bought rice at Le 180,000 per bag and it now costs Le 210,000 to replace, selling at a price calculated on Le 180,000 leaves you unable to maintain your stock level. The relevant price is always the current replacement cost.', [('Always use the original purchase price to calculate selling price', False), ('Price based on replacement cost, not original purchase price — otherwise stock cannot be maintained', True), ('Replacement cost is only relevant for equipment, not trading stock', False), ('Use the average of original and current price', False)]),
('What is the osusu and how does it protect against inflation?', 'multiple_choice', 'Osusu (rotating savings groups) are traditional savings clubs where members contribute regularly and each member takes the pot in rotation. This enforces savings discipline and provides access to lump sums for investment. Investing lump sums in stock or business assets protects value better than holding Leones in a savings account, where inflation erodes purchasing power over time.', [('A government savings bond that pays inflation-beating interest', False), ('A rotating savings group that enforces discipline and provides lump sums for investment in assets', True), ('A type of microfinance loan available to market traders', False), ('The informal money transfer system used in Sierra Leone', False)]),
('A trader holds Le 5,000,000 in cash while inflation runs at 30%. What has happened to its real value after one year?', 'multiple_choice', 'After one year at 30% inflation, the purchasing power of Le 5,000,000 has fallen by 30%. It now buys only what Le 3,500,000 would have bought at the start of the year. The nominal amount is still Le 5,000,000, but its real value (what it can actually buy) is only Le 3,500,000. This is why holding cash in Leones during high inflation is costly — better to hold stock or assets.', [('Still Le 5,000,000 — the amount in the bank does not change', False), ('Real purchasing power has fallen to approximately Le 3,500,000 — 30% less buying power', True), ('The value increases because interest is added', False), ('Real value doubles because money becomes more scarce', False)]),
])

create_quiz('Value-Added Business — Transforming Raw Materials into Profit', 'Value-Added Business — Final Assessment',
'This assessment covers the principles of adding value to raw materials to command higher prices and build profitable businesses.',
20, [
('What is the key difference between a value-added business and a pure trading business?', 'multiple_choice', 'A value-added business transforms raw materials into a more valuable product before selling — adding labour, skill, processing or packaging. A pure trader buys goods and resells without transformation. Value-added businesses generally achieve higher profit margins because customers pay for the skill and transformation in addition to the material cost.', [('Value-added businesses always have more employees', False), ('Value-added businesses transform raw materials, commanding higher margins through skill and processing', True), ('Pure trading is always more profitable because costs are lower', False), ('There is no meaningful difference — both sell products to consumers', False)]),
('Why must you include your own labour when costing a value-added product?', 'multiple_choice', 'Your time has economic value — if you could earn Le 15,000 per hour working for someone else, that is the opportunity cost of spending that hour in your own business. If you spend 3 hours making a product and do not include your labour cost, you are effectively working for free. Many small producers underprice because they forget to value their own time.', [('Labour is free when it is the owner\'s own time', False), ('Your time has opportunity cost — not including it means you are effectively working for free', True), ('Labour cost only applies to employees, not the business owner', False), ('Time cost is already included in overhead expenses', False)]),
('What is equipment depreciation in product costing?', 'multiple_choice', 'Equipment depreciates (loses value) over time. If your grinder cost Le 500,000 and lasts 2 years, it costs your business Le 20,833 per month (500,000 divided by 24). If you make 200 units per month, that is Le 104 per unit for the grinder. Including depreciation ensures you are saving to replace the equipment when it fails — failure to include it means the equipment replacement comes as an unexpected shock.', [('A tax deduction that reduces your business profit', False), ('The monthly cost of equipment spread over its useful life — included per unit in product cost', True), ('Only relevant for equipment worth over Le 10 million', False), ('Equipment is a one-time cost — it does not affect ongoing product pricing', False)]),
('What is value-based pricing and when should you use it?', 'multiple_choice', 'Value-based pricing charges what the product is worth to the customer, not just what it cost you. A wedding cake costing Le 50,000 in materials may be worth Le 500,000 to the bride — the skill, design and occasion justify the premium. Value-based pricing works when: your product is unique, quality is exceptional, and customers cannot easily find an equivalent elsewhere. It is the most profitable pricing strategy when you have earned the reputation to support it.', [('Pricing based on the total value of all materials used', False), ('Charging what the product is worth to the customer — justified by skill, uniqueness and reputation', True), ('Setting prices equal to your competitors to provide equivalent value', False), ('A government-regulated pricing system for essential goods', False)]),
('What should you do before scaling up production of your value-added product?', 'multiple_choice', 'Before scaling: ensure your process is documented and consistent (written recipe/process sheet), verify you have reliable suppliers for increased volumes at acceptable prices, confirm you have buyers for the increased output, and ensure you have sufficient cash flow to finance larger production runs. Scaling without these conditions leads to quality failures, stock piling unsold goods, or cash flow collapse.', [('Immediately hire as many workers as possible to meet expected demand', False), ('Document the process, secure suppliers and buyers, ensure cash flow — before scaling', True), ('Borrow money to invest in maximum capacity immediately', False), ('Scale when you feel confident — no formal planning is needed', False)]),
])

# Final summary
print('\n' + '='*60)
from certifications.models import Quiz
total_q = sum(q.questions.count() for q in Quiz.objects.all())
quiz_count = Quiz.objects.count()
print(f'Total quizzes: {quiz_count}')
print(f'Total questions: {total_q}')

courses_without_quiz = []
from courses.models import Course
for c in Course.objects.all().order_by('title'):
    try:
        c.quiz
    except:
        courses_without_quiz.append(c.title)
print(f'Courses still needing quizzes: {len(courses_without_quiz)}')
for t in courses_without_quiz:
    print(f'  - {t}')