import os, django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'skillscontinua_core.settings')
django.setup()

from courses.models import Course
from certifications.models import Quiz, Question, Answer

def create_quiz(course_title, quiz_title, description, time_limit, questions_data):
    try:
        course = Course.objects.get(title=course_title)
        quiz, created = Quiz.objects.get_or_create(
            course=course,
            defaults={
                'title': quiz_title,
                'description': description,
                'pass_mark': 60,
                'time_limit_minutes': time_limit,
                'is_active': True,
            }
        )
        if not created:
            quiz.title = quiz_title
            quiz.description = description
            quiz.time_limit_minutes = time_limit
            quiz.save()
            quiz.questions.all().delete()

        for order, (qtext, qtype, explanation, answers) in enumerate(questions_data, 1):
            q = Question.objects.create(
                quiz=quiz,
                question_text=qtext,
                question_type=qtype,
                order=order,
                marks=1,
                explanation=explanation,
            )
            for atext, correct in answers:
                Answer.objects.create(question=q, answer_text=atext, is_correct=correct)
        print(f'OK: {course_title} — {quiz.questions.count()} questions')
    except Course.DoesNotExist:
        print(f'NOT FOUND: {course_title}')

# ============================================================
# CARPENTRY AND WOODWORKS
# ============================================================
create_quiz('Carpentry and Woodworks', 'Carpentry and Woodworks — Final Assessment',
'This assessment covers carpentry principles, timber, tools, joints and professional practice. Every question reflects real decisions you will make on the job. Trust your training.',
25, [
('What does the cardinal rule "measure twice, cut once" mean in carpentry?', 'multiple_choice',
'Timber is expensive and cutting errors cannot be undone. Verifying your measurement before cutting prevents waste, saves money and maintains the standard of your work. Professional carpenters develop this as an automatic habit. The few seconds taken to re-measure saves hours of rework.',
[('Measure with two different tapes for accuracy', False), ('Always verify measurements before cutting to prevent costly errors', True), ('Cut twice in case the first cut is wrong', False), ('Use two different saws for each cut', False)]),
('What is the main difference between hardwood and softwood?', 'multiple_choice',
'Hardwoods come from deciduous (broad-leaved) trees like iroko, mahogany and teak. They are generally denser, more durable and more resistant to wear. Softwoods come from coniferous trees. The terms refer to botanical classification, not actual hardness — balsa wood is a hardwood but is very soft. In West Africa, hardwoods like iroko are preferred for furniture and construction for their durability and resistance to insects.',
[('Hardwood is always harder than softwood', False), ('Hardwood comes from deciduous trees and is generally more durable', True), ('Softwood is more expensive than hardwood', False), ('Hardwood is better for outdoor use because it is waterproof', False)]),
('What is the strongest traditional woodworking joint for chair and table legs?', 'multiple_choice',
'The mortise and tenon joint has been used for thousands of years because of its exceptional strength. The tenon (tongue) fits precisely into the mortise (hole), creating mechanical interlocking in addition to the glued surface area. This joint distributes stress effectively and is why well-made traditional furniture lasts generations. It requires skill and precision to cut well — which is why it commands a premium price.',
[('Butt joint — simple and strong when reinforced with screws', False), ('Mortise and tenon joint — mechanical interlock provides exceptional strength', True), ('Mitre joint — the angled cut increases gluing surface area', False), ('Halving joint — overlapping the wood doubles its strength', False)]),
('Why should you always use seasoned (dried) timber for indoor furniture?', 'multiple_choice',
'Fresh-cut (green) timber contains significant moisture. As it dries inside a warm building, it shrinks, warps, cracks and pulls joints apart. Properly seasoned timber has been dried to a stable moisture content matching its environment — so it will not move significantly after the furniture is made. Using unseasoned timber is one of the most common and costly mistakes an inexperienced carpenter makes.',
[('Seasoned timber is lighter and easier to work with', False), ('Seasoned timber is stable and will not warp or shrink after the piece is made', True), ('Seasoned timber takes paint better than unseasoned timber', False), ('Unseasoned timber is too hard to cut with hand tools', False)]),
('When using a circular saw, what is the most important safety precaution?', 'multiple_choice',
'The blade guard is a critical safety device that covers the blade before and after the cut. Many serious injuries occur when the guard is removed or disabled "for convenience." Always ensure the guard functions correctly before each use. Additionally, always wear eye protection and ensure the workpiece is secured. Never remove safety guards — if a guard interferes with a cut, find a better technique or use a different tool.',
[('Always cut away from yourself so the saw moves forward', False), ('Ensure the blade guard is functioning and wear eye protection', True), ('Use the highest blade speed setting for a cleaner cut', False), ('Hold the workpiece firmly with your hand near the cut line', False)]),
('What is the purpose of a try square in carpentry?', 'multiple_choice',
'A try square has a blade (ruler) set at exactly 90 degrees to the stock (handle). It is used to mark and check right angles — the most critical relationship in woodworking. If your squares are not square, every joint will be slightly off and assemblies will not fit together properly. A good try square should be tested regularly against a known true surface.',
[('To measure the length of timber accurately', False), ('To check and mark accurate 90-degree right angles', True), ('To check if timber is straight along its length', False), ('To measure the depth of grooves and rebates', False)]),
('A client asks for a piece of furniture that will last 20 years. What type of joint should be prioritised?', 'multiple_choice',
'Glued traditional joints — mortise and tenon, dovetail, dowel — perform far better over decades than mechanical fasteners alone. Screws loosen, nails work their way out, and flat-packed connections deteriorate. Joints that use both glue and mechanical interlock (like mortise and tenon) create bonds that actually get stronger as the glue fully cures and the wood adapts. Quality joinery is what separates heirloom furniture from disposable furniture.',
[('Metal screws throughout — modern and reliable', False), ('Traditional glued joints like mortise and tenon for permanent structural integrity', True), ('Nails and staples — faster and just as strong as joints', False), ('The type of joint does not affect longevity — only the timber quality matters', False)]),
('What does plywood consist of and why is it useful?', 'multiple_choice',
'Plywood is made from thin sheets (veneers) of wood glued together with alternating grain directions. This cross-lamination gives it exceptional stability — it resists warping, splitting and shrinkage far better than solid timber of equivalent thickness. It is strong in all directions. It is ideal for furniture backs, cabinet bases, drawer bottoms and any application requiring a large flat panel.',
[('Compressed wood fibres and resin — similar to MDF', False), ('Thin wood veneers glued with alternating grain — stable and strong in all directions', True), ('Solid hardwood cut very thin and glued together', False), ('Recycled timber chips compressed under high pressure', False)]),
('When sanding furniture, in what order should you proceed through sandpaper grades?', 'multiple_choice',
'Always sand from coarse to fine. Start with a coarser grit (80 or 100) to remove tool marks and level the surface. Then progress through medium (120, 150) to fine (180, 220) grits. Each grade removes the scratches left by the previous grade. Never skip more than one grade — jumping from 80 to 220 leaves deep scratches under an apparently smooth surface that become visible after finishing.',
[('Start with the finest grit to avoid scratching the surface', False), ('Progress from coarse grit to fine grit, removing previous scratches at each stage', True), ('Use the same grit throughout — consistency gives the best finish', False), ('Sand across the grain first then with the grain for a smooth result', False)]),
('What is the most professional way to price a carpentry job?', 'multiple_choice',
'Professional pricing requires calculating all material costs (including 10% for waste), estimating accurate labour hours, applying your hourly rate, adding business overhead, and then adding a profit margin of at least 20%. Always provide this as a written quotation before starting. Pricing based on what you think the client will pay, or matching the lowest competitor, is a route to working for less than minimum wage.',
[('Estimate roughly and adjust the final price based on how long it took', False), ('Calculate materials plus labour hours plus overhead plus at least 20% profit margin', True), ('Charge the same as the cheapest competitor to win the work', False), ('Base the price on what the client appears to be able to afford', False)]),
])

# ============================================================
# ELECTRICAL INSTALLATION
# ============================================================
create_quiz('Electrical Installation', 'Electrical Installation — Final Assessment',
'Electrical work affects people\'s safety and lives. This assessment tests your knowledge of principles, safety, installation practice and professional standards. A qualified electrician takes these responsibilities seriously.',
25, [
('What is the purpose of an earth (ground) connection in an electrical installation?', 'multiple_choice',
'Earthing provides a safe path for fault current to flow to the ground, which causes the circuit breaker or fuse to trip immediately. Without earthing, if a live wire touches a metal appliance casing, the casing becomes live at mains voltage. Anyone who touches it while in contact with the ground completes the circuit — causing potentially fatal electric shock. Earthing is the primary protection against this.',
[('To improve the efficiency of electrical appliances', False), ('To provide a safe fault current path that trips the breaker and prevents electric shock', True), ('To reduce electricity consumption by stabilising voltage', False), ('To prevent static electricity building up in metal components', False)]),
('What does a circuit breaker do that a fuse does not?', 'multiple_choice',
'Both fuses and circuit breakers protect circuits from overcurrent (too much current flowing, which can cause fires). However, a blown fuse must be replaced. A circuit breaker simply trips (switches off) and can be reset by hand once the fault is corrected. Circuit breakers are faster, more reliable, and allow repeated use — which is why they have replaced fuses in modern installations.',
[('Circuit breakers provide higher voltage protection than fuses', False), ('Circuit breakers can be reset after tripping, unlike fuses which must be replaced', True), ('Circuit breakers protect against both overcurrent and undervoltage', False), ('Fuses and circuit breakers work identically but circuit breakers are larger', False)]),
('What colour is the live wire in a standard West African 230V installation?', 'multiple_choice',
'Following IEC standards used across most of West Africa, the live (phase) wire is brown (or red in older installations). The neutral wire is blue (or black in older installations). The earth wire is green and yellow striped. Knowing these colours is essential for safe working. Never assume without testing — always verify with a multimeter or voltage tester before touching any wire.',
[('Red or brown — depending on age of the installation', True), ('Black always in modern installations', False), ('Yellow — to indicate it carries current', False), ('All wires are the same colour — they must be traced to identify them', False)]),
('Why must electrical cables never be run over sharp metal edges?', 'multiple_choice',
'Sharp edges can cut through cable insulation over time, especially when cables vibrate or move slightly with temperature changes. Damaged insulation causes short circuits which trip breakers, or worse — arc faults which can cause fires. All cables should be routed through conduit, grommets or cable protectors where they cross or contact metal edges. This is a building regulation requirement in most countries.',
[('Sharp edges create electrical resistance that reduces supply voltage', False), ('Sharp edges can cut insulation over time, causing short circuits or fire hazards', True), ('Metal edges cause magnetic interference with the electrical signal', False), ('It is purely an aesthetic issue — sharp edges look unprofessional', False)]),
('What tool must you use before touching any wire in an existing installation?', 'multiple_choice',
'A voltage tester (non-contact or contact type) confirms whether a wire is live before you touch it. Never assume a wire is dead because a switch is off or a breaker is tripped — other circuits or backfeed from other sources can still make wires dangerous. Always test first. This single habit prevents most electrical fatalities. Professional electricians test before every touch, every time, without exception.',
[('A multimeter set to resistance to check wire continuity', False), ('A voltage tester to confirm the wire is de-energised before touching', True), ('Your hand — carefully feel if the wire is warm from carrying current', False), ('A torch to see the wire clearly before deciding what to do', False)]),
('What is the purpose of a Residual Current Device (RCD)?', 'multiple_choice',
'An RCD monitors the difference between current flowing in the live and neutral conductors. In a healthy circuit they should be equal. If there is a difference — indicating current is leaking to earth (possibly through a person) — the RCD trips in milliseconds, far faster than the heart can go into fibrillation. RCDs are mandatory in bathrooms, kitchens and outdoor circuits because of the increased shock risk in wet environments.',
[('To protect against high voltage surges from lightning', False), ('To detect current leaking to earth and disconnect the circuit before fatal shock occurs', True), ('To improve energy efficiency by balancing loads across phases', False), ('To protect expensive appliances from voltage fluctuations', False)]),
('When calculating cable size for a circuit, what is the primary factor?', 'multiple_choice',
'The current the cable must carry (load current) is the primary factor in cable sizing. Undersized cables overheat — the insulation melts, fire risk increases, and voltage drop causes appliances to malfunction. The calculation: determine the load in watts, divide by voltage to get amps, then select a cable rated for at least that current with an appropriate safety margin. Cable installation method also affects the current rating.',
[('The length of the cable run determines what size is needed', False), ('The current the cable must carry — undersized cables overheat and create fire risk', True), ('The voltage of the supply — higher voltage needs larger cables', False), ('The type of insulation is the only important factor', False)]),
('What is meant by a three-phase power supply?', 'multiple_choice',
'Three-phase power uses three live conductors, each carrying alternating current 120 degrees out of phase with each other. This provides more efficient power delivery for large loads like industrial motors, large air conditioning systems and workshop machinery. Single-phase (one live, one neutral) is used for domestic and light commercial loads. Understanding the difference is important when installing power for commercial or industrial premises.',
[('A power supply that goes through three separate meters for billing purposes', False), ('Three live conductors 120 degrees out of phase — more efficient for large industrial loads', True), ('Three separate single-phase circuits connected together for redundancy', False), ('A special high-voltage supply for use only in factories', False)]),
('What is the first action when you arrive at a job where someone has received an electric shock?', 'multiple_choice',
'Do NOT touch the casualty while they may still be in contact with the live source — you will also receive a shock. First, disconnect the power at the source (switch off, remove plug, trip breaker). Only when the circuit is confirmed dead should you approach the casualty, call for emergency help, and begin first aid if trained. This sequence is drilled into all electrical safety training because the instinct to grab the person immediately can kill the rescuer.',
[('Immediately grab the person and pull them away from the electrical source', False), ('Disconnect the power first, then approach and call for emergency help', True), ('Call for help before doing anything else', False), ('Check the person\'s pulse before disconnecting the power', False)]),
('Why should an electrician always provide a written quotation before starting work?', 'multiple_choice',
'A written quotation protects both parties. It defines exactly what work will be done, the materials to be used, the total price, and the payment terms. If a dispute arises, the document is the reference. Without a written quotation, clients may dispute the price, claim work was not done, or refuse to pay. Professional tradespeople use written agreements for every job, however small. It also demonstrates professionalism that builds client trust.',
[('It is a legal requirement in all West African countries', False), ('It protects both parties by defining scope, price and terms before work begins', True), ('It allows the electrician to increase the price if the job takes longer', False), ('Clients will only accept quotations in writing — they will not agree verbally', False)]),
])

# ============================================================
# PLUMBING
# ============================================================
create_quiz('Plumbing', 'Plumbing — Final Assessment',
'Plumbing knowledge protects public health and prevents property damage. This assessment tests the principles, materials, techniques and business skills of a professional plumber.',
25, [
('What is the purpose of a trap (U-bend) under a sink?', 'multiple_choice',
'The trap holds a small amount of water at all times. This water seal prevents sewer gases — including hydrogen sulphide (rotten egg smell) and methane — from entering the building through the drain. Without a working trap, toxic and unpleasant gases would continuously enter the property. This is why unused drains should have water poured down them periodically to keep the trap filled.',
[('To slow water flow and prevent drain blockages', False), ('To maintain a water seal that prevents sewer gases from entering the building', True), ('To make it easier to access blockages for clearing', False), ('To reduce water pressure entering the waste system', False)]),
('What material is most commonly recommended for water supply pipes in modern installations?', 'multiple_choice',
'CPVC (Chlorinated Polyvinyl Chloride) and PPR (Polypropylene Random) pipes are widely recommended for modern water supply. They are lightweight, do not corrode, are easy to work with, do not impart taste or odour to drinking water, and have long service lives. They have largely replaced galvanised iron pipes which corrode internally over time, reducing flow and potentially contaminating the water. PVC is used for drainage but not hot water supply.',
[('Galvanised iron — the most durable option for drinking water', False), ('CPVC or PPR plastic pipe — corrosion-resistant and suitable for drinking water', True), ('Standard PVC — cheaper than metal and never corrodes', False), ('Copper is the only safe material for drinking water supply pipes', False)]),
('A customer reports intermittent water hammer (banging in pipes). What is the most likely cause?', 'multiple_choice',
'Water hammer occurs when water flow is stopped suddenly — typically by a fast-closing solenoid valve (in washing machines or dishwashers), or by taps turned off quickly. The kinetic energy of moving water has nowhere to go and creates a pressure wave that bangs the pipes. Solutions include installing air chambers or water hammer arrestors near the problematic valves, and securing pipes that are not properly supported.',
[('The water pressure is too low for the pipe diameter', False), ('Sudden stop of water flow creating pressure waves — caused by fast-closing valves', True), ('Air in the pipes that needs to be bled out', False), ('Pipes that are too cold expanding and contracting', False)]),
('What is the correct fall (gradient) for a horizontal waste water drain?', 'multiple_choice',
'Horizontal drains need sufficient slope to carry waste away by gravity without leaving solids behind. Too little fall and solids settle, causing blockages. Too much fall and water runs ahead of the solids, also causing blockages. The recommended gradient is 1:40 to 1:80 — approximately 25mm fall per metre for typical drain pipe sizes. This is a standard building regulation requirement.',
[('Perfectly level — any slope causes water to run too fast', False), ('1:40 to 1:80 — approximately 25mm fall per metre to carry waste efficiently', True), ('As steep as possible — the steeper the fall the less likely to block', False), ('The fall does not matter if the pipe diameter is large enough', False)]),
('Why is cross-connection between potable (drinking) water and sewage systems extremely dangerous?', 'multiple_choice',
'Cross-contamination of drinking water with sewage causes serious waterborne diseases — cholera, typhoid, dysentery, hepatitis A. In West Africa, contaminated water supplies cause tens of thousands of preventable deaths annually. Plumbers have a legal and moral responsibility to ensure complete separation between supply and waste systems. Back-siphonage prevention devices and correct installation prevent this from occurring.',
[('It causes burst pipes due to pressure differences between the systems', False), ('Sewage can contaminate drinking water causing serious waterborne disease and death', True), ('It reduces water pressure in the supply system', False), ('Cross-connections are only dangerous in commercial properties, not domestic', False)]),
('When joining copper pipe, what process is used?', 'multiple_choice',
'Capillary soldering uses heat from a blowtorch to melt solder (an alloy of tin and copper) which is drawn by capillary action into the gap between the pipe and fitting. When cooled, it forms a watertight, strong bond. The pipe and fitting must be cleaned and fluxed first — flux removes oxide from the metal surface, allowing the solder to bond properly. Incorrect technique leads to cold joints that leak under pressure.',
[('Welding — melting the copper itself to fuse the pieces together', False), ('Capillary soldering — heat draws molten solder into the joint forming a watertight seal', True), ('Gluing with waterproof adhesive specifically formulated for copper', False), ('Crimping using a mechanical crimp ring that deforms the pipe', False)]),
('A customer\'s toilet keeps running (cistern never empties fully). What is the most likely fault?', 'multiple_choice',
'A continuously running toilet cistern is almost always caused by either a faulty float valve that does not shut off water intake, or a faulty flap valve that allows water to leak from the cistern into the pan continuously. Both are inexpensive, quick repairs. A running toilet can waste hundreds of litres per day — a significant cost for the customer. Diagnosing which valve is at fault requires checking the water level and listening for the source of the flow.',
[('The water pressure to the toilet is too high', False), ('A faulty float valve or flap valve causing continuous water flow', True), ('The drain from the toilet is partially blocked', False), ('The cistern is the wrong size for the toilet bowl', False)]),
('What should you do before cutting into any wall to run new pipes?', 'multiple_choice',
'Walls contain hidden electrical cables, existing water pipes and gas pipes. Cutting or drilling into any of these can cause electrocution, flooding or gas leaks. A cable and pipe detector (stud finder/detector) scans the wall non-invasively to identify what is hidden before you cut. This is standard professional practice — skipping this step has caused serious injuries and property damage.',
[('Check the plans if available, then cut carefully and slowly', False), ('Use a cable and pipe detector to identify all hidden services before cutting', True), ('Turn off the main electricity supply and then cut confidently', False), ('It is not necessary if the pipes will run horizontally as cables run vertically', False)]),
('What is the difference between a ball valve and a gate valve?', 'multiple_choice',
'A ball valve uses a rotating ball with a hole through it — fully open when aligned with the pipe, fully closed when turned 90 degrees. It operates quickly (quarter turn), seals reliably and can be used for both isolation and flow control. A gate valve uses a threaded gate that screws up and down — slower to operate, prone to seizing when not used regularly, and less reliable for complete shutoff. Ball valves are preferred for isolation purposes in modern installations.',
[('Gate valves are better for isolation — ball valves are only for flow control', False), ('Ball valves give reliable isolation with a quarter turn — gate valves can seize and are slower', True), ('They are functionally identical — the choice is purely aesthetic', False), ('Ball valves are only suitable for cold water — gate valves handle hot and cold', False)]),
('What is the most important business habit for a professional plumber?', 'multiple_choice',
'Deposits protect the plumber from clients who disappear after materials have been purchased. Materials for plumbing work can be expensive and specific to the job — difficult or impossible to return. A standard 30-50% deposit before starting any job covers materials and initial labour. It also filters out clients who are not serious. Professional tradespeople always collect deposits, issue receipts, and complete work with a written invoice.',
[('Always carry a full range of materials to every job', False), ('Always collect a deposit before purchasing materials or starting work', True), ('Complete the work first to demonstrate trust and ask for payment after', False), ('Price jobs as low as possible to win the maximum number of contracts', False)]),
])

# ============================================================
# AUTOMOBILE REPAIRS
# ============================================================
create_quiz('Automobile Repairs', 'Automobile Repairs — Final Assessment',
'This assessment tests your knowledge of vehicle systems, diagnosis, maintenance and professional practice. A skilled mechanic saves clients money and keeps them safe on the road.',
25, [
('What does the engine oil do in a vehicle engine?', 'multiple_choice',
'Engine oil serves multiple critical functions: it lubricates all moving metal surfaces, reducing friction and wear; it cools parts that water cannot reach; it cleans by carrying dirt and debris to the oil filter; it protects against corrosion; and it seals small gaps between piston rings and cylinder walls. Without oil, an engine seizes within minutes. Regular oil and filter changes are the single most important maintenance activity.',
[('Fuel the engine in emergencies when petrol runs low', False), ('Lubricate, cool, clean and protect all moving engine components', True), ('Only lubricate the gearbox and transmission', False), ('Cool the engine by flowing around the outside of the cylinders', False)]),
('A customer\'s car pulls strongly to the left when braking. What is the most likely cause?', 'multiple_choice',
'Brake pull on one side indicates unequal braking force between the left and right front wheels. This is usually caused by a stuck brake caliper on one side, uneven brake pad wear, contaminated brake pads (oil or brake fluid), or a collapsed brake hose that restricts fluid to one caliper. This is a serious safety issue — the car becomes very difficult to control during emergency braking. It must be investigated and repaired immediately.',
[('The steering wheel is not centred and needs adjustment', False), ('Unequal braking force between left and right — likely caliper, pad or hose fault', True), ('The tyre pressure on the left is higher than the right', False), ('The car needs wheel alignment — it is a steering issue, not a braking issue', False)]),
('What does OBD-II stand for and why is it useful?', 'multiple_choice',
'OBD-II (On-Board Diagnostics, second generation) is a standardised diagnostic system built into all vehicles manufactured after 1996. It monitors all engine and emissions systems and stores fault codes (DTCs) when something goes wrong. A basic OBD-II reader — available very cheaply — connects to the diagnostic port and reads these codes. This allows mechanics to diagnose problems quickly and accurately without extensive manual testing. Every modern mechanic should have one.',
[('Optional Battery Diagnostics — a system for testing battery health', False), ('On-Board Diagnostics — monitors vehicle systems and stores fault codes for diagnosis', True), ('Oil and Brake Detector — alerts when service is overdue', False), ('Operational Breakdown Detector — a tracking system to locate broken down vehicles', False)]),
('Why is it important to replace a timing belt at the manufacturer\'s recommended interval?', 'multiple_choice',
'The timing belt synchronises the crankshaft and camshaft, ensuring valves open and close at exactly the right moment. If the belt snaps, the pistons and valves collide — causing catastrophic engine damage costing many times more than belt replacement. Many engines are "interference engines" where this damage is immediate and total. The timing belt interval is typically 60,000 to 100,000 km and must not be exceeded.',
[('The timing belt affects fuel efficiency — replacing it saves petrol', False), ('A broken timing belt causes catastrophic engine damage — replacement is far cheaper than repair', True), ('The timing belt affects the vehicle\'s electrical systems', False), ('Timing belt replacement is only necessary on older vehicles', False)]),
('What does a catalytic converter do?', 'multiple_choice',
'A catalytic converter uses precious metal catalysts (platinum, palladium, rhodium) to convert toxic exhaust gases — carbon monoxide (CO), unburned hydrocarbons (HC) and nitrogen oxides (NOx) — into less harmful carbon dioxide, water and nitrogen. It is a critical emissions control device. Damaged catalytic converters cause failed emissions tests, reduced performance, poor fuel economy and increased toxic emissions.',
[('Converts fuel to energy more efficiently in the engine', False), ('Converts toxic exhaust gases into less harmful carbon dioxide, water and nitrogen', True), ('Reduces engine noise by muffling exhaust flow', False), ('Increases exhaust gas temperature to improve engine performance', False)]),
('A car engine overheats repeatedly despite having sufficient coolant. What should be checked next?', 'multiple_choice',
'If coolant level is correct but the engine still overheats, the cooling system is not circulating or dissipating heat effectively. The thermostat is the most common cause — if it sticks closed, coolant cannot flow to the radiator. Also check: the radiator fan (not running, or running slowly), the water pump (impeller worn or broken), blockage in the radiator, or a blown head gasket (which can allow combustion gases into the coolant, causing overheating despite correct fluid level).',
[('Add more coolant — the level is never truly sufficient', False), ('Check thermostat, fan, water pump and head gasket — the coolant is not circulating or cooling', True), ('Replace the radiator cap — it may not be holding pressure', False), ('The problem is in the engine itself and requires a full engine overhaul', False)]),
('What is wheel alignment and why does it matter?', 'multiple_choice',
'Wheel alignment sets the angles at which tyres contact the road. Incorrect alignment causes uneven tyre wear (costing money through premature replacement), increased fuel consumption (rolling resistance), poor handling, and pulling to one side. Common causes of misalignment include hitting potholes, kerb strikes, and general wear of suspension components. Alignment should be checked after any significant impact and with every tyre change.',
[('Balancing the weight of the wheels to prevent vibration at speed', False), ('Setting the correct angles of the tyres to the road for even wear and good handling', True), ('Ensuring all four tyres are inflated to the same pressure', False), ('Adjusting the steering wheel so it is centred when driving straight', False)]),
('What is the function of the alternator?', 'multiple_choice',
'The alternator is driven by the engine via a belt and generates electrical power while the engine runs. It charges the battery and supplies power to all electrical systems. The battery provides power only to start the engine; once running, the alternator takes over. If the alternator fails, the battery runs down quickly and eventually the engine stops. Warning signs: battery warning light, dimming lights, unusual electrical behaviour.',
[('Starts the engine by providing initial rotation to the crankshaft', False), ('Generates electrical power while the engine runs, charging the battery and supplying all systems', True), ('Converts combustion energy into mechanical rotation more efficiently', False), ('Controls fuel injection timing and mixture for optimal combustion', False)]),
('A customer asks if they should use synthetic or mineral engine oil. What is the correct advice?', 'multiple_choice',
'Always follow the manufacturer\'s specification for the vehicle. Modern vehicles (especially turbocharged engines) are designed for synthetic oil which provides better protection at extreme temperatures, flows more easily at cold start, and lasts longer between changes. Older vehicles designed for mineral oil can use synthetic but gain less benefit. Never use a lower specification than the manufacturer requires — it will reduce engine life.',
[('Always use synthetic — it is better for every vehicle in all circumstances', False), ('Follow the manufacturer\'s specification — the engine is designed for a specific oil grade', True), ('Always use mineral oil — synthetic causes seal leaks in older engines', False), ('Any engine oil of the correct viscosity (e.g. 5W30) is equally suitable', False)]),
('What is the most effective way to build a loyal customer base as a mechanic?', 'multiple_choice',
'Trust is the foundation of a mechanic\'s business. Show clients the worn or faulty part before replacing it. Explain in plain language what is wrong and why it needs repair. Never invent problems. Call to confirm the quote before doing additional work. Return the vehicle clean. Follow up to check they are happy. Customers who trust their mechanic return for every service and recommend to family and friends — building a business without any advertising spend.',
[('Price every job as low as possible to retain clients through value', False), ('Build trust by showing clients faults, explaining clearly and never inventing repairs', True), ('Specialise in only one vehicle brand to become the expert', False), ('Focus on completing jobs as quickly as possible to maximise throughput', False)]),
])

# ============================================================
# MASONRY AND BRICKLAYING
# ============================================================
create_quiz('Masonry and Bricklaying', 'Masonry and Bricklaying — Final Assessment',
'Masonry is one of the oldest and most important construction trades. This assessment tests your knowledge of materials, techniques, safety and professional practice.',
25, [
('What is the correct water-cement ratio for standard mortar used in bricklaying?', 'multiple_choice',
'Mortar is typically mixed at 1 part cement to 4 or 5 parts sand (1:4 or 1:5) for bricklaying. Water is added to achieve a workable consistency — approximately 0.5 litres of water per kilogram of cement (0.5 water:cement ratio). Too much water weakens mortar and causes shrinkage cracking. Too little makes it unworkable and causes poor bonding. The test: mortar should hold its shape when squeezed but still be plastic enough to work.',
[('Equal parts water and cement creates the strongest mix', False), ('Approximately 0.5 water to cement ratio — enough for workability without weakening the mix', True), ('As much water as possible — wetter mortar bonds better', False), ('No water — dry mortar is stronger than wet mortar', False)]),
('Why is it important to stagger brick joints (not stack them vertically)?', 'multiple_choice',
'Staggered joints (called bonding) distribute loads through multiple bricks rather than concentrating them on single vertical lines. If joints were stacked vertically, a crack would travel straight through the entire wall. Bonded brickwork redirects cracks and shares structural loads across the wall. This is the fundamental principle that makes brickwork strong — it transforms individual bricks into a unified structural element.',
[('To make the wall look more attractive — it has no structural benefit', False), ('To distribute loads and prevent cracks running straight through the wall', True), ('To use fewer bricks and reduce the cost of construction', False), ('Staggered joints are not necessary — vertical stacking is equally strong', False)]),
('What is the purpose of leaving weep holes in retaining walls?', 'multiple_choice',
'Water that accumulates behind a retaining wall creates hydrostatic pressure — a horizontal force pushing the wall outward. Without drainage, this pressure builds and can eventually push the wall over, even if the wall is strongly built. Weep holes (small openings near the base of the wall) allow water to drain through the wall, relieving this pressure. They are a critical structural requirement for any retaining wall.',
[('To allow air to circulate and dry the wall surface', False), ('To drain water and relieve hydrostatic pressure that would otherwise push the wall over', True), ('To create a decorative pattern in the wall surface', False), ('Weep holes are optional and only used in wet climates', False)]),
('How should you test mortar consistency before use?', 'multiple_choice',
'The squeeze test is the traditional and reliable method: take a handful of mortar and squeeze it in your fist. When you open your hand, it should hold the shape of your fingers clearly, without collapsing (too wet) or crumbling (too dry). Good mortar has a smooth, plastic consistency — it spreads and works easily under the trowel but holds its shape when placed. Adjust by adding small amounts of water or dry mix.',
[('Mix by the clock — a standard mixing time produces correct consistency', False), ('Squeeze a handful — it should hold finger shape without collapsing or crumbling', True), ('The ratio is fixed — consistency depends entirely on exact measurement', False), ('Only test mortar by how easily it pours from the bucket', False)]),
('What is the purpose of a DPC (Damp Proof Course)?', 'multiple_choice',
'Rising damp travels upward through brickwork by capillary action — the same process that draws water up through a sponge. A DPC is a horizontal layer of impermeable material (bituminous felt, slate, plastic) placed in the wall near the ground level to block this upward movement. Without a DPC, walls become permanently damp, causing structural damage, mould growth and an unhealthy living environment.',
[('To provide a horizontal structural layer to distribute the load of the wall', False), ('To block rising damp from travelling up through the brickwork by capillary action', True), ('To waterproof the outer surface of the wall against rain', False), ('To provide thermal insulation at the base of the wall', False)]),
('What angle should a mason\'s spirit level bubble be at to confirm a truly level surface?', 'multiple_choice',
'A spirit level works by using a sealed vial containing liquid and a bubble of air. When the bubble is exactly centred between the two marks on the vial, the surface is perfectly horizontal (level) or perfectly vertical (plumb) depending on the vial being read. Any deviation from centre shows the direction and approximate degree of error. Every course of bricks must be checked for both level and plumb before the mortar sets.',
[('The bubble should be against the left-hand mark', False), ('The bubble should be perfectly centred between the two marks', True), ('The bubble should touch but not cross the right-hand mark', False), ('The position of the bubble does not matter — only the reading at the end matters', False)]),
('When should you wet bricks before laying them?', 'multiple_choice',
'Dry porous bricks absorb moisture from mortar immediately on contact, pulling water away from the mortar before it can bond properly. The result is a weak joint that crumbles. Wetting bricks (but not soaking them) ensures the mortar retains enough water to cure correctly and bond strongly. However, over-wet bricks cause mortar to be too fluid and difficult to work. The surface should be damp but not dripping.',
[('Never — wet bricks cause mortar to become too fluid', False), ('In hot or dry conditions, to prevent mortar from drying too quickly', True), ('Only when using cement-heavy mixes that need extra water', False), ('Always for every brick on every job regardless of conditions', False)]),
('What is efflorescence on brickwork and what causes it?', 'multiple_choice',
'Efflorescence is the white powdery deposit that appears on brick surfaces. It is caused by soluble salts present in the brick, mortar or soil being carried to the surface by water. As the water evaporates, the salts crystallise and appear as white deposits. While unsightly, surface efflorescence is usually not structurally damaging and can be removed by dry brushing. Persistent efflorescence indicates ongoing moisture movement requiring investigation.',
[('Black mould growth indicating serious structural damage requiring immediate repair', False), ('White salt deposits left on the surface as water evaporates through the brickwork', True), ('Cement stains from mortar splashed during construction', False), ('Rust stains from metal reinforcement corroding inside the wall', False)]),
('Why is it important to protect fresh brickwork from rain in the first 24 hours?', 'multiple_choice',
'Freshly laid mortar must cure (harden) through a chemical process. Heavy rain in the first 24 hours washes cement out of the mortar joints before this process can occur, resulting in weak, crumbly joints. Rain can also cause mortar to run and stain brick faces. New brickwork should be covered with plastic sheeting in wet weather. In hot sun, the opposite problem — mortar drying too fast — requires protection and sometimes light misting.',
[('Rain causes colour variation in the bricks that is impossible to remove', False), ('Rain washes cement from mortar before it has cured, creating weak crumbly joints', True), ('Rain makes bricks expand and crack the mortar joints', False), ('Rain protection is only necessary for decorative or rendered walls', False)]),
('What is the professional approach when a client asks you to use substandard materials to reduce cost?', 'multiple_choice',
'A professional mason must refuse to use materials that will fail to meet structural requirements, even under client pressure. Substandard mortar, incorrect block grades or inadequate foundations create buildings that can fail catastrophically — potentially injuring or killing the occupants. The mason has a professional and moral responsibility to use correct materials. The correct approach is to explain why the specified materials are necessary and find cost savings elsewhere if needed.',
[('Always accommodate the client\'s request — they are paying and have the final say', False), ('Refuse and explain that structural materials must meet standards to protect the occupants\' safety', True), ('Secretly use the correct materials and charge the original price anyway', False), ('Agree but reduce the labour charge to compensate for the material savings', False)]),
])

# ============================================================
# INTRODUCTION TO COMPUTERS
# ============================================================
create_quiz('Introduction to Computers', 'Introduction to Computers — Final Assessment',
'This assessment covers the fundamentals of computing that every digital citizen needs to know. You have taken a significant step by completing this course.',
20, [
('What is the difference between hardware and software?', 'multiple_choice',
'Hardware is the physical, tangible components of a computer — the parts you can touch: monitor, keyboard, processor, memory, storage. Software is the programs and instructions that run on the hardware — the parts you cannot touch: the operating system, applications, files. Both are essential: hardware without software is a box of electronics; software without hardware has nothing to run on. Together they make a computer system.',
[('Hardware runs the programs; software stores the data', False), ('Hardware is the physical components; software is the programs and instructions', True), ('Hardware is the expensive part; software is always free', False), ('There is no difference — the terms are used interchangeably', False)]),
('What does the CPU do?', 'multiple_choice',
'The CPU (Central Processing Unit) executes every instruction in every program. When you click a button, save a file, or load a web page, the CPU is carrying out billions of calculations per second to make that happen. Its speed is measured in GHz (gigahertz — billions of cycles per second). Modern CPUs have multiple cores, allowing them to work on several tasks simultaneously. Everything the computer does flows through the CPU.',
[('Stores all your files and documents permanently', False), ('Executes all instructions and calculations — the brain of the computer', True), ('Displays information on the screen', False), ('Connects the computer to the internet', False)]),
('What is RAM and why does more RAM generally mean better performance?', 'multiple_choice',
'RAM (Random Access Memory) is the computer\'s working memory — where programs and data are held while you are using them. It is like a desk: the bigger the desk, the more you can have open and ready to use at once. With more RAM, more programs can run simultaneously without the computer slowing down. When RAM is full, the computer uses slower storage as virtual memory — this is why computers feel sluggish when RAM is exhausted.',
[('RAM stores files permanently — more RAM means more storage space', False), ('RAM is working memory — more RAM allows more programs to run simultaneously without slowing down', True), ('RAM is the processing chip — more RAM means faster calculations', False), ('RAM connects to the internet — more RAM means faster downloads', False)]),
('What is the difference between a file and a folder?', 'multiple_choice',
'A file is a collection of data stored as a single unit with a name and extension — a document, photo, video, or program. A folder (also called a directory) is a container that organises files. Folders can contain files and other folders, creating a hierarchical structure. Good file organisation in meaningful folders makes finding your work much faster and prevents losing important files.',
[('Files contain folders; folders are stored inside files', False), ('A file is a single item of data; a folder is a container that organises files', True), ('Files are for programs; folders are for documents', False), ('There is no functional difference — folders are just renamed files', False)]),
('What does saving a file do?', 'multiple_choice',
'When you work on a document, the changes exist only in RAM (volatile memory) — they are lost if the power goes off or the program crashes. Saving writes the current state of the file to the hard drive or SSD (non-volatile storage) where it persists permanently until you deliberately delete it. The golden habit: save frequently with Ctrl+S. Many people have lost hours of work by not saving regularly.',
[('Sends a copy of the file to the cloud automatically', False), ('Writes the current file state to permanent storage so it survives the computer being switched off', True), ('Creates a backup copy of the file in a safe location', False), ('Reduces the file size so it takes less storage space', False)]),
('What is a web browser?', 'multiple_choice',
'A web browser is an application that retrieves, interprets and displays web pages from the internet. When you type a web address, the browser sends a request to a web server, receives the page data (HTML, CSS, images), interprets it, and displays it visually. Common browsers include Chrome, Firefox, Edge and Safari. The browser is the main tool through which most people experience the internet.',
[('A program that searches for viruses on websites before you visit them', False), ('An application that retrieves and displays web pages from the internet', True), ('A type of search engine that finds information online', False), ('Software that creates websites for businesses', False)]),
('What is the purpose of an antivirus program?', 'multiple_choice',
'Antivirus software scans files, downloads and running programs for known patterns of malicious code (viruses, worms, trojans, ransomware). When detected, it quarantines or removes the threat. Modern antivirus also uses behaviour analysis to detect threats that have not been seen before. Without antivirus protection, a computer connected to the internet will eventually be infected. Free antivirus (like Windows Defender) provides basic protection; paid versions offer more features.',
[('To make the computer run faster by removing unnecessary files', False), ('To detect and remove malicious software that could damage the computer or steal data', True), ('To prevent unauthorised users from logging into the computer', False), ('To fix errors in the operating system that cause crashes', False)]),
('What should you do before clicking a link in an unexpected email?', 'multiple_choice',
'Phishing emails are one of the most common ways people\'s accounts and devices are compromised. Before clicking any link, verify the sender\'s actual email address (not just the display name), hover over the link to see the actual destination URL, and ask yourself: was I expecting this? Does it make sense? When in doubt, go directly to the website by typing the address manually rather than clicking the link. If an offer seems too good to be true, it is a scam.',
[('Click it quickly before the offer expires', False), ('Verify the sender, hover over the link to check the URL, and question whether you were expecting it', True), ('Forward it to friends so they can benefit too', False), ('Reply to ask if the email is genuine before clicking', False)]),
('What does CTRL+Z do in most applications?', 'multiple_choice',
'Ctrl+Z is the universal Undo shortcut in virtually every application on Windows. It reverses the last action taken. Most applications allow multiple levels of undo — pressing Ctrl+Z repeatedly steps back through your recent actions. This is one of the most valuable shortcuts to know. The equivalent on Mac is Command+Z. Ctrl+Y or Ctrl+Shift+Z typically redoes (reverses the undo).',
[('Deletes the current file without confirmation', False), ('Undoes the last action — one of the most useful keyboard shortcuts', True), ('Opens the application settings menu', False), ('Saves the current file as a new version', False)]),
('What is the benefit of using cloud storage like Google Drive?', 'multiple_choice',
'Cloud storage keeps your files on remote servers accessible from any device with internet access. If your computer is stolen, damaged or broken, your files are safe and can be accessed from another device immediately. Files can be shared with others easily. Changes sync automatically across all your devices. The main risks are internet dependency and privacy concerns — be careful what sensitive data you store in the cloud.',
[('Files in the cloud load faster than files on your hard drive', False), ('Files are accessible from any device and protected if your computer is lost or damaged', True), ('Cloud storage is always free with unlimited space', False), ('Files in cloud storage cannot be accessed by hackers', False)]),
])

# ============================================================
# WINDOWS OPERATING SYSTEM
# ============================================================
create_quiz('Windows Operating System', 'Windows Operating System — Final Assessment',
'A solid understanding of the Windows operating system makes you more productive and more valuable in any workplace. This assessment tests practical knowledge you will use every day.',
20, [
('What does the Task Manager show you?', 'multiple_choice',
'Task Manager (opened with Ctrl+Shift+Esc or right-clicking the taskbar) shows all running processes, their CPU and memory usage, disk and network activity, startup programs, and user sessions. It is the first tool to use when a computer is running slowly — you can identify which program is consuming excessive resources. You can also end unresponsive programs (End Task) without restarting the computer.',
[('A list of all files stored on the computer', False), ('Running processes, resource usage, and allows ending unresponsive programs', True), ('A calendar of upcoming system maintenance events', False), ('A history of all websites visited in the browser', False)]),
('What is the Windows Registry?', 'multiple_choice',
'The Windows Registry is a hierarchical database that stores configuration settings for Windows, installed programs and hardware. It tells Windows how to behave, what programs to run at startup, and how installed software is configured. Incorrect registry edits can cause system instability or prevent Windows from starting. Regular users should not edit the registry directly. Malware often modifies the registry to start automatically with Windows.',
[('A list of all licensed Windows users on the network', False), ('A database storing Windows and application configuration settings', True), ('The recycle bin where deleted files are stored temporarily', False), ('A log of all errors that have occurred in Windows', False)]),
('What is the fastest way to find a file when you cannot remember where you saved it?', 'multiple_choice',
'Windows Search (accessed by pressing the Windows key and typing, or clicking the search bar in the taskbar) indexes files and can find them by name or content within seconds. You can also use the search box within File Explorer to search within a specific folder. If the file was recently opened, the Recent files list in the application (File menu) is even faster.',
[('Open every folder manually until you find the file', False), ('Use Windows Search — type the file name and Windows finds it instantly', True), ('Restart the computer — Windows rebuilds the file index on startup', False), ('Ask someone to find it as only trained technicians can search effectively', False)]),
('What does defragmenting a hard drive do?', 'multiple_choice',
'When files are saved and deleted on a traditional HDD, they become fragmented — stored in multiple non-contiguous locations across the disk. The drive head must travel between these fragments to read the file, slowing performance. Defragmentation reorganises files into contiguous blocks, reducing this travel time and improving speed. Important: never defragment an SSD — SSDs work differently and defragmentation reduces their lifespan.',
[('Deletes temporary files to free up storage space', False), ('Reorganises fragmented files on HDDs into contiguous blocks, improving read speed', True), ('Checks the hard drive for errors and repairs them', False), ('Defragmenting is a myth — it makes no difference to modern drives', False)]),
('A Windows program stops responding. What should you do first?', 'multiple_choice',
'When a program freezes, wait 30-60 seconds first — it may be processing a complex task and will recover. If it remains unresponsive, open Task Manager (Ctrl+Shift+Esc), find the program in the Processes tab, select it and click End Task. This closes the program without affecting other running programs or requiring a restart. Only restart the computer if multiple programs are frozen or the entire system is unresponsive.',
[('Immediately press the power button to restart the computer', False), ('Wait briefly, then use Task Manager to end the unresponsive process', True), ('Uninstall the program immediately as it has been corrupted', False), ('Leave it — Windows will automatically fix frozen programs', False)]),
('What is the purpose of Windows Update?', 'multiple_choice',
'Windows Update downloads and installs security patches, bug fixes and feature improvements from Microsoft. Security patches are especially critical — they close vulnerabilities that attackers actively exploit. Many devastating cyberattacks (including the WannaCry ransomware that affected thousands of organisations) exploited Windows vulnerabilities that Microsoft had already patched. An unpatched Windows system is significantly more vulnerable to attack.',
[('To upgrade Windows to the next version when it becomes available', False), ('To install security patches and bug fixes that protect the system from known vulnerabilities', True), ('To update Microsoft Office applications automatically', False), ('To back up files to Microsoft\'s servers for safe keeping', False)]),
('What does "Run as Administrator" do?', 'multiple_choice',
'Windows User Account Control (UAC) restricts what normal user accounts can do — they cannot install programs or change system settings. Running as Administrator grants temporary elevated permissions to carry out these actions. This protects the system from accidental or malicious changes when using the computer for everyday tasks. When installing software or making system changes, right-click and select "Run as Administrator".',
[('Logs in as a different user who has no file access restrictions', False), ('Grants elevated permissions to perform actions that require administrative rights', True), ('Runs the program faster by giving it priority access to the CPU', False), ('Sends the program details to Microsoft for safety verification', False)]),
('What is the best practice for password management?', 'multiple_choice',
'Using the same password across multiple accounts means a breach on any one site exposes all your accounts. Using simple, guessable passwords makes brute force attacks easy. Best practice: use a unique, strong password for every account. A password manager (like Bitwarden, which is free) generates and stores complex passwords securely — you only need to remember one master password. Enable two-factor authentication wherever available.',
[('Use the same strong password everywhere so you never forget it', False), ('Use unique strong passwords for every account, managed with a password manager', True), ('Change all passwords every week to stay ahead of attackers', False), ('Write passwords in a notebook kept near the computer for easy reference', False)]),
('What should you do when you see a pop-up claiming your computer is infected?', 'multiple_choice',
'Legitimate antivirus software does not display alarming pop-ups urging you to call a phone number or download software urgently. These are scareware — fake alerts designed to trick you into calling premium-rate phone numbers, installing malware disguised as "security software," or paying for fake "cleanup" services. Close the pop-up (use Task Manager if it will not close), run your actual antivirus scan, and do not call any number displayed.',
[('Call the number displayed immediately as your computer is in danger', False), ('Close the pop-up — these are scareware scams. Run your actual antivirus if concerned.', True), ('Download and install the software it recommends to clean the infection', False), ('Restart the computer immediately to remove the virus', False)]),
('What is the purpose of creating a System Restore point?', 'multiple_choice',
'A System Restore point saves a snapshot of Windows settings, drivers and the registry at a specific moment. If a software installation, driver update or system change causes problems, you can roll back to the restore point — restoring stability without losing personal files. Always create a restore point before making significant changes to Windows. It takes seconds but can save hours of troubleshooting.',
[('Backs up all personal files and documents to a safe location', False), ('Saves a snapshot of Windows settings that can be restored if changes cause problems', True), ('Creates a complete backup of the entire hard drive including files', False), ('Resets Windows to factory settings removing all installed programs', False)]),
])

# ============================================================
# WORD PROCESSING
# ============================================================
create_quiz('Word Processing', 'Word Processing — Final Assessment',
'Word processing skills are required in virtually every modern workplace. This assessment tests your ability to use word processing software professionally and efficiently.',
20, [
('What does CTRL+B do in a word processor?', 'multiple_choice',
'Ctrl+B applies or removes bold formatting to selected text. This and the companion shortcuts Ctrl+I (italic) and Ctrl+U (underline) are among the most-used in word processing. Learning keyboard shortcuts dramatically increases productivity — experienced word processor users rarely take their hands off the keyboard for basic formatting tasks.',
[('Opens the Format menu for advanced formatting options', False), ('Applies or removes bold formatting to selected text', True), ('Creates a new blank document', False), ('Saves the document as a backup copy', False)]),
('What is the purpose of the spell checker?', 'multiple_choice',
'The spell checker identifies words that do not match the dictionary and suggests corrections. However, it cannot catch correctly-spelled words used incorrectly (their/there/they\'re, you/your), does not understand context, and may flag technical terms or proper nouns as errors. Always proofread manually after spell checking — the spell checker is a first pass, not a complete solution. Grammar checkers help but also have limitations.',
[('To check that the document follows proper grammar rules', False), ('To identify words not in the dictionary and suggest corrections — always proofread manually too', True), ('To format the document according to professional standards', False), ('To automatically correct all writing errors without needing to proofread', False)]),
('What is the difference between Save and Save As?', 'multiple_choice',
'Save (Ctrl+S) saves the current document over itself — the file is updated with your latest changes. Save As (Ctrl+Shift+S or F12) opens a dialog asking where to save and what to name the file — creating a new file without overwriting the original. Use Save As when: saving a copy with a new name, saving in a different format (e.g. as PDF), or saving to a different location. After Save As, you are working on the new file.',
[('They are the same function — Save As is just an older version of Save', False), ('Save updates the current file; Save As creates a new file at a location and name you specify', True), ('Save goes to cloud storage; Save As saves to the local hard drive', False), ('Save As creates a backup; Save deletes previous versions', False)]),
('What is a template in word processing?', 'multiple_choice',
'A template is a pre-designed document containing formatting, layouts, placeholder text and styles. Rather than setting up a new document from scratch each time, you open the template and fill in the specific content. Templates ensure consistency — every business letter, invoice or report looks the same. Creating templates for frequently-used documents saves significant time and ensures a professional, consistent appearance.',
[('A document that cannot be edited — only viewed and printed', False), ('A pre-designed document with formatting and layouts that you fill with specific content', True), ('An automatic form that fills in dates and names by itself', False), ('A legal document that serves as a contract template', False)]),
('What does "track changes" do in a document?', 'multiple_choice',
'Track Changes records every edit made to a document — insertions are shown in a different colour, deletions appear with strikethrough, and comments can be added. This allows a reviewer to see exactly what changes were made and accept or reject each one individually. Track Changes is essential for collaborative writing, document review workflows, and legal documents where every change must be traceable.',
[('Automatically saves the document every time a change is made', False), ('Records all edits so a reviewer can see, accept or reject each change individually', True), ('Counts the total number of changes made to monitor editing progress', False), ('Prevents others from making unauthorised changes to the document', False)]),
('What is a header and footer in a document?', 'multiple_choice',
'Headers appear at the top of every page; footers at the bottom. They typically contain: page numbers, document title, company name, date, version number, or confidentiality notice. Once created, the header/footer appears automatically on every page — you do not need to add it manually to each page. Professional documents (reports, proposals, legal documents) always use headers and footers.',
[('The first and last paragraphs of a document that introduce and conclude the content', False), ('Content that appears automatically at the top and bottom of every page', True), ('Formatting applied to heading and footer text to make them stand out', False), ('The title page and contents page at the beginning of a document', False)]),
('What is the most professional format to send a word-processed document to a client?', 'multiple_choice',
'PDF (Portable Document Format) preserves the document\'s formatting exactly regardless of what software, operating system or device the recipient uses. A Word document may look different on the recipient\'s computer if they have different fonts or a different version of Word. PDF also prevents easy editing, which is appropriate for invoices, contracts, proposals and reports. Save As PDF in Word or LibreOffice with one click.',
[('The original Word (.docx) format — so clients can edit if needed', False), ('PDF format — preserves formatting exactly on any device and prevents unintended editing', True), ('Plain text (.txt) — works on any computer regardless of software', False), ('HTML format — allows viewing in any web browser', False)]),
('What does right-click, then "Format Paragraph" allow you to control?', 'multiple_choice',
'Paragraph formatting controls: indentation (how far text is indented from margins), line spacing (single, 1.5, double), space before and after paragraphs, and alignment (left, centre, right, justified). These settings dramatically affect the professionalism and readability of a document. Professional business documents typically use 1.15 or 1.5 line spacing with 6-10pt space after paragraphs rather than a blank line between paragraphs.',
[('The colour and style of the text within the paragraph', False), ('Indentation, line spacing, space before/after and alignment for the paragraph', True), ('The border and shading applied around the paragraph', False), ('The spell check settings for words within the paragraph', False)]),
('When should you use numbered lists versus bullet points?', 'multiple_choice',
'Use numbered lists when sequence matters — steps in a process, ranked items, instructions. The reader needs to know what comes first, second and third. Use bullet points when items are equal and non-sequential — features of a product, items in a list, options to consider. Using numbered lists for non-sequential items implies a ranking or order that does not exist, which can confuse readers.',
[('Numbered lists for long lists; bullets for short lists of three or fewer items', False), ('Numbered lists for sequential items where order matters; bullets for equal, non-sequential items', True), ('Bullets are always more professional than numbered lists in business documents', False), ('They are interchangeable — use whichever looks better in the document', False)]),
('What is the keyboard shortcut to select all content in a document?', 'multiple_choice',
'Ctrl+A (Select All) selects the entire contents of the document simultaneously. Once selected, you can apply formatting to everything at once, copy the entire document, or delete all content. Other essential selection shortcuts: Shift+Arrow keys extend selection character by character; Ctrl+Shift+Arrow extends word by word; clicking at the start then Shift+clicking at the end selects a specific range.',
[('Ctrl+S selects all and saves simultaneously', False), ('Ctrl+A selects all content in the document', True), ('F5 opens a selection dialogue for choosing what to select', False), ('Double-clicking the document background selects all content', False)]),
])

# ============================================================
# INTERNET AND EMAIL
# ============================================================
create_quiz('Internet and Email', 'Internet and Email — Final Assessment',
'The internet and email are essential professional tools. This assessment tests your ability to use them safely, effectively and professionally.',
20, [
('What does HTTPS indicate in a website address?', 'multiple_choice',
'HTTPS (Hypertext Transfer Protocol Secure) means the connection between your browser and the web server is encrypted using TLS (Transport Layer Security). Your data — including login credentials, personal information and payment details — cannot be read by anyone intercepting the connection. Always check for HTTPS before entering sensitive information. HTTP (without the S) sends data in plain text that can be intercepted.',
[('The website is registered in a country where data is protected by law', False), ('The connection is encrypted — data transmitted cannot be read by third parties', True), ('The website has been verified as free of malware', False), ('The website is hosted on a fast server for better performance', False)]),
('What is phishing?', 'multiple_choice',
'Phishing is a social engineering attack where criminals send fraudulent emails, messages or create fake websites impersonating legitimate organisations to trick people into revealing passwords, bank details or personal information. The name comes from "fishing" — using bait to catch victims. Red flags: unexpected communications, urgency, requests for credentials or money, links to unfamiliar URLs. Always verify before clicking or responding.',
[('A method of searching the internet more quickly using special software', False), ('Fraudulent communications that impersonate legitimate organisations to steal credentials or money', True), ('Accessing websites that are not intended to be public', False), ('A way of downloading copyrighted content from the internet illegally', False)]),
('What is the correct format for a professional business email?', 'multiple_choice',
'A professional email has: a clear, specific subject line; a formal greeting; a concise opening stating the purpose; a well-organised body with one idea per paragraph; a clear call to action or conclusion; a professional sign-off (Regards, Yours faithfully); your name, title and contact information. Avoid slang, excessive exclamation marks, all capitals (implies shouting), and emojis in formal communication.',
[('No fixed format — emails are informal and flexible', False), ('Clear subject line, formal greeting, concise content, professional sign-off and contact information', True), ('Start with a joke to build rapport before getting to the point', False), ('Keep it as short as possible — one sentence is ideal for professional emails', False)]),
('What should you check before clicking a link in an email?', 'multiple_choice',
'Hover your cursor over the link without clicking — the actual URL destination appears in the browser status bar or a tooltip. The displayed text might say "www.yourbank.com" but the actual link goes to "malicioussite.ru/bank". If the destination URL does not match what you expect, do not click. Verify by going directly to the website by typing the known address in the browser. This simple habit prevents most phishing attacks.',
[('Check how many people the email was sent to', False), ('Hover over the link to see the actual destination URL before clicking', True), ('Check whether the email has any attachments', False), ('Verify that the email was sent during business hours', False)]),
('What is CC and BCC in email?', 'multiple_choice',
'CC (Carbon Copy) sends a copy of the email to additional recipients, and all recipients can see who else received it. BCC (Blind Carbon Copy) also sends copies but recipients cannot see who else received a BCC copy. Use BCC when emailing a large group to protect everyone\'s email addresses from being shared, or when you want someone to see a message without the primary recipient knowing. Misusing CC and BCC can cause professional embarrassment.',
[('CC means the email is confidential; BCC means it is public', False), ('CC copies recipients visibly to all; BCC copies recipients invisibly', True), ('CC sends to a colleague for comments; BCC sends to your manager for approval', False), ('CC and BCC are the same — the choice is just personal preference', False)]),
('What is a cookie on a website?', 'multiple_choice',
'A cookie is a small text file a website stores on your device to remember information about you — your login state, preferences, shopping cart contents, or tracking data about your visit. Session cookies expire when you close the browser. Persistent cookies remain until deleted or they expire. Tracking cookies follow your activity across multiple websites for advertising purposes. You can view and delete cookies in browser settings.',
[('A malicious file that websites try to install to hack your computer', False), ('A small text file websites store on your device to remember preferences and login state', True), ('An automatic download from websites when you first visit them', False), ('A type of internet virus found on unsafe websites', False)]),
('What is a strong password?', 'multiple_choice',
'A strong password is at least 12 characters long and combines uppercase and lowercase letters, numbers and symbols. It does not contain dictionary words, personal information (name, birth date), or obvious substitutions (P@ssw0rd). The strongest passwords are long random strings generated by a password manager. The length is more important than complexity — "correct-horse-battery-staple" is far stronger than "P@55w0rd" despite looking simpler.',
[('Eight characters using your name and birth year', False), ('At least 12 characters combining uppercase, lowercase, numbers and symbols, with no dictionary words', True), ('A word with a few letters replaced by similar-looking numbers', False), ('The same complex word repeated twice for extra security', False)]),
('Why should you log out of accounts when using a shared or public computer?', 'multiple_choice',
'When you log in to an account on any browser, the session is typically maintained by a cookie until you explicitly log out. On a shared computer, the next user can simply return to your account without knowing your password. They could read private emails, access banking, or send messages in your name. Always log out of every account after using a shared device, and never save passwords in public browsers.',
[('Logging out speeds up the computer for the next user', False), ('The next user can access your account if you do not log out — they do not need your password', True), ('Logging out deletes your browser history from the computer', False), ('Public computers automatically log out all accounts after 30 minutes', False)]),
('What is the most effective way to search the internet for specific information?', 'multiple_choice',
'Search engines respond well to specific, descriptive search terms. Add quotation marks around exact phrases ("plumbing regulations Nigeria 2023"). Use minus signs to exclude terms (-forum excludes forum results). Use site: to search within one website (site:who.int malaria). Use filetype: to find specific document types (filetype:pdf water safety). Specific searches return far more useful results than vague single-word queries.',
[('Type a question in exactly the same way you would ask a person', False), ('Use specific terms, quotation marks for exact phrases, and operators like site: and filetype:', True), ('Search in your local language as search engines work better in each language', False), ('Search engines are all the same — the choice of search engine affects results more than the query', False)]),
('What should you do if you receive a suspicious email at work?', 'multiple_choice',
'Report it to your IT department or manager before deleting it — they can investigate whether it is a targeted attack on the organisation, block the sender for everyone, and warn colleagues. Simply deleting it leaves others vulnerable and removes evidence. Never reply to suspicious emails, click links in them, or open attachments. Your report could prevent a significant security incident for your entire organisation.',
[('Delete it immediately to prevent it spreading to other computers', False), ('Report it to IT or your manager before deleting — it may be a targeted attack on the organisation', True), ('Forward it to colleagues to warn them about the scam', False), ('Reply asking the sender to remove you from their list', False)]),
])

# Print summary
print('\n' + '='*60)
from certifications.models import Quiz
total_q = 0
for q in Quiz.objects.all().order_by('course__title'):
    count = q.questions.count()
    total_q += count
    print(f'  {q.course.title}: {count} questions')
print(f'\nTotal quizzes: {Quiz.objects.count()}')
print(f'Total questions: {total_q}')